### ISSUE TITLE
Evaluate golicense

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#1042]
Maybe this could be used to enhance our analysis for Go based projects - golicense, aGo Binary OSS License Scanner: https://github.com/mitchellh/golicense

**Comment by sschuberth** [comment]
Hmm, the project page says it "scans *compiled* Go binaries". That's a fundamental difference to how ORT is designed to work. ORT's concept is to scan source code (both for dependency analysis and for licenses), not binaries. That said, [golicense](https://github.com/mitchellh/golicense) might be a good fit for [Quartermaster](https://github.com/QMSTR/qmstr) (which also is written in Go).

**Comment by mnonnenmacher** [comment]
Closing this for the reason @sschuberth provided and because the golicense project has not been updated since 2019.
