### ISSUE TITLE
Integrate Gitter.im and enable transition from Slack with matterbridge

### ISSUE THREAD

**Issue by lenucksi** [oss-review-toolkit/ort#1268]
#  Rationale
[Gitter.Im](https://gitter.im/) is a Slack-like rich instant messaging tool strongly integrated with GitHub and likely GitLab. It is very well received with the community, free, offers badge-style integration for repositories, multiple rooms and direct identity integration with GitHub, GitLab and Twitter making it very easy and open to access lowering the barriers to contribution and interaction.

# Proposal
- Move off of Slack and onto Gitter.
- For a period of migration we should consider syncing both communication channels.

# Approach
- Ask [Gitter.im](https://gitter.im/home/explore#createcommunity) to create an integration PR.
- Setup [Matterbridge](https://github.com/42wim/matterbridge/) for the sync.
- Create a migration time plan and handle the communication around the migration.

# Technical stuff
- We need a *very small* box to run Matterbridge.

**Comment by sschuberth** [comment]
Note that [Gitter.im has been sold to the makers to Matrix](https://techcrunch.com/2020/09/30/element-acquires-gitter-to-get-more-developers-on-board-with-the-open-matrix-messaging-protocol) meanwhile. But I'll stick with Slack for the foreseeable time.
