### ISSUE TITLE
Docker image build failure

### ISSUE THREAD

**Issue by silenceleaf** [oss-review-toolkit/ort#1357]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':reporter-web-app:yarnInstall'.
> A problem occurred starting process 'command 'yarn''

**Comment by sschuberth** [comment]
Please see https://github.com/heremaps/oss-review-toolkit#installation, [Yarn](https://yarnpkg.com/) is required for building the web app reporter (which gets added to the Docker image).
