### ISSUE TITLE
scan downloading scancode-toolkit each time. please made a cache of it once per installation session

### ISSUE THREAD

**Issue by sweetca** [oss-review-toolkit/ort#1580]
Regarding to logs of scan execution 
```
16:23:08.099 INFO  - Bootstrapping scanner 'ScanCode' as required version 2.9.7 was not found in PATH.
16:23:08.099 INFO  - Downloading ScanCode from https://github.com/nexB/scancode-toolkit/archive/v2.9.7.tar.gz... 
16:23:09.840 INFO  - Retrieved ScanCode from local cache.
16:23:48.622 INFO  - Unpacking '/var/folders/l1/q8mfwlln2pqf5pg30c553ytc0000gn/T/ort7289663463082405698ScanCode-v2.9.7.tar.gz' to '/var/folders/l1/q8mfwlln2pqf5pg30c553ytc0000gn/T/ort1678906659374181145ScanCode-2.9.7'... 
16:23:52.952 INFO  - Running '/var/folders/l1/q8mfwlln2pqf5pg30c553ytc0000gn/T/ort1678906659374181145ScanCode-2.9.7/scancode-toolkit-2.9.7/scancode --version' in '/Users/alexskorohod/space/oss/ort/here/oss-review-toolkit'...
```
we spending each time 5 min to download & unpack scancode-toolkit.
@tsteenbe is it possible to make this download step not necessary if scancode-toolkit/archive/v2.9.7.tar.gz already was downloaded? just copy it to tmp dit & unpack there...

thanks

**Comment by sschuberth** [comment]
Thanks for the report, @sweetca. This is currently a known limitation, and I've started to draft a fix already some time ago. For now, the easiest work-around is to globally install ScanCode so it's available in `PATH` via `sudo -H pip install scancode-toolkit==2.9.7`.

**Comment by sweetca** [comment]
> Thanks for the report, @sweetca. This is currently a known limitation, and I've started to draft a fix already some time ago. For now, the easiest work-around is to globally install ScanCode so it's available in `PATH` via `sudo -H pip install scancode-toolkit==2.9.7`.

@sschuberth thanks a lot for fast reply. really helpful...
