### ISSUE TITLE
Add support for the Vcpkg (C/C++) package manager

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#1643]
Add support for the Vcpkg dependency manager to the analyzer module.

package manager website: https://github.com/Microsoft/vcpkg
docs website: https://vcpkg.readthedocs.io/en/latest/

**Comment by sschuberth** [comment]
Maybe [this hint](https://github.com/microsoft/vcpkg/discussions/27030#discussioncomment-4203882) helps with the implementation.

**Comment by ksg97031** [comment]
I glanced into it, and it seems that Vcpkg doesn't drop the lockfile on the project side after a successful build. Additionally, when using the [vcpkg depend-info](https://learn.microsoft.com/en-us/vcpkg/commands/depend-info#tree) command, it doesn't display version information.

One promising solution could be to manage dependencies using a file similar to Python's requirement.txt called [vcpkg.json](https://learn.microsoft.com/ko-kr/vcpkg/users/manifests). This file can help specify and manage the versions of packages your project depends on, much like a Python requirements.txt file.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
