### ISSUE TITLE
Add support for the Poetry (Python) package manager

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#1699]
Add support for the Poetry dependency manager to the analyzer module.

package manager website: https://github.com/sdispater/poetry

**Comment by sschuberth** [comment]
Project page is now at https://github.com/python-poetry/poetry / https://python-poetry.org/.

**Comment by heliocastro** [comment]
Adding a relevant file:

`[tool.poetry]
name = "sparen-server"
version = "0.1.0"
description = ""
authors = ["Helio Chissini de Castro <helio@kde.org>"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.0.1"
Flask-SQLAlchemy = "^2.5.1"
Flask-BS4 = "^5.0.0"
Flask-WTF = "^0.15.1"
mt-940 = "^4.23.0"
psycopg2 = "^2.9.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.12.1"
pre-commit = "^2.14.1"
flake8 = "^3.9.2"
mypy = "^0.910"
isort = "^5.9.3"
black = {version = "^21.8b0", allow-prereleases = true}
pip = "^21.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79

[tool.black]
line-length = 79
target-version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
`

**Comment by dgutson** [comment]
@heliocastro what is required to support poetry besides that code? I'm interested in this issue so I might assign someone to contribute.

**Comment by qequ** [comment]
@tsteenbe  Is it possible to translate Poetry dependencies to a pip requeriments.txt and use the Analyzer's Pip class? just like what pipenv ends up doing

**Comment by dgutson** [comment]
@mnonnenmacher any idea when this will be released?

**Comment by sschuberth** [comment]
> @mnonnenmacher any idea when this will be released?

@dgutson, it's merged, so it's released :-) ORT currently does [not make formal releases](https://github.com/oss-review-toolkit/ort/issues/1901) on its own. You have to build your own "release" from source / using the `Dockerfile`.
