### ISSUE TITLE
Add support for the Nimble (nim) package manager

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#1781]
Add support for the Nimble dependency manager to the analyzer module.

See also https://github.com/nim-lang/nimble

To implement Nimble support in ORT, we need several things things:

1. ability to detect whether a project is using Nimble

>If a project has an [.nimble](https://github.com/nim-lang/nimble#nimble-reference) then it likely a Nim-based project. Can use this files for [globsForDefinitionFiles](https://github.com/heremaps/oss-review-toolkit/blob/master/analyzer/src/main/kotlin/managers/CocoaPods.kt#L40)

2. declared license for a package

> See [license in .nimble](https://github.com/nim-lang/nimble#package). Furher research need to determine how to read-out the package name, version and license from .nimble file

3. source code location of the package (VCS location + revision, package source code/binary artifact)

> .nimble files do not defined source code location but we could download and parse https://github.com/nim-lang/packages/blob/master/packages.json which contains central listing of all packages for Nimble and then query Git tag to determine the revision / SHA1 for a specific version.

4. dependency tree including package name, version

>  No dependency tree option found in Nimble's docs but believe we can use [nimble list](https://github.com/nim-lang/nimble#nimble-list)

5.  Example Nim project that can be used to test Nimble support

> Maybe use https://github.com/PMunch/nimlsp/blob/master/nimlsp.nimble? or pick another package from https://github.com/nim-lang/packages which contains central listing of all packages for Nimble

For known scopes I propose we use by default [requires](https://github.com/nim-lang/nimble#dependencies) for dependencies.

No plugin should be required/to be installed in order to analyze Nimble based projects

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
