### ISSUE TITLE
Analyze Docker images / Dockerfiles

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#1833]
We could add a "meta package manager" implementation for Docker images / Dockerfiles that uses [Tern](https://github.com/vmware/tern) to get the OS-level packages, and additionally runs the ORT analyzer on the layers to identify language-level packages, similar like described at https://github.com/vmware/tern/issues/149.

*Edit:* I'll be updating this comment with a list of tool that might come in question:

- https://github.com/tern-tools/tern (moved from the "vmware" org)
- https://github.com/org-metaeffekt/metaeffekt-container-annex (probably outdated by now)
- https://github.com/nexB/container-inspector (part of scancode.io)
- https://github.com/anchore/syft (for vulnerabilities use https://github.com/anchore/grype)
- https://github.com/aquasecurity/trivy
- https://github.com/kubernetes-sigs/bom

**Comment by sschuberth** [comment]
Alternatively, looking at https://github.com/org-metaeffekt/metaeffekt-container-annex might be worthwhile.

**Comment by sschuberth** [comment]
Another new tool from nexB to look at: https://github.com/nexB/container-inspector

**Comment by sschuberth** [comment]
Ping @porsche-rishisaxena, FYI.

**Comment by sschuberth** [comment]
I'll be updating this comment with a list of tool that might come in question:

- https://github.com/tern-tools/tern (moved from the "vmware" org)
- https://github.com/org-metaeffekt/metaeffekt-container-annex (probably outdated by now)
- https://github.com/nexB/container-inspector (part of scancode.io)
- https://github.com/anchore/syft (for vulnerabilities use https://github.com/anchore/grype)
- https://github.com/aquasecurity/trivy

**Comment by dgutson** [comment]
@sschuberth you may want to look at [hadolint](https://github.com/hadolint/hadolint) too

**Comment by sschuberth** [comment]
@dgutson AFAIK hadolint is, as the name suggests, just a linter for the syntax in Dockerfiles. It tells you nothing about the semantics of the software being added to the Docker image.

**Comment by sschuberth** [comment]
For similar reasons as [mentioned for Nix support](https://github.com/oss-review-toolkit/ort/issues/2179#issuecomment-1788114523) I'm closing this as not planned.

**Comment by dgutson** [comment]
> Another new tool from nexB to look at: https://github.com/nexB/container-inspector

out of curiosity, why this comment was marked as outdated? @sschuberth

**Comment by sschuberth** [comment]
> > Another new tool from nexB to look at: https://github.com/nexB/container-inspector
> 
> out of curiosity, why this comment was marked as outdated? @sschuberth

Because I started to gather tools by editing the top post, to have everything in one place, so you don't have to scan through the whole thread.

**Comment by sschuberth** [comment]
For reference, this (German) article shows that [Grype is often returning much better results than Trivy](https://www.heise.de/hintergrund/Docker-Image-Security-Teil-1-Die-groessten-Irrtuemer-ueber-Image-Scanner-10497655.html).
