### ISSUE TITLE
Visualize `license finding curations`

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#1894]
License finding curations have been introduced in context of #1726.
The implementation currently uses the curations to correct the detected licenses whereas in the reports only the corrected detected licenses are visible.

The curations should be made visible somehow.
Ideas for use cases to consider
- Verifying / reviewing the whole report
- Verifying / reviewing / seeing the effect of a single curation

**Comment by mnonnenmacher** [comment]
To show applied license finding curations in the web app reporter they need to be added to the evaluated model. Currently the `EvaluatedFinding` only contains applied path excludes:
https://github.com/oss-review-toolkit/ort/blob/main/reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedFinding.kt

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
