### ISSUE TITLE
LicenseView: Allow for using raw + curated detected licenses separately

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#1895]
Why actually needed: TODO

Allow using the raw detected licenses as well as the curated detected licenses.
This would increase flexibility in implementing rules.

As using 4 sets in the license view leads to many combinations and as the tests are already quite redundant the license view should be generalized before introducing that feature.

**Comment by sschuberth** [comment]
@fviernau, is this issue still valid, or can we close it?

**Comment by fviernau** [comment]
Thinking about this again 
1. I do not see the need for the rules to run on uncurated detected licenses. E.g. if there are false detections
    by the scanner for which we have corrections for, there should be no reason to operate on the faulty raw data.
2. Maybe generalizing the license view is some idea which could be done (to improve tests)

Closing this as won't fix as the main point of the ticket is #1.
