### ISSUE TITLE
Create automation for ORT releases (incl. release notes)

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#1901]
Currently, there are not fixed releases for ORT available, but only dynamically built artifacts via [JitPack](https://jitpack.io/#heremaps/oss-review-toolkit). While this works reasonably well for "early adopters" like [SW360 Antenna](https://github.com/eclipse/antenna/blob/master/pom.xml#L263-L272), it would be nice to have "real" releases with semantic versioning.

While a common option is to publish JVM artifacts to Maven central or JCenter, another option for us is to use GitHub's built-in [package registry](https://github.com/features/package-registry). Publishing to GitHub can the nicely automated using GitHub [actions](https://github.com/features/actions).

As discussed internally earlier, the trigger for a release should be the push of a(n) (annotated) tag of a special name. Luckily, a [ready-made GitHub action](https://github.com/softprops/action-gh-release) exists which seems to do exactly that. We should evaluate that action and eventually take it into use to prepare for automating releases in the near future.

*Edit:* I'll update the following list with suggestions about release tools from the comments below.

- https://github.com/orhun/git-cliff
- https://github.com/jreleaser/jreleaser
- https://github.com/release-drafter/release-drafter (see e.g. [semver4j](https://github.com/semver4j/semver4j/releases), [graphql-kotlin](https://github.com/ExpediaGroup/graphql-kotlin/releases))
- https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
- https://github.com/semantic-release/semantic-release

**Comment by sschuberth** [comment]
Creating an ORT release should involve running ORT on ORT in order to create a proper disclosure document, e.g. a `NOTICE` file, to be bundled with the distribution / Fat JAR for the CLI.

**Comment by gongzhao1** [comment]
Hi, Is there an official image available in Docker Hub?

**Comment by sschuberth** [comment]
No, not yet, see https://github.com/oss-review-toolkit/ort/issues/2441. You currently have to build the image yourself.

**Comment by sschuberth** [comment]
FYI, I recently came across https://github.com/orhun/git-cliff to generate changelog files / release notes from the Git history, which might be interesting for us in this context.

**Comment by sschuberth** [comment]
Maybe also https://github.com/jreleaser/jreleaser could become useful here.

**Comment by aalmiray** [comment]
Hi there, I'm the author of JReleaser. The tool can certainly help you craft a changelog based on just commit information. If you're looking for an option to generate the changelog based on GH Issues/PRs then I'd recommend https://github.com/release-drafter/release-drafter

Of course JReleaser works both in local and CI environments.

One more thing, if you're interested in posting ready made binaries (such as CLI based tools) then JReleaser can also help you
- posting those binaries to a GitHub release page
- creating platform packagers for those binaries with Homebrew, Scoop, others.

**Comment by sschuberth** [comment]
Probably also relevant for us is GitHub's new feature to [automatically generate release notes for GitHub releases](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes).

**Comment by sschuberth** [comment]
Publishing to the new [Adoptium Marketplace](https://adoptium.net/marketplace/) could also be an option.

**Comment by mawl** [comment]
https://github.com/semantic-release/semantic-release <= a fine tool we're using.

Integrates with github actions as well: https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md

**Comment by sschuberth** [comment]
Idea from @mnonnenmacher at the ORT Community Day: Attach release notes to annotate Git tags to be independent of GitHub.

**Comment by sschuberth** [comment]
After reading through @pombredanne's https://www.nexb.com/software-versioning/, I wonder whether we could use a mix of CalVer and ideas from SemVer for ORT. The version number "prefix" would be CalVer (for sorting), plus a "suffix" that contains the *number* of breaking changes, new features, and bugfixes, respectively. The latter numbers could be calculated from our [Conventional Commits](https://www.conventionalcommits.org/) easily, and in contrast to "pure" SemVer these numbers also give you a clue about *how much* (not only *that*) something has changed.

So, for example an initial ORT release from today would have version `2023.7.19+0.0.0` as relative to the previous release (there is none) no changes can be computed. The next release on the last day of next month with 3 breaking changes, 1 new feature, and 5 bug fixes would have version number `2023.8.31+3.1.5`. When omitting leading 0 in the date, the whole string is SemVer compliant, and using `+` instead of `-` nicely resembles that the following "build metadata" describes what has been *added*.

**Comment by sschuberth** [comment]
> `3.1.5+2023.8.31`. Should still have the same properties.

That breaks sorting (by date).

**Comment by maxhbr** [comment]
if the leading version is just increased and every increased version is released at a later date, the sorting should still be the same. (If not just string sorting, but semantically sorting the parts)

**Comment by maxhbr** [comment]
oh, sorry, I missed the relative.

**Comment by sschuberth** [comment]
As discussed in today's community meeting, we'll like stick to plain SemVer after all, mostly for for simplicity as remembering the date as part of a version (if you want to upgrade) is hard.

**Comment by sschuberth** [comment]
This is now [done](https://github.com/oss-review-toolkit/ort/releases/tag/1.1.0) (using https://github.com/jmongard/Git.SemVersioning.Gradle).
