### ISSUE TITLE
Add support for pnpm packages

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#2024]
Add support for pnpm to the ORT analyzer module.

- https://pnpm.js.org
- https://github.com/pnpm/pnpm

## Package Manager Support Questions/Requirements

1. Detect whether a project is a pnpm project 

> The presence of [pnpm-lock.yaml](https://github.com/pnpm/pnpm/blob/master/pnpm-lock.yaml) which is pnpm lockfile or pnpm-workspace.yaml which is used for workspaces.

2. Detect declared license for a package

> pnpm is part of Node.js ecosystem so it has package.json and uses npmjs.com as its central package repository.

3. How to get dependency tree including package names, versions

> https://pnpm.js.org/en/cli/list

4. Obtain the source for a dependency

> Same as npm, pnpm queries registry.npmjs.com

5. Determine how to separate code dependencies from build/test ones

> Same scopes as `npm` and `yarn` - `dependencies` amd `devDependencies` 

6. Example pnpm projects to test implementation

> https://github.com/Golfklub/paperJS-playground
> https://github.com/strangebreww/tic-tac-toe
> https://github.com/zkochan/packages/tree/2cb8e0072168869e86d8a81206330352455746cd/rename-overwrite

**Comment by sschuberth** [comment]
FYI, [pnpm 5.0.0](https://github.com/pnpm/pnpm/releases/tag/v5.0.0) has some really nice performance improvements, also when compared to Yarn.
