### ISSUE TITLE
Conan: Get real provenance data

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#2037]
The VCS location of several Conan dependencies point to repositories which contain only recipes used to publish these packages on Conan Central, but not the actual source code of the packages.
As result the actual sources are not being scanned, see e.g. [1,2,3].

[1] https://bintray.com/conan/conan-center
[2] https://bincrafters.readthedocs.io/en/latest/
[3] https://github.com/bincrafters/conan-protobuf

**Comment by sschuberth** [comment]
Some news about ConanCenter (not "Central"): https://blog.conan.io/2020/01/13/New-Conan-Center-Improves-Search-Discovery.html

**Comment by sschuberth** [comment]
See the [Recipe and Sources in a Different Repo](https://docs.conan.io/en/latest/creating_packages/external_repo.html) docs for details.
