### ISSUE TITLE
big web-app report problem

### ISSUE THREAD

**Issue by fb33** [oss-review-toolkit/ort#2091]
Hello

I build ORT locally from the master branch
I run ORT on windows with git bash in admin mode.

The project analyzed is a node project.

The reporter generate an about 50Mo scan-report-web-app.html file.

With firefox 71.0, the report is successfuly rendered but it's a bit slow : about 1m30s
With chrome 79.0.3945.88n the report can't be rendered. It stucks at 25% of the processing result data.

Regards

**Comment by sschuberth** [comment]
@tsteenbe can you please take a look at this?

**Comment by tsteenbe** [comment]
@fb33 Aware of this issue, problem is the amount of calculations needed to compute the UI out of the JSON that comes from ORT's Kotlin code within the web browser. We currently working on a major rewrite of the Reporter to optimize the Web App data format to make it easier for the web browser to render all the data.

**Comment by fb33** [comment]
Ok, thanks for these informations.

**Comment by tsteenbe** [comment]
Rewrite of the Reporter took to longer then expected but we nearly there ..

**Comment by tsteenbe** [comment]
@fb33 This issue has been fixed please update your local copy of ORT which includes the new Web App report and do a rebuild of ORT.  Can you let me know if the issue is now resolved?

**Comment by fb33** [comment]
Thanks, I'll test it.

**Comment by fb33** [comment]
Hello, I ve just tested it with the docker-bionic branch.
I did this on 2 different projects that generated ~110MB webApp report each.
And it works fine !

**Comment by sschuberth** [comment]
That's great to hear, thanks for testing @fb33!
