### ISSUE TITLE
Consider getting certified by the Linux Foundation's CII Best Practices Badge Program

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#2151]
Project page:
https://github.com/coreinfrastructure/best-practices-badge

Getting certified:
https://bestpractices.coreinfrastructure.org/en

Criteria:
https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md#current-criteria-best-practices-for-floss

**Comment by tsteenbe** [comment]
Closing as old issue, ORT has had a CII badge now for a couple of months
