### ISSUE TITLE
Add support for Nix packages

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#2179]
Add support the Nix package manager to ORT's analyzer component - https://nixos.org/nix/  

@maxhbr Can you help out?

The questions outline the prerequisites of things we need to figure out prior to be able to add Nix to ORT 

1.    How can you detect a project uses this specific package manager?
2.    How can you get the declared license for a package?
3.    How to can one get dependency tree including package names, versions?
4.    How can one obtain the source code for a dependency?
5.    How can one separate code dependencies from build/test ones?
6.    Can you provide example projects that can be used test implementation?

**Comment by deeplook** [comment]
Can we please finalize existing PRs to support existing needs like https://github.com/heremaps/oss-review-toolkit/issues/1534, first?

**Comment by sschuberth** [comment]
@deeplook, please don't hijack issues by linking to arbitrary other issues. @tsteenbe has clearly marked this as "help wanted", i.e. he does not intend to work on this in the short term. Also, filing issues (as a collection of ideas) is different from prioritizing them. Finally, this is an Open Source project, which is not solely driven by HERE's needs. Other contributing companies, like Bosch, might be interesting in implementing this before HERE does.

**Comment by tsteenbe** [comment]
@deeplook FYI I created this ticket after speaking to @maxhbr from TNG at FOSDEM and he asked me to create a ticket to capture what would be needed to add Nix to ORT so he could kick-off discussion on this topic with the Nix community and collect ideas.

**Comment by deeplook** [comment]
@sschuberth @tsteenbe Appologies, but I had no plan to highjack anything. I see the labels, and as much as I like Nix I was simply concerned that other missing things like conda support would drop on the priority list...

**Comment by sschuberth** [comment]
> I created this ticket after speaking to @maxhbr from TNG at FOSDEM

@maxhbr, is this issue still a feasible goal? Like, does Nix's dependency management fit into the way ORT's analyzer discovers dependencies / definition files?

**Comment by maxhbr** [comment]
not sure. Would be similar to supporting Ansible, Dockerfiles and Bazel at the same time, since it is so capable.

Further, it is very parameterized, it is not uncommon to define multiple targets in the same file. It is even not uncommon to just re-export the whole set of nixpkgs, which are currently over 80k. So, just scanning all targets is not a solution.

Maybe the default targets of flakes might be a smaller goal.

**Comment by sschuberth** [comment]
Considering the conversations I had a PackagingCon with @maxhbr, Nix is a "system package manager", not a "language package manager", but the latter is what ORT is focusing at. So I'm closing this as not planned.
