### ISSUE TITLE
Configurable package repository URL for nuget/dotnet analyzers

### ISSUE THREAD

**Issue by kallesoranko** [oss-review-toolkit/ort#2189]
Package repository for Nuget package repository URL should be configurable or being read from a configuration file. At the moment it is hard coded in `analyzer/src/main/kotlin/managers/utils/DotNetSupport.kt` at 

https://github.com/heremaps/oss-review-toolkit/blob/5f3bc12f16cd34b60d158b1f6af5865229943dfe/analyzer/src/main/kotlin/managers/utils/DotNetSupport.kt#L277-L280

and search API at

https://github.com/heremaps/oss-review-toolkit/blob/5f3bc12f16cd34b60d158b1f6af5865229943dfe/analyzer/src/main/kotlin/managers/utils/DotNetSupport.kt#L338-L341

**Comment by sschuberth** [comment]
Thanks for the suggestion. Do you happen to know where a regular (Visual Studio?) build picks up custom registries from?

**Comment by kallesoranko** [comment]
@sschuberth no, I do not know that yet. We have a workshop this week about compliance automation topics and this is one point that we'll be working on. I will update the progress here.

**Comment by kallesoranko** [comment]
That file would be `nuget.config`, see example (from https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file):  

```xml
<packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Contoso" value="https://contoso.com/packages/" />
    <add key="Test Source" value="c:\packages" />
</packageSources>
```

Not sure how search API URL is constructed, though. Or why does it point to different URL anyway? Will keep investigating...

**Comment by sschuberth** [comment]
Thanks @kallesoranko for the info, @julscha will be looking at implementing this.

**Comment by julscha** [comment]
> That file would be `nuget.config`, see example (from https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file):
> 
> ```
> <packageSources>
>     <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
>     <add key="Contoso" value="https://contoso.com/packages/" />
>     <add key="Test Source" value="c:\packages" />
> </packageSources>
> ```
> 
> Not sure how search API URL is constructed, though. Or why does it point to different URL anyway? Will keep investigating...

So, for now, I grasped as much: "For projects using the PackageReference format, NuGet uses local sources first, then sources on network shares, then HTTP sources, regardless of the order in the configuration files. NuGet always ignores the order of sources with restore operations." But what I haven't found out yet is where the "packageSources" information is stored when only using dotnet as a package manager. @kallesoranko  Do you happen to know that too?

**Comment by kallesoranko** [comment]
@julscha sorry about delay in reply, but I have to say that I am not so familiar with Nuget/Dotnet.

My best guess would be `.csproj` file since that file is used with Dotnet.

There is some information at https://stackoverflow.com/questions/52996560/how-to-register-new-nuget-package-source-on-net-core

**Comment by MarcelBochtler** [comment]
@kallesoranko I implemented the support for the configured repository URLs (See: #3176).
Anyways, there are some constraints:
1. The format of the catalog entry must be the same as the packages from https://api.nuget.org/v3/index.json (see #3190)
2. Authenticated package sources are not yet supported (see #3188)

Does this implementation work for your use case?
