### ISSUE TITLE
Provide a scan storage provider for scan results from SW360

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [oss-review-toolkit/ort#2211]
SW360 is able to store scan results as clearing report attachements. In order to have a roundtrip with SW360 a scan storage backend provider is needed that retrieves these attachments for usage in the ORT scanner.

Acceptance Criteria:
- [ ] Scancode results stored as clearing report attachment in SW360 are retrieved in ORT scan run
- [ ] Scancode results created by the ORT scanner are stored within SW360.

**Comment by blaumeiser-at-bosch** [comment]
Issue: In the logical sequence of event, at the end of the ORT scan step, it is difficult to upload the raw scan result to SW360 because the component at this point is not known and the creation is done in a later step. Therefore the store part of the provider needs some further discussison.

**Comment by neubs-bsi** [comment]
This is the library from antenna that is able to handle attachment uploads and downloads from sw360:
https://download.eclipse.org/antenna/releases/org/eclipse/sw360/antenna/sw360-client/
