### ISSUE TITLE
Synchronuous vs. asynchronuous scanning in ORT scanner

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [oss-review-toolkit/ort#2253]
It should be possible to run fresh scan asynchronously instead of a synchronuous run.

Reason: In a CI environment, the ORT scan is executed frequently. In these cases, it makes sense to not run the build for a very long time, but to provide information to the user fast by a report that states also the open components which have not been reviewed so far.

This enables the following use cases:
- The scan is outsourced to an external provider like Clearly Defined with an undefined resonse behavior
- The review can be extended by, e.g., manual steps, so that the scan result is assessed and approved by an compliance office.

Acceptance Criteria:
- [ ] Scans can be executed asynchronuously switched by a parameter in the cli
- [ ] The scan result is stored in the storage backend as usual and retrieved from there, e.g., in the next run, if already available

Open Question: Is there a feedback needed somehow, that retriggers the scan step automatically, as soon as the asynchronuous scans have been completed.

**Comment by sschuberth** [comment]
I believe the correct way to implement this is via https://github.com/oss-review-toolkit/ort/issues/4688. In particular, I don't see how this could be implemented in the CLI frontend with a good UX. So I'm closing this in favor of addressing this as part of the ORT server epic.
