### ISSUE TITLE
ReporterTests: Create / use a minimal test asset covering all important cases

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#2287]
The rather higher level tests for the reporters lack coverage for actually quite important cases. E.g. the `NoticeSummaryReporter` does not cover path excludes. Further the tests use test assets shared with other test so that they cannot be easily adjusted.

Let's create on test asset which covers all cases relevant test cases for reporters and use for all the reporter tests to get more meaningful test and a better use case coverage.

**Comment by sschuberth** [comment]
> E.g. the notice reporter does not cover path excludes.

Is this still true now that I see that https://github.com/heremaps/oss-review-toolkit/pull/2286 *did* need to also update expected test results for the NOTICE-BY-PACKAGE reporter?

**Comment by fviernau** [comment]
> Is this still true now that I see that #2286 _did_ need to also update expected test results for the NOTICE-BY-PACKAGE reporter?

Thanks, I've updated the description accordingly.

**Comment by sschuberth** [comment]
I believe we have that by now in https://github.com/oss-review-toolkit/ort/blob/3832de6b085db813797df95e62bb6e8d8e2e2ce0/reporter/src/funTest/kotlin/TestData.kt.

**Comment by sschuberth** [comment]
Reopening because @mnonnenmacher says:

> Not all reporter tests use the TestData yet, and some features like scope excludes or license configurations are not tested with the reporters.

**Comment by sschuberth** [comment]
This is somewhat related to https://github.com/oss-review-toolkit/ort/issues/2842.

**Comment by mnonnenmacher** [comment]
This is also related to #5991, as an abstraction for the `OrtResult` could make it easier to use mocks in some tests without having to create a complete `OrtResult`.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
