### ISSUE TITLE
Understanding the Evaluator Errors

### ISSUE THREAD

**Issue by CleanHit** [oss-review-toolkit/ort#2301]
For testing purposes I've used the default `rules.kts` and `licenses.yml` files. I don't quite understand this error and its suggested solution.
```bash
13:06:39.469 [main] ERROR com.here.ort.commands.EvaluatorCommand - RuleViolation(rule=COPYLEFT_IN_DEPENDENCY, pkg=Identifier(type=Maven, namespace=org.glassfish, name=javax.json, version=1.0.4), license=GPL-2.0-only, licenseSource=DECLARED, severity=ERROR, message=The project Gradle:my_app:app: has a dependency licensed under the ScanCode copyleft catagorized license GPL-2.0-only., howToFix=A text written in MarkDown to help users resolve policy violations
which may link to additional resources.)
```

**Comment by sschuberth** [comment]
Well, that is the error that gets trigger by the rule violation. I.e. it's not an error that something went wrong with running the evaluator itself; it's the outcome of evaluating the rules on the project.

**Comment by CleanHit** [comment]
> Well, that is the error that gets trigger by the rule violation. I.e. it's not an error that something went wrong with running the evaluator itself; it's the outcome of evaluating the rules on the project.

And I'm getting that because the `Severity` in this section is set to `ERROR`:
```kotlin
// Define a rule that is executed for each dependency of a project.
    dependencyRule("COPYLEFT_IN_DEPENDENCY") {
        licenseRule("COPYLEFT_IN_DEPENDENCY", LicenseView.CONCLUDED_OR_DECLARED_OR_DETECTED) {
            require {
                +isCopyleft()
            }

            issue(
                Severity.ERROR,
                "The project ${project.id.toCoordinates()} has a dependency licensed under the ScanCode " +
                        "copyleft catagorized license $license.",
                howToFixDefault()
            )
        }
    }
```
I wander, why is it being categorise as an error?

**Comment by sschuberth** [comment]
> I wander, why is it being categorise as an error?

It's simply an example. Each user / company using ORT is responsible for create its own rules and may choose to categorize this differently, or not to use this rule at all.

**Comment by CleanHit** [comment]
OK :). Is there a documentation on the required syntax for creating own `rules.kts` and `licenses.yml` files? There are some file parts that I have a hard time to follow. e.g.:

1. Regarding the `rules.kts` file:
    1. Where are `LicenseView.CONCLUDED_OR_DECLARED_OR_DETECTE` or `LicenseSource.DETECTED` being defined?
    2. I see the usage of `-isExcluded()` but I don' t see its definition anywhere in the file.

1. Regarding the `licenses.yml` file:
    1. Where can I find the allowed file structure with all the allowed yml keys?

Since I must provide the `--rules-file` and `-license-configuration-file` inputs for the `Evaluator`, I must use syntactically correct inputs.

**Comment by tsteenbe** [comment]
@CleanHit  It's on my to-do to write proper docs for how to write the rules but for definitions simply see the comments in the source code.

- `LicenseView.CONCLUDED_OR_DECLARED_OR_DETECTED`: https://github.com/heremaps/oss-review-toolkit/blob/master/evaluator/src/main/kotlin/LicenseView.kt
- `LicenseSource.DETECTED`: https://github.com/heremaps/oss-review-toolkit/blob/master/model/src/main/kotlin/LicenseSource.kt
- isExcluded: https://github.com/heremaps/oss-review-toolkit/blob/master/evaluator/src/main/kotlin/PackageRule.kt
- `licenses.yml`: https://github.com/heremaps/oss-review-toolkit/blob/master/model/src/main/kotlin/licenses/License.kt

**Comment by CleanHit** [comment]
@tsteenbe Thanks for the links. Since Kotlin or Java are not my strongest suites could you please explain me: 
1. what does `+` and `-` in the this code fragment mean:
```kotlin
        licenseRule("COPYLEFT_LIMITED_IN_HERE_SOURCE", LicenseView.CONCLUDED_OR_DECLARED_OR_DETECTED) {
            require {
                -isExcluded()
                +isCopyleftLimited()
            }
```
2. What actually happens when I pass `--rules-file ./rules.kts` to the evaluator? How can the _rules.kts_ file use the ` -isExcluded()` function if it's being defined in <https://github.com/heremaps/oss-review-toolkit/blob/master/evaluator/src/main/kotlin/PackageRule.kt> and I don't see any import of _PackageRule.kt_ in the _rules.kts_ file

**Comment by mnonnenmacher** [comment]
>1. what does `+` and `-` in the this code fragment mean:

`+` adds the matcher as requirement, `-` adds the inverse of the matcher as requirement (by enclosing it with `Not()`).

These operator functions are defined here:
https://github.com/oss-review-toolkit/ort/blob/1809de1bb866a7e3c97de7c59b272934846a2874/evaluator/src/main/kotlin/Rule.kt#L153-L167

>1. What actually happens when I pass `--rules-file ./rules.kts` to the evaluator? How can the _rules.kts_ file use the ` -isExcluded()` function if it's being defined in https://github.com/heremaps/oss-review-toolkit/blob/master/evaluator/src/main/kotlin/PackageRule.kt and I don't see any import of _PackageRule.kt_ in the _rules.kts_ file

The evaluator automatically adds a preface to the `rules.kts` with imports for most required classes:
https://github.com/oss-review-toolkit/ort/blob/1809de1bb866a7e3c97de7c59b272934846a2874/evaluator/src/main/kotlin/Evaluator.kt#L36-L50

**Comment by CleanHit** [comment]
@mnonnenmacher Thank you for your clarification.
