### ISSUE TITLE
Low Speed of gradle dependency analyze

### ISSUE THREAD

**Issue by dd-jy** [oss-review-toolkit/ort#2302]
Hi,
I tested the analyzer module for the various package managers.
And then I wonder that the performance of analyzer module for gradle is actually low compared to other package mangers (npm, pip, maven).

Can you explain it to me?
Thank you!

**Comment by sschuberth** [comment]
That's probably because of https://github.com/heremaps/oss-review-toolkit/issues/2115, although that affects Maven projects, too.

For NPM projects we basically have the same issue, and there it's even worse, as there is no NPM command to only determine the dependencies without actually installing them.

**Comment by dd-lge** [comment]
Actually, it's too low even if it takes time to install the jars.
I used the gradle license plugin(https://github.com/hierynomus/license-gradle-plugin) previously.
I tested the same java project with the ORT and gradle license plugin.
The plugin only took 6 sec for downloading license information.

On the other hand, npm runtime is acceptable compared to license-checker(https://github.com/davglass/license-checker) even though it includes installation time.

I hope this information is helpful.
Thank you for your help! It's really helpful to me :).

**Comment by sschuberth** [comment]
> Actually, it's too low even if it takes time to install the jars.

Well, I'd say that depends on the time need to download the JARs :wink:

But I cannot rule out that there are additional factors that influence performance. So let's keep this open until #2115 is fixed and you can confirm the performance to be somewhat on par with the *license-gradle-plugin*.

**Comment by sschuberth** [comment]
Issue #2115 was fixed meanwhile, and additionally I just merged https://github.com/oss-review-toolkit/ort/pull/3502, which in sum should greatly improve Gradle project analysis thanks to @oheger-bosch's work.
