### ISSUE TITLE
StaticHtml is too Large because of the Excludes

### ISSUE THREAD

**Issue by CleanHit** [oss-review-toolkit/ort#2312]
I think it's meaningful to exclude:

1. Listing of the excluded scopes in the **Scopes** column.
1. Showing package information if it only exists in an excluded scope.

Maybe it is possible to define a flag for the `StaticHtml` output to include **VCS Information** only from included scopes, the Default output could have full **VCS Information** as it does so far.

**Comment by sschuberth** [comment]
The Static HTML report became sort of legacy by now, so this is not going to happen probably.
