### ISSUE TITLE
Distinguish declared and detected licenses in Cyclone DX output

### ISSUE THREAD

**Issue by CleanHit** [oss-review-toolkit/ort#2314]
Why do libraries have more than one license assigned to them? For example:
```xml
<group>androidx.coordinatorlayout</group>
<name>coordinatorlayout</name>
<version>1.0.0</version>
<purl>pkg:maven/androidx.coordinatorlayout/coordinatorlayout@1.0.0</purl>
```
Has all the following license assigned to it:
```xml
<licenses>
  <license>
    <id>Apache-1.1</id>
  </license>
  <license>
    <id>Apache-2.0</id>
  </license>
  <license>
    <id>BSD-2-Clause</id>
  </license>
  <license>
    <id>BSD-3-Clause</id>
  </license>
  <license>
    <id>LGPL-2.1-only</id>
  </license>
  <license>
    <id>LGPL-2.1-or-later</id>
  </license>
  <license>
    <id>MIT</id>
  </license>
  <license>
    <id>OFL-1.1</id>
  </license>
  <license>
   <name>LicenseRef-scancode-unicode</name>
  </license>
  <license>
    <name>NOASSERTION</name>
  </license>
</licenses>
```
According to its [Maven repository](https://mvnrepository.com/artifact/androidx.coordinatorlayout/coordinatorlayout/1.0.0) it uses only the **Apache 2.0** License.

**Comment by sschuberth** [comment]
Because `Apache-2.0` is only the *declared* license, i.e. what the author intents / claims the library to be licensed under. However, from actually scanning the source code with a license scanner, additional licenses might be *detected*. For completeness, ORT puts both *declared* and *detected* licenses into the BOM.

**Comment by CleanHit** [comment]
> For completeness, ORT puts both _declared_ and _detected_ licenses into the BOM.

OK, I don't remember seeing any split into _declared_ and _detected_ Licenses inside the library component, I'll check that again.

**Comment by sschuberth** [comment]
That's the whole point: Libraries only declare *declared* licenses in their meta-data. ORT additionally *detects* licenses e.g. from `LICENSE` files or file headers etc., for the ORT user to compare if *declared* and *detected* licenses match.

**Comment by CleanHit** [comment]
I still think that a distinction must be made in the resulting BOM file, I for example rely on that distinction. e.g.
```xml
<licenses>
  <license type="detected">
    <id>Apache-1.1</id>
  </license>
  <license type="declared">
    <id>Apache-2.0</id>
  </license>
  <license type="detected">
    <id>BSD-2-Clause</id>
  </license>
</licenses>
```
Or by their place order e.g. the first license is always the _declared_ one and the following licenses are always the _detected_ ones, if using  `<license type="declared"> ... </license>` and `<license type="detected"> ... </license>` is not an option.

**Comment by sschuberth** [comment]
I like your proposal for a `type` attribute on the `license` tag. However, in order to support it, we'd need Cyclone DX to implement that feature. I've filed an [issue](https://github.com/CycloneDX/cyclonedx-core-java/issues/31) in their project about this.

**Comment by CleanHit** [comment]
Is it possible for you to sort them like suggested in the second option until CycloneDX acts on your [issue](https://github.com/CycloneDX/cyclonedx-core-java/issues/31)?

**Comment by sschuberth** [comment]
While sorting would probably be possible, how do you know when declared licenses end and detected licenses start, as you could have multiple declared licenses (e.g. for dual-licensed projects)? Also, we kannot add XML comments or anything like that as ORT is not writing the XML, but the Cyclone DX Java library does.

But if you have any proposal, we are also happily accepting pull requests :wink:

**Comment by CleanHit** [comment]
I've seen yesterday that cycloneDX added the needed support for this issue. Do you  know approximately when you'll be able to implement it in ORT?

**Comment by sschuberth** [comment]
Probably within a week or so, due to current high workload. But to quote myself again:

> we are also happily accepting pull requests :wink:

**Comment by CleanHit** [comment]
Do I need to run the whole ORT process from scratch after the change or can I use my _scan-result.yml_ file with the evaluator and then execute the reporter to create the new _bom.xml_ file?

**Comment by sschuberth** [comment]
The latter, i.e. no need to perform another scan. The reporter only brings existing analyzer / scan results into a different form.

PS: This has already been implemented by @julscha but needs to first pass an internal review.

**Comment by CleanHit** [comment]
> PS: This has already been implemented by @julscha but needs to first pass an internal review.
Good to know :-).

**Comment by CleanHit** [comment]
> PS: This has already been implemented by @julscha but needs to first pass an internal review.

@sschuberth, @julscha Is there a branch that I can check out in the meanwhile and try the changes with my tool?

**Comment by sschuberth** [comment]
Not yet, sorry. The review is called *internal* review because, well, it's *internal* 😉

**Comment by CleanHit** [comment]
> Not yet, sorry. The review is called _internal_ review because, well, it's _internal_ :wink:

I'm just being impatient :smiley:.

**Comment by CleanHit** [comment]
@sschuberth Any positive news on this matter? :smiley:

**Comment by sschuberth** [comment]
@CleanHit, the PR is now under public review, see #2545.
