### ISSUE TITLE
Allow setting scriptable HowToFix texts for Analyzer and Scanner errors

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#2347]
Propose we implement a mechanism to allow defining HowToFix texts for Analyzer and Scanner errors similar to Evaluator to provide user instructions how they can fix their errors.

Making it scriptable versus a config file will allow use of conditions and variables.

Thought a basic implementation would be simply a string matcher on error message similar to error/rule violation resolutions.

**Comment by fviernau** [comment]
Proposal for this task:

RuleViolations do have a property howToFix: String which can be used to inject how to fix markdown texts into the reports via
the evaluator rules kotlin script file. This task is about providing means for injecting custom how to fix texts for OrtIssues.

From one perspective it may seem consistent to just add a similar howToFix property to OrtIssue, but that would require to pass the custom how to fix configuration to the analyzer and to the scanner and thus these how to fix texts would be included in the OrtResult in the very first steps. Passing the howToFixTexts only to the reporter seems to be better and it would also be consistent, not with the RuleViolation.howToFix but with how rule violation resolutions are passed.

To enable some degree of flexibility I propose to use a kotlin script file, which implements a resolver for such howToFix texts, for any given OrtIssue.
