### ISSUE TITLE
Allow to limit what entities (projects vs packages) get scanned

### ISSUE THREAD

**Issue by dd-jy** [oss-review-toolkit/ort#2349]
Hi,
The scanner module works to scan including project id. And there is no option to exclude project id.
But the downloader module has the option to select entities from the ORT file's analyzer result.

I think this option is also needed for the scanner.
Because the ORT can be used for the companies' commercial project. And this case the project id should not excluded to scan.

Please consider adding this option.

**Comment by sschuberth** [comment]
> And this case the project id should not excluded to scan.

I'm confused by this, the project is currently *not* excluded from the scan. But you are asking it to be excluded, right?

**Comment by dd-lge** [comment]
Yes, that's right. Sorry for my poor English. ;(

**Comment by sschuberth** [comment]
Then we can basically implement this as suggested at https://github.com/heremaps/oss-review-toolkit/issues/2130, would you agree?

**Comment by dd-lge** [comment]
I agree. That's exactly what I mean.

**Comment by sschuberth** [comment]
Ok, great. Let me still leave this issue open to ensure that the feature to have a separate scanner for projects can also be used to specify no scanner at all for projects.
