### ISSUE TITLE
webapp format reporter can be displayed result of scanner without analyzer results.

### ISSUE THREAD

**Issue by dd-jy** [oss-review-toolkit/ort#2369]
If the 'scan-result.json' file doesn't have the result of analyzer, then the reporter doesn't show any result. 
However, in reality, the scanner results contain the information about the detected license and package scan results, so these information can be displayed.
Can you improve it to make the report without analyzer results?

**Comment by sschuberth** [comment]
> If the 'scan-result.json' file doesn't have the result of analyzer

My first thought was that this should actually never happen, as the analyzer result usually is the input for the scanner, and the results get amended. But I guess your use-case is to scan a directory directly, and not use an analyzer result as the input for the scanner, correct?

**Comment by dd-lge** [comment]
Yes, That's correct.
If the project doesn't use the package manager, (for example, firmware project based on linux), then it can only have a scanner result. And ORT already supports to run the scanner directly without analyzer result.

**Comment by mnonnenmacher** [comment]
If ORT does not detect a package manager it will create a project of the type `Unmanaged` in the analyzer result. An `Unmanaged` project is also created if no package manager is detected in the root repository to ensure that all files in the repository are mapped to a project.

If the directory you are scanning is checked out from a VCS  the ORT analyzer will detected that and add the VCS information to the analyzer result. You can pass this analyzer result to the scanner and then report generation will work.

**Comment by dd-lge** [comment]
@mnonnenmacher 
Is ORT the tool for only project that have dependency information with the VCS information?

If not, there are many projects that didn't use the package manager but use the source code of open source software. In this case, it doesn't have the analyzer results but has the scanner results. 

So I suggested the webapp format reporter should display only it has scanner results without analyzer result.

**Comment by tsteenbe** [comment]
@dd-jy  I am currently working on a proposal for an SPDX package manifest to provide package metadata for cases where source code was copied into an project. This will be usefull for C/C++ where there is no package manager. Having the package metadata will allow ORT in the future to looks up vulnerabilities info or give feedback whether there are upstream changes.

**Comment by dd-jy** [comment]
@tsteenbe Thank you for the information. Then the webapp format reporter with only scanner results will not be supported?

**Comment by tsteenbe** [comment]
@dd-jy Update from my side - see for the proposal for an SPDX package manifest https://github.com/spdx/spdx-spec/issues/439 - we will soon implement an SPDX package manifest _analyzer_ in ORT with the idea that you run the _analyzer_ which will then pick-up the *.spdx.yml, *.spdx.yaml or *.spdx.json files defining the metadata for say C/C++ package, then you run the ORT's _scanner_ followed by optionally the ORT's _evaluator_ and/or _reporters_.

>  Then the webapp format reporter with only scanner results will not be supported?

Why would you only like to see the scanner results and not package metadata that to which scanner results belong?

Alternatively, but this something we need to discuss in the [ORT TSC](https://github.com/oss-review-toolkit/ort-governance/blob/master/CONTRIBUTING.md) we could insert an empty/stub _analyzer_ result into _scanner_ output so people who don't run the analyzer at least get a WebApp report with scanner results.

**Comment by dd-jy** [comment]
I understood it.

Using the SPDX package manifest analyzer, ORT can show the scanned result (detected result) that can be compared with analyzer result(declared result).

Actually, only scanned result could be reported with Scancode workbench.
So I closed this issue.
