### ISSUE TITLE
Read configuration files from default location

### ISSUE THREAD

**Issue by mnonnenmacher** [oss-review-toolkit/ort#2424]
ORT uses many configuration files, for example for curations, license configuration, and custom license texts. Currently these need to be passed to the ORT commands as command line options. To simplify usage, ORT should by default look for those files in the `~/.ort` configuration directory, for example `~/.ort/curations.yml`.

**Comment by sschuberth** [comment]
Implemented as part of https://github.com/oss-review-toolkit/ort/pull/3078.
