### ISSUE TITLE
No error or warning for invalid license ID during NOTICE generation

### ISSUE THREAD

**Issue by uszeiss** [oss-review-toolkit/ort#2429]
When the `licenses.yml` contains a custom license with an invalid ID (e.g `INTERNAL`), and I generate the reports, no warning or error message is shown in the (debug) logs of the reporter.

As suggested by @tsteenbe , the reporter should throw an error when the `licenses.yml` contains invalid SPDX IDs.

**Comment by mnonnenmacher** [comment]
The implementation was changed to use the `SpdxSingleLicenseExpression` instead of a string for the license IDs in #2723, so it would fail now if a license cannot be parsed to an SPDX expression.
