### ISSUE TITLE
Provide an easy and documented way to customise notices

### ISSUE THREAD

**Issue by uszeiss** [oss-review-toolkit/ort#2433]
The `notice-pre-processor.kts` file allows for customisation of the generated notice file, see https://github.com/oss-review-toolkit/ort/blob/master/docs/notice-pre-processor-kts.md.

Not all customisations seem possible, though. I would like to:

* customize the notice separator
* get rid of the separator between the different headers
* include the license name/id before the license text
* show the package URL
* change the order of the copyright statement and the license text (minor prio)
* change the automatically inserted texts such as `The following copyrights and licenses were found in the source code of this package` (minor prio)

Ideally, an entry for a package could be customised to look like this:
```
<name of package> (used under <license name>) <homepage url>
<state changes to original code if any>
<copyright notice>
<license text>
```
Note that I'm not sure how to to automatically fill the 'state changes to original code' part in this case, but this is a problem not to be solved as part of this issue.

**Comment by tsteenbe** [comment]
@uszeiss  Can you clarify the "change the order of the copyright statement and the license text" point? What would you like to do?

**Comment by uszeiss** [comment]
I was assuming ORT manages the copyright info and the license info separately such that one could in principle define the order in which these two bits of information will be shown in the notice. This assumption might be wrong of course.

**Comment by apfelkraut** [comment]
Just for clarification: The element `<state changes to original code if any>` aims at satisfying the obligation of some Copyleft licenses to describe any changes made to the original source code. A sample text could be: _"The original source code has been modified. For modifications please see "../3rdPartySW/Component_XYZ/File_A.diff" and "../3rdPartySW/Component_XYZ/File_B.diff"_. 

Ultimately this text could be specified within the project specific curations and is for sure a new/separate feature.

**Comment by apfelkraut** [comment]
I want to add an additional requirement to the list of @uszeiss :

- ability to add any characters (markup or free text) before or after the shown elements like `<name of package>`

_Use case:_ Depending on the application you always want to display (or at least provide somehow) this text as the FOSS Disclosure Statement to the user. Sometimes pure ASCII is sufficient, other times HTML/LaTeX is requested. In the worst case you have to prepare for some old-fashioned documentation software that needs some kind of weird XML.

**Comment by uszeiss** [comment]
Perhaps supporting a Freemarker template or something similar might be a solution?

**Comment by sschuberth** [comment]
Freemaker-based templating of NOTICE files is available since https://github.com/oss-review-toolkit/ort/pull/2925.
