### ISSUE TITLE
Usage document of cd-upload

### ISSUE THREAD

**Issue by dd-lge** [oss-review-toolkit/ort#2439]
There is no usage document of cd-upload command.
Is it a beta function yet?
Can you give me an example file of input file of this command?

**Comment by sschuberth** [comment]
It's not beta, but was so far mostly targeting internal workflows. Did you run `./gradlew :cli:run --args="cd-upload --help"`? If so, what information were you missing from that help? The input to the command are curation files as described at https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-curations-yml.md.

**Comment by dd-lge** [comment]
I ran the help command and used the input based on config-file-curations.yml.
And then ORT printed the below error message.

```
15:37:05.487 [main] ERROR org.ossreviewtoolkit.commands.ClearlyDefinedUploadCommand - The REST API call failed with: The contribution has failed because some of the supplied component definitions do not exist
15:37:05.491 [main] DEBUG org.ossreviewtoolkit.commands.ClearlyDefinedUploadCommand - Error: The contribution has failed because some of the supplied component definitions do not exist
    at GitHubCurationService.addOrUpdate (/opt/service/providers/curation/github.js:213:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async updateCurations (/opt/service/routes/curations.js:85:18)
    at async /opt/service/middleware/asyncMiddleware.js:6:5
Usage: ort cd-upload [OPTIONS]
```


And I solved this problem after seeing this commit message (https://github.com/oss-review-toolkit/ort/commit/1b09ae42ee6cc891380f1c8e06f78a4e0363959e).

The id that I tried to curate was only existed PRODUCTION server.

**Comment by sschuberth** [comment]
> The id that I tried to curate was only existed PRODUCTION server.

Great that you were able to figure it out!
