### ISSUE TITLE
Analyzer scan fails 

### ISSUE THREAD

**Issue by ghost** [oss-review-toolkit/ort#2451]
The following projects have failed to be scanned in all cases we've tried them.

All of them have been tested on two Ubuntu machines (18.04/19.10) and failed on both.

https://github.com/mytechgroup/tor
Failed after 30 minutes / interrupted after 60 minutes. Other gradle dependent projects have worked on our machines. 
[mytech-tor-log.log](https://github.com/oss-review-toolkit/ort/files/4414954/mytech-tor-log.log)

https://github.com/oss-review-toolkit/ort/
Fails after 10 minutes. Other maven dependent projects have worked on our machines.
[ort-log.log](https://github.com/oss-review-toolkit/ort/files/4414956/ort-log.log)

**Comment by sschuberth** [comment]
There are indeed several problems in each of these projects.

In no particular order for the **tor** project (I'll edit this list):

```
Downloading https://services.gradle.org/distributions/gradle-4.4-all.zip
..............................................................................................
Could not determine java version from '11.0.6'.
```

So the project uses ancient Gradle 4.4, and you are running ORT under Java 11, but Gradle 4.4 does not support Java 11 yet. You either need to upgrade the Gradle version *in the project*, or downgrade the java version *on your machine*.
