### ISSUE TITLE
License text from package's LICENSE.TXT does not appear in notice file

### ISSUE THREAD

**Issue by uszeiss** [oss-review-toolkit/ort#2452]
Inspired by [this comment on another Jira issue](https://github.com/oss-review-toolkit/ort/issues/1788#issuecomment-580256830), I want to show the license text of one of my project's dependencies in the `NOTICE_BY_PACKAGE` file.
The (Maven) dependency (`com.example.abc:2.0.0`) provides its license text in the `LICENSE.txt` file in the `META-INF` subdirectory of the jar.

I use the following `config` file to enable to detection of the license text by ORT's scanner:
```
ort {
  scanner {
    archive {
      patterns = [
   	"COPYING*",
        "Copying*",
        "copying*",
        "COPYRIGHT",
        "Copyright",
        "copyright",
        "LICENCE*",
        "Licence*",
        "licence*",
        "*.LICENCE",
        "*.Licence",
        "*.licence",
        "LICENSE*",
        "License*",
        "license*",
        "*.LICENSE",
        "*.License",
        "*.license",
        "UNLICENCE",
        "UNLICENSE",
        "Unlicence",
        "Unlicense",
        "unlicence",
        "unlicense",
        "**/LICENSE*",
        "**/License*",
        "**/license*"
      ]
      storage {
        localFileStorage {
          compression = true
          directory = "~/.ort/scanner/archive"
        }
      }
    }
  }
}
```
Now  I can see the package's license text in the archive ZIP file under `~/.ort/scanner/archive` but it does not appear in the `NOTICE_BY_PACKAGE` report, which still shows the standard license text.
But I can see the following error in the log of the notice reporter:
```
ERROR org.ossreviewtoolkit.utils.storage.FileArchiver - Could not unarchive from Maven/com.example/abc/2.0.0/8cb78a0db70208f4692546fc6259af1c7130e23a: FileNotFoundException: /home/user/.ort/scanner/archive/Maven/com.example/abc/2.0.0/8cb78a0db70208f4692546fc6259af1c7130e23a/archive.zip (No such file or directory)
```
When I check the directory, I see an `archive.zip.xz` file instead of an `archive.zip` file. If I repackage the '.xz` file into a `.zip` archive and run the notice reporter again, the error disappears. But the notice still shows the standard license text.

The project's source code as well as the dependencies source and jar files can be found as attachments in [this thread](https://ort-talk.slack.com/archives/C9NNJ54B1/p1585572859068000) of ORT's Slack channel.

I can provide further input or sources if needed.
I'd appreciate any support. Thanks.

**Comment by sschuberth** [comment]
> When I check the directory, I see an `archive.zip.xz` file instead of an `archive.zip` file.

@mnonnenmacher, could this be a side-effect of https://github.com/oss-review-toolkit/ort/pull/2438?

**Comment by uszeiss** [comment]
I can confirm that I do not see the 'No such file' error in my log if I set `compression = false` in the `config`file. ORT creates an `archive.zip` file in this case.
