### ISSUE TITLE
Container build failed on downloading nodejs

### ISSUE THREAD

**Issue by pilvikala** [oss-review-toolkit/ort#2464]
I can't build the docker container using the command 
`docker build -t ort .`

error:
```
> Task :reporter:compileKotlin

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kotlinNodeJsSetup'.
> Could not resolve all files for configuration ':detachedConfiguration3'.
   > Could not download node-12.14.0-linux-x64.tar.gz (org.nodejs:node:12.14.0)
      > Could not get resource 'https://nodejs.org/dist/v12.14.0/node-v12.14.0-linux-x64.tar.gz'.
         > Read timed out
```

I tried on two different computers on two different networks.

[build.log](https://github.com/oss-review-toolkit/ort/files/4437294/build.log)

**Comment by sschuberth** [comment]
I might have been a temporary outage at the https://nodejs.org/ side. Please try again shortly.

**Comment by pilvikala** [comment]
Yes, it looks like the https://nodejs.org/dist/v12.14.0/node-v12.14.0-linux-x64.tar.gz is returning 500 but it sometimes works. This has been happening the last few days. Is there something we could do to make the build of the container more stable?

**Comment by sschuberth** [comment]
As a quick measure, if you're fine with the Docker build writing to the host, you could try mounting the host's Gradle directory into the container so the dependencies get cached between builds instead of being re-downloaded.

**Comment by pilvikala** [comment]
I am using gitlab to build this because I actually do not want anything to cache. If this happens more often, I'll need to consider it though. Thanks!
