### ISSUE TITLE
Pub: Revisit handling of skipped `sdk` packages

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#2470]
ORTs `Pub` implementation has the recursive `buildDependencyTree()`. It skips all packages which have the attribute `source = sdk` set in the `lockfile` since the implementation cannot parse such packages. As the only `dependant` of `archive` is `flutter_test` which is skipped there is no `(package) reference` to `archive`. Similar for other packages. See also: https://github.com/oss-review-toolkit/ort/blob/master/analyzer/src/main/kotlin/managers/Pub.kt#L248-L250

_Originally posted by @fviernau in https://github.com/oss-review-toolkit/ort/pull/2466_

It needs to be decided if unreferenced packages should be removed and if so the implementation needs to be changed.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
