### ISSUE TITLE
docker build issue

### ISSUE THREAD

**Issue by pilvikala** [oss-review-toolkit/ort#2477]
The docker container cannot be built using
`docker build -t ort .`.
Build error:
 Version '0.40.0-3ubuntu1~18.04.1' for 'cargo' was not found

[build.log](https://github.com/oss-review-toolkit/ort/files/4449719/build.log)

**Comment by sschuberth** [comment]
That was already fixed meanwhile as part of https://github.com/oss-review-toolkit/ort/pull/2476/commits/dbc5b3734108663cd0b83613099a16db4c8b1c23.
