### ISSUE TITLE
ORT analyzer has false negatives in yarn

### ISSUE THREAD

**Issue by ghost** [oss-review-toolkit/ort#2483]
I have been scanning 7 projects that contain a yarn.lock file aswell as a package.json file.
If yarn is not installed, analysis will fail.
If yarn is installed, ORT analyzes the package.json, lists its dependencies and outputs that has_issue: false.

Thus the user believes ORT has found all dependencies, although none of the yarn dependencies were found. 

Example project: https://github.com/verekia/js-stack-from-scratch.git
19 dependencies found, all NPM. No issues. 
Example 2: https://github.com/patternfly/patternfly-react.git
Finds 3404 dependencies, of which 3404 are NPM.

**Comment by sschuberth** [comment]
> I have been scanning 7 projects that contain a yarn.lock file aswell as a package.json file.
> If yarn is not installed, analysis will fail.

That's expected. If a `yarn.lock` is present we assume the project must be analyzed with Yarn, and not as a fallback with NPM. Thus Yarn as an external tool is required in this case.

> Thus the user believes ORT has found all dependencies, although none of the yarn dependencies were found.

I have a hunch that there might be a misunderstanding of what "Yarn dependencies" are in this context: Both Yarn and NPM are package managers for NPM packages, that is, there is no such thing as a Yarn "package format". That's also why all package dependencies in a Yarn project have an ` id`  starting with `NPM`.

See e.g. how the *project* here has an ` id` starting with `Yarn`:

https://github.com/oss-review-toolkit/ort/blob/745fcc2d3aa32bef9d11ac5eb60182233ece9dd5/analyzer/src/funTest/assets/projects/synthetic/yarn-expected-output.yml#L3

But its package dependencies have an `id` starting with `NPM`:

https://github.com/oss-review-toolkit/ort/blob/745fcc2d3aa32bef9d11ac5eb60182233ece9dd5/analyzer/src/funTest/assets/projects/synthetic/yarn-expected-output.yml#L23

This is BTW similar to Gradle and Maven: Maven is both a build system and a "package format", i.e. a convention about the server-side structure for storing artifacts. Gradle (when used for the JVM) uses Maven artifacts, so Gradle projects have Maven dependencies, not Gradle dependencies.

Does that resolve the confusion?

**Comment by emalstm** [comment]
Yes it does! Thank you :)
