### ISSUE TITLE
Provide summary output format

### ISSUE THREAD

**Issue by pilvikala** [oss-review-toolkit/ort#2521]
It would be useful for testing of ORT on different systems and for the CI pipeline to get only a human readable summary of the analysis.
An example output that I use after parsing the analyzer-result.json file:

Elapsed time:14.979767084121704 
Environment:
  ort_version:0.1.0-SNAPSHOT
  java_version:11.0.6
  os:Linux
  variables:{'SHELL': '/bin/bash', 'TERM': 'xterm-256color'}
  tool_versions:{}
Has Issues: True
Issues:
analyzer ERROR:Multiple projects with the same id 'NPM:@netflixadseng:an-ER-fade-in:1.0.0' found. Not adding the project defined in 'https://github.com/NetflixDev/an-ER-fade-in.git/dist/npm/package.json' to the analyzer results as it duplicates the project defined in 'https://github.com/NetflixDev/an-ER-fade-in.git/src/package.json'.
Dependencies: 476
Dependencies while ignoring version numbers: 406
NPM::acorn-jsx:3.0.1
NPM::acorn:3.3.0
NPM::acorn:5.4.1
NPM::ajv-keywords:2.1.1
...

**Comment by sschuberth** [comment]
Closing this as it could easily be implemented with custom post-processing of the existing YAML / JSON result files.
