### ISSUE TITLE
How to remove the directories in the /tmp directory?

### ISSUE THREAD

**Issue by lemoshi** [oss-review-toolkit/ort#2538]
Hi team, I found there are many directories generated in the /tmp when more and more scans are executed. Do you know how these directories are generated and how I can remove this automatically after the scanning? Thanks for your time.
<img width="1392" alt="Screen Shot 2020-04-27 at 12 27 52 AM" src="https://user-images.githubusercontent.com/10217033/80313755-aca3c880-881f-11ea-939e-a26a938d2bcb.png">

**Comment by sschuberth** [comment]
The `ort*process` directories are used to store temporary files for *stdout* / *stderr* of externals tools. The temporary files are in fact deleted, but the (empty) parent directory was not so far, which is something that I'll fix.

The `scancode-tk-*` directories are not created by ORT I believe.
