### ISSUE TITLE
Consider leveraging GitHub as a security vulnerability provider

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#2561]
At least for dependencies whose source code is hosted on GitHub, it could be possible to leverage GitHub itself as a provider for security vulnerability information via its [API](https://developer.github.com/v4/object/repositoryvulnerabilityalert/).

**Comment by tsteenbe** [comment]
@sschuberth  Already have been testing GitHub GraphQL API together with @adambhere  in addition to several other security APIs in preparation for implementing ORT's auditor component. From our preliminary testing it seems to be the best of the bunch - only restriction to keep in mind is the 5000 calls per hours limit

**Comment by sschuberth** [comment]
> ORT's auditor component

"advisor"?

**Comment by sschuberth** [comment]
Also see https://github.blog/changelog/2020-07-06-using-open-source-static-analysis-tools-with-code-scanning/.

**Comment by sschuberth** [comment]
And https://github.blog/changelog/2020-09-08-github-advisory-database-contains-all-npm-security-advisories/.

**Comment by sbs2001** [comment]
@sschuberth  VulnerableCode collects data from the mentioned sources, see https://github.com/nexB/vulnerablecode/blob/main/vulnerabilities/importers/github.py  .

**Comment by sschuberth** [comment]
Thank for confirming @sbs2001. However, an advantage of a direct integration with GitHub might be that no additional service (like VulnerableCode) needs to be run by the user, so I'll keep this open for now even if we're going to have [integration with VulnerableCode](https://github.com/oss-review-toolkit/ort/issues/3287).

**Comment by sschuberth** [comment]
Also see https://github.com/advisories.

**Comment by sschuberth** [comment]
FYI, [GitHub Advisory Database now includes Go advisories](https://github.blog/changelog/2021-05-18-github-advisory-database-now-includes-go-advisories/): "The addition of Go brings us to seven ecosystems including: Composer (PHP), Go, Maven, npm, NuGet, pip, and RubyGems."

**Comment by sschuberth** [comment]
The [GitHub Advisory Database](https://github.com/github/advisory-database) is now available.

**Comment by sschuberth** [comment]
GitHub advisories are [included in VulnerableCode](https://github.com/nexB/vulnerablecode/blob/main/SOURCES.rst) and [OSV](https://github.com/google/osv.dev#current-data-sources) which [ORT supports both already](https://github.com/oss-review-toolkit/ort#advisor), so the recommendation is to use either of these.
