### ISSUE TITLE
Implement a work-around if SSH for downloads is blocked

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#2568]
In some corporate networks SSH access is blocked and cannot be used to download / clone from Git repos. Implement a possible work-around, like a fallback to try (anonymous) HTTPS, at least for GitHub repos.

**Comment by mnonnenmacher** [comment]
Implementing this as an option (e.g. enabled by configuration file or on the command line) would have the benefit that if the option is enabled, the downloader would not even try to download using SSH.

**Comment by mnonnenmacher** [comment]
I assume this is related to https://github.com/oss-review-toolkit/ort/pull/2555 ? In this case, having configurable patterns to transform the SSH URL to a valid HTTPS URL would be nice.

**Comment by sschuberth** [comment]
> I assume this is related to #2555 ?

Yes.

> In this case, having configurable patterns to transform the SSH URL to a valid HTTPS URL would be nice.

I'm undecided yet. Maybe we should just leverage Git's built-in [insteadOf](https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf) mechanism in some way.

**Comment by sschuberth** [comment]
We don't have a need for this anymore, so I'm closing this.
