### ISSUE TITLE
Sort by number of detect licenses per package in Web App report

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#2606]
Currently, in the Web App report's table view "Package" is the only column that can be sorted by. However, it would be very useful to be able to sort esp. the "Detected Licenses" column by the *number* of licenses to quickly identify potentially problematic packages. As a bonus, the same could be trivially done for "Declared Licenses", too.

**Comment by sschuberth** [comment]
@tsteenbe, is this something that you could implement quickly?

**Comment by tsteenbe** [comment]
@sschuberth  easy feature to add, implemented in https://github.com/oss-review-toolkit/ort/pull/2608
