### ISSUE TITLE
Consider renaming license sets

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#2624]
As discussed offline, license "sets" in "licenses.yml" like at

https://github.com/oss-review-toolkit/ort/blob/6f7d1047c28d711d378564676d2f3cb0dc3fe691/docs/examples/licenses.yml#L8

https://github.com/oss-review-toolkit/ort/blob/6f7d1047c28d711d378564676d2f3cb0dc3fe691/docs/examples/licenses.yml#L15

should probably be renamed to something less technical, like "tags", "labels" or "categories".

**Comment by sschuberth** [comment]
FYI, [FSF License Metadata API](https://github.com/wking/fsf-api) [uses](https://github.com/wking/fsf-api#license-properties) the term "tags".

**Comment by mnonnenmacher** [comment]
Slightly related to #2663.

**Comment by sschuberth** [comment]
In `OrtResult`, we already have a `labels` mechanism which actually does not only allow to label results with a key, but also have a value associated to that key. @mnonnenmacher @fviernau, do we need such flexibility for licenses, too? If yes, I'd rename "sets" to "labels" and implement it analog to `OrtResult`. If not, I'd use a different name than "label" to make clear it's a different mechanism.

**Comment by oheger-bosch** [comment]
Just wondering whether the section currently named *license_sets* is actually needed. If I understand the code in LicenseConfiguration correctly (property *licensesBySetId*), it is not enforced that the sets defined for a license match the declared *license_sets*. So this section is implicitly defined by these sets.

**Comment by sschuberth** [comment]
> So this section is implicitly defined by these sets.

Correct. I guess @fviernau' intention here was to make the "sets" explicit for a better overview in the beginning of the file, and to avoid things like typos in set names by requiring them to be declared beforehand.

**Comment by sschuberth** [comment]
The renaming was done in https://github.com/oss-review-toolkit/ort/pull/3327/commits/0e817f12dac497aa5ebab26999c3d4674486a640.
