### ISSUE TITLE
Support the import from "License Classification Providers"

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#2625]
While ORT itself should stay neutral about *how* licenses are classified, we should make it easy for the user to choose and use a classification. For this, we should have something like a `LicenseClassificationProvider` similar to like we have a `PackageCurationProvider`. The existing [license-classifications.yml](https://github.com/oss-review-toolkit/ort/blob/master/examples/license-classifications.yml) could then be used via a `FileLicenseClassificationProvider` (compare `FilePackageCurationProvider`). Potential other providers could be (in no specific order):

- [OSADL Open Source License Checklists](https://www.osadl.org/?id=3115)
- [FSF License Metadata API](https://github.com/wking/fsf-api)
- [OSI license information](https://github.com/OpenSourceOrg/licenses) ([API](https://github.com/OpenSourceOrg/api))
- [TLDRLegal](https://tldrlegal.com/) ([Developer API](https://tldrlegal.com/developers))
- [Choose a license](https://choosealicense.com/) ([appendix table](https://choosealicense.com/appendix/), [project page](https://github.com/github/choosealicense.com))
- [ifrOSS](https://github.com/ifrOSS/ifrOSS)

**Comment by sschuberth** [comment]
Should be done after https://github.com/oss-review-toolkit/ort/issues/2624.

**Comment by sschuberth** [comment]
Note that [Gitter.im has been sold to the makers to Matrix](https://techcrunch.com/2020/09/30/element-acquires-gitter-to-get-more-developers-on-board-with-the-open-matrix-messaging-protocol) meanwhile. But I'll stick with Slack for the foreseeable time.

**Comment by fviernau** [comment]
@tsteenbe  @sschuberth @mnonnenmacher shall we really add the complexity of requesting licenses at runtime?
I believe it suffices to provide means to export the license classifications from the above APIs to a `licenses.yml`.
Having this file makes it much clearer what actual licenses classifications have been used.
IMO this is adding complexity without need.

Apart from that, re-computing reports locally can be optimized by not recomputing evaluation results if no configuration was changed. Whether the configuration has changed will become harder / impossible to detect if license classifications are obtained at runtime.

**Comment by sschuberth** [comment]
> shall we really add the complexity of requesting licenses at runtime?

I'd argue it does not really add that much (code) complexity, unless you actually *do* add a (difficult to handle) remote license provider. This issue is only about making it *possible* to add such providers, not necessarily already about adding such providers. And just abstracting away the current implementation behind a `FileBasedLicenseClassificationProvider` is really not that complex, esp. as we have the same concept already elsewhere.

> IMO this is adding complexity without need.

In the larger (Open Chain) community we had several asks over the years to add support for TLDR legal, and also @tsteenbe has filed [two](https://github.com/oss-review-toolkit/ort/issues/734) [related](https://github.com/oss-review-toolkit/ort/issues/736) issued about this.

> Whether the configuration has changed will become harder / impossible to detect if license classifications are obtained at runtime.

Certainly not impossible. On a low level OkHttp already takes care of not re-downloading unmodified resources again, and if really needed we could easily add our own hash-based caching mechanism on top of that.

**Comment by fviernau** [comment]
> Certainly not impossible. On a low level OkHttp already takes care of not re-downloading unmodified resources again, and if really needed we could easily add our own hash-based caching mechanism on top of that.

The use case I had in mind was: downloading an OrtResult produced on CI and re-doing the evaluator step locally using the exact same license classifications as was used when the original OrtResult was produced. I don't see how this would be working without adding quite a bit of complexity.

**Comment by sschuberth** [comment]
After giving this some thought again, I'd now also prefer to realize this via "importers" that create `license-classifications.yml` and `rules.kts` files which can serve as a template / starting point for custom rules, and be used "offline" without being dependent on third-party infrastructure.

**Comment by sschuberth** [comment]
I'm deprecating this idea in favor of recommending the use of [license classifications generated by LDBcollector](https://github.com/maxhbr/LDBcollector/blob/generated/ort/license-classifications.yml) as mentioned in our [license classifications docs](https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-license-classifications-yml.md).
