### ISSUE TITLE
Analysis stuck

### ISSUE THREAD

**Issue by pilvikala** [oss-review-toolkit/ort#2658]
Running the analyze command against the purely cloned ORT repository with a limited set of package managers seems to get stuck. At this moment, I've been waiting for around 30 minutes with no progress update.

The command I ran:
sudo /fossid/lib/ort/bin/ort analyze --input-dir /fossid/uploads/files/scans/1/ --output-dir . -m "BUNDLER,DOTNET,GRADLE,MAVEN,NPM,PIP,PIPENV"
Log:
[ort.log](https://github.com/oss-review-toolkit/ort/files/4694824/ort.log)

ort requirements:
[ort-requirements.log](https://github.com/oss-review-toolkit/ort/files/4694836/ort-requirements.log)

java:
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Debian-3deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Debian-3deb10u1, mixed mode, sharing)

OS: Debian GNU/Linux 10 (buster)

We've seen a similar issue (stuck at a different point of the analysis) on Kubuntu 19.10 with jdk-14-headless.

**Comment by sschuberth** [comment]
@pilvikala, does this issue persist with the current version of ORT?

**Comment by pilvikala** [comment]
@sschuberth I can't reproduce this anymore. I do not have access to the same machine though.
