### ISSUE TITLE
Provide license obligations in web report

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [oss-review-toolkit/ort#2662]
Licenses have obligations, it should be reported for a project, which obligations need to be matched. Furthermore, many obligations are already covered, by, e.g., the generation of an attribution document or by providing sources in some kind, so it should be expressed in the report, whether the obligation needs further actions or whether it is already covered by the generated artifacts.

E.g., an obligation, that cannot be met by an automation is the 4th clause of BSD-4 or my favorite, the Beerware license with the requirement to spend a beer to the author :-).

**Comment by sschuberth** [comment]
IMO the retrieval of license *obligations* (not limited to displaying them in the web app report) is covered by https://github.com/oss-review-toolkit/ort/issues/2625, even if I was only mentioning the word *classification* in that issue.

**Comment by sschuberth** [comment]
Conflating this into https://github.com/oss-review-toolkit/ort/issues/736.
