### ISSUE TITLE
Rename or change the source property in licenses.yml

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [oss-review-toolkit/ort#2663]
The current property "include_source_code_offer_in_notice_file" is not phrased nicely because it does not reflect the original intention that the license requires to provide sources, but already proposes a solution by providing an offer in the notice file.

I would rather like this property to be changed.

**Comment by oheger-bosch** [comment]
We are currently working on a more generic mechanism to assign licenses to arbitrary, customizable categories. The two hard-coded properties will then no longer exist, but users can define their own set of categories instead.

If I am not mistaken, the "include_source_code_offer_in_notice_file" property is nowhere used in the current code base anyway; also not from any template files or rules.

**Comment by sschuberth** [comment]
> If I am not mistaken, the "include_source_code_offer_in_notice_file" property is nowhere used in the current code base anyway; also not from any template files or rules.

My guess is that it's being used by HERE internal rules. @mnonnenmacher or @fviernau may be able to confirm.

**Comment by fviernau** [comment]
@sschuberth we are using both boolean, but this is easy to migrate if the representation changes.

**Comment by mnonnenmacher** [comment]
Fixed by #3327 which removed the predefined names for license categories.

**Comment by sschuberth** [comment]
On a somewhat related note, I recently realized that the NOTICE reporters require a license to be part of the hard-coded "include-in-notice-file" category in order to get listed. We should probably make that category name configurable, too.
