### ISSUE TITLE
Rule waiving

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [oss-review-toolkit/ort#2664]
When executing rules in the evaluator, it might be possible that a rule violation is allowed in a certain project context. This would require a mechanism to tell the evaluator that a certain violation is waived.

This allows to have a clean report that does not contain uncommented rule violations which do not apply for the current situation.

**Comment by sschuberth** [comment]
IMO that's already possible via [resolutions for rule violations](https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-resolutions-yml.md#resolving-policy-rule-violations). Does that cover the case you have in mind?

**Comment by sschuberth** [comment]
Closing this for now, feel free to reopen if necessary.
