### ISSUE TITLE
Always scan full VCS repositories and filter results later

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#2668]
Currently, for performance reasons the scanner is implemented to scan as few files from a VCS repository as needed (i.e. by taking `VcsInfo.path` into account) to cover the respective package's source code. However, e.g. for mono-repos that contain the source code for multiple related packages it's likely that all packages get scanned at some point anyway. Also, there are use-cases where the scan result for a whole VCS repository is of interest, and then "stitching together" that result from the individual results of multiple packages can become difficult. Finally, the general ORT philosophy is to collect all data that we can and then filter it down to what is needed in a particular workflow.

That's why we should consider switching the scanner to "scan by repository" rather than "scan by package".

**Comment by mnonnenmacher** [comment]
This has been fully implemented in the experimental scanner, but we should leave this ticket open until it is properly documented and becomes the default scanner implementation.

**Comment by mnonnenmacher** [comment]
This is fixed since #5799.
