### ISSUE TITLE
Analyzer issue: Pip setuptools - setupName must not be null

### ISSUE THREAD

**Issue by yannjor** [oss-review-toolkit/ort#2703]
Running the ORT analyzer on the [KNIX Microfunctions](https://github.com/knix-microfunctions/knix) project, I get the following errors:

```
PIP::mfn_cli/setup.py:

2020-05-26T11:29:29.887Z [ERROR]: PIP - Resolving dependencies for 'setup.py' failed with: IllegalStateException: setupName must not be null

PIP::mfn_sdk/setup.py:

2020-05-26T11:29:23.333Z [ERROR]: PIP - Resolving dependencies for 'setup.py' failed with: IllegalStateException: setupName must not be null
```

The mfn_cli & sdk are set up using the Setuptools `setup.cfg` [file](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files). Thus the setup() call in `setup.py` doesn't contain any arguments, which results in `setupName` becoming null in the Analyzer's `Pip.kt` [here](https://github.com/oss-review-toolkit/ort/blob/master/analyzer/src/main/kotlin/managers/Pip.kt#L259).

This is my current understanding of the issue. Could you comment on this?

**Comment by yannjor** [comment]
Here is my idea of how this could be fixed: check if there is a `setup.cfg` file present, and if so, run some python script that fetches the meta-data from there. For example using this python [library](https://docs.python.org/3/library/configparser.html). You could then use this result as the projectName if setupName and requirementsName are empty.

Here is a simple example of how this script could look like:
```python
import configparser

def main():
    config = configparser.ConfigParser()
    config.read('setup.cfg')
    return (config['metadata']['name'], config['metadata']['version'], config['metadata']['homepage'])

main()
```
You could then add something like this to [Pip.kt](https://github.com/oss-review-toolkit/ort/blob/master/analyzer/src/main/kotlin/managers/Pip.kt#L285):

```kotlin
// Try to get meta-data from "setup.cfg" if such a file is present
val (setupConfigName, setupConfigVersion, setupConfigHomepage) = if (File(workingDir, "setup.cfg").isFile) {
    runInVirtualEnv(virtualEnvDir, workingDir, "my-script.py")
} else {
    listOf("", "", "")
}
```
And modify lines [308-315](https://github.com/oss-review-toolkit/ort/blob/master/analyzer/src/main/kotlin/managers/Pip.kt#L308-L315) to something like:
```kotlin
val projectName = when (Triple(setupName.isNotEmpty(), setupConfigName.isNotEmpty(), requirementsName.isNotEmpty())) {
    Triple(true, false, false) -> setupName
    Triple(false, true, false) -> setupConfigName
    // In case of only a requirements file without further meta-data, use the relative path to the analyzer
    // root as a unique project name.
    Triple(false, false, true) -> definitionFile.relativeTo(analysisRoot).invariantSeparatorsPath
    Triple(true, false, true) -> "$setupName-requirements$requirementsSuffix"
    else -> throw IllegalArgumentException("Unable to determine a project name for '$definitionFile'.")
}
```

Any comments or suggestions? Let me know what you think.

**Comment by sschuberth** [comment]
Thanks for the detailed report and proposed solution @yannjor! Unfortunately, it will take me some more time to be able to look at this.

**Comment by yannjor** [comment]
Hi @sschuberth, I made a [pull request](https://github.com/oss-review-toolkit/pydep/pull/1) to the pydep repo that attempts to fix this issue. I don't think any changes to ORT itself is needed.

**Comment by sschuberth** [comment]
> I made a [pull request](https://github.com/oss-review-toolkit/pydep/pull/1) to the pydep repo

Thanks! That indeed looks like the proper place to address this.

That said, I was long dreaming of actually getting rid of our pydep fork completely, in favor of a single Python script that we maintain as part of this repository and temporarily write out when needed like we already do e.g. for [Bundler](https://github.com/oss-review-toolkit/ort/blob/81f0030df433b7998d9c0562c6370c4a5ad9407c/analyzer/src/main/kotlin/managers/Bundler.kt#L200).

**Comment by yannjor** [comment]
Yeah, that seems like it could be a better solution.
