### ISSUE TITLE
Docker build : Analyzer. Add support for DotNet and NuGet package managers

### ISSUE THREAD

**Issue by camillem** [oss-review-toolkit/ort#2731]
Hi,

The current docker build doesn't include support for DotNet and NuGet.
Is this a deliberate choice due to their limitations (as mentioned in #1303 ) ?

Thanks,
Camille

**Comment by sschuberth** [comment]
Hi @camillem, the Docker image should support analyzing DotNet / NuGet projects just fine. For these, ORT does not require any external tools, so none need to be added to the Docker image.

What's exactly the problem you're seeing?

**Comment by camillem** [comment]
Hi @sschuberth , 

Thanks for the fast reply.
I haven't even tested yet, but during the build process, they don't appear among the package managers listed, so I thought they were disabled ; but as they don't require external tools, it's logical that they're not.
Sorry for the noise, 
Camille 

> PackageManagers:
> 	* Bower: Requires 'bower' in version =1.8.8. Found version 1.8.8.
> 	* Bundler: Requires 'bundle' in version >=1.16.0 <2.2.0. Found version 1.16.1.
> 	* Cargo: Requires 'cargo' in no specific version. Found version 1.41.0.
> 	* Conan: Requires 'conan' in version =1.18.0. Found version 1.18.0.
> 	* GoDep: Requires 'dep' in no specific version. Found version 0.5.4.
> 	* GoMod: Requires 'go' in no specific version. Found version 1.13.4.
> 	* Npm: Requires 'npm' in version >=5.7.0 <6.15.0. Found version 6.14.2.
> 	* PhpComposer: Requires 'composer' in version >=1.5.0. Found version 1.6.3.
> 	* Pip: Requires 'pip' in no specific version. Found version 9.0.1.
> 	* Pipenv: Requires 'pipenv' in version >=2018.10.9. Found version 2018.11.26.
> 	* Pub: Requires 'pub' in version >=2.2.0. Found version 2.7.2.
> 	* Sbt: Requires 'sbt' in version >=0.13.0. Found version 1.3.8.
> 	* Stack: Requires 'stack' in version >=2.1.1. Found version 2.1.3.
> 	* Yarn: Requires 'yarn' in version >=1.3.0 <1.23.0. Found version 1.21.1.

**Comment by sschuberth** [comment]
> but as they don't require external tools, it's logical that they're not.

That's exactly the reason: The `requirements` command only lists requirements on external tools, and since our DotNet / NuGet implementations don't have any, they are not listed.
