### ISSUE TITLE
[scanner] scanning symbolic link source directory could lead to infinite loop and OOM eventually

### ISSUE THREAD

**Issue by BennyThink** [oss-review-toolkit/ort#2747]
Hi dear developer,

Thanks for developing this magnificent tools. This might be a potential bug regarding to source code scanning with scancode
# version
OSS Review Toolkit, version 0.1.0-SNAPSHOT.
Running using Java 11.0.6 on Linux  
ScanCode version 3.0.2

# steps to reproduce
## find a source file
it must have at least two symbolic links to directory, the symbolic link must link to the inside of source code directory
## scan like this 
`/opt/ort/bin/ort --info --debug -c /var/proj/etc/ort.conf scan -p /var/proj/mnt/src/test -o /var/proj/mnt/src/scan_output`
## ort output is like
_Save scan results...
 Save scan results as: json-pp...
Scanning done.
Summary:        info, licenses, copyrights with 3 process(es)
Errors count:   0
Scan Speed:     1.04 files/sec. 7.13 KB/sec.
Initial counts: 5 resource(s): 3 file(s) and 2 directorie(s)
Final counts:   0 resource(s): 0 file(s) and 0 directorie(s)
Timings:
  scan_start: 2020-06-19T074247.781296
  scan_end:   2020-06-19T074253.331201
  setup_scan:licenses: 2.59s
  setup: 2.59s
  scan: 2.87s
  total: 5.56s
Removing temporary files...done._
## it hangs at the above message
And memory consumption keeps growing slowly, OOM eventually.

# More debug info
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space\\n
tat java.base/java.io.UnixFileSystem.resolve(UnixFileSystem.java:110)\\n
tat java.base/java.io.File.<init>(File.java:263)\\n
tat java.base/java.io.File.listFiles(File.java:1226)\\n
tat kotlin.io.FileTreeWalk$FileTreeWalkIterator$TopDownDirectoryState.step(FileTreeWalk.kt:177)\\n
tat kotlin.io.FileTreeWalk$FileTreeWalkIterator.gotoNext(FileTreeWalk.kt:98)\\n
tat kotlin.io.FileTreeWalk$FileTreeWalkIterator.computeNext(FileTreeWalk.kt:80)\\n
tat kotlin.collections.AbstractIterator.tryToComputeNext(AbstractIterator.kt:42)\\n
tat kotlin.collections.AbstractIterator.hasNext(AbstractIterator.kt:29)\\n
tat kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:131)\\n
tat kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)\\n
tat com.here.ort.spdx.SpdxUtilsKt.calculatePackageVerificationCodeForDirectory(SpdxUtils.kt:168)\\n
tat com.here.ort.scanner.scanners.ScanCode.generateSummary$scanner(ScanCode.kt:368)\\n
tat com.here.ort.scanner.scanners.ScanCode.scanPath(ScanCode.kt:328)\\n
tat com.here.ort.scanner.LocalScanner.scanInputPath(LocalScanner.kt:375)\\n
tat com.here.ort.commands.ScannerCommand.runCommand(ScannerCommand.kt:202)\\n
tat com.here.ort.CommandWithHelp.run(CommandWithHelp.kt:55)\\n
tat com.here.ort.OrtMain.runCommand(OrtMain.kt:167)\\n
tat com.here.ort.CommandWithHelp.run(CommandWithHelp.kt:55)\\n
tat com.here.ort.OrtMain.run(OrtMain.kt:150)\\n
tat com.here.ort.OrtMain.main(OrtMain.kt:106)\\n\'
```

# Examples
* Real example: [etcd-3.1.5-5.ph1.src.rpm](https://drive.google.com/file/d/1kHILj1dninoC-bBEusoIYHZJOX5luxwO/view?usp=sharing)

* [My self made example:](https://drive.google.com/file/d/1VCUHls93movn6Z4xoiu2Fb0OlmsyGojq/view?usp=sharing) the structure is as follows

![image](https://user-images.githubusercontent.com/14024832/85114333-77c65780-b24b-11ea-8bcc-398003aea5d4.png)

**Comment by sschuberth** [comment]
Thanks for the detailed report @BennyThink! Could you maybe confirm that https://github.com/oss-review-toolkit/ort/pull/2748 fixes the issue for you?

**Comment by sschuberth** [comment]
@BennyThink the change is now in `master` for you to verify. If the original issues still appears, please reopen this ticket.

**Comment by BennyThink** [comment]
Thanks! It works!
