### ISSUE TITLE
[scanner] how to ignore specific errors from scancode by .ort.yml?

### ISSUE THREAD

**Issue by BennyThink** [oss-review-toolkit/ort#2752]
Sometime the source code may contain some large files, and [scancode](https://github.com/nexB/scancode-toolkit) may timeout and exit with none-zero exit code. When that case happens, ort will report an error, even the majority of the source code has been scanned successfully.

I wonder how I can ignore such timeout errors.

I noticed about [.ort.yml](https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-ort-yml.md), I put a yaml file at my source code's directory. It does not seem to be working.

# version
OSS Review Toolkit, version 0.1.0-SNAPSHOT.
Running using Java 11.0.6 on Linux
ScanCode version 3.0.2

# ort.conf
```
ort {
    scanner {
        scanner {
            ScanCode {
                commandLine = "--copyright --license --info --license-diag --license-text --only-findings --is-license-text --strip-root "
            }
        }
      }
}
```

# ort command
```bash
/opt/ort/bin/ort -c /var/proj/etc/ort.conf scan -p /var/proj/mnt/src/test/ -o /var/proj/mnt/src/test/scan_output/
```

# .ort.yml
```yaml
---
    resolutions:
      issues:
      - message: ".*Some files failed to scan properly.*"
        reason: "SCANNER_ISSUE"
        comment: "The error can be ignored."
   
```

# structure
source code directory, i.e. `/var/proj/mnt/src/test/`
```
➜  test (develop) ls -alh                                                   ✭ ✱
total 15112
drwxrwxr-x@ 7 benny  staff   224B Jun 20 12:47 .
drwxrwxrwx  5 benny  staff   160B Jun 20 12:42 ..
-rw-r--r--@ 1 benny  staff   173B Jun 20 12:45 .ort.yml
-rw-r--r--@ 1 benny  staff    34K Jun 17 11:33 LICENSE
-r--r--r--@ 1 benny  staff   2.5K May 22 15:44 gen_helper.go
-rw-rw-r--@ 1 benny  staff   7.3M May 11  2001 lantest2.nam
```
# ort output
```
Setup plugins...
Collect file inventory...
Scan files for: info, licenses, copyrights with 3 process(es)...
Scanning done.
Some files failed to scan properly:
Path: lantest2.nam
Summary:        info, licenses, copyrights with 3 process(es)
Errors count:   1
Scan Speed:     0.26 files/sec. 325.43 KB/sec.
Initial counts: 7 resource(s): 6 file(s) and 1 directorie(s)
Final counts:   3 resource(s): 3 file(s) and 0 directorie(s) for 7.36 MB
Timings:
  scan_start: 2020-06-20T045047.438908
  scan_end:   2020-06-20T045113.478261
  setup_scan:licenses: 2.77s
  setup: 2.77s
  scan: 23.18s
  total: 26.06s
Removing temporary files...done.

Writing scan result to '/var/proj/mnt/src/scan_output/scan-result.yml'.
```

**Comment by sschuberth** [comment]
I believe the the regex for the message might not match. Could you try "ERROR: Timeout.*"?

**Comment by BennyThink** [comment]
hi @sschuberth , thanks for your quick response and generous help.

Unfortunately, I've tried  `ERROR: Timeout.*`, it doesn't work as expected. I've even tried `.*` which doesn't work, either.

`scan-result.yml` still shows an error and there's no other files' license and copyrights information.

[This link](https://drive.google.com/file/d/1qcPyi9fkDPwOSOF5nT72OwQzwlidzD_1/view?usp=sharing) is the source code and scan result.

**Comment by tsteenbe** [comment]
@BennyThink Tested the files you and found 2 issues:

1. Your local version of ORT is out-of-date, please update to the latest on the master branch
2. You only ran the ORT scanner component and not the [analyzer](https://github.com/oss-review-toolkit/ort#details-on-the-tools) as such there is no project for the .ort.yml to connect to - I can generate the WebApp report but StaticHTML straight up fails with

```
Creating the 'StaticHtml' report...
18:05:42.491 [main] ERROR org.ossreviewtoolkit.commands.ReporterCommand - Could not create 'StaticHtml' report: IllegalArgumentException: The provided ORT result does not contain an analyzer result.
```

Have had another ORT user with a similar issue see also  https://github.com/oss-review-toolkit/ort/issues/2369.

**Comment by BennyThink** [comment]
Thanks @tsteenbe for your help.

For now I only need scanner component and analyzer is not required. Is `.ort.yml` only functional with analyzer component?

**Comment by sschuberth** [comment]
> Is `.ort.yml` only functional with analyzer component?

No, depending on the *type* of issue resolution configured in `.ort.yml`, different ORT components (like the analyzer or scanner) make use of it.

BTW, I just noticed in your example that you're still using the old configuration syntax with two nested `scanner {}` blocks in `ort.conf`. While it shouldn't be related to your issue, please make sure to change the inner `scanner {}` block to `options {}`.
