### ISSUE TITLE
Improve handling if the same repository is analyzed multiple times

### ISSUE THREAD

**Issue by mnonnenmacher** [oss-review-toolkit/ort#2803]
If git-repo or Git submodules are used, it is possible that the same repository is cloned multiple times in the directory tree passed to the analyzer. Currently that causes the analyzer to create errors like this:

> Multiple projects with the same id 'Gradle:com.example:lib:1.0-SNAPSHOT' found. Not adding the project defined in 'ssh://git@example.com/lib.git/build.gradle' to the analyzer results as it duplicates the project defined in 'ssh://git@example.com/lib.git/build.gradle'.

If each clone of the repository uses the same revision, the analyze could detekt that and not try to analyze it multiple times. To correctly capture this in the analyzer result it would be required to allow multiple definition file paths for a project.

Another fix would be to allow multiple projects with the same id in an analyzer result, but this would require many code changes, as a lot of code is currently expecting that ids are unique.

**Comment by sschuberth** [comment]
Yet another option would be to assign an artificial unique project id for the second project, like by using the parent directory name / path to the VCS root as a prefix, similar to like we do already for Pip (IIRC) to be able to distunguish multiple `requirements.txt`-based projects in the tree.

**Comment by mnonnenmacher** [comment]
Basically yes, but it's more complex. For the scanner we can clone and scan the repositories separately, but for the analyzer it is possible that a project depends on the submodules to be there to function correctly, so we cannot assume that cloning and analyzing the repositories separately would work.

**Comment by sschuberth** [comment]
@mnonnenmacher, this is still an issue despite https://github.com/oss-review-toolkit/ort/pull/4660 being merged, correct?

**Comment by sschuberth** [comment]
I wonder whether the [WorkingTreeCache](https://github.com/oss-review-toolkit/ort/blob/4d240a9f660ed0aed7b41ce9e7da18be9ea8feac/scanner/src/main/kotlin/utils/WorkingTreeCache.kt#L37) could somehow be used to detect such cases and analyze "duplicate" repos only once.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
