### ISSUE TITLE
Get rid of our pydep fork in favor of a single script

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#2816]
That said, I was long dreaming of actually getting rid of our pydep fork completely, in favor of a single Python script that we maintain as part of this repository and temporarily write out when needed like we already do e.g. for [Bundler](https://github.com/oss-review-toolkit/ort/blob/81f0030df433b7998d9c0562c6370c4a5ad9407c/analyzer/src/main/kotlin/managers/Bundler.kt#L200).

_Originally posted by @sschuberth in https://github.com/oss-review-toolkit/ort/issues/2703#issuecomment-652454896_

**Comment by tsteenbe** [comment]
The Python foundation is funding a dependency resolver see  https://pyfound.blogspot.com/2019/11/seeking-developers-for-paid-contract.html and related ticket https://github.com/pypa/pip/issues/988

We could investigatehttps://github.com/ddelange/pipgrip/ as a  temporary replacement for our pydep fork pending pip getting its own dependency resolver.

**Comment by sschuberth** [comment]
*pipgrip* indeed looks interesting, but I'm having [issues](https://github.com/ddelange/pipgrip/issues/27) with it. Let's see how responsive the developer is.
