### ISSUE TITLE
Allow to specify different scanners depending on package / project properties

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#2819]
This is a generalization of the idea in https://github.com/oss-review-toolkit/ort/issues/2130. Instead of just distinguishing between packages and projects, we want to be able to use different scanners based on package / project properties. For example in a C/C++ project, if we know that a package is a third-party Open Source component *with modifications*, we might want to use a snippet scanner whereas *without* modifications a "normal" license scanner might suffice.

This ideally requires an extension of the package data model, with something like an "origin" (I'm open for a better name). "origin" could be a `enum class` with values like `COMPANY_INTERNAL`, `THIRD_PARTY_OPEN_SOURCE`, `THIRD_PARTY_COMMERCIAL`, `THIRD_PARTY_OPEN_SOURCE_WITH_MODIFICATIONS`, `THIRD_PARTY_COMMERCIAL_WITH_MODIFICATIONS`. As possibly more permutations might be needed, maybe it would make sense to instead come of with a "labeling system" where a package could have multiple labels, like `THIRD_PARTY` *and* `OPEN_SOURCE` *and* `WITH_MODIFICATIONS`.

**Comment by nnobelis** [comment]
How a package label would be populated ?

Does the user have to manually edit analyzer_result.yml and add the labels for each package ?

**Comment by sschuberth** [comment]
Ideally the analyzer would implement some heuristics to label packages, based on metadata the respective package manager provides. Or labels could be added via curations.

**Comment by neubs-bsi** [comment]
Note from planning 02.11.2020:
To be cleared: Which properties should be diefined (potentially ideal: configurable)

**Comment by KorSin** [comment]
Opened PR #3329 to solve this issue.

**Comment by KorSin** [comment]
I actually prefer the suggestion by @sschuberth to have, e.g., a `Set<PackageClassification>`, where you decide for the scanner by the combinations inside the set. It should not be too difficult to implement an additional field for the `Package` class which can be curated. 

Then, the configuration could be expanded to configure which scanner to use for which combinations. The `ScannerCommand` should then be responsible to filter the packages accordingly.

However, multiple scanners are not implemented yet. Maybe, once #3638 is implemented, one can use these implementation details.

Looking at the structure of my thoughts, it would make sense to divide this issue into three PRs.

**Comment by sschuberth** [comment]
A concrete use-case is: Use a snippet-scanner (as opposed to a regular license scanner) if a package has the `isModified` property set.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
