### ISSUE TITLE
Gradle : error when resolving dependencies

### ISSUE THREAD

**Issue by fb33** [oss-review-toolkit/ort#2823]
Hello,

I use ORT in docker with master@70345038.
I've got this error with a kotlin project build with Gradle 6.3:

```
        "Gradle::build.gradle.kts:" : [ {
          "timestamp" : "2020-07-03T14:42:27.404372Z",
          "source" : "Gradle",
          "message" : "Resolving dependencies for 'build.gradle.kts' failed with: BuildException: Could not fetch model of type 'DependencyTreeModel' using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-6.3-bin.zip'.\nCaused by: LocationAwareException: Project directory '/project/my-kotlin-project\' is not part of the build defined by settings file. If this is an unrelated build, it must have its own settings file.\nCaused by: InvalidUserDataException: Project directory '/project/my-kotlin-project\' is not part of the build defined by settings file. If this is an unrelated build, it must have its own settings file.",
          "severity" : "ERROR"
        } ],
```
I seem to remember that a few months ago I managed to audit a gradle project. 
Do you have any idea what's going on?

Thanks for your help

**Comment by sschuberth** [comment]
The error message coming from Gradle should be pretty much self-explanatory: Your Gradle project's setup is broken, and I'd guess also running a plain `./gradlew dependencies` from the command line in the project directory fails.

You either need to create a `settings.gradle.kts` file alongside of your `build.gradle.kts` file, or add the directory of that build file to a `settings.gradle.kts` file in one of the parent directories. If the latter is already the case, you also need to point the ORT analyzer at the directory of the `settings.gradle.kts` file so ORT gets the "full picture", and not just a view on a single sub-project of a multi-project setup.

**Comment by fb33** [comment]
Hum.... the project build well with intellij. 
I'll try to build "manually"

**Comment by fb33** [comment]
Hello, 
My project didn't have got gradle-wraper.jar in his git repo.
The build successfull with Intellij hide the point.
I fixed that, and analyzer works better but I've got now an error about retreiving dependencies.
`"message" : "Resolving dependencies for 'build.gradle.kts' failed with: BuildException: Could not fetch model of type 'DependencyTreeModel' using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-6.3-bin.zip'.\nCaused by: LocationAwareException: Initialization script '/tmp/init14793059512304365429.gradle' line: 183\nCould not resolve all dependencies for configuration ':detachedConfiguration3'.\nCaused by: ResolveException: Could not resolve all dependencies for configuration ':detachedConfiguration3'.\nCaused by: ContextualPlaceholderException: Cannot resolve external dependency org.springframework.boot:spring-boot-dependencies:2.3.0.RELEASE because no repositories are defined.\nRequired by:\n    project :",`

When I run the analyzer locally with the Cli, it's work fine. I've got a .gradle/init.gradle.kts in my home that declare my entreprise maven repo.
When I run with Docker (I made a specific image by adding my configuration file init.gradle.kts to /root/.gradle/), it failed with the previous error message.

**Comment by sschuberth** [comment]
Maybe ORT running inside Docker is using a different home directory than what you think it is, so please double-check ORT's starting output which looks like

```
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version 0.1.0-SNAPSHOT.
 /   |   \|       _/ |    |    Running 'analyze' under Java 11.0.6 on Linux with
/    |    \    |   \ |    |    ORT_DATA_DIR = /var/lib/jenkins/workspace/ort-pipeline-test@tmp/.ort
\_______  /____|_  / |____|
```

The user home is the portion of the `ORT_DATA_DIR` before `.ort`, so in this case `/var/lib/jenkins/workspace/ort-pipeline-test@tmp`. In your case, you need to verify it's `/root/.gradle`.

**Comment by fb33** [comment]
I've got this:
```
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version 0.1.0-SNAPSHOT.
 /   |   \|       _/ |    |    Running 'scan' under Java 11.0.7 on Linux with
/    |    \    |   \ |    |    ORT_DATA_DIR = /root/.ort
\_______  /____|_  / |____|    JAVA_HOME = /opt/java/openjdk
        \/       \/
```
I also add settings.xml in /root/.m2, and it works well for maven projects with the same ORT_DATA_DIR = /root/.ort
What can be the difference with gradle ?

**Comment by sschuberth** [comment]
I'm not sure. What commit of ORT are you using? In particular, does  your copy of ORT include https://github.com/oss-review-toolkit/ort/pull/2751/commits/5fcc221b94c10f01e6e6b0e0502d82a095bd0f21?

**Comment by fb33** [comment]
Yes, I've got this commit.
Finally it works fine ! 
The orginal problem was that the jar of the wrapper wasn't in the source.
My other comments are not relevant, I missed out on something local. It works in CI. 
Thanks

**Comment by sschuberth** [comment]
> Finally it works fine !

I'm glad it works for you now.

> The orginal problem was that the jar of the wrapper wasn't in the source.

Actually, having the Gradle wrapper in place should not be *required*. It makes your life easier and builds deterministic, but if it's not present the Gradle Tooling API that we use [simply uses the Gradle version of the Tooling API itself](https://docs.gradle.org/current/javadoc/org/gradle/tooling/GradleConnector.html). That said, we're using a very recent version of Gradle that might be incompatible with your build. So it's certainly still good to use the wrapper to be on the safe side.
