### ISSUE TITLE
Address LGTM alerts (in the WebApp)

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#2832]
All our [current LGTM alerts](https://lgtm.com/projects/g/oss-review-toolkit/ort/alerts) are located in the WebApp and we should address them.

**Comment by tsteenbe** [comment]
Fixed most issues in #2860 but can't fix the error for `new webpack.DefinePlugin(env.stringified),`. Search the internets but there currently does not seem to be a better solution available to pass needed env variables to this plugin.
