### ISSUE TITLE
Generate report directly from analyzer-result.yml

### ISSUE THREAD

**Issue by kneep** [oss-review-toolkit/ort#2839]
In many cases we just need the metadata of packages and don't need bother to scan individual files. Is it possible to generate a report directly from analyzer-result.yml?

**Comment by sschuberth** [comment]
Basically yes. However it might depend on the result format you chose. For some report formats, like NOTICE files, it does not make sense to use them without scan result as then no copyright information would be available.

So bottom line, just try it out 😉 And if you run into an issue with some specific report format that should in your view work with only an analyzer result, but does not, please report back here.

**Comment by sschuberth** [comment]
Does my previous post answer your question @kneep?

**Comment by kneep** [comment]
@sschuberth Hi Sebastian. Yes for now. I'm closing it.
