### ISSUE TITLE
Docker build ends with "non-zero code: 100"

### ISSUE THREAD

**Issue by Brausepaul** [oss-review-toolkit/ort#2873]
I followed the steps to create a Docker build in Windows 10 2004. While the build itself reports as be successful it creates an error in the following steps:

`See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 3m 47s
49 actionable tasks: 49 executed
Removing intermediate container 22acf8df5c93
 ---> 72c416ecdf1d
Step 6/14 : FROM adoptopenjdk:11-jre-hotspot-bionic
 ---> ca2a8f23400d
Step 7/14 : ENV     BOWER_VERSION=1.8.8     BUNDLER_VERSION=1.16.1-1     CARGO_VERSION=0.42.0-0ubuntu1~18.04.1     COMPOSER_VERSION=1.6.3-1     CONAN_VERSION=1.18.0     FLUTTER_VERSION=v1.12.13+hotfix.9-stable     GO_DEP_VERSION=0.5.4     GO_VERSION=1.13.4     HASKELL_STACK_VERSION=2.1.3     NPM_VERSION=6.14.2     PYTHON_PIP_VERSION=9.0.1-2.3~ubuntu1.18.04.1     PYTHON_PIPENV_VERSION=2018.11.26     PYTHON_VIRTUALENV_VERSION=15.1.0     SBT_VERSION=1.3.8     YARN_VERSION=1.21.1     ANDROID_SDK_VERSION=6609375     SCANCODE_VERSION=3.0.2     ANDROID_HOME=/opt/android-sdk     FLUTTER_HOME=/opt/flutter     GOPATH=$HOME/go
 ---> Using cache
 ---> 37d0cb36043d
Step 8/14 : ENV DEBIAN_FRONTEND=noninteractive     PATH="$PATH:$HOME/.local/bin:$FLUTTER_HOME/bin:$FLUTTER_HOME/bin/cache/dart-sdk/bin:$GOPATH/bin:/opt/go/bin"
 ---> Using cache
 ---> bf7cd88268b1
Step 9/14 : RUN apt-get update &&     apt-get install -y --no-install-recommends gnupg &&     echo 'Acquire::https::dl.bintray.com::Verify-Peer "false";' | tee -a /etc/apt/apt.conf.d/00sbt &&     echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list &&     curl -ksS "https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key adv --import - &&     apt-get update &&     apt-get install -y --no-install-recommends         lib32stdc++6         libffi-dev         libgmp-dev         libxext6         libxi6         libxrender1         libxtst6         make         netbase         openssh-client         unzip         xz-utils         zlib1g-dev         cvs         git         mercurial         subversion         bundler=$BUNDLER_VERSION         cargo=$CARGO_VERSION         composer=$COMPOSER_VERSION         npm         python-pip=$PYTHON_PIP_VERSION         python-setuptools         python3-pip=$PYTHON_PIP_VERSION         python3-setuptools         sbt=$SBT_VERSION     &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 27080836a61e
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Reading package lists...
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 1h 16min 46s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 22min 40s). Updates for this repository will not be applied.
E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 58min 53s). Updates for this repository will not be applied.
The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends gnupg &&     echo 'Acquire::https::dl.bintray.com::Verify-Peer "false";' | tee -a /etc/apt/apt.conf.d/00sbt &&     echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list &&     curl -ksS "https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key adv --import - &&     apt-get update &&     apt-get install -y --no-install-recommends         lib32stdc++6         libffi-dev         libgmp-dev         libxext6         libxi6         libxrender1         libxtst6         make         netbase         openssh-client         unzip         xz-utils         zlib1g-dev         cvs         git         mercurial         subversion         bundler=$BUNDLER_VERSION         cargo=$CARGO_VERSION         composer=$COMPOSER_VERSION         npm         python-pip=$PYTHON_PIP_VERSION         python-setuptools         python3-pip=$PYTHON_PIP_VERSION         python3-setuptools         sbt=$SBT_VERSION     &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100`

Running the Docker container fails as no local image can be found.

**Comment by mnonnenmacher** [comment]
Hi @Brausepaul , the `Release file for ... is not valid yet` errors indicate that this could be an issue with the timezone settings on your machine, see e.g. https://askubuntu.com/questions/1096930/sudo-apt-update-error-release-file-is-not-yet-valid.

**Comment by Brausepaul** [comment]
Thanks for your reply. I checked my BIOS as well as my OS' time setting but could not find any problem there. But I do recall a "time hickup" after dual-booting Ubuntu some time ago. Anyways, I could not reproduce the issue described above any longer, closing this one.
