### ISSUE TITLE
Support build2 as a package manager (for C/C++ projects)

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#2877]
See https://build2.org/.

**Comment by tsteenbe** [comment]
For people looking to use ORT to scan C/C++ projects maybe ORT helper CLI maybe a solution  to generate ORT analyzer file use `ort/helper-cli/build/install/orth/bin/orth create-analyzer-result-from-package-list  --package-list-file  package-list.yml --ort-file analyzer.json`.  See also this [helper-cli/src/funTest/assets/package-list.yml](https://github.com/oss-review-toolkit/ort/pull/7305/commits/bcaddf481c203c03ee6e4fbb915ddbd6be392436#diff-1df5116af82270dd1841900c175cb81b20e16ac6de52442783741649a6c8d8c8) example.

Related "Producing SBOMs for CMAKE projects using ORT's standard workflow" presentation from EPAM (@fviernau) and Zeiss at the [ORT Community Days 2024 ](https://github.com/oss-review-toolkit/ort/wiki/ORT-Community-Days-2024).

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
