### ISSUE TITLE
Provide means to address `unmappable declared licenses` issues

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#2898]
There can be different reasons why a declared license mapping entry cannot be placed in
ORTs declared license mapping:

- The mapping entry is confidential
- The entry does not refer to a license, e.g. it is a copyright statement and should be mapped to an empty string
- The entry would be packages specific
- The declared license string is globally unique but refer to a license whose license text changed without specifying the date or version of that license text
- The declared license string does not contain sufficient information, e.g. `GPL` without any version specified.

There are already means available to address the above:
- Error resolutions could be used to address invalid entries. This however only gets rid of the error, but does not lead to a fixed declared license which would be possible for the case where a package specific mapping would be needed.
- Declared license curation can be used to fix all of the above, but the entries need to be version specific and thus more entries are required. Further it overrides all declared licenses, and thus it consumes much more manual review effort. The reviewer must lookup all detected licenses and check
- It'd be better to have a single dedicated way to address this.

Find below two alternative implementation proposals

**Implementation via package curation**

```
- id: "Maven:com.example.sdk"
  declared_license_mapping:
    "Copyright (c) holder": 

- id: "Maven:com.example.sdk:4.0.1"
  declared_license_mapping:
    GPL : "GPL-3.0-only"
```

nice to have: matching the group of the Identifier as a regex.

**Implementation via a declared license mapping file**

The declared license mapping file already implemented in ORT must not make any assumptions about the package the mapping entry is used for. But it already contains some entries which are questionable in this regard. In order to share declared license mapping entries which are package specific, this file could be extended to support that. Further a command line parameter could be introduced to specify a custom mapping file to be used in addition to ORTs mapping file, with the exact same format.

```
- "*"
  "(MIT-style) netCDF C library license": NetCDF
  "2-clause BSD license": BSD-2-Clause
  "2-clause BSDL": BSD-2-Clause
  "2-clause bdsl": BSD-2-Clause
  "3-Clause BSD License": BSD-3-Clause
  "3-Clause BSD": BSD-3-Clause
- "Maven:com.example.sdk"
  "Copyright (c) holder": 
- "Maven:com.example.sdk:4.0.1"
  "GPL": GPL-3.0-only
```

**Comment by mnonnenmacher** [comment]
We agreed in the TSC meeting to implement declared license mappings in the curations. Once this is implemented the option to overwrite declared licenses in curations should be removed, as this is a kind of license conclusion that should be avoided. Instead, declared licenses should either be mapped or a concluded license should be created.

**Comment by fviernau** [comment]
In case one wants to overwrite the declared license, it is much cheaper to actually only overwrite the declared license rather compared to doing a concluded license. So I don't really see why overwriting should be eliminated.

Or can the mapping easily achieve an overwrite?
