### ISSUE TITLE
Feature request: Add option to overwrite output files

### ISSUE THREAD

**Issue by OctagonHex** [oss-review-toolkit/ort#2899]
I would like to have an option to allow overwriting existing output files.
I'm learning oss-rt and I run the same command with slightly different arguments, but inbetween runs, I always have to manually delete the old output, otherweise oss will complain `Error: None of the output files [analyzerOut\analyzer-result.json] must exist yet.`

It is customary to use a agrument like "--force", or "--overwrite" in such cases to explictily allow overwriting files. If the whole directory needs to be empty, an argument like "--force-delete-dir" could allow to delete the whole output dir before starting the analysis.

**Comment by sschuberth** [comment]
As practically all our modules output something, this could be done by a global `--force-overwrite` option, instead of one per sub-command.
