### ISSUE TITLE
Publish artifacts to Maven Central (e.g. spdx-utils)

### ISSUE THREAD

**Issue by vlsi** [oss-review-toolkit/ort#2906]
`spdx-utils` looks like a Java API, however, it is not really accessible via regular repositories like Sonatype OSSRH.

**Comment by sschuberth** [comment]
Strongly relates to https://github.com/oss-review-toolkit/ort/issues/1901. @tsteenbe @mnonnenmacher do you see any (legal or otherwise) issues with publishing ORT libraries to Maven Central, now that we've moved the package namespace to `org.ossreviewtoolkit` and are a Linux Foundation project?

**Comment by mnonnenmacher** [comment]
No, I would very much appreciate if we started publishing to Maven Central.

**Comment by tsteenbe** [comment]
Yes, I think we need to have a call to decided on the version number for our first ORT release.

**Comment by sschuberth** [comment]
For the record, the `org.ossreviewtoolkit` project namespace on OSSRH / Maven Central has [long been created](https://issues.sonatype.org/browse/OSSRH-60269).

**Comment by sschuberth** [comment]
Version 1.0.0 artifacts of ORT have been published to Maven Central today, see e.g. https://repo1.maven.org/maven2/org/ossreviewtoolkit/utils/spdx-utils/.
