### ISSUE TITLE
Differentiate between Direct and Transitive Libraries in CycloneDX Report

### ISSUE THREAD

**Issue by CleanHit** [oss-review-toolkit/ort#2929]
Is it possible to add some mark for direct and transitive project libraries in the _CycloneDX_ report. For example a differentiation between a detected library __X__ (with some OSS license(s)) as a "direct" project dependency (i.e. first level dependency) and a library __Y__ as a "transitive" project dependency (e.g. is used by __X__)?

**Comment by CleanHit** [comment]
@sschuberth, @KorSin Thank you for implementing this. From which step (Evaluator?) should I execute ORT again to get the added tags populated in the CycloneDX report?

**Comment by sschuberth** [comment]
Just the reporter.

**Comment by CleanHit** [comment]
I'm not sure that it works correctly. I get the same number of libraries if I ignore the `dependencyTaype` tag and filter the __CycloneDX__ report by `scope = 'required'`. The thing is, that not every required library is a `direct` project dependency so I'm hoping to filter the transitive ones out. 

The _build.gradle_ file has 45 libraries marked with `implementation` so, I guess that only those are librarie's `direct` dependencies. The generated __CycloneDX__ report has 117 libraries with `<dependencyType xmlns="ort">direct</dependencyType>` where some of the results are definitely transitive libraries of direct ones.

I don't know if it's related but I'm using an old _evaluation-result.yml_ file (30.04.2020) generated form an even older _scan-result.yml_ file (04.03.2020) to generate my __CycloneDX_ report. So, maybe I need to run the whole _ORT_ process from scratch.

**Comment by sschuberth** [comment]
> The _build.gradle_ file has 45 libraries marked with `implementation` so, I guess that only those are project's `direct` library dependencies.

Note that e.g. `api` dependencies also are direct dependencies. In fact, everything directly declared in a *build.gradle* file is a "direct" dependency. Dependencies of dependencies are what we call "transitive" dependencies.

**Comment by CleanHit** [comment]
Ok, I've checked my _build.gradle_ file and there are no more than 45 direct dependencies. All of them use either the `implementation` or the `kapt` dependency annotation. Executing `../gradlew dependencies --configuration <same_as_my_ort_process_uses> | grep -v '| '` shows also 45 direct dependencies. 2 of them are 'jar' file dependecies so, in total there are 43 direct dependencies that should be marked by _ORT_ as direct dependencies.

I'll be running the whole _ORT_ process again just to fresh all of my output files and see what happens, because the _ORT_ Tool has significantly evolved since my lust full run.

**Comment by CleanHit** [comment]
The CycloneDX report has has 117 dependencies marked as `direct` instead of 43. Anyway, apart from that I've encountered this error again in multiple places regarding other packages during the `analyze` step
```
14:59:51.390 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenLogger - Failed to build parent project for org.glassfish.jaxb:txw2:jar:2.2.11
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[WARNING] Reporting configuration should be done in <reporting> section, not in maven-site-plugin <configuration> as reportPlugins parameter. @ 
[ERROR] 'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} @ com.sun.xml.bind.mvn:jaxb-parent:2.2.11, /root/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind.mvn/jaxb-parent/2.2.11/9496f6747e6d5ab5da869941dea4143969122b91/jaxb-parent-2.2.11.pom, line 188, column 29
``` 
At the button of my _analyzer-result.yml_ file I have `has_issues: true`, with older _ORT_ code state (03.2020) it was always `has_issues: false` without the error above. I don't see any _JAVA_ related errors in the _.yml_ file that have caused `has_issues: true` so, maybe there are some other issues that set this values.

Nevertheless, the only thing that has changed is _ORT_'s code. I'm still using the same _JDK12.0.2_ and project repository snapshot as before. I've even deleted the _.gradle/cache/_ content to be sure.

**Comment by sschuberth** [comment]
> Anyway, apart from that I've encountered this error again in multiple places regarding other packages during the `analyze` step

Please don't hijack issue reports with other problems, but file a new issue to we can track them individually.

> At the button of my _analyzer-result.yml_ file I have `has_issues: true`, with older _ORT_ code state (from 04.03.2020) it was always `has_issues: false` without the error above.

I recall there was a but in ORT which caused `has_issues` not to be set although it should have been set.

Unfortunately, I cannot really comment any further unless you can share your *analyzer-result.yml* file.

**Comment by CleanHit** [comment]
@sschuberth I've opened a new issue. Could you please place your response there? I'll remove the unneeded comments from this one afterwards

**Comment by sschuberth** [comment]
> I'll remove the unneeded comments from this one afterwards

That probably just creates confusion for people who already saw the comments here. Let's just separate issue comments going forward.

**Comment by CleanHit** [comment]
Ok, the related part to this ticket was that the CycloneDX report still shows 117 dependencies marked as direct instead of 43.

**Comment by sschuberth** [comment]
And here, like said, we can only help efficiently if you share the *analyzer-result.yml* file, or at least the `result:` section of it.

**Comment by CleanHit** [comment]
The `result:` section is very long. The file is 640 MB big and I would sys that much of it belongs to the `result:` section.

**Comment by CleanHit** [comment]
@sschuberth the `result:` section of my _analyzer-result.yml_ file has 10010385 lines. I've exported that section into a separate _YML_ file and it is **581MB** big. I guess you don't want it to be attached to this ticket...

**Comment by sschuberth** [comment]
Just `.tar.bz2`-compress (or ZIP) it, and it will become *much* smaller.

**Comment by CleanHit** [comment]
@sschuberth Done. Please rename the `.jpeg` to `.tar.bz2` because I couldn't upload the file with the original extension. 
![analyzer-result-section-only](https://user-images.githubusercontent.com/16132350/96118689-245bd180-0eec-11eb-9861-5dd160baaac1.jpeg)

**Comment by CleanHit** [comment]
Did you have time too look in to the file? Did you find anything helpful there?

**Comment by sschuberth** [comment]
I didn't have time to look at this yet, but a quick check by running

    $ grep "^        - id:" analyzer-result-section-only.yml | sort -u | wc -l
    209

shows that there are even 209 direct dependencies in the original YAML file already. Note that the Android plugin itself adds quite a few implicit direct dependencies, e.g. on various libraries from the `androidx` namespace. So I'm still not convinced that something is wrong.

Also, you may want to compare to the output of a plain `./gradlew dependencies`.
