### ISSUE TITLE
Using ORT image in Gitlab Pipeline

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#2930]
Hello
I have been using ORT image, built from a Dockerfile, for some time but recently I wanted to use the same ORT image in a gitlab pipeline and I am facing an error
```
Created fresh repository.
 Checking out 96b094dc as auditBranch...
 Skipping Git submodules setup
Executing "step_script" stage of the job script
00:04
 WARNING: An illegal reflective access operation has occurred
 WARNING: Illegal reflective access by retrofit2.Platform (file:/opt/ort/lib/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
 WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
 WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
 WARNING: All illegal access operations will be denied in a future release
 Usage: ort [OPTIONS] COMMAND [ARGS]...
 Error: Invalid value for "-c": File "if [ -x /usr/local/bin/bash ]; then
 	exec /usr/local/bin/bash 
 elif [ -x /usr/bin/bash ]; then
 	exec /usr/bin/bash 
 elif [ -x /bin/bash ]; then
 	exec /bin/bash 
 elif [ -x /usr/local/bin/sh ]; then
 	exec /usr/local/bin/sh 
 elif [ -x /usr/bin/sh ]; then
 	exec /usr/bin/sh 
 elif [ -x /bin/sh ]; then
 	exec /bin/sh 
 elif [ -x /busybox/sh ]; then
 	exec /busybox/sh 
 else
 	echo shell not found
 	exit 1
 fi
 " does not exist.                
 ERROR: Job failed: exit code 1
```
Maybe there is something different in using docker image from a docker run and gitlab-runner
Maybe I should play with entrypoint.

**Comment by sschuberth** [comment]
I guess we'd need some background info on *how* our `Dockerfile` / image is used in your gitlab-runner. At least the error message sounds as if some shell expansion goes nuts in the arguments passed to `ort`.

**Comment by tsteenbe** [comment]
@woznik I am actually working on ORT GitLab integration togehter with the help from engineer at GitLab - already fixed this issue by setting the entry point to an empty string. Plan to publish the integration soon as a new repository under on github.com/oss-review-toolkit and mirrored under gitlab.com/oss-review-toolkit.

**Comment by woznik** [comment]
Hi
The Dockerfile exactly the same as the one in the mater branch
In fact I have fixed the issue by applying entrypoint: [""] and triggering the scan from 
script: 
  - /opt/ort/bin/ort --info analyzer .......
  - /opt/ort/bin/ort --info scan .......
  - /opt/ort/bin/ort --info reporter .......

I am testing this case at the moment. It seems to run as from "docker run"

**Comment by woznik** [comment]
Hello,
After several tests it seems to be working well
Thank you for your feedback. The issue can be close
