### ISSUE TITLE
Remove superfluous blank lines from "how to fix" and "rule violation" details in the static HTML report

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#2975]
> @sschuberth I had to undo the removal of the superfluous blank lines.
> I think it's ok to keep them in the context of this PR as the output is identical with the how-to-fix sections for `rule violations` in that same file.

Ok, but I'll file a follow-up issue to remove those lines from both places.

_Originally posted by @sschuberth in https://github.com/oss-review-toolkit/ort/pull/2966/review_comment/create_

**Comment by mnonnenmacher** [comment]
I could not find a way to suppress those empty lines in the flexmark `HtmlRenderer`. I have tried a few of the options like `HtmlRenderer.MAX_BLANK_LINES` but to no avail. I also could not find any useful examples for customizing the formatting of the `HtmlRenderer`, so my suggestion would be to close this ticket.

**Comment by sschuberth** [comment]
Agreed, thanks for checking on this.
