### ISSUE TITLE
Artifactory Storage Issue - Could not read scan results for 'REPO' from path '...../scan-results.yml': IOException: 503

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#2982]
Hello
Recently I set up a storage to the Artifactory service
There is a problem in deploying or reading from repo with a 503 errorcode
It is likely the network communication problem, perhaps PROXY
I run the proces of analysis, scanner and reporter in a gitlab pipeline
In the job I need to provide the proxy to the INTERNET in order to get the public metadata and src. 
But in the same time I need to access INTERNAL artifactory service to store the cache
I have set up http_proxy, https_proxy and no_proxy to resolve all the addresses

![image](https://user-images.githubusercontent.com/17202024/91162603-9540f300-e6cc-11ea-8583-25c306a13a97.png)

A simple command "curl" works ok and I can deploy an artifact on Artifactory service but ORT scanner obtains an error saying that the servcice in Unavailable. 

![image](https://user-images.githubusercontent.com/17202024/91162374-4d21d080-e6cc-11ea-9f96-917c0a258e09.png)

Is there a way I colud investigate the network issue. Does no_proxy command is taken into account by ORT scanner?
Thanks in advance

**Comment by sschuberth** [comment]
> Recently I set up a storage to the Artifactory service

Just FYI, we recommend to use a PostgreSQL storage back-end over Artifactory for performance reasons, and PostgreSQL has other nice capabilities like being able to make interesting queries over the collected data etc.

> Does no_proxy command is taken into account by ORT scanner?

No, ORT currently does not take a `no_proxy` environment variable into account. I'll try to find the time to look into that.

**Comment by sschuberth** [comment]
@woznik would you mind testing whether https://github.com/oss-review-toolkit/ort/pull/2983 fixes your problem?

**Comment by woznik** [comment]
Sure, absolutely

**Comment by woznik** [comment]
OK, I have built the image from a "no-proxy-env-support" branch
I selected the new image in the gitlab pipeline 
I set up http_proxy, https_proxy and no_proxy to resolve all the addresses
and behavior is the same:

![image](https://user-images.githubusercontent.com/17202024/91176090-0fc83d80-e6e2-11ea-86dc-21c89c7087d5.png)

**Comment by sschuberth** [comment]
Which commit exactly did you use? As I've force-pushed the branch in between.

**Comment by woznik** [comment]
I have used the commit:
![image](https://user-images.githubusercontent.com/17202024/91176599-cb896d00-e6e2-11ea-95f5-f6cee3a82d9b.png)
I have checked before build if I see changes in the

**Comment by sschuberth** [comment]
Please use the current version of the branch which points to commit 1396f8eca5f04e476454a16bb08f8ccaf690beb0.

Also, can you share the contents of your `no_proxy` variable, or at least the general syntax you're using for it?

**Comment by woznik** [comment]
Yes, I just discovered the recent commit.
for no_proxy I use:

no_proxy: "docker,si.copmany.fr"

the address of internal artifactory is: 
`https://artifactory.si.company.fr/artifactory`

**Comment by sschuberth** [comment]
Ok, thanks, I believe the new version of the PR should be able to deal with that syntax.

**Comment by woznik** [comment]
I just verified the no_proxy in ORT image and it works well!!
Very good job. Thank you

**Comment by sschuberth** [comment]
I'm glad it works for you. Let's hope for the review to be completed soon so I can merge to `master`.
