### ISSUE TITLE
[postgres] Multiple entry in cache

### ISSUE THREAD

**Issue by fb33** [oss-review-toolkit/ort#2993]
Hello,

When I look in scan_results table in my ortdb postgres, I can see some multiple entry for the same identifier.
Do you know how can it happen ? Concurrent scanner phase ?

Regards

**Comment by sschuberth** [comment]
I believe this might happen due to the issue @fviernau did put a stop-gap in at https://github.com/oss-review-toolkit/ort/pull/2850.

**Comment by fviernau** [comment]
I'm aware of the following scenario where this happens:

1. You trigger a scan let's say passing an analyzer result
2. The scanner at the very beginning look-up scan cache entries for all packages and enqueues only the packages with no cache entry for scanning
3. The actual scan for each package takes place which involves writing to the scan cache at the end.

In above scenario the time interval between (2) and the storing of the cache entries in (3) might be large, e.g. even hours.
If during that time that same scenario is run in parallel, you'd end up with duplicate cache entries.

**Comment by fb33** [comment]
Hi @fviernau 

Yes in some rare cases, this scenario happens when I do tests in // with the jenkins pipeline. But we have normaly only 1 job running for OSS analysis
But I think, more oftens it's due to a crash/failure in CI when the scanner write in cache

**Comment by mnonnenmacher** [comment]
If no parallelism is involved I don't see how scan results could be duplicated. What kind of crash do you mean? I haven't seen any crashes while reading from or writing to the database so far.

**Comment by fb33** [comment]
I run ORT with docker in a K8S infrastructure. Sometimes K8S kill the pod for cpu or memory constraints.

**Comment by mnonnenmacher** [comment]
Since #4496 duplicate entries in the `PostgresStorage` are prevented by an index. For existing databases this index needs to be manually added after removing any duplicates, see: https://github.com/oss-review-toolkit/ort/blob/cef3f17fd000cd77c8e041e5381878d215460110/scanner/src/main/kotlin/storages/PostgresStorage.kt#L124-L131
