### ISSUE TITLE
Gitlab pipeline scan with token authentication - Repo URL question

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#2994]
Hello

I wanted to ask if it is a normal behavior for ORT that results and especially REPO URL is properly constructed

In my case I use gitlab with forced gitlab-ci-token authentication
As a result in analyzer yml output , scanner yml output and in the report I can see a following construction

URL | https://gitlab-ci-token@my-company-gitlab/group/project.git

![image](https://user-images.githubusercontent.com/17202024/91467700-35e01000-e891-11ea-8229-8b59875a3161.png)

These entries apear also on the artifactory side

Should it be like this or should it be a clean URL like: https://my-company-gitlab/group/project.git

Context: I use ORT image in a gitlab pipeline to scan the code from current branch

**Comment by sschuberth** [comment]
I'm not sure I got your question right: Are you concerned about the username being exposed as part of the URL included in the report?

**Comment by woznik** [comment]
I was only concerned about the gitlab-ci-token prefix in the repo url which also appears in the scan-result.yml files 
After double check it doesn not affect rescan using different credentials
I am closing the question. Thank you for your response
