### ISSUE TITLE
gitlab license scanning template quick feedback with ORT

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#2995]
Hello
I was trying to follow the yt video and put in place a sample proces of a quick  feedback by reusing the include of 
built-in template 
```yaml
include:
  - template: Security/License-Scanning.gitlab-ci.yml
```
Will it work with GitLab Community Edition 13.1.4 or only gitlab.com and Gitlab Ultimate /GOLD version?

**Comment by sschuberth** [comment]
Such questions are best directed at our [Slack channel](https://join.slack.com/t/ort-talk/shared_invite/enQtMzk3MDU5Njk0Njc1LThiNmJmMjc5YWUxZTU4OGI5NmY3YTFlZWM5YTliZmY5ODc0MGMyOWIwYmRiZWFmNGMzOWY2NzVhYTI0NTJkNmY) for faster feedback. But @tsteenbe and / or @mokhan might know the answer.

**Comment by woznik** [comment]
I would love to ask on slack but it is blocked in my company so far.

**Comment by mokhan** [comment]
At the moment License Scanning is only available to Ultimate customers. Some of us have tried to make this available to CE and all customers. It's a work in progress.

**Comment by woznik** [comment]
Thank you mokhan
