### ISSUE TITLE
Generalize the root license handling

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#3054]
ORT uses the term root licenses for the license information contained in files which:

1. match a given file name pattern, e.g. `/LICENSE` and
2. Are (a) located in the analyzer root for projects (b) located in the repository root for packages

There are projects out there which organize the `LICENSE` files hierarchically, e.g. consider
```
/LICENSE
/project-path/LICENSE
/project-path/build.gradle
/project-path/src/Hello.java
```
Currently the content of `LICENSE` is considered as `root license` for project located at `project-path/buid.gradle`.
As consequence `/LICENSE` is included in the scan results for `/project-path/build.gradle` and also in the `NOTICE` file generated from it.

Goal of this task: change the implementation so that the root license for any file x is determined by a search from x upwards the directory tree for files matching ORTs License file name pattern and then taking the first match as result.

**Comment by fviernau** [comment]
The ticket description only talks about a file named `LICENSE`, and if only that name is used it seems to make sense.
If multiple names come into play, it's not that clear anymore. `ORT` defines the license filenames:
- "license*",
- "licence*",
- "*.license",
- "*.licence",
- "unlicense",
- "unlicence",
- "copying*",
- "copyright",
- "patents",
And also:
- "readme"

This leads to the question: How should overriding work when names are different?

**Comment by sschuberth** [comment]
IMO any match from the first list that is closest to the analyzer root should win.

**Comment by fviernau** [comment]
@sschuberth did you mabybe mean `furthest away from` instead of closest?

Let me re-phrase the question with examples:

example 1:
```
/readme
/LICENSE
/deps/dep1/project1/build.gradle
/deps/dep1/LICENSE
```

example 2:
```
/LICENSE
/deps/dep1/project1/build.gradle
/deps/dep1/readme
```

For each example, which `license files` would apply to the files of `project1` ?

**Comment by sschuberth** [comment]
No, I really meant "closest", but I shouldn't have said "analyzer root", but probably "VCS path". I.e. in your example 1, only `/deps/dep1/LICENSE` should be taken into account for `project1`. For example 2, only `/LICENSE` should be considered for `project1`, even though there is a `/deps/dep1/readme`, whit the reason being that IMO `readme` should only serve as a last fallback if no other matches from the first list are found anywhere.

This could probably be implemented as a two-pass algorithm: First pass, try to find matches from first list starting from nested project directory to root. Only if none found, start a second pass trying to find matches from the second list (which contains `readme` only currently), also starting from nested project directory to root.

**Comment by fviernau** [comment]
Thanks @sschuberth for you great help! I'd just go and implement it accordingly if the rest of the TCS agrees, @mnonnenmacher @tsteenbe - do you?

**Comment by tsteenbe** [comment]
+1 from my side
