### ISSUE TITLE
StaticHtmlReport: introduce sections for the labels

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#3062]
I looks a bit arbitrary to swallow the part before the first `.`, and assuming that `.` as part of a label has a special meaning is not really generic. While I'd be fine to introduce the latter as a convention, I believe we should not omit parts before `.` but use them for some visual grouping as part of the reports.

_Originally posted by @sschuberth in https://github.com/oss-review-toolkit/ort/pull/3037#discussion_r484403786_

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
