### ISSUE TITLE
Include the dependency type to the Analyzer output

### ISSUE THREAD

**Issue by timovandeput** [oss-review-toolkit/ort#3084]
Currently the "scopes" section of the Analyzer YAML output provides a tree of package dependencies. Each entry consists of a package "id" and a list of "dependencies".

When using the Analyzer output for license analysis, the type of the dependency ("static link", "dynamic link" or "other") can have important implications for the license conditions. (E.g.: LGPL licensed code is only allowed in proprietary software if it is dynamically linked.)

Suggestion is to extend the existing elements in the "scopes" tree with a new field indicating their "type" of dependency on the level above, and extend all supported package manager implementations to provide this information.

**Comment by sschuberth** [comment]
That element is actually already supported, but it's only serialized if it deviates from the default of "dynamic linkage" to reduce the file size. See e.g. https://github.com/oss-review-toolkit/ort/blob/264ec63076d8d5b6afa389ed19d4c5dbbdaa2b84/analyzer/src/funTest/assets/projects/synthetic/cargo-expected-output.yml#L24.

**Comment by timovandeput** [comment]
I concluded it was not supported because for Pub packages (Flutter / Dart) the dependencies were not indicated as statically linked.

Should I report that as a separate issue?

**Comment by sschuberth** [comment]
I just did that. Please indicate in that new ticket whether you have any hints on how to find out whether a Pub package is statically or dynamically linked.
