### ISSUE TITLE
Package concluded license: Allow using "NONE"?!

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#3122]
@sschuberth @tsteenbe @mnonnenmacher : Shall we file a ticket for making "NONE" a valid value for the package concluded license in ORT?

Note that for license finding curations we already do allow that.

_Originally posted by @fviernau in https://github.com/oss-review-toolkit/ort/pull/3117#discussion_r494196928_

I'm a bit undecided. On the one hand it would be consistent to align on SPDX expressions for "everything about licenses". On the other hand, checking for (not) `null` is much more convenient than checking for `isPresent()` / `isNotPresent()`. My hunch is that we should still align on SPDX expression, but I'd like to also hear @mnonnenmacher opinion on that once he's back.

_Originally posted by @sschuberth in https://github.com/oss-review-toolkit/ort/pull/3117#discussion_r494258854_

**Comment by tsteenbe** [comment]
@fviernau  I prefer to follow SPDX see https://spdx.github.io/spdx-spec/3-package-information/#313-concluded-license: Data Format: <SPDX License Expression> | NONE | NOASSERTION

**Comment by sschuberth** [comment]
Very much related to https://github.com/oss-review-toolkit/ort/issues/2852 for declared licenses.
