### ISSUE TITLE
Analyzer com.sun:tools:jar Dependency SystemPath Error

### ISSUE THREAD

**Issue by CleanHit** [oss-review-toolkit/ort#3127]
I've decided to run the whole _ORT_ process on my old repositry from the start using latest _ORT_ master branch and I've  encountered this error again in multiple places regarding other packages during the `analyze` step
```
14:59:51.390 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenLogger - Failed to build parent project for org.glassfish.jaxb:txw2:jar:2.2.11
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[WARNING] Reporting configuration should be done in <reporting> section, not in maven-site-plugin <configuration> as reportPlugins parameter. @ 
[ERROR] 'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} @ com.sun.xml.bind.mvn:jaxb-parent:2.2.11, /root/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind.mvn/jaxb-parent/2.2.11/9496f6747e6d5ab5da869941dea4143969122b91/jaxb-parent-2.2.11.pom, line 188, column 29
...
``` 
At the button of my _analyzer-result.yml_ file I have `has_issues: true`, with older _ORT_ code state (from 04.03.2020) it was always `has_issues: false` without the error above. I don't see any _JAVA_ related errors in the _.yml_ file that have caused `has_issues: true` so, maybe there are some other issues that set this values or maybe I'm not searching correctly.

Nevertheless, the only thing that has changed is _ORT_'s code. I'm still using the same _JDK12.0.2_ and project repository snapshot as before. I've even deleted the _.gradle/cache/_ content to be sure.

**Comment by sschuberth** [comment]
The "[...] for com.sun:tools:jar must specify an absolute path but is [...]" is a generic error cause by using Java >= 11 with older JAXB versions. There's nothing ORT could do about it, but you (or the dependency using JAXB) should [upgrade to at least JAXB 2.3.0](https://stackoverflow.com/a/58787483/1127485).

**Comment by CleanHit** [comment]
So basically, I'll need to update every package where the problem occurs and see if the errors pop up again in the analyze step. If those errors are gone then in this case the `has_issues: true` conditions is harmless and I can ignore it with current package versions.

**Comment by sschuberth** [comment]
That's one way to do it, yes, but actually the same error should occur with a regular Maven build of the project when using Java 12.

**Comment by CleanHit** [comment]
I've checked out an old _ORT_ commit `e8369c3dcd57d41bd3cfa4f3961bc4757a65b420` (04.03.2020) and left everything else as is. The error was still present and I think it was always there but I've forgot about it. Nevertheless the issue flag reports:  `has_issues: false`, did anything change in _ORT_ that could have caused this behavior?

**Comment by sschuberth** [comment]
Yes, as mentioned before there was a bug in ORT back then which caused `has_issues` to be set to `false` although there *were* issues, see https://github.com/oss-review-toolkit/ort/pull/2405.
