### ISSUE TITLE
Analyze Android NDK projects without NDK installed

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#3129]
We should investigate whether it's somehow possible to analyze Android projects that depend on the Android NDK either without installing the NDK at all, or by bootstrapping the NDK, so we do not need to install it / add it to the `Dockerfile` beforehand.

**Comment by sschuberth** [comment]
Maybe a project from https://github.com/android/ndk-samples can be used for testing.

**Comment by sschuberth** [comment]
And maybe https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin implements some ideas that we could reuse (also ping @mnonnenmacher).

**Comment by mnonnenmacher** [comment]
The Android Gradle plugin can bootstrap the NDK so it should not be necessary to add it to the Dockerfile (relates to https://github.com/oss-review-toolkit/ort/pull/5059/commits/44ece47f73718a93725c7066bc3bc403e462e746).

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
