### ISSUE TITLE
Create a file to easily integrate ORT with Azure Pipelines

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#3154]
Similar to the `Jenkinsfile`, we should have a file to easily set up ORT as a parameterized job in Azure Pipelines.

**Comment by Martin-Idel-SI** [comment]
First PR here: https://github.com/oss-review-toolkit/ort/pull/3339

**Comment by sschuberth** [comment]
There were several smaller follow-up PRs merged meanwhile which in sum resolve this feature.
