### ISSUE TITLE
ClearlyDefinedStorage does not filter for scanner details and provenance

### ISSUE THREAD

**Issue by oheger-bosch** [oss-review-toolkit/ort#3164]
The _ClearlyDefinedStorage_ class implements the two overloaded _readFromStorage()_ methods as required by the abstract _ScanResultStorage_ base class. The contract of these methods has only recently been defined explicitly by adding further documentation; in addition, a default implementation for one of these methods has been added.

The current implementation of _ClearlyDefinedStorage_ does not adhere to the contract of the _readFromStorage()_ methods because it does not correctly filter scan results based on the parameters provided. So for instance, the version of ScanCode is not taken into account. This causes potential false-positives: results are returned when they should not.

**Comment by sschuberth** [comment]
> The contract of these methods has only recently been defined explicitly by adding further documentation; in addition, a default implementation for one of these methods has been added.

Note that this is not merged yet, it's pending review at https://github.com/oss-review-toolkit/ort/pull/3160.

**Comment by mnonnenmacher** [comment]
> 
> 
> > The current implementation of _ClearlyDefinedStorage_ does not adhere to the contract of the _readFromStorage()_ methods because it does not correctly filter scan results based on the parameters provided.
> 
> @mnonnenmacher, is this already solved generically in the experimental [provenance-based storage implementations](https://github.com/oss-review-toolkit/ort/pull/4525)?

No, for all existing package based storages this change only added a wrapper for the new storage interfaces, so existing bugs inside the storage implementations are still relevant.

**Comment by sschuberth** [comment]
This was addressed as part of https://github.com/oss-review-toolkit/ort/pull/7666.
