### ISSUE TITLE
Build fails on OpenJDK15

### ISSUE THREAD

**Issue by Duncan-Howe** [oss-review-toolkit/ort#3175]
I have encountered an issue trying to build the repository regarding a deprecated method call in Kotlin.

**Error message:**
Task :spdx-utils:compileKotlin FAILED
e: warnings found and -Werror specified
w: <myPath>\ort\spdx-utils\src\main\kotlin\model\SpdxPackage.kt: (202, 28): 'isEmpty(): Boolean' is deprecated. This member is not fully supported by Kotlin compiler, so it may be absent or have different signature in next major version
w: <myPath>\ort\spdx-utils\src\main\kotlin\model\SpdxPackage.kt: (206, 26): 'isEmpty(): Boolean' is deprecated. This member is not fully supported by Kotlin compiler, so it may be absent or have different signature in next major version

**OS:** Windows 10
**JDK:** OpenJDK15

**Workaround:** I was able to work around the issue by changing the Kotlin compiler options in **<myPath>\ort\build.gradle.kts** to set **allWarningsAsErrors = false** (line 201)

With this workaround, the build succeeds (with lots of warnings of the same nature) and everything seems to run - I have "analyzed", "scanned" and "reported" to CycloneDX successfully.

**Comment by sschuberth** [comment]
Thanks for the report, I've also seen the `'isEmpty(): Boolean' is deprecated` error with Java 15, but decided to postpone looking into it until after the Gradle 6.7 final release which [will have support Java 15](https://docs.gradle.org/6.7-rc-3/release-notes.html).

**Comment by sschuberth** [comment]
@Duncan-Howe can you report back whether the issue is still there with current ORT?

**Comment by Duncan-Howe** [comment]
@sschuberth It seems to be fine now - I took the latest version a few days ago and built it successfully from source. The only warnings displayed were about deprecated features for Gradle 8.0.
