### ISSUE TITLE
NuGet/DotNet: Support authenticated package sources

### ISSUE THREAD

**Issue by MarcelBochtler** [oss-review-toolkit/ort#3188]
The `NuGet.Config` configuration file supports adding multiple package sources (See: #2189).
These package sources may require authentication which is described [here](https://docs.microsoft.com/de-de/nuget/reference/nuget-config-file#packagesourcecredentials).
```xml
<packageSourceCredentials>
    <Contoso>
        <add key="Username" value="user@contoso.com" />
        <add key="Password" value="..." />
    </Contoso>
    <Test_x0020_Source>
        <add key="Username" value="user" />
        <add key="Password" value="..." />
    </Test_x0020_Source>
</packageSourceCredentials>
```

These credentials should be used in order to resolve the dependencies of NuGet packages from the authenticated package sources.

**Comment by sschuberth** [comment]
@MarcelBochtler have you tested this to be fixed with https://github.com/oss-review-toolkit/ort/pull/6209?

**Comment by pombredanne** [comment]
@sschuberth this is supported on the nuget-inspector side and tested extensively there.
