### ISSUE TITLE
NuGet/DotNet: Support different package source catalog formats

### ISSUE THREAD

**Issue by MarcelBochtler** [oss-review-toolkit/ort#3190]
The retrieval and parsing of NuGet catalog URLs currently only works if the catalog URL follows the format from the  [the default indexer (api.nugget.org)](https://api.nuget.org/v3/index.json):
```jsonc
{
  "@id": "https://api.nuget.org/v3/registration5-gz-semver2/colorful.console/1.2.11.json",
  "@type": [
    "Package",
    "http://schema.nuget.org/catalog#Permalink"
  ],
  "catalogEntry": "https://api.nuget.org/v3/catalog0/data/2020.08.22.17.09.36/colorful.console.1.2.11.json",
  "listed": true,
  "packageContent": "https://api.nuget.org/v3-flatcontainer/colorful.console/1.2.11/colorful.console.1.2.11.nupkg",
  // ...
  }
}
```

Some indexers seem to provide the catalogEntry when building the URL as it is done for api.nuget.org.
`val dataUrl = "$baseUrl/$lowerId/${id.version}.json"`
E.g. when building the URL from [this indexer](https://www.myget.org/F/rogueexception/api/v3/index.json):
```
      "@id": "https://www.myget.org/F/rogueexception/api/v3/registration1/",
      "@type": "RegistrationsBaseUrl/3.6.0",
```
The build URL links to a file that seems to be the catalogEntry directly:
https://www.myget.org/F/discord-net/api/v3/registration1/discord.net/2.3.0-dev-20200718.1.json
```jsonc
{
  // ...
  "@id": "https://www.myget.org/F/discord-net/api/v3/registration1/discord.net/2.3.0-dev-20200718.1.json",
  "@type": [
    "Package",
    "catalog:Permalink"
  ],
  "authors": "Discord.Net Contributors",
  "catalog:commitId": "4ac141ba-7673-4471-a763-a8ffd3476730",
  "catalog:commitTimeStamp": "2020-07-18T17:55:33.8952496",
  // ...
}
```

Another example format that ORT is currently not able to parse is packages from https://pkgs.dev.azure.com ([example index.json](https://pkgs.dev.azure.com/ms/terminal/_packaging/TerminalDependencies/nuget/v3/index.json)) which use this format for [packages hosted there](https://pkgs.dev.azure.com/ms/20953fb4-d427-4ad6-b78c-13142d0c5462/_packaging/64e3bf16-3e04-41cd-b90f-60fdc9ccf494/nuget/v3/registrations2-semver2/terminal.themehelpers/0.2.200324001.json):
```jsonc
{
  // ...
  "catalogEntry": "https://pkgs.dev.azure.com/ms/20953fb4-d427-4ad6-b78c-13142d0c5462/_apis/packaging/64e3bf16-3e04-41cd-b90f-60fdc9ccf494/nuget/commitLog/ce5d3446dbb7427fb3f8179cf3f9802f",
  "listed": true,
  "packageContent": "https://pkgs.dev.azure.com/ms/20953fb4-d427-4ad6-b78c-13142d0c5462/_packaging/64e3bf16-3e04-41cd-b90f-60fdc9ccf494/nuget/v3/flat2/terminal.themehelpers/0.2.200324001/terminal.themehelpers.0.2.200324001.nupkg",
  // ...
}
```

**Comment by sschuberth** [comment]
@MarcelBochtler have you tested this to be fixed with https://github.com/oss-review-toolkit/ort/pull/6209?

**Comment by sschuberth** [comment]
> In nuget-support

I guess you mean *nuget-inspector*.

> we support all the different formats supported by the NuGet libraries

Ok, then let's close this and reopen if needed.
