### ISSUE TITLE
Docker build fails behind proxy

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#3227]
Hello
I have noticed that after the recent changes in the source code I see that the docker build fails at pullng sbt package

![image](https://user-images.githubusercontent.com/17202024/96696410-062e1f80-138b-11eb-96b4-74b77314b52f.png)

My previous successful build was on commit: 
https://github.com/oss-review-toolkit/ort/commit/0faec0319e3050d15b87c927bdeee976e5044681

I use still the same command docker build --build-arg "http_proxy=..." --build-arg "https_proxy=..." (...)

Should I add something to properly handle the proxy?

Of course I set up DOCKER_BUILDKIT: "1" in my pipeline Image DOCKER: "docker-18.09-dind"

**Comment by sschuberth** [comment]
Could this be another implication of https://github.com/AdoptOpenJDK/openjdk-docker/issues/445, also see https://github.com/oss-review-toolkit/ort/issues/3226? If so, this should be fixed by now.

**Comment by woznik** [comment]
I switched to `19.03` and the build works fine. There was indeed an issue with the upperstream image. 

Thank you.

Closing the ticket.
