### ISSUE TITLE
ORT configuration should support references to environment variables

### ISSUE THREAD

**Issue by oheger-bosch** [oss-review-toolkit/ort#3242]
When ORT is run in certain environments (e.g. in cloud environments) some configuration properties should be obtained from environment variables rather than reading them from the configuration file. This is especially important for sensitive data like credentials for the Postgres database.

Note: The _hoplite_ library used for reading the configuration file already supports a configuration source for environment variables. This just has to be integrated.

**Comment by neubs-bsi** [comment]
Necessary to define priority: 
- environment variables have higher priorities than configuration file entry values.
- command line parameters have highest priority

**Comment by oheger-bosch** [comment]
@KorSin, last week I had a look into this issue as well. I noticed that the [Hoplite](https://github.com/sksamuel/hoplite) library used to load the configuration file already supports a way to reference environment variables. I have created a [PR](https://github.com/oss-review-toolkit/ort/pull/3272) with a documentation update.

In addition to this mechanism, Hoplite has a configuration source for environment variables. I think it would make sense to support this as well, which can be done in this ticket. This would allow overriding parts of the configuration via environment variables in a way analogously to ORT's -P command line option.

**Comment by KorSin** [comment]
Thank you for the information @oheger-bosch. Actually, Hoplite scans environmental variables by default, so ORT already supports this unknowingly. The only problem is the priority, as environmental variables have right now the highest priority which is in conflict with the command line parameters. I try to figure out how to solve this.

**Comment by oheger-bosch** [comment]
@KorSin, FYI: The [PR with the documentation update](https://github.com/oss-review-toolkit/ort/pull/3272) has been merged.
