### ISSUE TITLE
Allow specifying http authentication via environment variables

### ISSUE THREAD

**Issue by Martin-Idel-SI** [oss-review-toolkit/ort#3245]
Similar to #3242 : 

When we need credentials to access a repository, they currently need to be provided via .netrc files.
This is totally fine for local use, but suboptimal for cloud deployments on shared runners, because it requires writing files with credentials. The usual solution is using environment variables. 

- Allow specifying environment variables for the `download` step
- Environment variables take precedence over .netrc

**Comment by sschuberth** [comment]
How would you deal with host-specific credentials? Would you have a proposal for an environment variable naming scheme? Is there an existing (semi) standard that we could follow, similar to the one for `.netrc` files?

**Comment by Martin-Idel-SI** [comment]
Good questions. Regarding standardisation, there is no standard that I know of except for the fact that shell-used environment variables must be upper-case snake case and not start with a number and not contain "=" (see https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html) - but this standard is weak.

As for host-specific environment variables I wonder whether this is needed. I would assume that one of two workflows works:

Either:
- the user knows about the benefits and risks of using this file, i.e. the system running ORT is secure and only used by known agents
- several hosts are managed by a `.netrc` file
- this is always used by whoever runs ort (either in a docker container or not)

Or:
- the system is insecure, thus storing credentials is not a good idea
- credentials to different hosts are stored separately and managed by the user (e.g. in a cloud vault)
- the user manages host-specific credentials by passing in only the username/password currently needed

For instance, when downloading the config I would provide one set of credentials and when downloading the project another set. Since those are two calls to ORT anyway, I can switch environment variables in between. The credential environment variables could then be `ORT_USERNAME` and `ORT_PASSWORD` for instance.

If, however, multi-hostname scenarios for one download call need to be supported - I am unsure that this is necessary - I agree that environment variables get cumbersome. In that case, could we maybe use encrypted .netrc files and provide the decryption key via environment variable? Git allows something similar.

**Comment by sschuberth** [comment]
> Environment variables take precedence over .netrc

Note that in my proposed PR https://github.com/oss-review-toolkit/ort/pull/3259 the `.netrc` takes precedence as its contents might be machine-specific, and IMO machine-specific credentials should take precedence over generic credentials.

**Comment by Martin-Idel-SI** [comment]
Yes, this looks good to me. Maybe add a sentence to the README somewhere?

**Comment by sschuberth** [comment]
> Maybe add a sentence to the README somewhere?

Done in a new commit in the same PR: https://github.com/oss-review-toolkit/ort/pull/3259/commits/b03b5995e50d2d1810d3505a552808b2f4637390
