### ISSUE TITLE
why build failed?

### ISSUE THREAD

**Issue by 00032118** [oss-review-toolkit/ort#3246]
D:\openSource\ort-master>gradlew.bat installDist
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\openSource\ort-master\buildSrc\build.gradle.kts' line: 31

* What went wrong:
Plugin [id: 'org.gradle.kotlin.kotlin-dsl', version: '1.3.6'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:1.3.6')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 17s

D:\openSource\ort-master>

**Comment by sschuberth** [comment]
Superseded by https://github.com/oss-review-toolkit/ort/issues/3253.
