### ISSUE TITLE
Ensure ORT runs with a maximum of at least 8 GiB in Docker

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#3248]
For larger (Gradle) projects the analyzer might run into memory issues if the maximum mount of memory available to the JVM is less than something like 8 GiB. We should ensure in the `Dockerfile` to start ORT with according memory settings.

**Comment by MarcelBochtler** [comment]
ORT itself should be configured to be allowed to use more memory to avoid issues with larger projects. This can be done using the `JAVA_OPTS="-Xmx8g"` environment variable.
For Gradle projects I observed that analysing the dependencies runs out of memory with the exception:
```
Resolving dependencies for 'build.gradle' failed with: 
BuildException: Could not fetch model of type 'DependencyTreeModel' using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-6.6.1-all.zip'.
Caused by: LocationAwareException: Java heap space\nCaused by: OutOfMemoryError: Java heap space
```
This can be solved by configuring gradle with `org.gradle.jvmargs=-Xmx8g` in `~/.gradle/gradle.properties`.

A related issue is #3091 but this change will only lower the propebility that out of memory issues occur and not solve the root cause.

**Comment by sschuberth** [comment]
> This can be solved by configuring gradle with `org.gradle.jvmargs=-Xmx8g` in `~/.gradle/gradle.properties`.

We should fine a way to do this automatically via the Gradle Tooling API. @MarcelBochtler did you already have any luck with this?

**Comment by MarcelBochtler** [comment]
> @MarcelBochtler did you already have any luck with this?

Yes this works:
```kotlin
val dependencyTreeModel = connection
    .model(DependencyTreeModel::class.java)
    .addJvmArguments("-Xmx8g")
    .setStandardOutput(stdout)
    .setStandardError(stderr)
    .withArguments("-Duser.home=${Os.userHomeDirectory}", "--init-script", initScriptFile.path)
    .get()
```
IMO this should not be hard coded but still be configurable.
At the moment ORT uses the user's `gradle.properties` when analyzing a Gradle project.

Not sure if ORT should keep this strategy. I think from a user's perspective it makes more sense to use the Xmx value that is passed into ORT also for the spun up JVM for the gradle dependencies task.
What do you think? @sschuberth

**Comment by sschuberth** [comment]
Which setting takes precedence, `gradle.properties` or `addJvmArguments()`? If the former takes precedence, I believe it should be fine for us to hard-code a memory amount via `addJvmArguments()` that works for our recently scanned projects. This is more convenient than requiring users of the Dockerfile to create a `gradle.properties`.

**Comment by MarcelBochtler** [comment]
`addJvmArguments()` taskes precendence.

**Comment by MarcelBochtler** [comment]
> This is more convenient than requiring users of the Dockerfile to create a gradle.properties.

Dockerfile users won't have to create a `gradle.properties` if they do not want to override the max heap memory setting.

IMO we have two options:
1. Read and use the existing gradle setting (not the file, but maybe the `GradleConnector` contains this information).
2. Ignore the gradle setting and use the setting from `JAVA_OPTS`
