### ISSUE TITLE
Rework the licenses.yml file

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#3274]
This is the epic to bundle several issues with the current `licenses.yml` file:

* The file itself should be renamed to `license-classification.yml` as `licenses.yml` sounds as if this was *the* list of licenses support / known in ORT, which it is not (what comes closest to such a list is the resources under `spdx-utils/src/main/resources`).
* `license_sets` [should be renamed](https://github.com/oss-review-toolkit/ort/issues/2624).
* Flags like `include_in_notice_file` and `include_source_code_offer_in_notice_file` [are too specific](https://github.com/oss-review-toolkit/ort/issues/2663) and should be replaced by the set / label / category mechanism from above.
* Add the concept of [License Classification Providers](https://github.com/oss-review-toolkit/ort/issues/2625).

**Comment by sschuberth** [comment]
@mnonnenmacher @fviernau I'd like to start working on this epic. To start with, are you fine with the renaming `license-classification.yml`, or do you propose a different name?

**Comment by tsteenbe** [comment]
@sschuberth We agreed in the TSC meeting on to rename `licenses.yml` to `﻿﻿﻿license-classifications.yml` see point 1 in https://github.com/oss-review-toolkit/ort-governance/blob/8ef193dcd8d810aa9d693ab1c2ca61078c722efa/minutes/2020-05-07.md

**Comment by sschuberth** [comment]
Thanks for reminding me. I was briefly thinking about whether we should really use plural "...-classification*s*.yml" or singular "...-classification.yml" as the former sounds a bit over-complicated to me, but given that we use plural for many other similar files ("curations.yml", "rules.kts") I guess it's fine to also use plural here.

**Comment by oheger-bosch** [comment]
@sschuberth, all points have been implemented except for the concept of license classification providers. As there is a [dedicated ticket](https://github.com/oss-review-toolkit/ort/issues/2625) for this purpose, can this issue now be closed?

**Comment by sschuberth** [comment]
I believe there might be still some low-hanging fruit to finish up this task. Here's what I propose:

- Rename the `LicenseConfiguration` class to `LicenseClassifications` to match the naming of `license-classifications` which is the file whose contents it represents. Also, the class docs for `LicenseConfiguration` already talk about "A classification ..." (which BTW maybe then should be changed to "Classifications ..."), so I believe we should align here.

- Rename the `License` class to `LicenseCategorization` because that's what it does: Associating a license a with categories.

Does that make sense to you @oheger-bosch and also @fviernau?

Once that's done I'm with with closing this only only keeping https://github.com/oss-review-toolkit/ort/issues/2625 open for now.

**Comment by fviernau** [comment]
> Does that make sense to you @oheger-bosch and also @fviernau?

I'm ok with it.
