### ISSUE TITLE
Add VulnerableCode as a security vulnerability provider

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#3287]
See https://github.com/nexB/vulnerablecode. It's already aggregating data, see https://github.com/nexB/vulnerablecode/tree/main/vulnerabilities/importers, and might avoid the need to separately implement e.g. https://github.com/oss-review-toolkit/ort/issues/2880.

**Comment by neubs-bsi** [comment]
Should be merged first: https://github.com/oss-review-toolkit/ort/issues/3268

**Comment by oheger-bosch** [comment]
An initial implementation has been added to the code base. It may be extended/improved when the bulk API of VulnerableCode for querying vulnerabilities is available.

**Comment by sschuberth** [comment]
> An initial implementation has been added to the code base.

An it was done in https://github.com/oss-review-toolkit/ort/pull/3548.

**Comment by sschuberth** [comment]
There is now a public instance hosted at https://public.vulnerablecode.io/, also see https://github.com/nexB/vulnerablecode/issues/253.
