### ISSUE TITLE
Docker Image Build Fails at

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#3306]
Hello
Did you notice any perticular probles in building docker image on a commit (`6dbe7e37`) to the master branch

![image](https://user-images.githubusercontent.com/17202024/98407418-f04d7980-206f-11eb-9af8-8146d13e5f54.png)

Are you able to build the docker on your side?

PS: Do you have in plans to publish ORT Docker Image on a public repository, for instance Docker Hub?

**Comment by mmurto** [comment]
The Dockerfile uses some features only available to Docker's BuildKit backend, so you need to enable it with the env variable `DOCKER_BUILDKIT`.

Try running `DOCKER_BUILDKIT=1 docker build -t ort .`

**Comment by sschuberth** [comment]
This is unrelated to BuildKit and is going to be fixed by https://github.com/oss-review-toolkit/ort/pull/3302.
