### ISSUE TITLE
[Docker] Failed to build

### ISSUE THREAD

**Issue by fb33** [oss-review-toolkit/ort#3318]
Hi, 

I updated my ort source this morning, and now the build docker is failing.
There is a compilation error :
```
#14 34.57 > Task :downloader:compileKotlin FAILED
#14 34.57 e: /usr/local/src/ort/downloader/src/main/kotlin/vcs/Subversion.kt: (268, 46): Unresolved reference: requestPasswordAuthenticationInstance
#14 34.57
#14 34.57 FAILURE: Build failed with an exception.
```
The method requestPasswordAuthenticationInstance  is not in jdk8 but in the 9.
```
    /**
     * Ask this authenticator for a password.
     *
     * @param host The hostname of the site requesting authentication.
     * @param addr The InetAddress of the site requesting authorization,
     *             or null if not known.
     * @param port the port for the requested connection
     * @param protocol The protocol that's requesting the connection
     *          ({@link java.net.Authenticator#getRequestingProtocol()})
     * @param prompt A prompt string for the user
     * @param scheme The authentication scheme
     * @param url The requesting URL that caused the authentication
     * @param reqType The type (server or proxy) of the entity requesting
     *              authentication.
     *
     * @return The username/password, or null if one can't be gotten
     *
     * @since 9
     */
    public PasswordAuthentication
    requestPasswordAuthenticationInstance(String host,
                                          InetAddress addr,
                                          int port,
                                          String protocol,
                                          String prompt,
                                          String scheme,
                                          URL url,
                                          RequestorType reqType)
```
We have to change `FROM frolvlad/alpine-java:jdk8-slim AS build` to go to a jdk9.
But which one to choose?

**Comment by sschuberth** [comment]
Hmm, I wonder whether we could simply bump the required Java version straight to 11, which is an LTS release.

@mnonnenmacher @fviernau do you see any problems with requiring Java 11?

**Comment by mnonnenmacher** [comment]
Before we can switch to Java 11 we need to know if this issue is fixed in the current Android SDK: https://stackoverflow.com/questions/53076422/getting-android-sdkmanager-to-run-with-java-11

**Comment by sschuberth** [comment]
Yes, it is fixed. Our official [Dockerfile uses Java 11](https://github.com/oss-review-toolkit/ort/blob/ac66e17e670f955895a9a13f47c89d8f8159f25e/Dockerfile#L42) and installs / [configures the Android SDK just fine](https://github.com/oss-review-toolkit/ort/blob/ac66e17e670f955895a9a13f47c89d8f8159f25e/Dockerfile#L147).

**Comment by sschuberth** [comment]
Unfortunately, we can't use Gradle's new [toolchain](https://blog.gradle.org/java-toolchains) mechanism [yet](https://youtrack.jetbrains.com/issue/KT-43095) to bootstrap Java.

**Comment by mnonnenmacher** [comment]
Then I don't see any general issue with upgrading to Java 11, except if this somehow prevents the analyzer from analyzing older Maven/Gradle/SBT projects. But I would suggest you upgrade the Dockerfile and the Java requirement in different PRs, so that the Docker fix is not blocked by our internal upgrades.

**Comment by sschuberth** [comment]
> But I would suggest you upgrade the Dockerfile and the Java requirement in different PRs

Agreed: https://github.com/oss-review-toolkit/ort/pull/3319
