### ISSUE TITLE
source code build error

### ISSUE THREAD

**Issue by dd-jy** [oss-review-toolkit/ort#3322]
Hi,
I tried to build the latest source code.
But it failed with below error.
Can you check it?

```
Configuration on demand is an incubating feature.

> Configure project :
Reckoned version: 0.1.0-SNAPSHOT

> Configure project :reporter-web-app
Will use the Node executable file from '/home/jiyeongseok/.gradle/nodejs/node-v12.16.1-linux-x64/bin/node'.
Will use the Yarn JavaScript file from '/home/jiyeongseok/.gradle/yarn/yarn-v1.22.4/bin/yarn.js'.

> Task :downloader:compileKotlin FAILED
e: /home/jiyeongseok/ort/downloader/src/main/kotlin/vcs/Subversion.kt: (268, 46): Unresolved reference: requestPasswordAuthenticationInstance

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':downloader:compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork
   > Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s
32 actionable tasks: 6 executed, 26 up-to-date

```

**Comment by sschuberth** [comment]
We (accidentally) require Java 11 as of recently, but we're actually planning to bump the required Java version to 11 officially due to that. Out of curiosity, would the requirement of Java 11 be an issue for you?

**Comment by dd-jy** [comment]
It is not an issue for me to update the Java version to 11.

 I updated the Java version to 11, but it failed to build with the same error.
It may have another issue.
![image](https://user-images.githubusercontent.com/50347670/98788915-ded7e900-2444-11eb-8feb-16d2a75194a9.png)

**Comment by sschuberth** [comment]
Can you please verify that Gradle is actually using your Java 11 installation for compilation? You can do so by running `./gradlew --version` and looking at the "JVM" line.

Note that Gradle distinguishes between the Java version used for running Gradle itself, and the Java version used for building the project. The latter is usually configured using the `org.gradle.java.home` property.

**Comment by dd-jy** [comment]
Thank you for your quick support!
I changed JAVA_HOME environment value and it built successfully!

**Comment by dd-jy** [comment]
One more requests.
Can you update the system requirements in the README.md?
![image](https://user-images.githubusercontent.com/50347670/98793138-cf5b9e80-244a-11eb-987e-f3afe0e22c40.png)

**Comment by sschuberth** [comment]
As written above, we are *planning* / considering to bump the required Java version to 11. It's not yet fully decided. Either we make the code compile with Java 8, or I'll update the docs accordingly.
