### ISSUE TITLE
PostgresStorage uses only a single database connection

### ISSUE THREAD

**Issue by oheger-bosch** [oss-review-toolkit/ort#3328]
So far when creating an instance of PostgresStorage a single database connection is fetched from the database driver and stored by the instance. This connection is then used for the whole life-time of the storage object.

We have encountered problems with this setup with a managed PostgresDB in Azure. Sometimes the connection gets broken, and then the storage does not work any longer - the cache cannot be queried, and no new scan results can be stored any more.

In addition, as the database can be accessed from multiple threads - LocalScanner.scanPackages() creates a separate dispatcher for querying the storage with 5 threads -, having a single connection only is not ideal; refer for instance to [this question on stackoverflow](https://stackoverflow.com/questions/1531073/is-java-sql-connection-thread-safe).

A better alternative could be using a DataSource with an underlying connection pool, e.g. [Apache Commons DBCP](https://commons.apache.org/proper/commons-dbcp/) or [C3p0](https://www.mchange.com/projects/c3p0/). Here the pool would manage multiple connections to be used by multiple threads in parallel. It could also detect broken connections and refresh them automatically.

**Comment by neubs-bsi** [comment]
- Connection pool  can be configured, but initial hard coded configuration would be okay. 
- @nnobelis Advise to not use c3p0 or apache commons dbcp, recommendation to use: https://github.com/brettwooldridge/HikariCP
