### ISSUE TITLE
Package configuration file not applied to the reporters

### ISSUE THREAD

**Issue by mlmilan** [oss-review-toolkit/ort#3363]
It looks like packageConfigurationProvider (https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-package-configuration-yml.md) provided by ReporterInput is not being used anywhere except for SpdxDocumentReporter. The reports are not excluding licenses from subfolders of dependencies. Example:

packages.yml:

```
\- id: "NPM::esprima:4.0.1"
&nbsp;&nbsp;vcs:
&nbsp;&nbsp;&nbsp;&nbsp;type: "Git"
&nbsp;&nbsp;&nbsp;&nbsp;url: "https://github.com/jquery/esprima.git"
&nbsp;&nbsp;&nbsp;&nbsp;revision: "0ed4b8afdf2abd416f738977672c6232836f410a"
&nbsp;&nbsp;path_excludes:
&nbsp;&nbsp;- pattern: "test/**"
&nbsp;&nbsp;&nbsp;&nbsp;reason: "TEST_OF"
&nbsp;&nbsp;&nbsp;&nbsp;comment: "This directory contains documentation which is not distributed."

scan-result.yml

\- id: "NPM::esprima:4.0.1"
&nbsp;&nbsp;results:
&nbsp;&nbsp;- provenance:
&nbsp;&nbsp;&nbsp;&nbsp;download_time: "2020-11-19T14:09:41.489156Z"
&nbsp;&nbsp;&nbsp;&nbsp;vcs_info:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type: "Git"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;url: "https://github.com/jquery/esprima.git"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;revision: "0ed4b8afdf2abd416f738977672c6232836f410a"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;resolved_revision: "0ed4b8afdf2abd416f738977672c6232836f410a"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path: ""
&nbsp;&nbsp;&nbsp;&nbsp;original_vcs_info:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type: "Git"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;url: "https://github.com/jquery/esprima.git"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;revision: "0ed4b8afdf2abd416f738977672c6232836f410a"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path: ""
....
\- license: "MIT"
&nbsp;&nbsp;location:
&nbsp;&nbsp;&nbsp;&nbsp;path: "test/3rdparty/jquery-1.9.1.js"
&nbsp;&nbsp;&nbsp;&nbsp;start_line: 9
&nbsp;&nbsp;&nbsp;&nbsp;end_line: 10
```

reporter call:
`./cli/build/install/ort/bin/ort --debug --stacktrace report -f CycloneDX -O CycloneDx=single.bom=true -O CycloneDx=omit.excluded=true -i ./work/scan-result.yml -o ./work/Downloads --package-configuration-file ./work/packages.yml`

**Comment by sschuberth** [comment]
I can confirm that there was an issue in the `CycloneDxReporter` (and also in `AmazonOssAttributionBuilderReporter` and `AntennaAttributionDocumentReporter`), but esp. the new `AsciidocTemplateReporter` should not have this issue.

Can you confirm that https://github.com/oss-review-toolkit/ort/pull/3384 fixes your issue, and that the `AsciidocTemplateReporter` was not affected?

**Comment by mnonnenmacher** [comment]
> It looks like packageConfigurationProvider (https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-package-configuration-yml.md) provided by ReporterInput is not being used anywhere except for SpdxDocumentReporter.

The `packageConfigurationProvider` is not used directly by the reporters, instead it is used by the `LicenseInfoResolver` class which is the interface reporters use to get license and copyright information. The `SpdxDocumentReporter` you mention was just recently changed to not use the `packageConfigurationProvider` directly in 7889caf.

I can confirm that package configurations definitely work for the Static HTML, Web App and Notice Template reporters, #3384 should fix the issue for the remaining reporters.

**Comment by mlmilan** [comment]
@sschuberth @mnonnenmacher I can confirm that **CycloneDx** and **AntennaAttributionDocumentReporter** works as it should now. I could not test **AmazonOssAttributionBuilder** i havent got this configured at all so it will take some time for me to introduce. I could also confirm that **StaticHTML** and **WebApp** also works as it should (it marks package licenses as excluded within the report).

But the new PDF **AsciidocTemplateReporter** reporter does not work, at least on this branch. This are the outputs of

**AsciidocTemplateReporter**

Package: esprima:4.0.1
The following copyrights and licenses were found in the source code of this package:
License:
• BSD-2-Clause
• Copyrights:
◦ Copyright JS Foundation and other contributors, https://js.foundation
License:
• BSD-3-Clause
• Copyrights:
License:
• GPL-2.0-only
• Copyrights:
License:
• LGPL-2.0-or-later
• Copyrights:
License:
• MIT
• Copyrights:

**StaticHTML**

NPM::esprima:4.0.1 | dependencies                 devDependencies Excluded: DEV_DEPENDENCY_OF - Packages for development only. | Declared Licenses:                                                   BSD-2-Clause                                               Detected Licenses:                                                   BSD-2-Clause (exemplary link to the first of 7 locations)                   BSD-3-Clause (link to the location)                   GPL-2.0-only (Excluded: TEST_OF - This directory contains documentation which is not distributed.) (exemplary link to the first of 2 locations)                   LGPL-2.0-or-later (Excluded: TEST_OF - This directory contains documentation which is not distributed.) (exemplary link to the first of 2 locations)                   MIT (Excluded: TEST_OF - This directory contains documentation which is not distributed.) (exemplary link to the first of 42 locations)

**CycloneDx**

 <component type="library">
            <group/>
            <name>esprima</name>
            <version>4.0.1</version>
            <description><![CDATA[ECMAScript parsing infrastructure for multipurpose analysis]]></description>
            <scope>required</scope>
            <hashes>
                <hash alg="SHA-1">13b04cdb3e6c5d19df91ab6987a8695619b0aa71</hash>
            </hashes>
            <licenses>
                <license>
                    <id>BSD-2-Clause</id>
  <origin xmlns="ort">declared license</origin>
                </license>
                <license>
                    <id>BSD-2-Clause</id>
                    <text content-type="plain/text"><![CDATA[Redistribution and use in source and binary forms, with or without modification,
 <origin xmlns="ort">detected license</origin>
                </license>
                <license>
                    <id>BSD-3-Clause</id>
                    <text content-type="plain/text"><![CDATA[Redistribution and use in source and binary forms, with or without modification,
 <origin xmlns="ort">detected license</origin>
                </license>
            </licenses>
            <purl>pkg:npm/esprima@4.0.1?classifier=sources</purl>
            <dependencyType xmlns="ort">transitive</dependencyType>
        </component>

without license text

**Comment by sschuberth** [comment]
> I could not test **NoticeTemplate** too as i dont have archive folder populated on the system where i performed tests.

Note, however, that the new `AsciidocTemplateReporter` actaully also makes use of archived license files.

@mnonnenmacher would you have some time today helping me to find out what's going on in the Asciidoc template as I'm not yet very familiar with Freemarker?
