### ISSUE TITLE
[Question]How to use Advisor

### ISSUE THREAD

**Issue by soimkim** [oss-review-toolkit/ort#3367]
I'm trying to use Adivsor, where do I sign up for an Account?
Is it free?

**Comment by sschuberth** [comment]
ORT by itself does not provide the actual data for security vulnerabilities. You already need to have an account with one of the providers supported by ORT. And currently, the only supported provider is Sonartype Nexus IQ Server, commercial product. But we plan to add support for more providers soon.

**Comment by woznik** [comment]
Is it possible to consider adding https://ossindex.sonatype.org/ or https://nvd.nist.gov/ ?

**Comment by sschuberth** [comment]
Please see the [separate issue about OSS Index](https://github.com/oss-review-toolkit/ort/issues/718#issuecomment-731150111), there might be some issues with their terms of use.

And NVD we'd get "for free" when adding support for [VulnerableCode](https://github.com/oss-review-toolkit/ort/issues/3287), which is something we're planning to look into soon.

Anyway, @soimkim, I believe the original question has been answered, so can we close this?

**Comment by soimkim** [comment]
Yes. Thank you for fast reply.
