### ISSUE TITLE
Helper CLI is not included in the Docker image

### ISSUE THREAD

**Issue by mmurto** [oss-review-toolkit/ort#3368]
Helper CLI could be useful to include in the image to not require installing it separately when using ORT with Docker.

**Comment by sschuberth** [comment]
As mentioned in the [chat](https://ort-talk.slack.com/archives/C9NNJ54B1/p1606219339298300), we just figured that we cannot easily make the `helper-cli` usable from the Docker image, as we'd need to change the entry point then. Certainly overriding the entry point via `docker run --entry-point` is possible, but probably not the best user experience.

**Comment by mmurto** [comment]
Do you think a script as an entry point would break something? 

```sh
#/!bin/sh

if [ $1 = "orth" ]; then
  shift;
  echo "path/to/orth $@"
else
  echo "path/to/ort $@"
fi
```

Something with that kind of conditions could forward the arguments to the helper if the first argument is `orth`, otherwise run ORT as usual. If something like this would be ok, I can create a PR some day.

**Comment by sschuberth** [comment]
THB I don't like it as it makes `orth` look like a sub-command of `ort`.

If you can live with writing `docker run --entrypoint /opt/ort/bin/orth ort` then #3369 resolves your issue.

**Comment by mmurto** [comment]
> If you can live with writing `docker run --entrypoint /opt/ort/bin/orth ort` then #3369 resolves your issue.

Sounds good to me!
