### ISSUE TITLE
Filter only non-excluded scopes in scan report web app

### ISSUE THREAD

**Issue by hanna-modica** [oss-review-toolkit/ort#3397]
In the scan report web app, one can go to the table view and filter the packages by their scopes. Unfortunately, one cannot select only non-excluded scopes. Usually, I am not interested in excluded packages, so when searching for information in this view, I want to filter this. 

![image](https://user-images.githubusercontent.com/40762532/100629428-92881680-3329-11eb-8820-97094866b83d.png)

There should be a button, that says "select only non-excluded", so one can filter out all excluded packages.

**Comment by tsteenbe** [comment]
@hanna-modica  Not sure if I follow you feature request - the Web App has built in filter to show only include package, it's the first filter on the left in front of the word "Package". The idea with filtering in the Table view is that you start you filter from left to right.

**Comment by hanna-modica** [comment]
@tsteenbe I somehow overlooked this column. Then this ticket is obsolete. Thank you very much for the hint.
