### ISSUE TITLE
Advisor / Nexus IQ: Do not request vulnerabilities for all dependencies at once

### ISSUE THREAD

**Issue by MarcelBochtler** [oss-review-toolkit/ort#3414]
As a project may have multiple thousands of dependencies, this can result in a timeout from the Nexus IQ Server quite easily.

I tested an NPM project containing >1000 dependencies and was not able to get a result in time from our server.
For ~500 dependencies I got a 455kb result after 20 seconds, I'm not sure what timeout is configured on the server.

My suggestion would be to split the packages into splices (maybe 100 dependencies per splice?!), call Nexus IQ sequentially and merge the results afterwards.

Relevant code snippet:

https://github.com/oss-review-toolkit/ort/blob/1a78ef2c7fd80105a8eda380aa7cabeb02a02739/advisor/src/main/kotlin/advisors/NexusIq.kt#L77-L95

**Comment by sschuberth** [comment]
FYI, Kotlin's `chuncked` might come in handy here: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/chunked.html
