### ISSUE TITLE
Download: unpack recursive 

### ISSUE THREAD

**Issue by fb33** [oss-review-toolkit/ort#3426]
Hello,

Is there a plan to have an unpack recursive ?
In some cases, we can have an archive containing jars for variety reasons.

Regards

**Comment by sschuberth** [comment]
There are no concrete plans yet. Are you talking about JARs contained in JARs (source artifacts), or JARs contained in Git Repos?

**Comment by fb33** [comment]
Concretely, I'm talking about zip files that contain external libs in jars in the case of unmanaged projects.
I have some projects that I try to scan using a sdpx description project file.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
