### ISSUE TITLE
Webapp reporter - project details

### ISSUE THREAD

**Issue by fb33** [oss-review-toolkit/ort#3469]
Hello,

It seems to have an issue with details for project.

In the table panel when we click on a row, it expands it and we get the details.
In the tree panel when we click on a node, a details panel appears from the right

It works fine with package, but with item corresponding to a project, it fails.
We get a blanck page, and there is that kind of error in the console

`react_devtools_backend.js:2430 TypeError: Cannot read property 'length' of undefined`

With a webapp report genarated by a ORT version built the 7 december it's OK
With a webapp report genarated by a ORT version built the 21 december it's KO

Regards

**Comment by fb33** [comment]
this also happens in the summary tab, when I try to expand an issue linked to a project

**Comment by sschuberth** [comment]
@tsteenbe is this something you can have a look at?

**Comment by sschuberth** [comment]
This will probably get fixed by @tsteenbe's `web-app-update` branch.
