### ISSUE TITLE
idea compile error

### ISSUE THREAD

**Issue by gaoyaqing12** [oss-review-toolkit/ort#3473]
hi:
    i imported the source code into idea , after  gradle auto build successfully,and it display some  errors  in file " ort\spdx-utils\src\main\kotlin\SpdxUtils.kt"
    the errors are  about:
    
    
    Error:(164, 9) Kotlin: Type mismatch: inferred type is (() -> String)? but Nothing? was expected
Error:(164, 43) Kotlin: Type mismatch: inferred type is () -> String but Nothing? was expected
Error:(164, 45) Kotlin: Type mismatch: inferred type is () -> String but Nothing? was expected

and so on 

my os is windows 7 and my jdk version is jdk11  the information is that "Information:Kotlin: kotlinc-jvm 1.4-M2 (JRE 11+28)"

what should i do for next?

**Comment by sschuberth** [comment]
Please ensure that you're using the latest version of IDEA and the latest version of the Kotlin plugin for IDEA. It should be working with IDEA 2020.3 and Kotlin plugin 203-1.4.21-release-IJ5981.133.

**Comment by gaoyaqing12** [comment]
yes ,when i upgrade my ide ,it display.  thanks for you help
