### ISSUE TITLE
Enhance the evaluator to be able to create rules for the Advisor result

### ISSUE THREAD

**Issue by MarcelBochtler** [oss-review-toolkit/ort#3503]
Add an `AdvisorRule` to be able to evaluate results from the Advisor using the evaluator.

**Comment by neubs-bsi** [comment]
Suggested implementation by Test Driven Development:
Write the dsl rule the way you would want the syntax to compile and develop the `AdvisorRule` based on that example

**Comment by mnonnenmacher** [comment]
@MarcelBochtler  FYI, I'm working on an update to the rules API that will make the rules more readable and will also make it easier to add new rule types, so I'll assign this issue to me.

**Comment by sschuberth** [comment]
@mnonnenmacher we need this feature urgently. Does it make sense for us to implement this *now*, an you migrate the syntax later to your new DSL?

**Comment by mnonnenmacher** [comment]
Yes.
