### ISSUE TITLE
Resolving dependencies for 'Gemfile' failed with: IOException

### ISSUE THREAD

**Issue by pilvikala** [oss-review-toolkit/ort#3505]
I am having an issue with this project and I am not sure how to proceed with the troubleshooting. The error ORT is giving is:
```shell
Resolving dependencies for 'Gemfile' failed with: IOException: Running 'bundle exec gem specification rubygems-update' in '/home/michal/Downloads/rubygems-3.1.4' failed with exit code 1:
ERROR:  No gem matching 'rubygems-update (>= 0)' found
```
There is no rubygems-update package in the Gemfile
[rubygems-3.1.4.zip](https://github.com/oss-review-toolkit/ort/files/5819890/rubygems-3.1.4.zip)

Can you help?

**Comment by sschuberth** [comment]
@KorSin can you maybe check whether the same happens with the Bundler improvements you're currently working on?

**Comment by KorSin** [comment]
Hi @pilvikala, I looked at your issue. The gem `rubygems-update` is the one you specified in your file `rubygem-update.gemspec`. In order for bundler to find it you need to add the line `gemspec` inside your `Gemfile`. If you rerun the bundler install, the gem appears now inside the lockfile, too. After that change, `ort`  ran through without problems. Let me know if this solved your issue.

**Comment by pilvikala** [comment]
Thank you, this solved the issue. I would like to point out, however, that this package is just the package rubygems-update downloaded from the source with its original lock file. Does this mean it's the source package that actually had an issue ORT could not recover from?

**Comment by KorSin** [comment]
Ok, I first thought this is your own gem you want to publish. Nevertheless, this is rather an user issue than an ort issue in my opinion. The [bundler homepage](https://bundler.io/gemfile.html) states that local dependencies need to be specified with the `path` attribute inside the `Gemfile`.

**Comment by pilvikala** [comment]
OK, great. Thank you!
