### ISSUE TITLE
Performance issues with reporter (AsciidocTemplate + CycloneDX at least)

### ISSUE THREAD

**Issue by Martin-Idel-SI** [oss-review-toolkit/ort#3511]
We experience problems with the reporter with very large projects. The issue can be seen with a vanilla scan of Keycloak (https://github.com/keycloak/keycloak).

Furthermore, we use the reporter options: `-f AsciidocTemplate,CycloneDX,NoticeTemplate,SpdxDocument,StaticHTML,WebApp`.

The report will usually just not finish - no stacktrace, nothing. If it finishes, the run takes > 1 hour on a 8 GB 4 CPU core machine.

Profiling revealed the biggest issue to be the `CopyrightStatementsProcessor.kt`:

- On my system, ORT never finished https://github.com/oss-review-toolkit/ort/blob/8fa22855c6e32d6f7e399fe5af41726ac7f0a5ef/utils/src/main/kotlin/CopyrightStatementsProcessor.kt#L146 - this can be fixed by making `    val originalStatements: List<String>` a `Set<String>` in `Parts`. What is the rationale here for needing a list if everything gets merged anyways? 
- When using the List <-> Set quickfix, the reporter still used a lot of time (in particular disclosure document and CycloneDX). About 60% of that time is spent with replacing regexes in https://github.com/oss-review-toolkit/ort/blob/8fa22855c6e32d6f7e399fe5af41726ac7f0a5ef/utils/src/main/kotlin/CopyrightStatementsProcessor.kt#L213 - the comment in this method seems to imply this is not necessary? I could try optimizing this method, but if it is only interesting for debugging purposes, I would tend to delete/replace it. 

RAM usage is about 4 GB (in particular due to loading a lot of copyrights) but that may still be acceptable.

**Comment by sschuberth** [comment]
> this can be fixed by making `    val originalStatements: List<String>` a `Set<String>` in `Parts`. What is the rationale here for needing a list if everything gets merged anyways?

> the comment in this method seems to imply this is not necessary? I could try optimizing this method, but if it is only interesting for debugging purposes, I would tend to delete/replace it.

For both questions, I believe @fviernau is in the best position to provide an answer.

**Comment by fviernau** [comment]
I''m looking into it...

**Comment by Martin-Idel-SI** [comment]
As promised, here is some more data on a report I did using a version of ORT from december (and the map <-> list replacement I needed).

The following shows a complete run on local infrastructure with VisualVM attached. Timings for reports were:
Asciidoc template: 868s
CycloneDX: 1264s
NoticeTemplate: 418s
SpdxDocument: 3s
StaticHtml: 27s
WebApp: 149s

The timings are similar (a bit lower) without VisualVM attached, so I am somewhat confident that the relative results are correct.

My most immediate concerns are clearly Asciidoc, CycloneDX and NoticeTemplate reports. Since this is a very large project, the other times are probably acceptable.

Here is what I see in VisualVM:

![monitor](https://user-images.githubusercontent.com/31658331/106920131-120bda80-670b-11eb-8721-9e2d2ae20c71.png)

The picture shows several phases:

- The first steep increase in heap usage corresponds to loading of Licenses and the ORT results into the Heap (note: I did not have the License files but used a local cache)
- The creation of templates starts after the sudden drop in heap space used.
- The first part with large heap usage changes corresponds to Asciidoc + CycloneDX report creation
- The second part where the overall used heap space slowly increases while the spikes remain the same corresponds to the Notice Template
- The last part with smaller increase and a sudden spike corresponds to the remaining reports.

It is clear that this uses up the most time, so this would be the first part where I proposed optimizations.
CPU sampling reveals the following profile:

![samples](https://user-images.githubusercontent.com/31658331/106920972-d6bddb80-670b-11eb-972c-3603ae79d857.png)

This shows where the process spent its time and more than 60% appear to be spent inside the CopyrightProcessor as I noted above. It makes sense to see regex appear there as well as regex processing is most of the nontrivial part happening in `replaceYears` and it is generally known that regexes tend to be tricky for optimisation purposes.

**Comment by fviernau** [comment]
Thanks @Martin-Idel-SI !

The `CopyrightStatementsProcesser.process()` is indeed not ultra fast.
However, I'm almost 100% certain that it is fast enough, and that the real problem is that the function is called "a bit more often" than needed. I doubt 3 million calls to it (as I observed) is the right amount. Working on the PR...

**Comment by Martin-Idel-SI** [comment]
@fviernau - clearly reducing the number of calls would also work and be even better!

I saw 1 million copyrights at some point on the heap - according to samples - so I assumed that's the number of copyrights to be processed, in which case 3 million calls (for three reports processing copyrights) seemed necessary if reusing the results of one report generation for different reports is an architectural challenge (my assumption). If the 1 million copyrights do not represent unique copyright statements (seems a bit large, but then again - the whole project produces very large output), then of course this should be the source of optimisation.

Again, thanks for looking into this. If I can help in any way with my very limited understanding of the code, I'm happy to help.

**Comment by Martin-Idel-SI** [comment]
Just to confirm here: This actually cuts reporter time by 2/3rd (from over an hour to around 20min). This is good enough for now!

**Comment by fviernau** [comment]
Thanks @Martin-Idel-SI ! Just out of curiousity.
Is this measured for computing all reports in one go or for computing the reports separately? 
...With or without profiler enabled?
...and with which -Xmx value for the JVM?

Note: my measure were done with computing reports separately, with -Xmx16G.

**Comment by Martin-Idel-SI** [comment]
@fviernau I did this on our production instance, so:
- No profiler enabled
- Xmx12g, although I think the machine running the request only had 8GB
- Reports were computed in one go

Before, we had failures of the report stage and >1h on the same machines, now it took 17 minutes (the whole step took 21 minutes, but we need some setup and uploading reports and such). Final performance output:

```
Successfully created the 'AsciiDocTemplate' report at [/output/results/AsciiDoc_disclosure_document.pdf, /output/results/AsciiDoc_vulnerability_report.pdf] in 811.823183732s.
Successfully created the 'CycloneDx' report at [/output/results/CycloneDX-BOM.xml] in 59.858172153s.
Successfully created the 'NoticeTemplate' report at [/output/results/NOTICE_default, /output/results/NOTICE_summary] in 65.9136707s.
Successfully created the 'SpdxDocument' report at [/output/results/document.spdx.yml] in 14.103918558s.
Successfully created the 'StaticHtml' report at [/output/results/scan-report.html] in 44.180965227s.
Successfully created the 'WebApp' report at [/output/results/scan-report-web-app.html] in 242.347232786s.
Created 6 of 6 report(s) in 811.879314301s.
```

So the CycloneDx and NoticeTemplate reports are now an order of magnitude faster, the AsciiDocTemplate is still somewhat slow but that will probably due to the pdf processing and such (about 2 mins is spent retrieving licenses from the license archive).

**Comment by sschuberth** [comment]
> the AsciiDocTemplate is still somewhat slow but that will probably due to the pdf processing and such

Yeah, there probably is the while JRuby overhead involved, with AsciiDoc being written in Ruby.

> about 2 mins is spent retrieving licenses from the license archive

That probably get faster with @mnonnenmacher's plans to [move the license archive also to a database](https://github.com/oss-review-toolkit/ort/pull/3633#issuecomment-779955036).
