### ISSUE TITLE
Add Google Open Source Vulnerabilities as an advisor

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#3599]
See https://osv.dev/. Note that https://github.com/google/osv is ~not live yet at the time of writing~ live now.

**Comment by sschuberth** [comment]
On a related note, we could also add a reporter for the [Open Source Vulnerability format](https://ossf.github.io/osv-schema/).

**Comment by tsteenbe** [comment]
Related https://github.com/goneall/spdx-to-osv which is a tool to produce an Open Source Vulnerability JSON file based on information in an SPDX document

**Comment by fviernau** [comment]
Some issues I found during development:

1. https://github.com/google/osv.dev/issues/497
2. https://github.com/google/osv.dev/issues/502

**Comment by fviernau** [comment]
I've filed a follow-up ticket to extend ORT's vulnerability model: #5593.

**Comment by fviernau** [comment]
Besides the linked changes above I've improved the identifiers of Go packages in:

1. https://github.com/oss-review-toolkit/ort/pull/5586
2. https://github.com/oss-review-toolkit/ort/pull/5546

Topics which came out of working on this ticket are further general advisor (and related areas) improvements:

1. https://github.com/oss-review-toolkit/ort/issues/5593
2. https://github.com/oss-review-toolkit/ort/issues/5597

I consider the initial implementation to be done, with https://github.com/oss-review-toolkit/ort/pull/5595 be the last small fix, so closing this ticket as done.
