### ISSUE TITLE
Allow multiple advisors to be run at once

### ISSUE THREAD

**Issue by KorSin** [oss-review-toolkit/ort#3638]
Due to now having two advisor implementations, i.e., `NexusIq` and `VulnerableCode`(and possibly others to come), it would be nice to use multiple advisors during a run. Currently, only one at a time can be used.

The advisors above use different sources and databases for their vulnerabilities, thus leading to different results.
A user might want to compare those results or combine both to have a richer pool of vulnerabilities.

It is probably best to implement this after #3628 is merged, since there is a restructuring of the `AdvisorConfiguration`.

**Comment by KorSin** [comment]
After a discussion with @oheger-bosch, we already have an idea how to implement this:

Right now, `NexusIq` and `VulnerableCode` are children of the `Advsior` class and only one instance
of this class is created in `AdvisorCommand`. If you look at `AnalyzerCommand`, it creates only one instance of
`Analyzer` which in turn creates and handles multiple `Packagemanager`. 

In our opinion, it would make sense to have a similar logic for the `Advisor`. In particular, create an interface called, e.g., `VulnerabilityProvider`, that is implemented by `NexusIq` and `VulnerableCode`. Then, the `Advisor` class is responsible for creating and calling those providers and writing the respective results into the final advisor result.

**Comment by tsteenbe** [comment]
> A user might want to compare those results or combine both to have a richer pool of vulnerabilities.

@KorSin  Are you thinking of also offering a de-duplication function in the Advisor? e.g. merge advisories for multiple providers for the same CVE?

**Comment by KorSin** [comment]
Interesting question. Here are my thoughts: 

- I could imagine the user wants to know whether one or multiple advisors found the same vulnerability. Could be solved by just appending a List of advisors after the merge.
- Even if multiple advisors found a vulnerability with the same CVE, is it really the same? Maybe they come to a different conclusion w.r.t. the score and URL.

**Comment by sschuberth** [comment]
See also the somewhat related discussion at https://github.com/nexB/vulnerablecode/issues/284#issuecomment-781869360.
