### ISSUE TITLE
Parsing NPM registry from .npmrc should support scope-specific registries

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#3741]
Currently, `readRegistryFromNpmRc()` only supports "global" registries:

https://github.com/oss-review-toolkit/ort/blob/db219febb94825b87e01a5d9e60239998050adff/analyzer/src/main/kotlin/managers/utils/NodeSupport.kt#L147

But we should support the syntax for [scope-specific registries](https://docs.npmjs.com/cli/v7/configuring-npm/npmrc#comments), too, see

```
# last modified: 01 Jan 2016
; Set a new registry for a scoped package
@myscope:registry=https://mycustomregistry.example.org
```

**Comment by nicorikken** [comment]
Ah, thanks for raising this. Now I know why I couldn't get our custom npm package to work.

**Comment by sschuberth** [comment]
This was obsoleted by https://github.com/oss-review-toolkit/ort/pull/5162 which removed `readRegistryFromNpmRc()` altogether in favor of a better solution based on `npm view`.
