### ISSUE TITLE
Download of Selenium repo leads to 1.4 Gb of local data

### ISSUE THREAD

**Issue by nnobelis** [oss-review-toolkit/ort#3756]
When I run
` ort --force-overwrite download --project-url ssh://git@github.com/SeleniumHQ/selenium.git --vcs-revision 3862ad0799952de277bca04bde92d3383464841c --output-dir selenium/`

The Downloader creates an empty directory to receive the source code and does

`git fetch --depth 50  --tags origin`

This creates a 1.4Go checkout. 

To be clear we are in this branch of the code (branch 2) :
https://github.com/oss-review-toolkit/ort/blob/master/downloader/src/main/kotlin/vcs/Git.kt#L202

The guilty file is this one :

`1.4G    ./.git/objects/pack/pack-7e6caf51b263881e1d382cf7c6905d87528d4cba.pack`

By looking at the biggest files in this index :

```
git verify-pack -v .git/objects/pack/pack-7e6caf51b263881e1d382cf7c6905d87528d4cba.idx | sort -k 3 -n |  tail -n 5 | less
f886fb00a4fb0da6ddfb90a054294c0bc65b934a blob   35416759 33245432 247567510
```

You see that the entry is only 35Mb. You can find the corresponding file with : 

```
git rev-list --objects --all | grep f886fb00a4fb0da6ddfb90a054294c0bc65b934a
f886fb00a4fb0da6ddfb90a054294c0bc65b934a third_party/jruby/jruby-complete.jar

```
 
Since this pack file is so big and the top files in this pack are so small, I assumed that the checkout was big because of all the tags we are fetching, each one having a copy of the file (as I pictured it).
This is confirmed by https://github.com/SeleniumHQ/selenium/issues/6351
 
Therefore I did the following test :

`git fetch --depth 50  --no-tags origin`

And now the checked-out repo is 370Mb and the biggest file is :

`377M    ./.git/objects/pack/pack-f39cf9764c065bdf43d57878138804d4afa5c75c.pack`
 
So I would say there are several solutions :
- remove the `--tags` in branch 2 and replace it with `--no-tags` ([having `--no-tags` IS different as having no `--tags`](https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---no-tags))
or
- add a new branch between branch 1 and branch 2 with `--no-tags`

**Comment by nnobelis** [comment]
For the sake of completeness, here is the full output :
```
--force-overwrite download --project-url ssh://git@github.com/SeleniumHQ/selenium.git --vcs-revision 3862ad0799952de277bca04bde92d3383464841c --output-dir selenium/


12:46:45.997 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download 'Downloader::selenium.git:' sources to '/home/nino/IdeaProjects/Tests/selenium' from VCS...
12:46:46.003 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Using VcsInfo(type=Git, url=ssh://git@github.com/SeleniumHQ/selenium.git, revision=3862ad0799952de277bca04bde92d3383464841c, resolvedRevision=null, path=).
12:46:46.003 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Detected VCS type 'Git' from type name 'Git'.
12:46:46.190 [main] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - Adding Git revision '3862ad0799952de277bca04bde92d3383464841c' (taken from package meta-data) as a candidate.
12:46:46.192 [main] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - No Git revision for version '' found: IOException: Cannot guess a revision name from a blank version.
12:46:46.192 [main] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - Trying revision candidate '3862ad0799952de277bca04bde92d3383464841c' (1 of 1)...
12:46:46.197 [main] INFO  org.ossreviewtoolkit.downloader.vcs.Git - Trying to fetch all refs with depth limited to 50.
12:54:09.997 [main] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - Successfully downloaded revision 3862ad0799952de277bca04bde92d3383464841c for package 'Downloader::selenium.git:.'.
12:54:10.013 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Finished downloading source code revision '3862ad0799952de277bca04bde92d3383464841c' to '/home/nino/IdeaProjects/Tests/selenium'.
12:54:10.020 [main] PERFORMANCE org.ossreviewtoolkit.downloader.Downloader - Downloaded source code for 'Downloader::selenium.git:' from VcsInfo(type=Git, url=ssh://git@github.com/SeleniumHQ/selenium.git, revision=3862ad0799952de277bca04bde92d3383464841c, resolvedRevision=3862ad0799952de277bca04bde92d3383464841c, path=) in 444024.258497ms.

Process finished with exit code 0

```

**Comment by sschuberth** [comment]
FYI, not that there is some special case code in ORT for SSH downloads from GitHub:

https://github.com/oss-review-toolkit/ort/blob/7fd852a42e5f5602a47b5eea58ef8f85bbd97970/downloader/src/main/kotlin/vcs/Git.kt#L171-L177

That is, a worthwhile performance improvement is *not* done when using SSH to download from GitHub. @nnobelis, I'd not be surprised if the issue went away when simply using HTTPS for the clone URL instead.

**Comment by nnobelis** [comment]
But when Selenium is a dependency, you have no control over the URL ?
The URL is coming for the pom and not modifiable, right ?

**Comment by sschuberth** [comment]
Right, but we were already considering replacement rules to turn SSH URLs into HTTPS URLs (specifically for GitHub) for completely different reasons, see https://github.com/oss-review-toolkit/ort/issues/2568.

**Comment by sschuberth** [comment]
@nnobelis, I'm positive that https://github.com/oss-review-toolkit/ort/pull/3762 fixes the issue.

**Comment by nnobelis** [comment]
I tested remotly and locally with aforementioned commit : the selenium local repo is now 289Mb. Also the bug is fixed
