### ISSUE TITLE
Dockerfile shouldn't be run with ROOT permissions

### ISSUE THREAD

**Issue by Martin-Idel-SI** [oss-review-toolkit/ort#3764]
When using the default Dockerfile, we get errors when using bower package manager:

> ERROR org.ossreviewtoolkit.analyzer.PackageManager - Resolving dependencies for 'bower.json' failed with: IOException: Running 'bower install' in '/input/project/...' failed with exit code 1:
bower ESUDO         Cannot be run with sudo
Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.
http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814
You can however run a command with sudo using "--allow-root" option

This issue will also appear in the reports later on, so it's a problem.

We could either add an option to run bower commands with `--allow-root` as suggested in the error message or add a user to the official Dockerfile and run without root permissions. This would be the cleaner solution in my opinion.

So the real question is whether there is something in the Dockerfile which inherently requires sudo permissions while running.

**Comment by sschuberth** [comment]
> So the real question is whether there is something in the Dockerfile which inherently requires sudo permissions while running.

I'm not aware of anything. We just run as root as that's Docker's default.

**Comment by tsteenbe** [comment]
Maybe we should run https://github.com/hadolint/hadolint - which is a Docker best practices linter -  over our DockerFile using the https://github.com/marketplace/actions/hadolint-action.

We could also look at implementing the recommendations in https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html - include steps how to use an unprivileged user

**Comment by mnonnenmacher** [comment]
Also see my comment here: https://github.com/oss-review-toolkit/ort/pull/4103#issuecomment-854137392

**Comment by sschuberth** [comment]
> Maybe we should run https://github.com/hadolint/hadolint - which is a Docker best practices linter - over our DockerFile using the https://github.com/marketplace/actions/hadolint-action.

I gave `hadolint` a try, and I'm not convinced of the tool. I was immediately running into multiple issues [[1]] [[2]] [[3]].

[1]: https://github.com/hadolint/hadolint/issues/285
[2]: https://github.com/hadolint/hadolint/issues/422
[3]: https://github.com/hadolint/hadolint/issues/679

**Comment by sschuberth** [comment]
> add a user to the official Dockerfile and run without root permissions. This would be the cleaner solution in my opinion.

As of https://github.com/oss-review-toolkit/ort/pull/5031 *funTests* are run as non-root in Docker to ensure everything works without being root.
