### ISSUE TITLE
Show number of unresolved issues in Scan Report Web App

### ISSUE THREAD

**Issue by hanna-modica** [oss-review-toolkit/ort#3766]
In the Scan Report Web App, the number of issues is shown in the summary view, e.g. `Issues (64)`. When I resolve some of these issues and lets say, there are only 16 of these 64 open/unresolved, the number still says `Issues (64)`. To get a better overview, how many of those issues still need action, I would like a display like the following: `Issues (16/64)`.

**Comment by sschuberth** [comment]
@tsteenbe is this a small enhancement you could look into?

**Comment by tsteenbe** [comment]
Implemented as part of https://github.com/oss-review-toolkit/ort/pull/3778
