### ISSUE TITLE
Maximum parallel database requests should be based on connection pool size

### ISSUE THREAD

**Issue by MarcelBochtler** [oss-review-toolkit/ort#3807]
The current implementation chunks the database queries and parallelizes the requests to the database depending on the number of packages:
https://github.com/oss-review-toolkit/ort/blob/9c0a1f506a2c8f2b190e33dec701ed0245abb295/scanner/src/main/kotlin/storages/PostgresStorage.kt#L194-L204

This causes issues when the number of requests is significantly higher than the configured connection pool.
The timeout for new connection pools in hikari is configured to 30000ms.
When all connections are busy and do not finish within 30s, no new connections can be created and this timeout is hit.
This was introduced and discussed in this PR: https://github.com/oss-review-toolkit/ort/pull/3704/files#r587191416

From my point of view the number of maximum parallel database requests should be based on the connection pool size which itself should be configurable.

**Comment by mnonnenmacher** [comment]
I am currently rewriting the `PostgresStorage` for #2668, I will implement it in such a way that the number of parallel requests is limited to the connection pool size. Therefore I would suggest to implement a quick fix for now, for example to limit the number of chunks to the currently hard coded connection pool size.

**Comment by sschuberth** [comment]
I also believe that we should generally, not just as a quick fix, *not* calculate the chunk size based on the number of packages. Because if we do, the chuck size might become arbitrarily large, which could also result in a timeout even for a single request.

**Comment by mnonnenmacher** [comment]
> I also believe that we should generally, not just as a quick fix, _not_ calculate the chunk size based on the number of packages. Because if we do, the chuck size might become arbitrarily large, which could also result in a timeout even for a single request.

AFAIK there is no default query timeout in PostgreSQL or JDBC, so this should not be an issue.

**Comment by mnonnenmacher** [comment]
@MarcelBochtler I have decided to implement a very simple quick fix, could you please verify if that fixes the issue for you?
