### ISSUE TITLE
Adapt VulnerableCode implementation to changes in the bulk API

### ISSUE THREAD

**Issue by oheger-bosch** [oss-review-toolkit/ort#3808]
The bulk API to query vulnerability information for multiple packages has now been finalized. (Refer to [this ticket](https://github.com/nexB/vulnerablecode/issues/284) for further information; documentation about the requests and responses supported by the API can be found [here](https://github.com/nexB/vulnerablecode/pull/369#issuecomment-796877606).) So the implementation of VulnerableCode in ORT can be updated to use the information returned by this API rather than to query further information about vulnerabilities in separate requests.

In order to make full use of the information provided, it may be necessary to enhance the data model of the Advisor. So far, there is a float field to represent the severity of a vulnerability. For a better interpretation of the severity, the scoring system needs to be available, and the value can be a string such as "HIGH" or "LOW".

**Comment by sschuberth** [comment]
> For a better interpretation of the severity, the scoring system needs to be available, and the value can be a string such as "HIGH" or "LOW".

While VulnerableCode has something like

    "scores": [{"value": "LOW", "scoring_system": "cvssv3.1_qr"}],

I'd actually prefer to have the original score plus the rating / scoring system, so the API user can perform the mapping to a human-readable rating. However, that might not be feasible if we do not get the original (raw) score from VulnerableCode.

**Comment by sbs2001** [comment]
@sschuberth  
>we do not get the original (raw) score from VulnerableCode.

The "LOW" thing is actually a raw score. Refer to https://github.com/nexB/vulnerablecode/blob/bfa005ece230ada9032c3c0b4a7bab7b59673e0b/vulnerabilities/severity_systems.py#L78 for additional scoring systems. 

For eg you could end up with scores like 

```
"scores": [
               {"value": "LOW", "scoring_system": "cvssv3.1_qr"},
               {"value": "3.7", "scoring_system": "cvssv3.1_qr"},
               {"value": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:L", "scoring_system": "cvssv3.1_vector"}

],
```

**Comment by sschuberth** [comment]
> The "LOW" thing is actually a raw score.

Ah, it's indeed a raw score in the "_qr" scoring / rating system. I missed that suffix. Thanks for pointing this out.
