### ISSUE TITLE
Scan stuck - endless FUTEX ETIMEDOUT

### ISSUE THREAD

**Issue by devsecopsale** [oss-review-toolkit/ort#3837]
When running a SCAN process in a docker container, the scan process never ends and gets stuck.
I enabled DEBUG but I couldn't find any useful information. I used linux 'strace' tool inside a container to attach to 'java' process and its threads. this is an extract of the output I get after a few minutes of normal execution:

43    futex(0x7f656809ab28, FUTEX_WAKE_PRIVATE, 1) = 0
43    getrusage(RUSAGE_THREAD, {ru_utime={tv_sec=1, tv_usec=692087}, ru_stime={tv_sec=2, tv_usec=129479}, ...}) = 0
43    futex(0x7f656809ab7c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=299999021} <unfinished ...>
52    <... futex resumed>)              = -1 ETIMEDOUT (Connection timed out)
52    futex(0x7f6568178628, FUTEX_WAKE_PRIVATE, 1) = 0
52    futex(0x7f656817867c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=49999063}) = -1 ETIMEDOUT (Connection timed out)
52    futex(0x7f6568178628, FUTEX_WAKE_PRIVATE, 1) = 0
52    futex(0x7f656817867c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=15999248}) = -1 ETIMEDOUT (Connection timed out)
52    futex(0x7f6568178628, FUTEX_WAKE_PRIVATE, 1) = 0
52    futex(0x7f656817867c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=33999606}) = -1 ETIMEDOUT (Connection timed out)
52    futex(0x7f6568178628, FUTEX_WAKE_PRIVATE, 1) = 0
52    futex(0x7f656817867c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=49999171}) = -1 ETIMEDOUT (Connection timed out)
52    futex(0x7f6568178628, FUTEX_WAKE_PRIVATE, 1) = 0
52    futex(0x7f656817867c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=49998563}) = -1 ETIMEDOUT (Connection timed out)
52    futex(0x7f6568178628, FUTEX_WAKE_PRIVATE, 1) = 0
52    futex(0x7f656817867c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=49998269}) = -1 ETIMEDOUT (Connection timed out)
52    futex(0x7f6568178628, FUTEX_WAKE_PRIVATE, 1) = 0
52    futex(0x7f656817867c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=49998896} <unfinished ...>
43    <... futex resumed>)              = -1 ETIMEDOUT (Connection timed out)
43    futex(0x7f656809ab28, FUTEX_WAKE_PRIVATE, 1) = 0
43    getrusage(RUSAGE_THREAD, {ru_utime={tv_sec=1, tv_usec=692087}, ru_stime={tv_sec=2, tv_usec=129620}, ...}) = 0
43    futex(0x7f656809ab7c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=299998802} <unfinished ...>
52    <... futex resumed>)              = -1 ETIMEDOUT (Connection timed out)
52    futex(0x7f6568178628, FUTEX_WAKE_PRIVATE, 1) = 0
52    futex(0x7f656817867c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=49998805}) = -1 ETIMEDOUT (Connection timed out)
52    futex(0x7f6568178628, FUTEX_WAKE_PRIVATE, 1) = 0
52    futex(0x7f656817867c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=49997408}) = -1 ETIMEDOUT (Connection timed out)
52    futex(0x7f6568178628, FUTEX_WAKE_PRIVATE, 1) = 0
52    futex(0x7f656817867c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=49998236}) = -1 ETIMEDOUT (Connection timed out)
52    futex(0x7f6568178628, FUTEX_WAKE_PRIVATE, 1) = 0
52    futex(0x7f656817867c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=49997979}) = -1 ETIMEDOUT (Connection timed out)
52    futex(0x7f6568178628, FUTEX_WAKE_PRIVATE, 1) = 0

**Comment by sschuberth** [comment]
Is it reproducible for a specific repo to scan that you can share?

**Comment by sschuberth** [comment]
Please reopen if this is still reproducible.
