### ISSUE TITLE
Git authentication not supported since upgrade to JGit 5.11

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#3864]
Hello
I have been using docker image build from the Dockerfile with the commit `8a44ec6751caaf6e4ad209ae6f7918809733de03` 09.03.2021
Yesterday I created a new image from the most recent commit: `9af63f4dde18d63d7bb10fe2e328079ecd9a4c1c` 07.04.2021
and suring a scan phase I face a git authentication issue
```
Caused by: TransportException: https://gitlab-ci-token@*******.git: authentication not supported
```
I use still the same .netrc file with machine address, gitlab-ci-token and the API_TOKEN.
In the debug mode I see that the .netrc file was loaded and there is a proper address of the machine collected

I read the changes and the docs and I didn't find any specific change in that matter.

Was there any specific change to the git authentication mechanisms?
Thanks for any help.

**Comment by tsteenbe** [comment]
@sschuberth  Is this maybe due to https://github.com/oss-review-toolkit/ort/pull/3762

**Comment by sschuberth** [comment]
Actually, that change shouldn't be related as Git still falls back to protocol v1 if v2 is not supported by the server.

**Comment by woznik** [comment]
Hello
Thank for your feedback
I have tested that the issue appears on the commit from 18 March on the commit: `9d06698a60b3f583e58c8faa55f623eae40e4690`

**Comment by sschuberth** [comment]
That [commit](https://github.com/oss-review-toolkit/ort/commit/9d06698a60b3f583e58c8faa55f623eae40e4690) is totally unrelated to anything Git. The cause must then be something else that coincidentally happened at the same time.

**Comment by woznik** [comment]
Yes, I agree. It does not relate to this specific commit
I just indicated the point in time where I find the issue for the first time

**Comment by sschuberth** [comment]
So, mind [bisecting](http://git-scm.com/docs/git-bisect) between 8a44ec6751caaf6e4ad209ae6f7918809733de03 and 9d06698a60b3f583e58c8faa55f623eae40e4690 to find out the exact commit that breaks for you?

**Comment by woznik** [comment]
I found that the `authentication not supported` appears on my side with this commit:
`Gradle: Upgrade JGit to version 5.11.0.202103091610-r` 
https://github.com/oss-review-toolkit/ort/commit/df23665ab7c41aaab8643673aee31cbd0e475612#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19

**Comment by sschuberth** [comment]
As the [JGit 5.11 release notes](https://projects.eclipse.org/projects/technology.jgit/releases/5.11.0) show several changes to `TransportHttp` it might be that they broke something... please reach out directly to the JGit community about this, e.g. by asking on their mailing list, or filing a bug on their side.

**Comment by sschuberth** [comment]
Also, do you happen to know which authentication scheme the server is expecting? Is it Kerberos?

**Comment by woznik** [comment]
I tested some config changes to force v1 to be used by the client but no use
finally I did a downgrade of JGit to 5.10 and it works on my side.
I will check the authentication scheme with the admins.
I will raise this issue to JGit community

**Comment by woznik** [comment]
> Also, do you happen to know which authentication scheme the server is expecting? Is it Kerberos?

Here is what I get from the admins: _For authentication (users mainly use graphical user interface) we use SAML auth solution with Lemonldap. For Git auth there are 2 possibles in https with username and a personnal access token or ssh key._

**Comment by sschuberth** [comment]
Feel free to re-open if this issue still occurs.
