### ISSUE TITLE
Capture the dependency graph in CycloneDX BOMs

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#3906]
Since the CycloneDX 1.2 spec, [the dependency graph moved from an extension to a core feature](https://github.com/CycloneDX/cyclonedx-core-java/issues/99#issuecomment-820619180). So after https://github.com/oss-review-toolkit/ort/pull/3897 is merged, we could make use of it as the hierarchy of dependencies is valuable additional information.

**Comment by mawl** [comment]
Hey,

we really would like to see see that this feature gets implemented. 
* Trivy can already generate CycloneDX SBOMs with a dependency graph included: https://trivy.dev/latest/docs/supply-chain/sbom/#generating * Since 2021 Dependency-Track can visualise dependency graphs: https://docs.dependencytrack.org/2021/03/17/v4.2.0/

**Comment by mawl** [comment]
@sschuberth: Thanks for your work.

Unfortunately I get a stackoverflow error with ort v43.0.0:

```
 ______________________________                                                
/        \_______   \__    ___/ The OSS Review Toolkit, version 43.0.0,        
|    |   | |       _/ |    |    built with JDK 21.0.5+11-LTS, running under Jav
|    |   | |    |   \ |    |    Executing 'report' as 'ort' on Linux           
\________/ |____|___/ |____|    with 8 CPUs and a maximum of 8192 MiB of memory
                                                                               
Environment variables:                                                        
ORT_CONFIG_DIR = /home/ort/.ort/config                                        
ORT_DATA_DIR = /builds/compliance/license-scanning/.ort                
HOME = /home/ort                                                              
JAVA_HOME = /opt/java/openjdk                                                 
ANDROID_HOME = /opt/android-sdk                                               
                                                                              
Looking for ORT configuration in the following file:
        /home/ort/.ort/config/config.yml
Generating the 'WebApp' report in thread 'DefaultDispatcher-worker-1'...
Generating the 'CycloneDX' report in thread 'DefaultDispatcher-worker-3'...
Generating the 'PlainTextTemplate' report in thread 'DefaultDispatcher-worker-4'...
Exception in thread "main" java.lang.StackOverflowError
	at org.ossreviewtoolkit.model.DependencyRefCursor.visitDependencies(DependencyGraphNavigator.kt:165)
	at org.ossreviewtoolkit.model.DependencyGraphNavigator.packageDependencies$traverse(DependencyGraphNavigator.kt:104)
	at org.ossreviewtoolkit.model.DependencyGraphNavigator.packageDependencies$traverse$lambda$8(DependencyGraphNavigator.kt:105)
	at org.ossreviewtoolkit.model.DependencyRefCursor.visitDependencies(DependencyGraphNavigator.kt:165)
...
	at org.ossreviewtoolkit.model.DependencyGraphNavigator.packageDependencies(DependencyGraphNavigator.kt:110)
	at org.ossreviewtoolkit.model.OrtResult.getDependencies(OrtResult.kt:241)
	at org.ossreviewtoolkit.plugins.reporters.cyclonedx.BomExtensionsKt.addDependencies(BomExtensions.kt:66)
...
        at org.ossreviewtoolkit.plugins.reporters.cyclonedx.BomExtensionsKt.addDependencies(BomExtensions.kt:67)
```

**Comment by mnonnenmacher** [comment]
Even large dependency trees should not cause a stackoverflow, if size was a problem I would expect an out of memory error.
@sschuberth Could there be an endless recursion if dependency graphs have circles?

**Comment by sschuberth** [comment]
> I was quite sure that the dependency graph implementation breaks cycles, but I'll double-check.

So when `build`-ing natively dependency *graphs*, cycles get removed automatically:

https://github.com/oss-review-toolkit/ort/blob/dcc97a0ecb3c604020601d6e514afa3fe9aed7cc/model/src/main/kotlin/utils/DependencyGraphBuilder.kt#L176-L189

But I'm not sure how it is for package managers that have not been converted yet, and that use a graph that is just converted from the tree...

@mawl which package managers does the analyzer find in your case?

**Comment by mawl** [comment]
> > I was quite sure that the dependency graph implementation breaks cycles, but I'll double-check.
> 
> So when `build`-ing natively dependency _graphs_, cycles get removed automatically (see the last line):
> 
> [ort/model/src/main/kotlin/utils/DependencyGraphBuilder.kt](https://github.com/oss-review-toolkit/ort/blob/dcc97a0ecb3c604020601d6e514afa3fe9aed7cc/model/src/main/kotlin/utils/DependencyGraphBuilder.kt#L176-L189)
> 
> Lines 176 to 189 in [dcc97a0](/oss-review-toolkit/ort/commit/dcc97a0ecb3c604020601d6e514afa3fe9aed7cc)
> 
>  fun build(checkReferences: Boolean = true): DependencyGraph { 
>      if (checkReferences) checkReferences() 
>   
>      val (sortedDependencyIds, indexMapping) = constructSortedDependencyIds(dependencyIds) 
>      val (nodes, edges) = references.toGraph(indexMapping) 
>   
>      return DependencyGraph( 
>          sortedDependencyIds, 
>          sortedSetOf(), 
>          constructSortedScopeMappings(scopeMapping, indexMapping), 
>          nodes, 
>          edges.removeCycles() 
>      ) 
>  } 
> But I'm not sure how it is for package managers that have not been converted yet, and that use a graph that is just converted from the tree...
> 
> [@mawl](https://github.com/mawl) which package managers does the analyzer find in your case?

@sschuberth:
```
Found in total 14 definition file(s) from the following 8 package manager(s):
        GoMod, Maven, NPM, NuGet, PIP, PNPM, Poetry, Yarn
```

**Comment by sschuberth** [comment]
> GoMod, Maven, NPM, NuGet, PIP, PNPM, Poetry, Yarn

Out of these, GoMod, NuGet and PIP / PNPM / Poetry do not use the dependency graph yet. Probably a good reason to continue working on https://github.com/oss-review-toolkit/ort/issues/3825.
