### ISSUE TITLE
UploadResultToSw360Command doesn't process transitive dependencies

### ISSUE THREAD

**Issue by bs-ondem** [oss-review-toolkit/ort#3907]
As discussed in the [ORT Slack channel,](https://ort-talk.slack.com/archives/C9NNJ54B1/p1616567910048300) it seems that the `UploadResultToSw360Command` doesn't process transitive dependencies although the result contains meta-data on transitive dependencies. That shouldn't be the case and the transitive dependencies should also be processed and uploaded to SW360.

**Comment by sschuberth** [comment]
Maybe something in this mapping goes wrong:

https://github.com/oss-review-toolkit/ort/blob/aceb4b3a29632975c34803a45a247e89819446b0/cli/src/main/kotlin/commands/UploadResultToSw360Command.kt#L184-L188

**Comment by yuvarajsanthakumar** [comment]
This issue couldn't be reproduced anymore. Not sure if this got fixed or it was some configuration issue.

**Comment by sschuberth** [comment]
We didn't yet change anything on our side. But I can also not think of any misconfiguration that could have caused this. So I'd really feel better if @bs-ondem could double-check that he also cannot reproduce the issue before we close this.

**Comment by bs-ondem** [comment]
I can't reproduce it either, so I think we can close it for now.
