### ISSUE TITLE
Provide more information about ORT-specific LicenseRefs

### ISSUE THREAD

**Issue by mnonnenmacher** [oss-review-toolkit/ort#3909]
The [declared license mapping](https://github.com/oss-review-toolkit/ort/blob/master/utils/spdx/src/main/resources/declared-license-mapping.yml) contains a few mappings to licenses that start with "LicenseRef-ort-". For the user there is no way to find out more information about those licenses, for example the license text, without investigating the text that was mapped to these licenses and searching the Git log for the commits that introduced those mappings.
We should either stop using ORT-specific LicenseRefs or provide an easy way for users to get more information about those licenses.

Also see the discussion in this PR: https://github.com/oss-review-toolkit/ort/pull/3898

**Comment by sschuberth** [comment]
FYI, at the example of `LicenseRef-ort-oracle-futc`, the license text is at https://www.oracle.com/downloads/licenses/oracle-free-license.html.

**Comment by mnonnenmacher** [comment]
This is partly fixed by #4920, the only left license is "LicenseRef-ort-google-maps-tos".
@sschuberth @tsteenbe I'm not sure if we would want to include the license text of a commercial license in our repository. Shall we keep this open until https://github.com/nexB/scancode-toolkit/issues/2322 is implemented? Or remove the LicenseRef even before that?

**Comment by sschuberth** [comment]
> include the license text of a commercial license in our repository.

I don't have a problem with that. And we I believe we already have rules depending on "LicenseRef-ort-google-maps-tos", I'd prefer to keep the ID and also add the text.

> Shall we keep this open until nexB/scancode-toolkit#2322 is implemented?

The issue is from 2020. So wouldn't hold my breath for it...
