### ISSUE TITLE
GoMod considers the entire graph of dependencies without checking if the code uses them

### ISSUE THREAD

**Issue by vbasem** [oss-review-toolkit/ort#3934]
currently the logic relies on go mod graph to extract the dependency tree.
For example if you are using [viper](https://github.com/spf13/viper) as a dependency ORT will report the [crypt](https://github.com/bketelsen/crypt) package as a dependency and an input for scan and download. 

This is only true, if the code uses the remote provider in viper and not the local implementation. To avoid this issue, we could use `go mod why <package>` to verify whether a dependency from the graph is actually used within the application or not, since by default the graph doesnt consider this.

Suggestion:

After building the dependency graph , verify each element through ```go mod why``` as explained [here](https://golang.org/ref/mod#go-mod-why)

<sub> Basem Vaseghi <basem.vaseghi@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by sschuberth** [comment]
> since by default the graph doesnt consider this.

Doh, that's quite a bummer. Thanks for pointing this out.

So taking `go mod why` into account should also help to address #3860.

**Comment by vbasem** [comment]
yes the pseudo code would be:
1. get the dependency tree using ```go mod graph``` which should print the module requirements
2. run each entry through ```go mod why``` to verify whether that dependency is part of the compilation or an unused dependency

**Comment by sschuberth** [comment]
> 2. run each entry through `go mod why` to verify whether that dependency is part of the compilation or an unused dependency

That bit unfortunately sounds very involving when you have hundreds or thousands of dependencies in the graph. But at least `go mod why` seems to accept multiple packages, so we can probably do one huge bulk-request, or at least go through the graph's nodes in chunks.

**Comment by vbasem** [comment]
thats true, luckily even in the kubernetes project we dont come anywhere near that many dependencies. Most larger projects converge anywhere between 100-500 deps. If the we know of an optimized way, the better!

**Comment by tsteenbe** [comment]
@dlorenc pointed out in his [Tweet|https://twitter.com/lorenc_dan/status/1397879783078379522] that `go list -deps -json ./...` is the only right way to get the dependencies for a Go project yet in OSS Review Toolkit we use we `go mod vendor -v`  and `go mod graph`. It was not clear to me from reading [GoMod.kt](https://github.com/oss-review-toolkit/ort/blob/master/analyzer/src/main/kotlin/managers/GoMod.kt) why we use `graph` and `vendor` and not `list`.

**Comment by sschuberth** [comment]
> It was not clear to me from reading [GoMod.kt](https://github.com/oss-review-toolkit/ort/blob/master/analyzer/src/main/kotlin/managers/GoMod.kt) why we use `graph` and `vendor` and not `list`.

See https://github.com/oss-review-toolkit/ort/pull/2430.

**Comment by oheger-bosch** [comment]
So the current implementation is correct? I would like to start working on this ticket.

**Comment by sschuberth** [comment]
> So the current implementation is correct?

I have no indication that it's *not* correct. When looking at the test asset changes in Martin's PR where he switched from `go list` to `go mod`, only two changes were made to the expected results, and it was discussed [here](https://github.com/oss-review-toolkit/ort/pull/2430/files#r402417015). So unless there is proof otherwise, I regard the current implementation to be correct (modulo this very bug you intend to work on).

But maybe @vbasem can also comment on the `go list` vs. `go mod` issue, and which one should preferably be used to get the dependency tree?
