### ISSUE TITLE
Support DotNet / NuGet `packages.lock.json` lock files

### ISSUE THREAD

**Issue by MoumitaManna** [oss-review-toolkit/ort#3943]
Hi,

We have a requirement where we have to feed  package.lock.json file to ORT tool and get an ORT output.
Package.lock.json file is generated using MSBuilds and it contains all the direct and transitive dependencies information of a project.
Is there any existing feature of ORT which will serve our purpose. PFA the sample for packages.lock.json file
Thankyou in anticipation.
[Packages.lock.json.txt](https://github.com/oss-review-toolkit/ort/files/6383607/Packages.lock.json.txt)

Regards,
Moumita

**Comment by sschuberth** [comment]
Lock file support for NuGet / DotNet projects is not implemented currently, see

https://github.com/oss-review-toolkit/ort/blob/5059bf1fe9070f5e8169c6d9cd7be9e64972b0f5/analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt#L223-L224

But we're happy accepting contributions in that area.

**Comment by sschuberth** [comment]
@pombredanne was this also implemented as part of https://github.com/oss-review-toolkit/ort/pull/6209?

**Comment by pombredanne** [comment]
@MoumitaManna feedback is much welcomed!

**Comment by sschuberth** [comment]
> @MoumitaManna feedback is much welcomed!

Sure, but there has been no feedback since 2021, so don't hold your breath.
