### ISSUE TITLE
[Question] Analysis scope exclusion

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#3944]
Hello
Is it possible to completely exlude the part of the code from the analysis?
Currently exclusion works only to gray-out the final results

My `.ort.yml` looks like this

```
excludes:
  scopes:
  - pattern: "test.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
  - pattern: ".*Test.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
  - pattern: "testapp/**"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
```

In the output of the console the project `testapp` is being analysed

```
Environment variables:
ORT_CONFIG_DIR = /root/.ort/config
ORT_DATA_DIR = /root/.ort
JAVA_HOME = /opt/java/openjdk
ANDROID_HOME = /opt/android-sdk
GOPATH = /go
The following configuration files are used:
	/root/.ort/config/curations.yml
The following package managers are activated:
	Bower, Bundler, Cargo, Carthage, Composer, Conan, DotNet, GoDep, GoMod, Gradle, Maven, NPM, NuGet, PIP, Pipenv, Pub, SBT, SpdxDocumentFile, Stack, Yarn
Analyzing project path:
	/builds/sqsc/home_cloud/hc_library
10:44:29.638 [main] INFO  org.ossreviewtoolkit.analyzer.Analyzer - Using configuration file '/builds/sqsc/home_cloud/hc_library/.ort.yml'.
10:44:30.013 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/builds/sqsc/home_cloud/hc_library/.git' as it is hard-coded to be ignored.
10:44:30.692 [main] INFO  org.ossreviewtoolkit.utils.OrtAuthenticator - Authenticator was successfully installed.
10:44:30.703 [main] INFO  org.ossreviewtoolkit.utils.OrtProxySelector - Proxy selector was successfully installed.
10:44:30.703 [main] INFO  org.ossreviewtoolkit.analyzer.Analyzer - Gradle projects found in:
10:44:30.704 [main] INFO  org.ossreviewtoolkit.analyzer.Analyzer - 	build.gradle
10:44:30.704 [main] INFO  org.ossreviewtoolkit.analyzer.Analyzer - 	hc_library/build.gradle
10:44:30.704 [main] INFO  org.ossreviewtoolkit.analyzer.Analyzer - 	testapp/build.gradle
10:44:30.704 [main] INFO  org.ossreviewtoolkit.analyzer.Analyzer - 	big5survey/build.gradle
10:44:30.733 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Resolving Gradle dependencies for '/builds/sqsc/home_cloud/hc_library/build.gradle'...
Downloading https://services.gradle.org/distributions/gradle-5.6.4-all.zip
.....................................................................................................................................
10:45:11.627 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.utils.OrtAuthenticator - Authenticator is already installed.
10:45:11.629 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.utils.OrtProxySelector - Proxy selector is already installed.
10:45:11.804 [DefaultDispatcher-worker-3] ERROR org.ossreviewtoolkit.analyzer.PackageManager - Resolving dependencies for 'build.gradle' failed with: BuildException: Could not fetch model of type 'DependencyTreeModel' using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-5.6.4-all.zip'.
Caused by: LocationAwareException: Build file '/builds/sqsc/home_cloud/hc_library/testapp/build.gradle' line: 17
A problem occurred evaluating project ':testapp'.
Caused by: GradleScriptException: A problem occurred evaluating project ':testapp'.
```

Is it possible to exclude it totally?

BTW 1: In the docs there is a list of samples for different technologies like `gradle-android.ort.yml`
Should I place the file with a name `gradle-android.ort.yml` into the root directory or it must be always `.ort.yml` ?

BTW 2: In the docs here https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-ort-yml.md#excluding-paths
there is a small typo. Instead of `TEST_OF` there should be `TEST_DEPENDENCY_OF`

![image](https://user-images.githubusercontent.com/17202024/116230156-980e4f00-a757-11eb-8382-ee15965e13e1.png)

Otherwise Analyzer throws:

![image](https://user-images.githubusercontent.com/17202024/116230259-b6744a80-a757-11eb-8b9c-44017da93175.png)

Thank you in advanced

**Comment by sschuberth** [comment]
> Is it possible to exclude it totally?

No, this is intentionally not possible. ORT's philosophy is it to not hide anything from the reports, but just mark it specially. Otherwise it would be too easy to "fake" reports, and it would be unclear to the reader whether the report is complete or not.

Also, we appreciate that as a "by-product" ORT is highlighting violation against best engineering practices, like being able to build projects out-of-the-box, and, well, being buildable at all.

> Should I place the file with a name `gradle-android.ort.yml` into the root directory or it must be always `.ort.yml` ?

Always as `.ort.yml`.

> Instead of `TEST_OF` there should be `TEST_DEPENDENCY_OF`

Actually `TEST_OF` is correct, see the code:

https://github.com/oss-review-toolkit/ort/blob/5059bf1fe9070f5e8169c6d9cd7be9e64972b0f5/model/src/main/kotlin/config/PathExcludeReason.kt#L69

As this was fixed a while back, I assume your ORT version is simply outdated.

**Comment by woznik** [comment]
Hi
Thanks for claryfication

Concerning `TEST_OF` I have built the image from the `master` branch (commit `cecaf6ed3029d3150ef15cbe612394142685e74b` - two weeks old) and I do have the file `PathExcludeReason.kt` so it seems that TEST_OF entry is not recognized in my case and it throws an error:

![image](https://user-images.githubusercontent.com/17202024/116400351-3b2f9900-a82a-11eb-84e1-03c2e20d16cc.png)

**Comment by sschuberth** [comment]
The error message complains about s *Scope*ExcludeReason being `TEST_OF` instead of `TEST_DEPENDENCY_OF`. So please double-check all your *scope* (not path) excludes to be correct.

**Comment by woznik** [comment]
ah, oh. you're right. `scope` keyword should be used instead og `paths`
