### ISSUE TITLE
Option to set a minimum score needed for ClearlyDefined curations to be taken into account

### ISSUE THREAD

**Issue by silverhook** [oss-review-toolkit/ort#3950]
The quality of curations on ClearlyDefined.io varies quite a bit. Luckily they know that and provide a score that can be used to estimate the quality of each curation.

I suggest that there should be an option (in config file, perhaps also as a flag) to set what the minimum score of a ClearlyDefined.io curation should be for the curation to be used as a conclusion by ORT.

Example:
- I decide that a score of 87 or above on ClearlyDefined.io guarantees me that if I scanned the code myself, I would not find anything new
- for everything else I want to check the code myself through ScanCode and/or FOSSology

**Comment by sschuberth** [comment]
As a side note, @borisbaldassari did something similar for Eclipse over [here](https://gitlab.eclipse.org/eclipsefdn/emo-team/eclipsefdn-ort/-/blob/main/scripts/curate_clearlydefined.py#L83-99). Doing this in ORT would probably allow to get rid of that script to reduce complexity on their side.

**Comment by sschuberth** [comment]
It would probably be good to first implement https://github.com/oss-review-toolkit/ort/issues/6055.
