### ISSUE TITLE
Provide more information when VCS download fails

### ISSUE THREAD

**Issue by mnonnenmacher** [oss-review-toolkit/ort#3952]
The [`updateWorkingTree`](https://github.com/oss-review-toolkit/ort/blob/ce30534806361486097700fb0c0fbab611a2d239/downloader/src/main/kotlin/VersionControlSystem.kt#L308) function only returns a `Boolean` to describe if the update was successful or not. If it fails, the actual errors get only written to the logs. For example, if Git fails to checkout a revision because it does not exist, this error is written to the logs, but will not be visible in the result files and reports, these will only contain a generic error message.

This makes the investigation of VCS download issues unnecessarily hard. It could be improved by either throwing an exception in `updateWorking` that provides more details in the message, or by returning a result object with more information instead of a `Boolean`.

**Comment by sschuberth** [comment]
As a note to myself, I had been doing some semi-related experiments in https://github.com/oss-review-toolkit/ort/pull/2721.

**Comment by sschuberth** [comment]
I plan to address this while debugging https://github.com/oss-review-toolkit/ort/pull/4024.
