### ISSUE TITLE
WebAppReporter: Add more times (scanner start time, reporter creation time) to metadata and About dialog

### ISSUE THREAD

**Issue by neubs-bsi** [oss-review-toolkit/ort#4041]
This is a follow up ticket to #3727 which was closed after merging #3978.

In the PR there was a discussion of adding more times, like the run of the scanner and the actual date of creation of the web app reporter. But the PR was merged and the ticket closed since an initial timestamp indicating a rough time frame was added with the time the anaylzer started. 

@sschuberth you expressed a wish for the time of creation of the report to be added.

Additionally those timestamps should include the exact time (hh:mm:ss), as currently they just display a date (e.g. Friday, 15th of June)

**Comment by tsteenbe** [comment]
@neubs-bsi  I propose not only add the start time for all ORT components but also include the duration and move this info into ORT result statistics. What we then can do is add a new tab stats where we can not only show times but also numbers for issues/violations in the webapp report. Believe would be a better approach then just cramming it in the About dialog.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
