### ISSUE TITLE
Support NPM dependencies that point to Git / GitHub repos

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#4044]
NPM not only allows to declare dependencies by scope / name / version, but also by [(shortcut) links to Git(Hub) repos](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#github-urls). This is very similar to the syntax ORT already supports for [referring to repositories](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository).

Currently, if the the `package.json` such a dependency is declared like

    "web-animations-js": "github:angular/web-animations-js#release_pr208"

 the ORT analyzer would emit a result of

    - package:
        id: "NPM::web-animations-js:2.3.2-pr208"
        purl: "pkg:npm/web-animations-js@2.3.2-pr208"
        declared_licenses:
        - "Apache-2.0"
        declared_licenses_processed:
          spdx_expression: "Apache-2.0"
        description: "JavaScript implementation of the Web Animations API"
        homepage_url: "https://github.com/web-animations"
        binary_artifact:
          url: ""
          hash:
            value: ""
            algorithm: ""
        source_artifact:
          url: "github:angular/web-animations-js#96635c1a82a730fc71cc5d6cabe5dfe7c8349ec5"
          hash:
            value: ""
            algorithm: ""
        vcs:
          type: "Git"
          url: "git+https://github.com/web-animations/web-animations-js.git"
          revision: "96635c1a82a730fc71cc5d6cabe5dfe7c8349ec5"
          path: ""
        vcs_processed:
          type: "Git"
          url: "https://github.com/web-animations/web-animations-js.git"
          revision: "96635c1a82a730fc71cc5d6cabe5dfe7c8349ec5"
          path: ""
      curations: []

So while `vcs_processed` is correct, the `source_artifact` URL is not, and at least user who have configured ORT to [prefer source artifacts over VCS](https://github.com/oss-review-toolkit/ort/pull/3736) will run into trouble.

As a first step towards the solution, we should probably simply call [expandNpmShortcutURL](https://github.com/oss-review-toolkit/ort/blob/23c421345ada0af0d0c0ebab54743defe9137e85/analyzer/src/main/kotlin/managers/utils/NodeSupport.kt#L80-L113) when [populating the source artifact's URL](https://github.com/oss-review-toolkit/ort/blob/3143d1d7617b71f80b1e688cf8ecf2c1f75328dd/analyzer/src/main/kotlin/managers/Npm.kt#L316). This should set the `url` in the analyzer result to

    https://github.com/angular/web-animations-js.git#96635c1a82a730fc71cc5d6cabe5dfe7c8349ec5

This of course also is not correct yet. But we should be able to easily map this to a URL to a dynamically created ZIP artifact that GitHub is able to crate:

    https://github.com/angular/web-animations-js/archive/96635c1a82a730fc71cc5d6cabe5dfe7c8349ec5.zip

which forwards to

    https://codeload.github.com/angular/web-animations-js/zip/96635c1a82a730fc71cc5d6cabe5dfe7c8349ec5

This second mapping could either be implemented in `expandNpmShortcutURL` as an optional post-processing, or in a new separate function, or more generally in the `VcsHost` class for *all* supported VCS hosting platforms.

**Comment by sschuberth** [comment]
FYI @neubs-bsi.

**Comment by neubs-bsi** [comment]
I found some links that describe how this could work for different uri schemes: 
- [github](https://stackoverflow.com/questions/13636559/how-to-download-zip-from-github-for-a-particular-commit-sha)
- gist -> similar to github, example: https://gist.github.com/moondev/09c17f2126c41d39043aa6ba5d4dc01e/archive/721b74eec670b86e37b70c99071662d05330f12c.zip
- [bitbucket](https://confluence.atlassian.com/bitbucketserver/download-a-repository-archive-913477030.html) 
- [gitlab](https://docs.gitlab.com/ce/api/repositories.html#get-file-archive)
