### ISSUE TITLE
Also get debug output from underlying processes

### ISSUE THREAD

**Issue by nicorikken** [oss-review-toolkit/ort#4080]
I was having an issue running a scan. I tried the `--debug` flag, and although I did get more output on the ORT-side of things, the actual problem happen to be in the `scancode` command, which didn't change its behavior with the `--debug` flag. So the run with `--debug` didn't provide me with any more useful information.

Some idea would be to also expand the output from the underlying processes. So the current scancode command https://github.com/oss-review-toolkit/ort/blob/edbb46cb1dab1529d5ffb81cba18d365b98ef23e/scanner/src/main/kotlin/scanners/scancode/ScanCode.kt#L83-L89 could be appended with `--verbose`. Unfortunately scancode doesn't seem to have a `--debug` option.

For now my current workaround is to run ORT with a simple inline config change option:
```
$ ort --info -P ort.scanner.options.ScanCode.commandLine="--copyright --license --info --strip-root --timeout 300 --verbose" scan ...
```

I mainly created this issue to discuss this option and keep track of this idea. ORT is configurable enough to increase debugging if you really need to.

**Comment by sschuberth** [comment]
Closing this for now. Feel free to reopen if I didn't convince you, @nicorikken.
