### ISSUE TITLE
Ability to analyse Composer projects with platform requirements via Docker

### ISSUE THREAD

**Issue by camillem** [oss-review-toolkit/ort#4109]
Hi,

I couldn't find any (simple) way to analyze via docker a Composer project where dependencies have platform requirements (like special extensions required).

## Steps to reproduce :

1 - Create an empty composer project, with a composer.json like the one attached. [composer.json.txt](https://github.com/oss-review-toolkit/ort/files/6590151/composer.json.txt)

2 - Launch the analyse of the project via docker (commit d563a56c7bbc4437f9800a1457b30ba138af48da) 

```bash
docker run -v [mypath]:/project ort -P ort.analyzer.allowDynamicVersions=true --info analyze -f JSON -i /project/ort_composer -o /project/rapports/ort_composer/analyzer
```
## Expected result : 
A full list of dependencies analyzed

## Actual results : 

An error in the resulting file : 

```json
      "issues" : {
        "Composer::composer.json:" : [ {
          "timestamp" : "2021-06-03T08:21:23.859536Z",
          "source" : "Composer",
          "message" : "Resolving Composer dependencies for 'composer.json' failed with: IOException: Running 'composer install' in '/project/ort_composer' failed with exit code 2:\nDo not run Composer as root/super user! See https://getcomposer.org/root for details\nLoading composer repositories with package information\nInstalling dependencies (including require-dev) from lock file\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - Installation request for endroid/qr-code 3.9.7 -> satisfiable by endroid/qr-code[3.9.7].\n    - endroid/qr-code 3.9.7 requires php ^7.3||^8.0 -> your PHP version (7.2.24) does not satisfy that requirement.\n  Problem 2\n    - Installation request for myclabs/php-enum 1.8.0 -> satisfiable by myclabs/php-enum[1.8.0].\n    - myclabs/php-enum 1.8.0 requires php ^7.3 || ^8.0 -> your PHP version (7.2.24) does not satisfy that requirement.\n  Problem 3\n    - Installation request for phpoffice/phpspreadsheet 1.18.0 -> satisfiable by phpoffice/phpspreadsheet[1.18.0].\n    - phpoffice/phpspreadsheet 1.18.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.\n  Problem 4\n    - myclabs/php-enum 1.8.0 requires php ^7.3 || ^8.0 -> your PHP version (7.2.24) does not satisfy that requirement.\n    - maennchen/zipstream-php 2.1.0 requires myclabs/php-enum ^1.5 -> satisfiable by myclabs/php-enum[1.8.0].\n    - Installation request for maennchen/zipstream-php 2.1.0 -> satisfiable by maennchen/zipstream-php[2.1.0].\n\n  To enable extensions, verify that they are enabled in your .ini files:\n[...skipping 2 lines...]\n    - /etc/php/7.2/cli/conf.d/10-pdo.ini\n    - /etc/php/7.2/cli/conf.d/20-calendar.ini\n    - /etc/php/7.2/cli/conf.d/20-ctype.ini\n    - /etc/php/7.2/cli/conf.d/20-exif.ini\n    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini\n    - /etc/php/7.2/cli/conf.d/20-ftp.ini\n    - /etc/php/7.2/cli/conf.d/20-gettext.ini\n    - /etc/php/7.2/cli/conf.d/20-iconv.ini\n    - /etc/php/7.2/cli/conf.d/20-json.ini\n    - /etc/php/7.2/cli/conf.d/20-phar.ini\n    - /etc/php/7.2/cli/conf.d/20-posix.ini\n    - /etc/php/7.2/cli/conf.d/20-readline.ini\n    - /etc/php/7.2/cli/conf.d/20-shmop.ini\n    - /etc/php/7.2/cli/conf.d/20-sockets.ini\n    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini\n    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini\n    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini\n    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini\n  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.\n\n(Above output is limited to each 20 heading and tailing lines.)",
          "severity" : "ERROR"
        } ]
      },
```
## Comments

You can reproduce the error locally (on a platform without the required extensions)

```bash
composer install
```
Fails with the error 
```bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpoffice/phpspreadsheet 1.9.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
[...]
```
This can be solved with 

```bash
composer install --ignore-platform-reqs
```

So is there a way to add this parameter to composer when called via the docker image ?

Thanks,
Camille

**Comment by sschuberth** [comment]
> So is there a way to add this parameter to composer when called via the docker image ?

Unfortunately not. Currently the only way is to create a custom Docker image which has this library additionally installed.

**Comment by camillem** [comment]
Thanks for the fast answer. Just out of curiosity, why not add "--ignore-platform-reqs" to the composer install command of the default image?

**Comment by sschuberth** [comment]
> Just out of curiosity, why not add "--ignore-platform-reqs" to the composer install command of the default image?

I did know about that option until you told me, and I somehow overread it in your initial post 😊 Sounds like a viable option to me. However, IIUC the correct place for this to go would be to where `Composer.kt` calls "install":

https://github.com/oss-review-toolkit/ort/blob/5753b599607caa6238238d0161a0a7f04fec2c44/analyzer/src/main/kotlin/managers/Composer.kt#L359

This line should be changed to `run(workingDir, "install", "--ignore-platform-reqs")`. Would you mind filing a PR for this? The commit message should explain what this is good for, and probably link to https://getcomposer.org/doc/03-cli.md#install-i for reference.

**Comment by camillem** [comment]
Thanks ! I re-did the PR as I had forgotten to signoff the first one and to mention Composer's documentation in the description. Hope the second one is OK.

**Comment by sschuberth** [comment]
FYI, there is no need to redo a PR if you forgot the signoff. Just amend your commit (`git commit --amend --signoff`) and force-push afterwards (`git push --force`). Thanks for the PR, I'll have a look.
