### ISSUE TITLE
ort takes long time

### ISSUE THREAD

**Issue by chimisu** [oss-review-toolkit/ort#4117]
Hi Team

ort is running in docker,it takes nearly 20 minutes,is this normal? How can I optimize it?

**Comment by sschuberth** [comment]
Can you be more specific about which part of ORT takes long for you? The analyzer tool? The scanner tool? Or building the Docker image?

**Comment by chimisu** [comment]
run analyze command in docker.

**Comment by sschuberth** [comment]
On what kind of project? Judging from your avatar I assume Go? If so, this might be related to https://github.com/oss-review-toolkit/ort/issues/3934 (and also https://github.com/oss-review-toolkit/ort/issues/3825 somewhat).

**Comment by chimisu** [comment]
java and nodejs project

**Comment by sschuberth** [comment]
NodeJS dependency trees are actually very deep, and we need to contact the NPM registry to get metadata for each package. So depending on the size of your project(s), the speed of your Internet connection etc., and analysis for such a project might indeed take several minutes.
