### ISSUE TITLE
Improve handling of module declaration for Golang packages

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#4127]
ORT currently throws a DownloadException for module declaration suffixes such as  `v2` or `v10` as it assumes them to be a part of the VCS path which they are not. Related Golang docs (https://golang.org/doc/modules/gomod-ref#module-syntax) is ambigious on whether module version should be a directory in the repo or not.

We can't just simply drop the `v[digit]` from the VCS path as their may be repositories that do use directories for each version module.

**Example go-playground/assert**

Id: GoMod::github.com/go-playground/assert/v2:v2.0.1
Package URL: pkg:golang/github.com%2Fgo-playground%2Fassert%2Fv2@v2.0.1
Repository Declared: https://github.com/go-playground/assert.git
Repository Processed: https://github.com/go-playground/assert.git

```
Could not download 'GoMod::github.com/go-playground/assert/v2:v2.0.1': DownloadException: Download failed for 'GoMod::github.com/go-playground/assert/v2:v2.0.1'. Suppressed: DownloadException: The Git working directory at '/tmp/ort-ScanCode13095570840845971637/GoMod/unknown/github.com%2Fgo-playground%2Fassert%2Fv2/v2.0.1' does not contain the requested path 'v2'. Suppressed: DownloadException: No source artifact URL provided for 'GoMod::github.com/go-playground/assert/v2:v2.0.1'.
```

**Example go-playground/validator**

Id: GoMod::github.com/go-playground/validator/v10:v10.4.1
Package URL: pkg:golang/github.com%2Fgo-playground%2Fvalidator%2Fv10@v10.4.1
Repository Declared: https://github.com/go-playground/validator.git
Repository Processed: https://github.com/go-playground/validator.git

```
Could not download 'GoMod::github.com/go-playground/validator/v10:v10.4.1': DownloadException: Download failed for 'GoMod::github.com/go-playground/validator/v10:v10.4.1'. Suppressed: DownloadException: The Git working directory at '/tmp/ort-ScanCode13095570840845971637/GoMod/unknown/github.com%2Fgo-playground%2Fvalidator%2Fv10/v10.4.1' does not contain the requested path 'v10'. Suppressed: DownloadException: No source artifact URL provided for 'GoMod::github.com/go-playground/validator/v10:v10.4.1'.
```

**Comment by tsteenbe** [comment]
Workaround for this issue is to create a VCS curations in `curations.yml` to simply set the VCS path to empty e.g.

```
- id: "GoMod::github.com/go-playground/validator/v10:v10.4.1"
  curations:
  comment: "Set path to empty as repository does not have `v10` directory."
  vcs: 
    path ""
```

**Comment by sschuberth** [comment]
> Related Golang docs (https://golang.org/doc/modules/gomod-ref#module-syntax) is ambigious on whether module version should be a directory in the repo or not.

For the record, I wouldn't say it's ambiguous, but it's just (too) loosely defined. Note the "should" (instead of "must") in:

> The module path *should* be a path from which Go tools can download the module source. In practice, this is typically the module source's repository domain and path to the module code within the repository.

**Comment by fviernau** [comment]
There are two options for doing a release whereas only one option involves the creation of a "v2" directory:
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by fviernau** [comment]
Note: The GoMod integration in ORT was developed such that it captures most of the cases for determining the VCS info. So accepting that several edge cases don't work. I believe it was never meant to become a re-implementation of what the `go` command actually does, instead in the long run the logic from the `go` command should be used to determine the VCS.
So not every kind of edge case issue would be an argument to extend the implementation, but could add to the list of arguments pointing at doing a re-write.

This particular case probably isn't an edge case, so it may make sense to cover it.
