### ISSUE TITLE
Load curations from a directory structure

### ISSUE THREAD

**Issue by MarcelBochtler** [oss-review-toolkit/ort#4128]
To avoid huge `curation.yml` files, ORT should be able to use curations from a directory structure similar to the `--package-configuration-dir` option.

The separate yml-files should be searched for recursively so the user can maintain their wanted directory structure.
As I don't see a technical reason to support both the `--package-curations-file` option and the new `--package-curations-dir` should not be mutually exclusive but merge the curations from both sources.

**Comment by tsteenbe** [comment]
Our `curations.yml` is currently larger than 1Mb and we noticed that web preview in GitLab won't render it anymore.

Propose to make `--package-curations-dir`similar to how do `--package-configuration-dir`.
