### ISSUE TITLE
Add `color` property to the categories in `license-classifications.yml`

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#4150]
*Edit:* But maybe we could add a `color` property to the categories in `license-classifications.yml`, and make use of them here.

_Originally posted by @sschuberth in https://github.com/oss-review-toolkit/ort/pull/4092#discussion_r648600089_

**Comment by sschuberth** [comment]
@tsteenbe, given that it's good practice to separate the data model from the visualization, I don't believe anymore that adding a `color` property to the license classification would be a good idea. If you agree, can we close this issue?

**Comment by sschuberth** [comment]
As discussed in the [community meeting](https://github.com/oss-review-toolkit/ort/wiki/ORT-Community-Meeting#2023-04-27), it's no the ORT configuration model that should associate colors (or in fact any visual representation) to semantics of the license classification. Instead, this should be a reporter-specific feature. In case of the web-app reporter, the proposal is to solve this via https://github.com/oss-review-toolkit/ort/issues/2643 instead.
