### ISSUE TITLE
Allow empty revisions in VCS matchers of package configurations

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#4196]
In [curations](https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-curations-yml.md) we already support (Ivy-style) ranges for versions as part of IDs. On the other hand, [package configurations](https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-package-configuration-yml.md) do currently not support version ranges.

While in a [recent developer meeting](https://github.com/oss-review-toolkit/ort/wiki/Developer-Meeting#2021-06-10) HERE expressed concerns about that feature due to potential misuse, the same risk of misuse already stems from curations, and Bosch definitely needs the feature. So we should implement it IMO, and simply leave it to every party to make use of it or not. If required, there could even be simple CI checks for package configuration changes that prevent the use of version ranges.

**Comment by sschuberth** [comment]
@fviernau, we realized this issue seems to confuse two things:

- the version as part of the `id` of a package configuration, and
- the `revision` as part of a VCS matcher.

What we'd like to implement is *not* to support version ranges as part of the `id`, because that would be nonsense anyway as the VCS / source artifact matches would still point to a fixed revision / artifact URL.

Instead, the idea is to allow to leave the `revision` of a VCS matcher empty, so any revision is matched. The use case is SPDX files that define packages whose source code resides in the same repository as the project itself, or whose package directories point to Git submodules. Currently, whenever the project or the submodule is updated, also the revision in the VCS matcher of package configurations needs to be updated, which is inconvenient.

So, would you been fine with optionally omitting the revision to match any revision? Would you require this possibility to be hidden behind a feature toggle?

**Comment by sschuberth** [comment]
> So, would you been fine with optionally omitting the revision to match any revision?

Alternatively, we could require to explicitly write the name of the symbolic revision (like "master" / "main"), which would probably get us around implementing a feature toggle: The toggle then is to write out the symbolic revision explicitly.

**Comment by fviernau** [comment]
> Instead, the idea is to allow to leave the `revision` of a VCS matcher empty, so any revision is matched. The use case is SPDX files that define packages whose source code resides in the same repository as the project itself, or whose package directories point to Git submodules. Currently, whenever the project or the submodule is updated, also the revision in the VCS matcher of package configurations needs to be updated, which is inconvenient.

Defining `LicenseFindingsCurations´s and `PathExclude`s is typically done via `ort.yml`, can you explain why you want to use package configurations for that purpose? ..Or rather, would it make sense to use `ort.yml` instead?

**Comment by sschuberth** [comment]
The package configurations I'm referring to *do* come from `.ort.yml`, i.e. we have `enableRepositoryPackageConfigurations` set to `true`.

**Comment by fviernau** [comment]
> The package configurations I'm referring to _do_ come from `.ort.yml`, i.e. we have `enableRepositoryPackageConfigurations` set to `true`.

I didn't mean package configurations in `ort.yml` but I meant the properties `excludes->paths` and `curations->license-findings`.

**Comment by sschuberth** [comment]
As just discussed with @mnonnenmacher matching symbolic revuisions is not possible as ORT does not store them in the scan results currently.

**Comment by hanna-modica** [comment]
Can it be documented in [1], that empty revisions are allowed and what the implications are?

[1] https://github.com/oss-review-toolkit/ort/blob/main/docs/config-file-package-configuration-yml.md#package-configuration-file-basics

**Comment by sschuberth** [comment]
> Can it be documented in [1], that empty revisions are allowed and what the implications are?

It *is* already briefly documented there by saying "[...] with an optional revision".
