### ISSUE TITLE
Remove fileCount from ScanSummary

### ISSUE THREAD

**Issue by neubs-bsi** [oss-review-toolkit/ort#4197]
In an ORT run with an SPDX dependency with a VCS info that referred to only one file we encountered the problem that when using ScanCode and that file contains no license or copyright information, the fileCount is set to 0, even though a file gets scanned. See here:

https://github.com/oss-review-toolkit/ort/blob/4615824c8aaa29fa276eaf01fd6c34d486e08976/model/src/main/kotlin/ScanSummary.kt#L100-L106

When the file count is 0, the scan result is considered to have failed andthis log output is printed:

https://github.com/oss-review-toolkit/ort/blob/4615824c8aaa29fa276eaf01fd6c34d486e08976/scanner/src/main/kotlin/ScanResultsStorage.kt#L276-L280

When checking the code, I could not see another place than the above check in `ScanSummary` where the `fileCount` was used other than reaching it through to be printed in e.g. the WebAppReporter. 

I propose to delete the variable all together, since it doesn't seem to add valuable functionality. This also removes the necessity to re-scan empty repositories or dependencies with just one file but no license or copyright findings.

**Comment by sschuberth** [comment]
@oss-review-toolkit/core-devs, would you agree to remove `fileCount` from `ScanSummary`? I do.

**Comment by fviernau** [comment]
Agree.

**Comment by sschuberth** [comment]
@mnonnenmacher any objections from your side? Does this impact the scan-by-repo topic?

**Comment by mnonnenmacher** [comment]
No objections, but please make sure to add a replacement for `FileCounterScannerFunTest`, I think that's the only integration test we have for the scanner and the only place where `scanOrtResult()` is tested.

**Comment by neubs-bsi** [comment]
@mnonnenmacher 
Would you be okay to replace the `FileCounterScannerTest` and the `FileCounterScanner` along with it, with a `DummyScanner`, that does absolutely nothing? Or do you want a Scanner that interacts with the given path in some form?

**Comment by mnonnenmacher** [comment]
I would prefer if the test scanner would report something based on the downloaded files to not lose that part of the test. The purpose of `FileCounterScanner` was to have a very fast scanner for testing, but I'm not sure if we need that anymore. I think I would just delete `FileCounterScanner`, rename `FileCounterScannerFunTest` to `ScannerIntegrationFunTest` and add a dummy scanner in the test code.
