### ISSUE TITLE
[Question] Dependency Level and Copyrights in the Spreadsheet report

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#4232]
Hello,
Is there a way to extract into the spreadsheet report an information about the dependency level as it is seen in the web app report and the copyright mentions?

Additionally, is it normal to have in the report a content of the Declared License data like the one on the screen?
![image](https://user-images.githubusercontent.com/17202024/123778188-24acc900-d8d1-11eb-828b-01e1eda9f85c.png)

Many thanks in advance

**Comment by sschuberth** [comment]
To be frank, we haven't been working on the Excel output for a long time, and I regard it as legacy. I doubt we'll put any bigger effort into maintaining it further. You should rather use / post-process one of the other report formats, like maybe the evaluated model report.

@tsteenbe do you guys still need the Excel report, or could we remove it?

**Comment by woznik** [comment]
In that case we can close the issue/question
