### ISSUE TITLE
support for golang 1.16.5?

### ISSUE THREAD

**Issue by mawl** [oss-review-toolkit/ort#4245]
Hey,

Do you support golang 1.16.5 ? 

With golang version 1.13.4, as in your Dockerfile, I get:
```
Resolving GoMod dependencies for 'go.mod' failed with: IOException: Running 'go mod why ...
malformed module path "io/fs": missing dot in first path element (Above output is limited to each 20 heading and tailing lines.)
```
With golang version 1.16.5 the exception disappears, but no licenses where found and this warning occurs.
```
10:11:42.310 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.GoMod - Resolving GoMod dependencies for '/builds/cs/examples/some-app/go.mod' took 19s.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/opt/ort/lib/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
10:12:17.055 [main] INFO  org.ossreviewtoolkit.utils.ProcessCapture - Running 'go version' in '/builds/cs/examples/some-app'...
10:12:17.077 [main] DEBUG org.ossreviewtoolkit.utils.ProcessCapture - go version go1.16.5 linux/amd64
```

Thanks for your answer.

Best regards,
Marco

**Comment by sschuberth** [comment]
You can ignore the `WARNING: An illegal reflective access operation has occurred`, it's a JVM thing and occurs in any case.

Regarding the Go version, we have no hard requirement there; version 1.13.4 is just what happens to be used in the Docker image right now. Let me see if anything breaks if we upgrade it.

**Comment by sschuberth** [comment]
Would version 1.15.13 also work for you @mawl? For that version I can easier argue that we've already tested it.

**Comment by mawl** [comment]
I will try it, thanks.

**Comment by mawl** [comment]
@sschuberth; updating go helps in the analyze phase to create the analyzer-result.yml file. And I understand now that I have to use the scanner to find license informationen for go.mod packages - thanks :)

(scancode has a bad performance (~120 Minutes for a semilarge project on the first run, 8 Core, 16GB RAM) but caching with artifactory helps for further runs. )

**Comment by sschuberth** [comment]
> updating go helps in the analyze phase to create the analyzer-result.yml file.

That is, updating to version 1.15.13, not to version 1.16.5, correct @mawl? If you, let's keep this open until we've updated our Docker image accordingly.
