### ISSUE TITLE
Jenkins pipeline building docker image in every stage

### ISSUE THREAD

**Issue by sameer1046** [oss-review-toolkit/ort#4261]
Jenkins pipeline building docker image in every stage.
Is it necessary to build it every time?

**Comment by sschuberth** [comment]
It's not strictly necessary, but in fact it should also not really be done: While it's correct that it looks like that from the `Jenkinsfile`, in reality the layer caching done by Docker will cause subsequent builds to be close to "no-ops".

So, are you *really* seeing (by observing the build time) that the Docker image is being rebuilt in every stage, or do you just see `docker build` being executed?

**Comment by sameer1046** [comment]
only docker build executed. There is a stage to build the docker image. I wonder why its repeted in every stage by the docker file agent

**Comment by sschuberth** [comment]
See the code comment:

https://github.com/oss-review-toolkit/ort/blob/53f24c06fa4bc5e89314d70b310378639fc397f1/integrations/Jenkinsfile#L169-L173

So the first stage explicitly builds the Docker image, mostly to get proper timing in the pipeline view for how long *only* building the Docker image takes.

The following stages also need the image, but as there is no Docker registry (in this simple pipeline) the image can be downloaded from, the image is being "rebuilt" in every stage. But effectively everything is taken from the layer cache, so this "rebuilding" should be fast actually.

**Comment by sameer1046** [comment]
Correct! In the first stage the docker image is built. So in the next stages the ort commands can be executed without the docker file agent. I have removed the docker file agent steps in second stage onwards still the pipeline working.

**Comment by sameer1046** [comment]
ok

**Comment by sschuberth** [comment]
> Correct! In the first stage the docker image is built. So in the next stages the ort commands can be executed without the docker file agent. I have removed the docker file agent steps in second stage onwards still the pipeline working.

Did you remove that comment because it yet turned out to not be working after all?
