### ISSUE TITLE
SpdxDocumentFile: Use packageFilename if present before using downloadLocation

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#4276]
In https://github.com/oss-review-toolkit/ort/blob/master/analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt#L320-L325 I propose we change the order of the check e.g. use packageFilename if present else use downloadLocation.
This make sense as if packageFilename is defined the code is already present locally so why download it again. Also this always the use case where a user uses downloadLocation to specify where he/she orginally got the code but wants to scan their local fork (with perhaps minor changes).

**Comment by sschuberth** [comment]
> This make sense as if packageFilename is defined the code is already present locally so why download it again.

I'm re-reading this in the context of reviewing https://github.com/oss-review-toolkit/ort/pull/6007. I guess the "code is already present locally" assumption wasn't really true, as there are cases where the SPDX file is stored independently of the source code of the package it describes. That is the 

> Otherwise it is not possible to define in SPDX that the source code of a package is located in a different VCS because the local working tree will always be preferred.

use-case that @mnonnenmacher tries to solve with https://github.com/oss-review-toolkit/ort/pull/6007.
