### ISSUE TITLE
please version releases

### ISSUE THREAD

**Issue by rfaircloth-splunk** [oss-review-toolkit/ort#4287]
It would be helpful to version releases by issues semver tags on the master branch. It would also be beneficial to the community to publish the docker container to ghcr.io

**Comment by tsteenbe** [comment]
Hi @rfaircloth-splunk,

There are ongoing discussions in the ORT technical steering committee (TSC) to start making official ORT releases related issues are  https://github.com/oss-review-toolkit/ort-governance/issues/20 and https://github.com/oss-review-toolkit/ort/issues/1901.

From the ORT side we deliberately have not published a Docket Image as for a license compliance tool we would like to publish a compliant image which is very difficult to do see for detailed discussion https://github.com/oss-review-toolkit/ort/issues/2441.

**Comment by sschuberth** [comment]
Is this good to be closed in favor of #1901 and #2441?

**Comment by sschuberth** [comment]
Closing in favor of the aforementioned issues.
