### ISSUE TITLE
Reporter: ORT is not transparently copying license text with copyright (c) holder name

### ISSUE THREAD

**Issue by porsche-rishisaxena** [oss-review-toolkit/ort#4295]
While running reporter on evaluate-result.yml, ORT is not transparently copying license text with copyright (c) holder name when it comes to some garbage value i.e. "Copyright (c), Contributor" or "Copyright (c) 2014-2021 the native-web".

Example(s): 
Actual Source Text (from license.txt): Copyright (c), Contributor
Reporter Output: Copyright (c),

Actual Source Text (from license.txt): Copyright (c) 2014-2021 the native-web
Reporter Output: Copyright (c) 2014-2015 the

**Comment by sschuberth** [comment]
This might actually be an issue with ScanCode itself, and eventually be fixed via [upgrading ScanCode](https://github.com/oss-review-toolkit/ort/issues/4296).

**Comment by porsche-rishisaxena** [comment]
@sschuberth 

In order to track down the issue, the following libraries have been scanned with various version of scan-code:

•	https://github.com/thenativeweb/uuidv4.git on tag branch 1.0.0
•	https://github.com/yargs/y18n.git on master branch

The following versions of scan-code were used:

•	3.2.1rc2 (ORT is using this Version)
•	21.3.31
•	21.7.30

With regards to the license findings, the following copyright statement were expected to be found:

•	uuidv4: Copyright (c) 2014-2021 the native web
•	y18n: Copyright (c) 2015, Contributors

![image](https://user-images.githubusercontent.com/87651181/128172708-9ad0400d-de4f-44f5-a284-1b7a8979ee49.png)
Note: The UUIDv4 issue has been reported as a bug in the Scan-code Backlog - https://github.com/nexB/scancode-toolkit/issues/2624

The results of the scan-code executions clearly show that the incomplete copyright statements are written out by scan-code and therefore are pointing towards a problem in the scan-code copyright detection and extraction algorithm. 

The result for the y18n package shows progress in that particular area and therefore a case can be built to upgrade the supported scan-code version.

**Comment by philippsimon** [comment]
I got fixed in scan-code and merged into the develop branch but it's not part of an official release yet:
https://github.com/nexB/scancode-toolkit/issues/2624

**Comment by sschuberth** [comment]
Thanks for the info @philippsimon. I'll still close this then, as this has never been an issue in ORT itself.
