### ISSUE TITLE
Scanner: How to upgrade scan-code version from ORT

### ISSUE THREAD

**Issue by porsche-rishisaxena** [oss-review-toolkit/ort#4296]
Scanner: We realized that ORT is running with year old version of scan-code. How to upgrade scan-code version from ORT to its latest version (scan-code)?

**Comment by tsteenbe** [comment]
@porsche-rishisaxena  We will be soon upgrading to the latest version of ScanCode currently doing upgrade tests, but if you have locally or in your Docker image have newer version of ScanCode the ORT will use it.

**Comment by porsche-rishisaxena** [comment]
Thank you @tsteenbe for the providing an update. Would you be so kind to provide some more insight to scan-code version upgrade in context to timelines?

**Comment by tsteenbe** [comment]
@porsche-rishisaxena  It's currently being worked on, expect at the latest last week of August if all goes well

**Comment by sschuberth** [comment]
@tsteenbe I'd be interested in what HERE is doing in the ScanCode upgrading context to maintain compatibility with existing scan results. That's a difficult topic, and one of the reasons why we didn't do the upgrade yet ourselves.

**Comment by porsche-rishisaxena** [comment]
@tsteenbe Would you be so kind to provide more information on what version of scan-code is under testing for the upgrade? 

We ran multiple test with different version of Scan-Code and the latest version of scan-code also result with a bug.
Reference: https://github.com/oss-review-toolkit/ort/issues/4295#issuecomment-892579247

**Comment by sschuberth** [comment]
> Would you be so kind to provide more information on what version of scan-code is under testing for the upgrade?

See the draft PR at https://github.com/oss-review-toolkit/ort/pull/4324.

**Comment by porsche-rishisaxena** [comment]
@tsteenbe: Is there any update on the progress or result from testing on the scan-code upgrade?

**Comment by mnonnenmacher** [comment]
@porsche-rishisaxena With the merge of my latest PR (#4669) ORT does not require a specific ScanCode version anymore. We do not yet provide an easy way to build the Docker image with a different ScanCode version, but you could already fork this repository and replace the ScanCode version in the Dockerfile or create your own Dockerfile that inherits from ours.

**Comment by sschuberth** [comment]
> We do not yet provide an easy way to build the Docker image with a different ScanCode version

This has been resolved meanwhile in https://github.com/oss-review-toolkit/ort/pull/4721, and upgrading ScanCode is now as easy as setting the `SCANCODE_VERSION` build argument when running `docker build`.
