### ISSUE TITLE
Differences in authentication between JGit and OrtAuthenticator

### ISSUE THREAD

**Issue by oheger-bosch** [oss-review-toolkit/ort#4311]
There seem to be corner cases, in which the authentication of JGit works differently than the one implemented by `OrtAuthenticator`. In a concrete scenario, the ORT downloader logged exceptions of the form `java.io.IOException: Unable to list the remote tags.`, but eventually the download via the `git` command line succeeded.

Analysis showed that this discrepancy was caused by a `.netrc` file that contained a `default` entry. Both ORT and JGit read this file, but JGit obviously does not interpret it correctly and thus fails to authenticate even if valid credentials are present in the file. (If there is no default entry in the file, authentication was successful in my tests.)

So ORT cannot rely on JGit's implementation that reads the `.netrc` file.

**Comment by sschuberth** [comment]
My proposal would then be to

1. simply revert https://github.com/oss-review-toolkit/ort/pull/3932 to remedy the issue for now,
2. fix the issue in upstream JGit,
3. eventually re-introduce https://github.com/oss-review-toolkit/ort/pull/3932 after upgrading to a JGit version with the fix.

**Comment by oheger-bosch** [comment]
Unfortunaltely, uncommenting the fix introduced by #3932 did not solve this issue; the authentication of JGit still failed. It is not clear to me why this is the case, but I assume that there is still some default logic in place.
My idea was to to install a specific JGit `CredentialsProvider` that delegates to the `Authenticator` and fetches the credentials from there. It is then guaranteed that the credentials between ORT and JGit are always in sync.
