### ISSUE TITLE
Support custom Conan repositories

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#4312]
By default Conan expects to find dependencies on [ConanCenter](https://conan.io/center/). However, similar to Maven and NPM, also Conan allows to declare custom / internal artifact repositories via [remotes](https://docs.conan.io/en/latest/uploading_packages/remotes.html). ORT currently does not support these, but it obviously should.

**Comment by sschuberth** [comment]
Some notes to myself:

Running `conan remote add conancenter https://center.conan.io` add the remote to `~/.conan/remotes.json`, but what we'd need is a way to define remotes in the Git repository where the Conan project itself resides.

**Comment by sschuberth** [comment]
Unfortunately, [Conan does not have a built-in mechanism for project-specific configuration (of remotes)](https://github.com/conan-io/conan/issues/9145). 😨 

The most viable work-around seem to be to

1. [export user-global configuration](https://docs.conan.io/en/latest/reference/commands/misc/remote.html#conan-remote) via `conan remote list --raw | cut -d' ' -f-3 > remotes.txt` once and commit `remotes.txt` to the Git repository next to the `conanfile.txt` / `conanfile.py` file,
2. make ORT's `Conan.kt` implementation [run](https://docs.conan.io/en/latest/reference/commands/consumer/config.html#conan-config-install) `conan config install remotes.txt` if `remotes.txt` is present.

**Comment by tthef** [comment]
Just be aware that the workaround installs a global config, i.e., it only works if you have a single such git checkout on the machine, as any other git checkout using this work around will clobber your previous setup. It's a real pain even with just 2 projects with different remotes setup.

**Comment by sschuberth** [comment]
> Just be aware that the workaround installs a global config, i.e., it only works if you have a single such git checkout on the machine

Thanks for the hint. So we probably need to add some logic to save / restore the original global Conan config before / after running `conan config install`...

**Comment by tthef** [comment]
That doesn't really work very well, I think. You can use CONAN_USER_HOME to have each repo to use a different conan cache, but that is suboptimal (my projects share common toolchains, which are 100s of MBs packages), or, if you are able to use full paths in your conan.conf you can set common storage.path in conan.conf as is mentioned early in the other issue, but that doesn't work unless you only build on a single OS and the machine has the same layout). I have not found a good solution to this, other than running 'conan config install' everytime a build is run. It's a poor design.

**Comment by sschuberth** [comment]
> I have not found a good solution to this, other than running 'conan config install' everytime a build is run.

Actually, we're not aiming to *build* anything, but only need to determine the transitive dependency tree of a Conan project (including license meta-data for all dependencies). So my hope is that we'd not to (re-)download any toolchains at all in that case...
