### ISSUE TITLE
Scan-Code (Current Version used by ORT) cannot correctly handle URI redirection from HTTP-Scheme to HTTPS-Scheme

### ISSUE THREAD

**Issue by porsche-rishisaxena** [oss-review-toolkit/ort#4345]
The analysis has shown that the referenced java library artifact has a valid and complete descriptor (pom.xml) stored in the public repos, for example maven central.

The descriptor also contains a valid source repository URI,.

The source repository URI uses the HTTP-Scheme and is pointing towards a public GitHub source repository. When executing a HTTP GET request onto that source URI, the response is a permanent redirection to the source repository URI but with a different protocol scheme, namely HTTPS:

$ curl -iv http://github.com/FasterXML/jackson-annotations

Trying 140.82.121.3:80...
Connected to github.com (140.82.121.3) port 80 (#0)
> GET /FasterXML/jackson-annotations HTTP/1.1
> Host: github.com
> User-Agent: curl/7.76.1
> Accept: /
>
Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
HTTP/1.1 301 Moved Permanently
< Content-Length: 0
Content-Length: 0
< Location: https://github.com/FasterXML/jackson-annotations
Location: https://github.com/FasterXML/jackson-annotations
<

Connection #0 to host github.com left intact
 

The assumption on the root cause is that the scan-code version (3.2.1rc2) used by ORT cannot correctly handle this relocation response but instead logs an error and quits the source artifact retrieval.

Please confirm if the assumption is correct or not?

**Comment by sschuberth** [comment]
Please note that ScanCode itself does not perform any download. If you see the issue happening when running an ORT command, please run the command with at least `--info` and copy & paste the relevant log lines as-is to this report.

**Comment by porsche-rishisaxena** [comment]
It is working now with the latest version of ORT. Porsche was using 3 months older version. 
This issue can be closed.
@sschuberth @rbieniek
