### ISSUE TITLE
Wrong package manager test

### ISSUE THREAD

**Issue by rbieniek** [oss-review-toolkit/ort#4350]
In the test case analyzer/src/test/kotlin/PackageManagerTest.kt the cargo-specific file 'Cargo-.tml' is assigned to 'bundler' but it should probably read 'cargo'

in lines:
- 39: 'bundler/Cargo.toml' should read 'cargo/Cargo.toml'
- 95: 'bundler/Cargo.toml' should read 'cargo/Cargo.toml'

**Comment by sschuberth** [comment]
Thanks for spotting, I've filed a PR to fix this.
