### ISSUE TITLE
Pattern glob expression excludes root file when applied on .ort.yml

### ISSUE THREAD

**Issue by heliocastro** [oss-review-toolkit/ort#4357]
Using Ort master

Applying the following pattern on the below tree results in excluding all but root build.gradle, forcing to add two patterns, one explicitly for root file.
```
 **/build.gradle inside 
```

```bash
testcode
├── app
│   └── build.gradle
└── build.gradle
```

**Comment by sschuberth** [comment]
Maybe this could be solved by using another glob matcher as outlined in my old [plexus-globs](https://github.com/oss-review-toolkit/ort/compare/plexus-globs) branch.

**Comment by mnonnenmacher** [comment]
One more example for the issue: With the pattern "**/examples/**" I would like to match all files below any folder called "examples", but this does not match an examples folder at the root. For this another pattern "examples/**" is required.

The problem for this is that there is no leading "/" for the examples folder at the root. A workaround for this would be to match all paths twice, once as they are, and again prefixed with "./". But using another matcher library where this works out of the box would be the better option. @sschuberth Do you have any plans to revive your branch?

**Comment by sschuberth** [comment]
> I would like to match all files below any folder called "examples", but this does not match an examples folder at the root. For this another pattern `examples/**` is required.

I'm actually surprised about this. I though supporting this was exactly the reason to switch to Spring's `AntPathMatcher` in 9632e0e8cc4d15dd142e7bee3bc59a42c8a37475.

**Comment by sschuberth** [comment]
Ok, I just created #5156 when I realized that the path exclude logic is not using the [FileMatcher](https://github.com/oss-review-toolkit/ort/blob/main/utils/common/src/main/kotlin/FileMatcher.kt) class at all, but its own matcher in [PathExclude](https://github.com/oss-review-toolkit/ort/blob/main/model/src/main/kotlin/config/PathExclude.kt). I'll look into unifying that.

**Comment by sschuberth** [comment]
> I would like to match all files below any folder called "examples", but this does not match an examples folder at the root.

BTW, if `**/examples/**` would match an "examples" folder at the root, which pattern would you then use if you only want to match "examples" directories within a sub-directory, but not at the root level?

**Comment by mnonnenmacher** [comment]
> Ok, I just created https://github.com/oss-review-toolkit/ort/pull/5156 when I realized that the path exclude logic is not using the [FileMatcher](https://github.com/oss-review-toolkit/ort/blob/main/utils/common/src/main/kotlin/FileMatcher.kt) class at all, but its own matcher in [PathExclude](https://github.com/oss-review-toolkit/ort/blob/main/model/src/main/kotlin/config/PathExclude.kt). I'll look into unifying that.

`FindingCurationMatcher` also does not use the `FileMatcher` for `LicenseFindingCuration`s.

> BTW, if **/examples/** would match an "examples" folder at the root, which pattern would you then use if you only want to match "examples" directories within a sub-directory, but not at the root level?

In general I think matching all folders should be the more frequent use case, but something like `*/**/examples/**` should work.

**Comment by sschuberth** [comment]
> In general I think matching all folders should be the more frequent use case, but something like `*/**/examples/**` should work.

I've added #5157 to prove that this indeed works, as it's IMO a requirement, even if it's maybe a less frequent use-case.

So, do we then all agree that with #5157 the `FileMatcherTest` documents the *desired* behavior?
