### ISSUE TITLE
Add support for a graph database

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#4362]
Given the kind of data ORT and esp. the analyzer stores, it seems reasonable to look into storing our data in a graph database instead of a classic key-value database. Historically, [ArangoDB](https://www.arangodb.com/) was proposed, but never really looked into. [This article](https://www.baeldung.com/spring-data-arangodb) reminded me of doing that.

**Comment by sschuberth** [comment]
For the record, here's some [slides](https://www.pgcon.org/2011/schedule/events/357.en.html) on how graphs / trees can be captured also by a Postgres DB.

**Comment by oheger-bosch** [comment]
@sschuberth, I think this depends on concrete use cases. A GraphDB probably makes sense if the results of many ORT runs are combined to collect the data of multiple/all repositories used within a company. Then one could build sophisticated queries on this data. Is this a use case ORT wants to support?

It would also be an option to implement an exporter that is able to insert ORT results in a GraphDB. But this opens the question which concrete data model should be used for this purpose.

**Comment by sschuberth** [comment]
> Is this a use case ORT wants to support?

I'd clearly say yes.

**Comment by sschuberth** [comment]
Maybe also https://github.com/apache/age could become of interest.
