### ISSUE TITLE
Advisor not evaluating config file

### ISSUE THREAD

**Issue by Qkey01** [oss-review-toolkit/ort#4371]
When I tried running the Advisor in the following way:
`docker run -v $PWD:/project ort advise -i <source_file> -o <target_directory> -a VulnerableCode`

the following error message was displayed:
![grafik](https://user-images.githubusercontent.com/71776269/129756671-2a521c69-0376-4546-a93a-d070684f8739.png)

When I tried to fix it, I copied the default config file inside the folder mounted as a volume and added the advisor code provided in the documentation to the file,
 `advisor {
    VulnerableCode {
      serverUrl = "http://localhost:8000"
    }
  }
`

and then tried setting it as the config file with the -c option:
`docker run -v $PWD:/project ort -c /project/ort.conf advise -i <source_file> -o <target_directory> -a VulnerableCode`

I also tried setting the variable via the -P option:
`-P ort__advisor__VulnerableCode__serverUrl="http://localhost:8000`

Both of those didn't work, so I entered the Container through a shell and tried the above manually as well as create the directory and file specified inside the error message with the altered default config file. All of which threw the same single error message.

I then tried to do it natively, but replicating the steps above in a native environment didn't result in any success either. (During the native part I actually started running VulnerableCode on the referenced Port but that still didn't seem to make a difference).

So I probably overlooked something very obvious or something's wrong my PC. Can anyone help?

**Comment by sschuberth** [comment]
Do you have a top-level `ort { ... }` in your `ort.conf`?

**Comment by Qkey01** [comment]
The beginning of my ort.conf looks like this
![grafik](https://user-images.githubusercontent.com/71776269/129853583-20faa878-4d36-431f-82cc-2241ece3e319.png)
with the advisor being the only thing different from the default configuration provided via `docker run ort config --show-default`

I also ran the command with the `debug` option and have some more output, if that helps
![grafik](https://user-images.githubusercontent.com/71776269/129854376-63f0fb4b-c37a-415a-a893-08e9f8dc3237.png)

**Comment by MarcelBochtler** [comment]
The configuration is case sensitive.
You should use `vulnerableCode` instead of `VulnerableCode`.

**Comment by MarcelBochtler** [comment]
The configuration is case sensitive.
You should use `vulnerableCode` instead of `VulnerableCode`.

**Comment by Qkey01** [comment]
Thank you, that fixed it! The ort.conf file now looks like this
![grafik](https://user-images.githubusercontent.com/71776269/129856551-9793d178-5810-4a65-87a9-fceee8fad017.png)

Would be cool if you could change the [documentation](https://github.com/oss-review-toolkit/ort#vulnerablecode) to reflect the case sensitivity :)

**Comment by MarcelBochtler** [comment]
I will fix it. Let's keep this issue open until it is fixed.
