### ISSUE TITLE
Fix extracting the FossID project name from Git URLs

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#4397]
This existing function is buggy:

https://github.com/oss-review-toolkit/ort/blob/e2b6a34e0a029308f63daf75dda4e1b42a846cb0/scanner/src/main/kotlin/scanners/fossid/FossId.kt#L105-L119

It results in something like

    Found project name in 'arc-swap.git' in URL 'https://github.com/vorner/arc-swap.git'.

altought the `.git` suffix should be omitted. I also believe we could simply the function to not use a regex.

**Comment by nnobelis** [comment]
Also create a regression test with various type of Git repo URLs.
Check particularly compatibility with Azure repo URLs e.g.:
https://dev.azure.com/example/_git/project

**Comment by nnobelis** [comment]
If we keep the Regex, a simple solution would be to change the first capturing group to a reluctant quantifier:
`^.*\/([\w.\-]+?)(?:\.git)?$`
