### ISSUE TITLE
Resolve symbolic VCS revisions already in the analyzer

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#4398]
When instructing a remote scanner, like FossID, what to scan, then the exact (resolved) revision needs to be known:

https://github.com/oss-review-toolkit/ort/blob/9fc990ce4a30b81a5d959347166387a2650f535c/scanner/src/main/kotlin/scanners/fossid/FossId.kt#L278-L281

However, not all packages have complete metadata that includes the resolved revision to checkout. This is usually circumvented by the Downloader's `guessRevisionName()`:

https://github.com/oss-review-toolkit/ort/blob/9fc990ce4a30b81a5d959347166387a2650f535c/downloader/src/main/kotlin/WorkingTree.kt#L83-L89

But in the case of a remote scanner, ORT's Downloader is not run at all. That's why already the Analyzer needs to either

* get the exact (resolved) revision from package metadata, or
* resolve a symbolic revision by itself, independently of the Downloader.

To do so, we probably need to reintroduce the `resolvedRevision` property in `VcsInfo` (which was removed in https://github.com/oss-review-toolkit/ort/pull/4132) with different semantics.

**Comment by mnonnenmacher** [comment]
This will be fixed by #4491. The new scanner implementation resolves provenance information for all packages before calling any remote scanners.

**Comment by sschuberth** [comment]
Do you think there's still a use-case to already resolve the provenance information in the analyzer, @mnonnenmacher?

**Comment by mnonnenmacher** [comment]
No, with the current scanner implementation provenance resolution is always performed and the result is available also to remote scanners.
