### ISSUE TITLE
Change color of hints in Scan Report Web App

### ISSUE THREAD

**Issue by hanna-modica** [oss-review-toolkit/ort#4421]
To avoid confusion and improve UX, I would like to have a more distinguishable colors for Warnings and Hints.

Maybe hints can be blue?

![image](https://user-images.githubusercontent.com/40762532/131673946-8cf118b3-9e11-4250-a499-32280391470b.png)

**Comment by sschuberth** [comment]
@tsteenbe the icons now seem to be gone completely as part of the filter:

![image](https://user-images.githubusercontent.com/349154/133992005-0f471001-c835-4fbd-a1e8-2983a5bff543.png)

I guess that's an unwanted side effect?
