### ISSUE TITLE
WebApp console in dev shows AntDesign FilteredKeys Warning

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#4443]
Running yarn start during WebApp development shows `Warning: [antd: Table] 'FilteredKeys' should all be controlled or not controlled.` This warning is due to not controlling each state of antd tables across the WebApp, for example in getColumnSearchProps we do row selection to do column search without doing `store.dispatch()` to update global state.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
