### ISSUE TITLE
GoMod: ORT should respect the `replace` directive

### ISSUE THREAD

**Issue by MarcelBochtler** [oss-review-toolkit/ort#4445]
As described in this draft PR: https://github.com/oss-review-toolkit/ort/pull/4435

ORT does not respect the `replace` directive as it should.
Using a `go.mod` file like this:

```
module github.com/oss-review-toolkit/ort/gomod-synthetic-test-project

go 1.13

require (
	github.com/fatih/color v1.7.0
	github.com/hashicorp/go-multierror v1.0.0 // indirect
	github.com/mattn/go-colorable v0.1.4 // indirect
	github.com/mattn/go-isatty v0.0.10 // indirect
	golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421 // indirect
	rsc.io/quote/v3 v3.1.0
)

replace rsc.io/quote/v3 => rsc.io/quote/v3 v3.0.0
```

Will still end up with `rsc.io/quote/v3 v3.1.0` listed in ORT's result file.

The reason for this is because `go mod vendor -v` and `go mod graph` is being used to find the dependencies.
Like @tsteenbe mentioned (https://github.com/oss-review-toolkit/ort/issues/3934#issuecomment-852299217), I think the correct solution would be to use `go list -deps -json ./...` to determine the dependencies, which might also enable us to remove the usage of `go mod why`.

**Comment by msukhotin** [comment]
There is also a GoMod related issue with multiple version packages.
Consider a go.mod file with the following lines in `require ` section:

```
github.com/cespare/xxhash v1.1.0 // indirect
github.com/cespare/xxhash/v2 v2.1.1 // indirect
```

The second one raises the error like:
```
Using scanner 'ScanCode'.
15:33:09.926 [main] ERROR org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode - Could not download 'GoMod::github.com/cespare/xxhash/v2:v2.1.1': DownloadException: Download failed for 'GoMod::github.com/cespare/xxhash/v2:v2.1.1'.
Suppressed: DownloadException: The Git working directory at '/var/folders/7j/7j53fywn1cs_gdgyp1m16k200000gn/T/ort-ScanCode1836334266063099117/GoMod/unknown/github.com%2Fcespare%2Fxxhash%2Fv2/v2.1.1' does not contain the requested path 'v2'.
Suppressed: DownloadException: No source artifact URL provided for 'GoMod::github.com/cespare/xxhash/v2:v2.1.1'.
```

Could the described above solution address this issue as well?
