### ISSUE TITLE
Show line count for scan results in web app reporter

### ISSUE THREAD

**Issue by hanna-modica** [oss-review-toolkit/ort#4458]
The scan-report-web-app.html shows detected licenses with start and end line:

![image](https://user-images.githubusercontent.com/40762532/133233647-9511e295-df26-4909-8a62-5a4fd10cc0fe.png)

However, for a [package configuration](https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-package-configuration-yml.md) a start line and the line count is required. To lower the possibilities for errors when writing a package configuration, I would like to have a column with the line count.

**Comment by tsteenbe** [comment]
@hanna-modica Propose not to fix this in the UI but show needed package configuration in the how to fix text - do not want to add UI element for each subpart of package configuration or curation as this would bloat the UX.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
