### ISSUE TITLE
Think about a better name for the `RepositoryConfiguration` class

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#4466]
While the class is named *Repository*Configuration, it is actually documented to apply to *projects*:

https://github.com/oss-review-toolkit/ort/blob/7bb799be242fb0f51cbffc748abab3873063dfc1/model/src/main/kotlin/config/RepositoryConfiguration.kt#L26-L30

In general, the class should probably named after the entity the configuration *applies* to, not after where it is *stored*.

Please add some proposals for a better name to this issue. To start with, here are some ideas from the ORT developer meeting:

(See below, in separate comments each, so people can vote via reaction on the comment.)

**Comment by sschuberth** [comment]
ProjectConfiguration

**Comment by sschuberth** [comment]
OrtResultConfiguration

**Comment by sschuberth** [comment]
DistributionConfiguration

**Comment by sschuberth** [comment]
ModuleConfiguration

**Comment by sschuberth** [comment]
ProductConfiguration

**Comment by fviernau** [comment]
ArtifactConfiguration

**Comment by fviernau** [comment]
ReleaseArtifactConfiguration

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
