### ISSUE TITLE
Trying to create a docker build: Unknown flag: mount

### ISSUE THREAD

**Issue by alex4200** [oss-review-toolkit/ort#4467]
I tried to create a docker build for the cloned version 7bb799b, but when I use the described command I get the following output:

```
$ docker build -t ort .
Sending build context to Docker daemon  18.51MB
Error response from daemon: Dockerfile parse error line 39: Unknown flag: mount
```

Is this a known issue?

**Comment by sschuberth** [comment]
Sounds like you didn't enable BuildKit as mentioned [here](https://github.com/oss-review-toolkit/ort#build-using-docker), did you?

**Comment by sschuberth** [comment]
Closing this as @alex4200 [mentioned](https://github.com/oss-review-toolkit/ort/issues/4471#issuecomment-926483121) ORT "is probably not for me", and as such probably does not plan to provide more info on this issue.
