### ISSUE TITLE
Resolving DotNet dependencies for 'xxx.csproj' failed with: JsonParseException

### ISSUE THREAD

**Issue by joergmetzler** [oss-review-toolkit/ort#4522]
Hi,

I'm trying to scan my code.
The code is written in C# and contains a packages.config next to the .csproj file.
When the package dependencies are resolved, the following message occours.
The package feed itself is hosted in the nexus server and serves a nuget-feed v2.

```json
{
    "timestamp": "2021-09-30T11:34:18.902188Z",
    "source": "DotNet",
    "message": "Resolving DotNet dependencies for 'xxx.csproj' failed with: JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (String)\"<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?>\n<service xml:base=\"https://nuget.xxx.intern/Nexus/repository/nuget-xxx-release-5-8/\" xmlns:atom=\"http://www.w3.org/2005/Atom\" xmlns:app=\"http://www.w3.org/2007/app\" xmlns=\"http://www.w3.org/2007/app\">\n  <workspace>\n    <atom:title>Default</atom:title>\n    <collection href=\"Packages\">\n      <atom:title>Packages</atom:title>\n    </collection>\n  </workspace>\n</service>\n\"; line: 1, column: 2]",
    "severity": "ERROR"
}
```

Best regards,

Jörg

**Comment by sschuberth** [comment]
Can you share your plain contents of the `csproj` file? Does it maybe contain some placeholders that are expanded as part of your build process as part of some preprocessing?

**Comment by joergmetzler** [comment]
Hi Sebastian,

thanks for the quick response.
I attached (a trimmed) version of my .csproj and packages.config.
The file contents a very close to the original. Internal names were replaced with xxx.
I guess no magic placeholders are used except of the common ones like $(Configuration) etc.

Thanks for your help,

Jörg

[csproj_and_packages.zip](https://github.com/oss-review-toolkit/ort/files/7261592/csproj_and_packages.zip)

**Comment by sschuberth** [comment]
I don't yet know why and how exactly, but my gut feeling is that the problem is related to the BOM header in your files...

**Comment by sschuberth** [comment]
This might be related: https://issues.sonatype.org/browse/NEXUS-10886. So, which version is your Nexus repository server? If it's at least version 3.25.0 it should be able to send JSON responses.

**Comment by joergmetzler** [comment]
We use the version 3.26.1-02.
The Nexus server can host NuGet v2 and NuGet v3 feeds.
We use the v2 protocol version in our project. The upgrade to v3 is planned for our next release.
I try to modify the nuget.config in our current version and give you feedback if it works.

**Comment by joergmetzler** [comment]
Ok, the results are back for v3.
The following url is used by ort: https://nuget.softwarehelden.intern/Nexus/repository/nuget-xxx-release-5-8/v3/registration
But my Nexus server does not implement the /v3/registration.
I try to update to the latest version over the weekend.

Maybe the issue NEXUS-25801will fix my problem.
https://help.sonatype.com/repomanager3/release-notes/2020-release-notes

**Comment by sschuberth** [comment]
@joergmetzler, DotNet / NuGet has been completely rewritten as part of https://github.com/oss-review-toolkit/ort/pull/6209. Please try again and reopen if the problem persists.
