### ISSUE TITLE
No relationship for SPDXRef-Package-Saxon in project.spdx.yml

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#4529]
See https://github.com/oss-review-toolkit/ort/blob/master/analyzer/src/funTest/assets/projects/synthetic/spdx/project/project.spdx.yml#L53-L67 it defines  SPDXRef-Package-Saxon but there is no relationship defined between it an `SPDXRef-Package-xyz`

**Comment by sschuberth** [comment]
Maybe that's not a bug, but a way to check in our tests that packages without relations do not show up in the dependency tree? @neubs-bsi do you recall?

**Comment by neubs-bsi** [comment]
Yeah, that was intentional, as @sschuberth described. Before, all packages were used in dependency tree, regardless of having a relationship or not.
