### ISSUE TITLE
Private github repos

### ISSUE THREAD

**Issue by martencassel** [oss-review-toolkit/ort#4539]
It might be helpful to inform people in the guide some hints on setting up private repos such as github using the docker container.

```bash
git config --global url."https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com".insteadOf /"https://github.com"
ls -l ~/.gitconfig
```

```bash
docker run -e -v $(pwd):/project \
	   -v ~/.gitconfig:/root/.gitconfig \
            ort:latest --info analyze -f JSON -i /project -o /project/ort/analyzer
 ```

**Comment by sschuberth** [comment]
Pull requests to improve [hints-for-use-with-docker.md](https://github.com/oss-review-toolkit/ort/blob/master/docs/hints-for-use-with-docker.md#authenticating-with-a-private-git-repository-fails) are very welcome!

**Comment by martencassel** [comment]
https://github.com/oss-review-toolkit/ort/pull/4559/files

**Comment by sschuberth** [comment]
Thanks. Please link your PR to this issue by amending the commit message as described [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
