### ISSUE TITLE
How to get a license dependency tree for a repo?

### ISSUE THREAD

**Issue by alex4200** [oss-review-toolkit/ort#4551]
How can I use ORT to get a licence dependency tree for a given repo? 

I want to investigate a certain github repository, and find all the modules/repos that repo depends on, and find all their licenses in an iterative way. By using the information in setup.py etc. 

How can I achieve that? How must I configure and run ORT?

**Comment by mnonnenmacher** [comment]
Hi @alex4200, please have a look at the [getting started guide](https://github.com/oss-review-toolkit/ort/blob/master/docs/getting-started.md), it describes what you are asking for. Also have a look at the [README](https://github.com/oss-review-toolkit/ort/blob/master/README.md) and the [docs folder](https://github.com/oss-review-toolkit/ort/tree/master/docs) in general.

**Comment by alex4200** [comment]
@mnonnenmacher In the README Isuggest you emphasize to a newcomer he/she HAS TO run the COMPLETE examples. Otherwise you will get the same issues over and over again!
