### ISSUE TITLE
Analyzer for Python returns error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by alex4200** [oss-review-toolkit/ort#4578]
Upon trying to run the analyzer on a project, I get an error 

```
   ....
    gcc: fatal error: cannot execute ?cc1plus?: execvp: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

two times. Is that a known issue? I though the analyzer works only passive?

I did run the command 

docker run -v ${PROJECT}:/project -v ${PWD}/output:/output ort --force-overwrite --info analyze -i /project -o /output/analyze_mime

where PROJECT points to a folder `BluePyOpt`, checked out with `git clone https://github.com/BlueBrain/BluePyOpt.git`.

Let me know any further information that are helpful to solve this problem

**Comment by alex4200** [comment]
Is there any workaround I can apply?

**Comment by sschuberth** [comment]
The only work-around I can think of is to install `gcc` (and any subsequently missing development library) on the system running ORT.

**Comment by alex4200** [comment]
Thanks, the workaround (installing gcc) did actually work for me. 
I had to install the following packages for the docker image to get things work: 

`gcc g++ python3-dev python3-pip libxml2-dev libxslt1-dev zlib1g-dev`

**Comment by sschuberth** [comment]
Reopening as #4637 now actually is a epic that refers to this issue.

**Comment by mnonnenmacher** [comment]
I assume the gcc error happens during `pip install`, so this could be closed as we don't run `pip install` anymore.

**Comment by sschuberth** [comment]
> I assume the gcc error happens during `pip install`, so this could be closed as we don't run `pip install` anymore.

@alex4200 could you verify this please with the latest ORT version?

**Comment by heliocastro** [comment]
This happens when a package is not available on specific abi on machine, so it calls wheel module to compile the native "binding".
Even not been used anymore with python-inspector, this could become an issue if we do need specific arch install.
So, in the end we need set a basic devel environment on the executor. Today's docker we don't have gcc enabled on the runner image

**Comment by sschuberth** [comment]
> checked out with `git clone https://github.com/BlueBrain/BluePyOpt.git`.

I've verified that this works now with the latest ORT that uses `python-inspector`.
