### ISSUE TITLE
Make versions of local scanners configurable

### ISSUE THREAD

**Issue by oheger-bosch** [oss-review-toolkit/ort#4582]
So far, for local scanners, ORT has the specific version it supports hard-coded; if a different version of the scanner is installed on the system, it is not accepted, but ORT tries to bootstrap this exact version (see https://github.com/oss-review-toolkit/ort/blob/4ab3679b1b654ab00953224e2c52b3f34a32b377/scanner/src/main/kotlin/LocalScanner.kt#L119).

This behaviour is rather strict, and it complicates updates to newer scanner versions (e.g. refer to #4296). To be more flexible, ORT could support setting the accepted scanner version (or even a version range) in the scanner configuration. For instance, for ScanCode, this could look as follows:

```
  scanner {
     ...
      ScanCode {
        commandLine = "--copyright --license --info --strip-root --timeout 300 --max-in-memory 5000"
        parseLicenseExpressions = true
	minVersion = 3.2.1
	maxVersion = 22.1.1
     }
   ...
}

```
_Note_: The properties _minVersion_ and _maxVersion_ are currently already used to configure the accepted versions when loading results from the scan result storage; so they would have to be renamed.

The `expectedVersion` hard-coded in ORT could be kept and used as default value if no version is configured for a scanner; this would also be the version that gets bootstrapped.

**Comment by sschuberth** [comment]
Closing this in favor of the even more relaxed approach in https://github.com/oss-review-toolkit/ort/pull/4669, which accepts any scanner version already installed on the host, but informs about a version mismatch.
