### ISSUE TITLE
invalid path handling: ort fails creating dirs with ':' on windows

### ISSUE THREAD

**Issue by mach-nf** [oss-review-toolkit/ort#4587]
I just started to get into ort and I'm failing at first stage with analyze of the internal project due to several exceptions.
ort was started on windows CMD with
   `ort.bat analyze -i \workspace\git-repos\mach -o mach-ort-analyzer`
and on git-bash
  `./ort analyze -i /d/workspace/git-repos/mach -o mach-ort-analyzer2`

> 10:37:53.729 [DefaultDispatcher-worker-3] WARN  org.eclipse.aether.internal.impl.TrackingFileManager - Failed to create parent directories for tracking file C:\Users\nf\.m2\repository\de\mach\commons\machweb-commons-interface\develop-SNAPSHOT\maven-metadata-file:\d:\workspace\.m2\repository\resolver-status.properties
> 10:37:53.731 [DefaultDispatcher-worker-3] WARN  org.eclipse.aether.internal.impl.TrackingFileManager - Failed to create parent directories for tracking file C:\Users\nf\.m2\repository\de\mach\commons\machweb-commons-interface\develop-SNAPSHOT\maven-metadata-https:\nexus.mach.de\repository\resolver-status.properties
> 10:37:53.733 [DefaultDispatcher-worker-3] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenLogger - Could not transfer metadata de.mach.commons:machweb-commons-interface:develop-SNAPSHOT/maven-metadata.xml from/to file:/d:/workspace/.m2/repository/ (file:/d:/workspace/.m2/repository/): C:\Users\nf\.m2\repository\de\mach\commons\machweb-commons-interface\develop-SNAPSHOT\maven-metadata-file:\d:\workspace\.m2\repository\.xml.part.lock (Die Syntax f▒r den Dateinamen, Verzeichnisnamen oder die Datentr▒gerbezeichnung ist falsch)
> org.eclipse.aether.transfer.MetadataTransferException: Could not transfer metadata de.mach.commons:machweb-commons-interface:develop-SNAPSHOT/maven-metadata.xml from/to file:/d:/workspace/.m2/repository/ (file:/d:/workspace/.m2/repository/): C:\Users\nf\.m2\repository\de\mach\commons\machweb-commons-interface\develop-SNAPSHOT\maven-metadata-file:\d:\workspace\.m2\repository\.xml.part.lock (Die Syntax f▒r den Dateinamen, Verzeichnisnamen oder die Datentr▒gerbezeichnung ist falsch)
> 
> 10:37:53.743 [DefaultDispatcher-worker-3] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenLogger - Could not transfer metadata de.mach.commons:machweb-commons-interface:develop-SNAPSHOT/maven-metadata.xml from/to https://nexus.mach.de/repository/maven-public (https://nexus.mach.de/repository/maven-public): C:\Users\nf\.m2\repository\de\mach\commons\machweb-commons-interface\develop-SNAPSHOT\maven-metadata-https:\nexus.mach.de\repository\maven-public.xml.part.lock (Die Syntax f▒r den Dateinamen, Verzeichnisnamen oder die Datentr▒gerbezeichnung ist falsch)
> org.eclipse.aether.transfer.MetadataTransferException: Could not transfer metadata de.mach.commons:machweb-commons-interface:develop-SNAPSHOT/maven-metadata.xml from/to https://nexus.mach.de/repository/maven-public (https://nexus.mach.de/repository/maven-public): C:\Users\nf\.m2\repository\de\mach\commons\machweb-commons-interface\develop-SNAPSHOT\maven-metadata-https:\nexus.mach.de\repository\maven-public.xml.part.lock (Die Syntax f▒r den Dateinamen, Verzeichnisnamen oder die Datentr▒gerbezeichnung ist falsch)

The char ':' is invalid on Windows and should be stripped from paths.
Is there any workaround (besides running on Linux)?

**Comment by sschuberth** [comment]
Closing this due to a lack of feedback.
