### ISSUE TITLE
Path excludes use case / feature clarification 

### ISSUE THREAD

**Issue by porsche-rbieniek** [oss-review-toolkit/ort#4589]
We are trying to understand the intended use case for path exlcudes in package configuration data

In our example here

id: "Pod:Firebase:CoreOnly:6.14.0"
vcs:
  type: "Git"
  url: "https://github.com/firebase/firebase-ios-sdk.git"
  revision: "20ab31fe130e9a1d22a75b35ba7046cfba0e5a47"
path_excludes:
  - pattern: "test/**"
    reason: "TEST_OF"
    comment: "This directory contains tests which are not distributed."
  - pattern: "CONTRIBUTING.md"
    reason: "OTHER"
    comment: "CONTRIBUTING.md not included in final product"
  - pattern: "scripts/**"
    reason: "OTHER"
    comment: "scripts not included in final product"

we try to exclude cerrtain subdirectories of a dependency form being processed at all.

After having the dependency fully processed through the ORT process pipeline, we figured that the subdirectories have been processed instead of being ignored.

Could you please explain how these path excludes are intended to be used.

**Comment by sschuberth** [comment]
Nothing is every being really ignored in ORT, for transparency reasons and reproducibility. The exclusion mechanism is used "mark" something as excluded. That is, findings from excluded paths will still show up, but are being visualized differently in the reports.

**Comment by mnonnenmacher** [comment]
There is a short documentation of path excludes for packages here: https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-package-configuration-yml.md#defining-path-excludes-and-license-finding-curations

The important bit is that path excludes in package configurations tell ORT that certain files in the source code are not distributed as part of the package and license findings in those files can be ignored. Like @sschuberth said, they will be shown differently in the reports (if at all). They will also not be passed to the evaluator rules.

Another reason why ORT still scans those files is that this allows to change the package configuration without having to scan the package again.

@porsche-rbieniek I hope this answers your question.
