### ISSUE TITLE
Improve ORT's general ways of working

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#4629]
Creating this ticket as a follow up to the [2021-10-21 ORT developer meeting](https://github.com/oss-review-toolkit/ort/wiki/Developer-Meeting#2021-10-21)

**Issues raised**
- Breaking changes are merged, and not properly documented
- Lack of transparency outside of core contributors Bosch and HERE core: What being worked on, what's next, why certain things are implemented in the way they are.

**Proposal**
Create working group with 3-4 people e.g. 1  per company to draft a document with "ways of working on ORT" to work out below initial ideas discussed in the meeting:
 
- Align on what is the expected behavior of ORT.
- Create principles and architecture document as commit messages/code comment do not document the "bigger picture".   
- Document what is planned to implemented and the things that won't (and in include the why). For the things where ORT TSC says "won't implement" we need to have a light-weight process that any ORT users can request a reconsideration of a past decision
- Set up light weight process to align on common roadmap e.g. dedicated roadmap meetings?
- Create a light weight "checklist" process for all non-trivial PRs, something like
   - Is the proposed change document in an issue?
   - Was is the change discussed in ORT developer meeting and were participants / ORT users given at least X time to give their input?
- Improve documentation regarding the "unspoken functionality" e.g. advisor, evaluator and some of the reporters lack docs.
- Create and maintain a change log so it easier for all ORT users to assess the impact / action required when they upgrade to a newer version of ORT.

**Comment by sschuberth** [comment]
I still believe we should start lightweight and address what's IMO the most pressing need: A clearer communication about what the core contributors at Bosch and HERE *plan* to work on (without any promises being made).

Therefore, I propose to delete @tsteenbe's [old project board](https://github.com/oss-review-toolkit/ort/projects/1), and to create a new roadmap (similar to [GitHub's](https://github.com/orgs/github/projects/4247)) using the new projects boards. Actually, to start with maybe separate roadmaps per contributing party would make sense to express and share a specific company's priorities, and we could later thing about creating a combined general roadmap from it.

For testing, I've started to create something [here](https://github.com/orgs/oss-review-toolkit/projects/3/views/1).

**Comment by sschuberth** [comment]
Some updates from today's backlog grooming session:
- Regarding breaking changes and missing change logs, we by now that proper SemVer-ed [releases](https://github.com/oss-review-toolkit/ort/releases).
- Regarding transparency of core contributors and future plans, we have a [public roadmap](https://github.com/orgs/oss-review-toolkit/projects/3) that everyone from the community is invited to participate in.
- Regarding checklists for issues / PRs, we now have issue templates and improved PR checks.

That said, there's basically nothing left in this issue that goes beyond the [other documentation issues](https://github.com/oss-review-toolkit/ort/issues/7793) we have, so I'm closing this.
