### ISSUE TITLE
Making a web application of ort

### ISSUE THREAD

**Issue by sameer1046** [oss-review-toolkit/ort#4641]
Can we have a web app of ort in future with all configuration in the app UI itself and as a docker based microservices for each agents.
Just thinking about it.

**Comment by sschuberth** [comment]
> with all configuration in the app UI itself

We'll never add ready-to-use configuration to ORT distributions in order to not give any legal advice, which might get us into trouble as we're developers, not attorneys.

> docker based microservices for each agents.

But something like that is going to happen, we're actively thinking about the design of an ORT server with frontend & backend.

**Comment by sschuberth** [comment]
Closing this in favor of the new epic at https://github.com/oss-review-toolkit/ort/issues/4688.
