### ISSUE TITLE
Make `severeIssueThreshold` only apply to `OrtIssue`s, not to `RuleViolation`s

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#4642]
> Is `OrtConfig.severeIssueThreshold` actually referring to just `OrtIssue`, not to `RuleViolation`?

Now that you name it, I have to agree that the name "severe*Issue*Threshold" is misleading. When I introduced that configuration option, I did not intent to limit it to issues / the `OrtIssue` class, but apply it to anything that has a `Severity` (I probably was under the misbelief that `RuleViolation` inhertis from `OrtIssue`).

That's why even for the Evaluator, which creates no `OrtIssue`s at all but only `RuleViolation`s, we currently have this code:

https://github.com/oss-review-toolkit/ort/blob/42845fa5eb5fbb1a9bc617aa778c2979ca0da26d/cli/src/main/kotlin/commands/EvaluatorCommand.kt#L304-L305

However, we also had already internal discussion about the multiple ways now to tweak the effect of a severity for rule violations: Either by changing the emitted `Severity` in the `rules.kts` directly, or by altering the `severeIssueThreshold`, and how this all should refer to the exit code of the Evaluator.

I guess we need some more brainstorming here.

_Originally posted by @sschuberth in https://github.com/oss-review-toolkit/ort/pull/4454#discussion_r707358332_

**Comment by sschuberth** [comment]
My initial reaction was the same as @mnonnenmacher's he [wrote](https://github.com/oss-review-toolkit/ort/pull/4640#discussion_r740184227):

> I think it would be better to have a separate `severeRuleViolationThreshold`, but let's wait for the outcome of the dicussion in the dev meeting.

But that would give user two knobs to turn how to deal with severities of rule violations, first the rules themselves, and second the threshold, which raises the question why not simply change the severity in the rules, if desired.

**Comment by fviernau** [comment]
> why not simply change the severity in the rules, if desired.

To me that translates to aligning the semantics of rule violations severity with the semantics of issue severity.
It may be undesired, e.g. I could imagine use cases like:
1. issues warnings are must fix, rule violation warnings are optional to fix.
2. issues warnings are nice to have fixed, rule violation warnings should not be fixed.

**Comment by mnonnenmacher** [comment]
> But that would give user two knobs to turn how to deal with severities of rule violations, first the rules themselves, and second the threshold, which raises the question why not simply change the severity in the rules, if desired.

Similar to what Frank wrote you might not want to make the configuration for issues and rule violations depend on each other. E.g. if you change `severeIssueThreshold` to `HINT` there is no way any more to have rule violations that do not have to be fixed, or in general, if you change the `severeIssueThreshold` you might have to adapt the severities for all your rules to still work as intended.

**Comment by sschuberth** [comment]
> Similar to what Frank wrote you might not want to make the configuration for issues and rule violations depend on each other.

I agree to that. But what I meant was: We could also have *neither* `severeIssueThreshold` *nor* `severeRuleViolationThreshold` apply to the severity of rule violations, but hard-code to always set a non-zero exit code in the evaluator if a violation with a severity > hint is reported. And if the user also would not want warnings to change the exit code, all rules with warnings would need to be changed to errors. So, do we want *that*, or do we want the `severeRuleViolationThreshold`? My understanding from the last ORT dev meeting was that we want `severeRuleViolationThreshold`...
