### ISSUE TITLE
Evaluator performance regression

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#4684]
Depending on the project the evaluator execution time increased by about 150% to 250% between 2021-08-19 and 2021-09-03.
This matches the time when the analyzer result switched from the legacy dependency representation to the dependency graph, so it might be related. For larger projects I observed execution times of 35+ minutes. 

This tremendously increases the feedback cycle for making changes to the configuration and thus negatively affects scan support work.

**Comment by sschuberth** [comment]
Can you still reproduce the issue @fviernau, or can we close this?

**Comment by fviernau** [comment]
@sschuberth this was reproducible with any larger ORT file and as there haven't been much changes in the dependency graph I guess this is still valid. Shall we keep it open to at least have some reminder on where to look for performance gains / problems?
