### ISSUE TITLE
CycloneDx report generation fails (VcsInfo cannot be found)

### ISSUE THREAD

**Issue by js-dot** [oss-review-toolkit/ort#4685]
### Versions
Ort version (commit-hash): `31790fd33e35c71c7108eb27c52de7e1542b68ab`

### How to Reproduce
Command: `docker run -v /home/dev/Downloads/infra-installer/:/project ort --debug --stacktrace report -f CycloneDx -i /project/ort/analyzer/analyzer-result.json -o /project/ort/reporter`

### Error
Log (including stacktrace): https://gist.github.com/js-dot/d99a067de9861baab52d9f59e25e70f8
analyzer-result.json (adapted / removed company-internal components; however, I can still reproduce): https://gist.github.com/js-dot/3bd566ce9945ddbfd3fc473e78b9a52a

**Comment by sschuberth** [comment]
Did you by any chance analyze source code from a local directory that is not under version control?

**Comment by sschuberth** [comment]
While there was no response from @js-dot, I assume the underlying issue to be the same as https://github.com/oss-review-toolkit/ort/issues/2896, so I'm closing this as a duplicate.
