### ISSUE TITLE
Problem with package name generation for Conan <-> SPDX roundtrips

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#4744]
When analyzing a Conan project and exporting the BOM to SPDX via the `SpdxDocumentReporter`, the SPDX package name gets constructed as

https://github.com/oss-review-toolkit/ort/blob/15904def7c33d3973b295ddcf9f77fbe2401e2ae/reporter/src/main/kotlin/reporters/spdx/SpdxDocumentModelMapper.kt#L204

However, when then reusing this SPDX output as the input in a new analyzer run using the `SpdxDocumentFile` "package manager", ORT fails to construct an `Identifier` from the SPDX package name as it contains colons

https://github.com/oss-review-toolkit/ort/blob/15904def7c33d3973b295ddcf9f77fbe2401e2ae/model/src/main/kotlin/Identifier.kt#L88-L91

In general, it seems to be fine for [SPDX package name](https://spdx.github.io/spdx-spec/package-information/#71-package-name-field) to contain colon, so we should support that.

Additionally, the question is we really need ORT's `type` and `namespace` as part of the package name, as these can be determined from the PURL in a more defined manner.

**Comment by maxhbr** [comment]
From discussions in slack: https://ort-talk.slack.com/archives/C9NNJ54B1/p1637702480109400
