### ISSUE TITLE
Extend Sonatype Lift with ORT

### ISSUE THREAD

**Issue by jlstephens89** [oss-review-toolkit/ort#4762]
Awesome to see ORT using Sonatype Lift! 

Lift is a way to deploy tools across multiple repositories without having to configure that tool for each repo and it also supports custom tools. You could experiment with adding ORT to Lift if you’re interested https://help.sonatype.com/lift/extending-lift. That might be a low-friction way to roll ORT out to GitHub users (i.e. install Lift + add ORT configuration). 

Let us know if you need any help!

**Comment by sschuberth** [comment]
Thanks for the idea! That could be a sneaky way to get [GitHub integration](https://github.com/oss-review-toolkit/ort/issues/3512) for free 😉

**Comment by jlstephens89** [comment]
Ha yea. That's one of the reasons we designed Lift to be extensible. It allows projects to install one thing to get multiple analyses rather than having to install and maintain multiple tools.

**Comment by sschuberth** [comment]
Closing, as Lift was [sunsetting on August 12, 2023](https://community.sonatype.com/t/sunset-notice-sonatype-lift/10940).
