### ISSUE TITLE
Create a repository for `curations`

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#4778]
Setup a separate repository for `PackageCurations`.

Consider the use cases:
- packaging a set of default curations with ORT
- sharing globally valid curations across organizations

Think about different risk profiles of curations:
- how correct / risky should the curations be
- should the curations for different risk appetites be separated

Best practices / commit guidelines:
- It seems important to agree upfront on best practices / commit guidelines, thinking about rules of thumb like prefer excludes over license finding curations, in which case to use package configuration vs. package concluded license and so forth.

File layout: 
- agree upfront on a file / directory layout

Setup a basic PSV

**Comment by mnonnenmacher** [comment]
The repository has been created with an initial set of package curations:
https://github.com/oss-review-toolkit/ort-config

I will close this ticket in favor of creating specific issues in the other repository if required.
