### ISSUE TITLE
cli: Add an `--json` option to the command `ort requirements`

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#4835]
Output a JSON file containing the actual used version of each tool.

Use case:
- Parse the versions used from a script
- (In order to store them long term along with all other scan parameters)

**Comment by sschuberth** [comment]
Could you please add a use-case to the issue description?

**Comment by sschuberth** [comment]
> I think I'd prefer to solve #4161 and further populate the [`Environment`'s `toolVersions`](https://github.com/oss-review-toolkit/ort/blob/fcdf3cb76c300fa6436d4fbda277df2b927636aa/utils/core/src/main/kotlin/Environment.kt#L65) that already ends up in the `OrtResult`.

@fviernau, would you agree to close this in favor of that proposal?

**Comment by mnonnenmacher** [comment]
@fviernau FYI reactions don't trigger notifications, so I'll close this in case @sschuberth misses the reaction.
