### ISSUE TITLE
PIP: Support "sanitized" project names

### ISSUE THREAD

**Issue by haikoschol** [oss-review-toolkit/ort#485]
[The Python Packaging Guide](https://python-packaging-user-guide.readthedocs.io/specifications/core-metadata/#name) specifies what characters can be used in the `name` field in setup.py. For some illegal characters (e.g. spaces), setuptools does not throw an error, but replaces them with dashes during installation.

The analyzer uses `pydep`, which hooks `setup()` and captures it's keyword arguments verbatim. Therefore it fails when searching for the original name in the output of `pipdeptree`.

**Comment by haikoschol** [comment]
Eventually we want to remove `pydep` (and `pipdeptree`). One approach would be to run `python setup.py egg_info` and parse the resulting metadata file.

**Comment by sschuberth** [comment]
> The analyzer uses `pydep`, which hooks `setup()` and captures it's keyword arguments verbatim.

`pydep` is not used anymore as of e235259c0324dc4d046f23d9780207c8125e3645, so I'm closing this.
