### ISSUE TITLE
reports: UI inconsistency for packages which are not assigned to any scope or project

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#4865]
StaticHtml: doesn't show the package at all, only related issues or violations
WebApp: Package appears in the package list as excluded package

**Comment by mnonnenmacher** [comment]
I don't know any scenario where the package list should contain a package that is not a dependency of any project. Is the underlying issue a bug in a package manager implementation?

**Comment by fviernau** [comment]
I filed it in the context of https://github.com/oss-review-toolkit/ort/pull/4837. So, in this case it was a bug in the package manager.
For GoMod this cannot happen anymore. I'm not sure if this should always be considered a bug, also for third-party package manager implementations. But I'd tend to agree that it could be considered a bug.

I also recall the related issue https://github.com/oss-review-toolkit/ort/issues/4095.
