### ISSUE TITLE
Collect requirements for an ORT server backend API

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#4870]
This issue should collect use-cases and concrete suggestions for (REST) API endpoints that should exist in an ORT server.

**Comment by sameer1046** [comment]
@sschuberth Thanks.
As per my idea, The ORT analyzer should run in CI pipeline which will produce the analyzer result file. This file should be send over rest api to ORT server for further analysis.

In ORT server the downloader agent should start processing the analyzer result and that result should be passed to the scanner agent. The scanner agent will analyse the downloaded components and store the results in database. This results should be reviewed by a reviewer in a SPA UI. The functionality of advisor agent, analyser agent and notifier agent will be available in the UI.

**Comment by JadenFurtado** [comment]
Hey, I would like to contribute to this project. Would Flask be a good fit for the APIs?

**Comment by sschuberth** [comment]
> Would Flask be a good fit for the APIs?

You mean [Python's Flask](https://palletsprojects.com/p/flask/)? IMO that would not be a good fit, as we'd prefer something JVM-native, i.e. a Java or (yet better) Kotlin framework. So far it seems our favorite would be [Ktor](https://ktor.io/), but we'll soon have a TSC meeting where Bosch is planning to share some updates.

But anyway this issue is not supposed to deal with the concrete framework choice, but the REST API endpoints that should be implemented via the framework.

**Comment by JadenFurtado** [comment]
>  IMO that would not be a good fit, as we'd prefer something JVM-native, i.e. a Java or (yet better) Kotlin framework.

Right, I got it.

> But anyway this issue is not supposed to deal with the concrete framework choice, but the REST API endpoints that should be implemented via the framework.

Yup, I just saw that issue #4687 was opened to deal with the framework choice. Sorry, I didn't see it then.

**Comment by sschuberth** [comment]
> This issue should collect use-cases and concrete suggestions for (REST) API endpoints that should exist in an ORT server.

This has actually been done mostly Bosch-internally. Is there something you can share here @mnonnenmacher?

**Comment by mnonnenmacher** [comment]
@sschuberth I have added the [presentation](https://github.com/oss-review-toolkit/ort/files/11832813/ORT.Server.-.ORT.Community.Day.pdf) to the [ORT Community Day wiki page](https://github.com/oss-review-toolkit/ort/wiki/ORT-Community-Day).
