### ISSUE TITLE
Path excludes of package configurations in repository configuration should be array in JSON Schema

### ISSUE THREAD

**Issue by mmurto** [oss-review-toolkit/ort#4874]
Path excludes should probably be an array of items instead of items; VSCode gives errors on this but the path excludes work.

https://github.com/oss-review-toolkit/ort/blob/7a57798fa4111277480266bd7b6fef19826643a2/integrations/schemas/repository-configuration-schema.json#L258-L276

**Comment by mnonnenmacher** [comment]
@MarcelBochtler Could you have a look at this?
