### ISSUE TITLE
Support for cyclonedx 1.3

### ISSUE THREAD

**Issue by mawl** [oss-review-toolkit/ort#4888]
Hey,

cyclonedx is already on 1.3 https://cyclonedx.org/news/cyclonedx-v1.3-released/

Are there plans to upgrade your reporter? This is in your sbom:

`<bom serialNumber="..." version="1" xmlns="http://cyclonedx.org/schema/bom/1.2">`

Cheers,
Marco

**Comment by sschuberth** [comment]
Just out of curiosity, is there a benefit of writing out schema version 1.3 instead of 1.2 if we don't use any of the new features as well?

**Comment by buildmanagement-trivy** [comment]
I wanted to merge two sbom files (yours in 1.2 and one in 1.3) with https://github.com/CycloneDX/cyclonedx-cli, but that leads to an error.

**Comment by mawl** [comment]
I wanted to merge your 1.2 sbom with a 1.3 sbom with https://github.com/CycloneDX/cyclonedx-cli but that leads to an error.

**Comment by sschuberth** [comment]
Hmm, sounds like a limitation of *cyclonedx-cli* then... but I'll simply make the schema version configurable via an reporter-specific option, and default to 1.3.
