### ISSUE TITLE
In dockeized execution, the analysis of python2 projects seems to fail

### ISSUE THREAD

**Issue by maxhbr** [oss-review-toolkit/ort#4901]
Using latest master (https://github.com/oss-review-toolkit/ort/commit/1ec0da0155442ba77b6cb8c724543b97292dac9d) docker image, the analysis of python2 projects fails:

```
$ git clone https://github.com/bayesian-trajectory-replay/bayesian_trajectory_replay
$ docker run -v "$(pwd)/bayesian_trajectory_replay:/project"  ort --info analyze -f JSON -i /project -o /project/ort/analyzer
[...]
14:31:09.639 [DefaultDispatcher-worker-3] ERROR org.ossreviewtoolkit.analyzer.managers.Pip - Resolving PIP dependencies for 'setup.py' failed with: IOException: Running '/tmp/ort-Pip-project-virtualenv5365724328195103716/bin/pip --trusted-host pypi.org --trusted-host pypi.python.org install --no-warn-conflicts --prefer-binary .' in '/project' failed with exit code 1:
  Failed building wheel for bayesian-trajectory-replay
Command "/tmp/ort-Pip-project-virtualenv5365724328195103716/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-0nvfj_q6/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-41ad7gsy/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/ort-Pip-project-virtualenv5365724328195103716/include/site/python3.6/bayesian-trajectory-replay" failed with error code 1 in /tmp/pip-req-build-0nvfj_q6/
You are using pip version 18.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[...]
```

`python3` is used to run and fails to build. The resulting analyzer output: [analyzer-result.json.txt](https://github.com/oss-review-toolkit/ort/files/7789369/analyzer-result.json.txt).

(The use example is a random project found with https://pypi.org/search/?q=&o=&c=Programming+Language+%3A%3A+Python+%3A%3A+2&c=Programming+Language+%3A%3A+Python+%3A%3A+2+%3A%3A+Only)

**Comment by sschuberth** [comment]
Just quickly without looking at the result: I believe that's a red herring and just part of our logic to try both Python 3 and Python 2 for analysis (in which case Python 3 is expected to fail if it's a Python 2 project). Try running with `--debug` to get more information about the Python heuristics being used.

**Comment by maxhbr** [comment]
you might be right. I am checking with a more complex project that actually has dependencies.

**Comment by maxhbr** [comment]
finding examples is hard:
* https://github.com/ghaering/pysqlite: fails with encoding problem: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 98: invalid continuation byte`
* https://github.com/thecesrom/incendium: fails with `incendium requires Python '==2.7.18' but the running Python is 2.7.17`
* https://github.com/euphorie/osha.oira: successful with [analyzer-result.json.txt](https://github.com/oss-review-toolkit/ort/files/7789552/analyzer-result.json.txt) and the log ([osha.oira.txt](https://github.com/oss-review-toolkit/ort/files/7789565/osha.oira.txt)) shows that it successfully did the fallback to python2
