### ISSUE TITLE
Provide "ExecutingReporter"

### ISSUE THREAD

**Issue by janmaterne** [oss-review-toolkit/ort#4904]
The reporter interface could be used to implement plugins which uses the gathered information to execute tasks.
E.g. 
* create JIRA issue on detected errors
* create pull request if new dependency version was detected (see issue #4903)
* write an alert (mail, ...) if a security risk with score>=$value was found (e.g. like the one of log4shell ;-) )

**Comment by sschuberth** [comment]
Are you aware or the [notifier module](https://github.com/oss-review-toolkit/ort/tree/master/notifier)? (I just realized it's not documented in the README yet; will fix that.) It's freely programmable very similar to the evaluator, and it can already create JIRA tickets and send (alert) emails.

**Comment by sschuberth** [comment]
> I just realized it's not documented in the README yet; will fix that.

See https://github.com/oss-review-toolkit/ort/pull/4905.
