### ISSUE TITLE
yarn version is checked in the wrong way

### ISSUE THREAD

**Issue by CsatariGergely** [oss-review-toolkit/ort#491]
Analyzer checks yarn's version using `yarn --version` while yarn expects `yarn version`.

**Comment by sschuberth** [comment]
Thanks @CsatariGergely for the report. However, are you sure? I'm getting:

    $ yarn --version
    1.3.2

    $ yarn version
    yarn version v1.3.2
    warning You are using Node "7.10.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semve
    r range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
    error Couldn't find a package.json file in "C:\\Dev\\oss-review-toolkit"
    info Visit https://yarnpkg.com/en/docs/cli/version for documentation about this command.

**Comment by CsatariGergely** [comment]
Interesting. Here are my outputs: 
``
$ yarn --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
``
and
``
$ yarn version
Hadoop 2.4.1
Subversion Unknown -r Unknown
Compiled by mockbuild on 2016-10-28T04:46Z
Compiled with protoc 2.6.1
From source with checksum e270dfd4b5d1fafed8b434caa19eb8
This command was run using /usr/lib/java/hadoop/hadoop-common.jar
``

**Comment by sschuberth** [comment]
Looks like you have the wrong `yarn` command in your `PATH`, namely https://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/YARN.html instead of https://yarnpkg.com/.
