### ISSUE TITLE
License texts for `+` variants of SPDX licenses

### ISSUE THREAD

**Issue by mmurto** [oss-review-toolkit/ort#5004]
ORT currently provides license text for license identifiers on the [SPDX license list](https://spdx.org/licenses/) for notice generation with Reporter. No license text is provided for SPDX licenses with `+` identifier; for example, a license expression `LPPL-1.0+` does not produce any license text for the notice files.

Should the non-plus variant of the license be used for the plus variants?

**Comment by mnonnenmacher** [comment]
@mmurto This was discussed in the [developer meeting today](https://github.com/oss-review-toolkit/ort/wiki/Developer-Meeting#2022-02-10) and the consensus was that it should be implemented as suggested.
