### ISSUE TITLE
GoMod analysis seems to get package versions and graph pruning wrong

### ISSUE THREAD

**Issue by andreasdotorg** [oss-review-toolkit/ort#5021]
I've been trying to make the ORT Analyzer work for a golang project, with less than satisfactory results. (If you want to follow along, you can find the code at https://github.com/impfen/services-inoeg). Main effects are: confusion about the right versions, missed dependencies.

After looking at the code, I think the main issue stems from the fact that the Analyzer looks at dependencies on a package level, not on a module level, and ignores minimum version resolution. Let me try to outline what I think is going wrong and why.

First, let's look at the definition of things in golang, what exactly are modules and packages? Here's a [definition](https://levelup.gitconnected.com/using-modules-and-packages-in-go-36a418960556):

> In Go, a package is a directory of .go files, and packages form the basic building blocks of a Go program. Using packages, you organize your code into reusable units. A module, on the other hand, is a collection of Go packages, with dependencies and versioning built-in.

I think the key here is the dependencies and versioning aspect. 

If we look at how the Analyzer works at the moment, it pulls a graph of module dependencies using `go mod graph`, and then tries to prune that graph to actually used modules by calling `go mod why`.  Let's look at how this fails with the example linked above. First issue: no resolution of versions. Let's find out who depends on github.com/golang/protobuf:

```
$ go mod graph|grep " github.com/golang/protobuf"
github.com/prometheus/client_golang@v1.11.0 github.com/golang/protobuf@v1.4.3
github.com/onsi/gomega@v1.16.0 github.com/golang/protobuf@v1.5.2
github.com/prometheus/client_model@v0.2.0 github.com/golang/protobuf@v1.2.0
github.com/prometheus/common@v0.26.0 github.com/golang/protobuf@v1.4.2
github.com/onsi/gomega@v1.10.1 github.com/golang/protobuf@v1.4.2
google.golang.org/protobuf@v1.23.0 github.com/golang/protobuf@v1.4.0
github.com/prometheus/client_golang@v1.7.1 github.com/golang/protobuf@v1.4.2
google.golang.org/protobuf@v1.26.0 github.com/golang/protobuf@v1.5.0
github.com/prometheus/common@v0.10.0 github.com/golang/protobuf@v1.3.2
google.golang.org/appengine@v1.4.0 github.com/golang/protobuf@v1.2.0
github.com/onsi/gomega@v1.7.1 github.com/golang/protobuf@v1.2.0
google.golang.org/protobuf@v1.21.0 github.com/golang/protobuf@v1.4.0-rc.4.0.20200313231945-b860323f09d0
github.com/prometheus/client_golang@v1.0.0 github.com/golang/protobuf@v1.3.1
github.com/prometheus/client_model@v0.0.0-20190129233127-fd36f4220a90 github.com/golang/protobuf@v1.2.0
github.com/prometheus/common@v0.4.1 github.com/golang/protobuf@v1.2.0
google.golang.org/protobuf@v1.20.1-0.20200309200217-e05f789c0967 github.com/golang/protobuf@v1.4.0-rc.2
google.golang.org/protobuf@v0.0.0-20200228230310-ab0ca4ff8a60 github.com/golang/protobuf@v1.4.0-rc.1.0.20200221234624-67d41d38c208
google.golang.org/protobuf@v0.0.0-20200221191635-4d8936d0db64 github.com/golang/protobuf@v1.4.0-rc.1
```

A lot of modules, apparently. But which version will end up in the binary? We cannot answer that before version resolution, and the package dependency graph doesn't give us that.

The second problem becomes apparent when we ask whether a certain module is in use:

```
$ $ go mod why golang.org/x/crypto
# golang.org/x/crypto
(main module does not need package golang.org/x/crypto)
```

This answer, while technically correct, isn't helpful. The main module does indeed not depend on the package. However, this isn't the question we're interested in, we're interested in the _module_ instead of the _package_! And the module is indeed in use, via another module that the main module depends on.

Here's an outline of what I believe is the correct approach to building the transitive dependency graph.

Step 1: build the module dependency graph using `go mod graph` as before, but drop the version numbers and unify package dependencies with different version numbers into a single node.

Step 2: get the list of all modules, resolved to their version numbers, by using `go list -m all`:

```
$ go list -m all | grep github.com/golang/protobuf
github.com/golang/protobuf v1.5.2
```

And then fix up the module dependency graph from step 1, by adding back the resolved version. 

Step 3: Prune the graph by using `go mod why -m` (the `-m` asks the question on a module level instead of the package level):

```
$ go mod why -m github.com/golang/protobuf
# github.com/golang/protobuf
github.com/impfen/services-inoeg/databases
github.com/prometheus/client_golang/prometheus
github.com/golang/protobuf/proto
```

Note that this command still uses the package graph instead of the module graph for answering the question, the dependency path shown is a package dependency.

My Kotlin is a bit rusty, I'm not sure I could quickly whip up an implementation of the above idea. Also, I'm not sure the analysis above is flawless, but I believe it might have some merit and that the analysis is useful

**Comment by sschuberth** [comment]
Thanks a lot for that thorough write-up, @andreasdotorg! None of us core ORT developers are native to Go, so we'd definitely appreciate some help here. We struggled with [proper GoMod support](https://github.com/oss-review-toolkit/ort/pull/4119) in the past and still seem to have [issues](https://github.com/oss-review-toolkit/ort/issues/3860).

**Comment by mawl** [comment]
Same issue here. ort isn't capable of finding a used aws-xray-sdk-go module with its dependency crypto.

trivy finds it and it seems that they only scan the go.mod file for it: https://github.com/aquasecurity/go-dep-parser/blob/main/pkg/golang/mod/parse.go

**Comment by fviernau** [comment]
Hi @andreasdotorg,

I've made a couple of changes / fixes to ORT's `GoMod` support. Your writing was extremely helpful!
Thanks a lot for taking the time! With above linked merged PRs the issues you described should be fixed.
The reported dependency tree to my understanding should be correct in the HEAD of main branch now.

In case you should experiment with GoMod and check whether its fixed it'd be great to receive some feedback here.
@mawl it'd be awesome to ave feedback from you about yuor use case as well.

Note: I have the following two further improvements improvements beyond the issues described here still in review
* https://github.com/oss-review-toolkit/ort/pull/5459
* https://github.com/oss-review-toolkit/ort/pull/5468

**Comment by fviernau** [comment]
GoMod now should return the right sets of depdencies and use reasonable scopes for main dependencies and dev depdendencies. So, the node set in the depdency tree should be correct now. There is one known issue with a missing edge, which is about to be fixed: https://github.com/oss-review-toolkit/ort/issues/5479.

The problems described in this ticket are all fixed, so closing as fixed.

**Comment by mawl** [comment]
Hey @fviernau,

ort now takes care of the missing module - so that's fine :) https://github.com/oss-review-toolkit/ort/issues/5021#issuecomment-1036132558 
But, I have another issue here with //go:embed and //go:generate. Please take a look at: https://github.com/oss-review-toolkit/ort/issues/5560 for that.

**Comment by fviernau** [comment]
Thanks @mawl  for the feedback!
