### ISSUE TITLE
Support license choices for SPDX licenses with the '+' operator

### ISSUE THREAD

**Issue by mnonnenmacher** [oss-review-toolkit/ort#5036]
License choices [1] currently allow choosing a license if the `OR` operator is used, for example for the license expression `Apache-1.1 OR Apache-2.0` the user could choose either `Apache-1.1` or `Apache-2.0`.

This should also be supported for the `+` operator [2]. For example, for the expression `Apache-1.1+` it should be possible to choose either `Apache-1.1` or `Apache-2.0`.

Note that the SPDX specification allows the `+` operator only for SPDX license ids, not for `LicenseRef`s.

[1]: https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-ort-yml.md#License-Choices
[2]: https://spdx.github.io/spdx-spec/SPDX-license-expressions/

**Comment by pombredanne** [comment]
My 2 cents is there is only a handful of case where I saw a license with a plus used outside of the A/L/GPL and GFDL. These are extremely rare meaning probably not worth tracking.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
