### ISSUE TITLE
Missing repository information in analyzer result leads to error in reporter

### ISSUE THREAD

**Issue by tafli** [oss-review-toolkit/ort#5052]
Scanning a git repository leads to a analyzer file that cannot be used as input for the reporter. Running the reporter leads to following error:
```
ERROR org.ossreviewtoolkit.cli.commands.ReporterCommand - Could not create 'WebApp' report in 136.718837ms: IllegalArgumentException: The VcsInfo(type=Git, url=https://path/to/my/project.git, revision=, path=) of project 'Yarn::myProject:0.1.0-1-SNAPSHOT' cannot be found in Repository(vcs=VcsInfo(type=, url=, revision=, path=), vcsProcessed=VcsInfo(type=, url=, revision=, path=), nestedRepositories={}, config=RepositoryConfiguration(excludes=Excludes(paths=[], scopes=[]), resolutions=Resolutions(issues=[], ruleViolations=[], vulnerabilities=[]), curations=Curations(packages=[], licenseFindings=[]), packageConfigurations=[], licenseChoices=LicenseChoices(repositoryLicenseChoices=[], packageLicenseChoices=[]))).
```

The `analyzer-result.json`does not contain any respository information, but the project itself references to one:

```
{
  "repository" : {
    "vcs" : {
      "type" : "",
      "url" : "",
      "revision" : "",
      "path" : ""
    },
    "vcs_processed" : {
      "type" : "",
      "url" : "",
      "revision" : "",
      "path" : ""
    },
    "config" : { }
  },
  "analyzer" : {
    "start_time" : "2022-02-14T07:49:34.899624Z",
    "end_time" : "2022-02-14T07:59:48.669457Z",
    "environment" : {
      "ort_version" : "DOCKER-SNAPSHOT",
      "java_version" : "11.0.11",
      "os" : "Linux",
      "processors" : 6,
      "max_memory" : 1031798784,
      "variables" : {
        "JAVA_HOME" : "/opt/java/openjdk",
        "ANDROID_HOME" : "/opt/android-sdk",
        "GOPATH" : "/go"
      },
      "tool_versions" : {
        "Yarn" : "1.22.10"
      }
    },
    "config" : {
      "allow_dynamic_versions" : true
    },
    "result" : {
      "projects" : [ {
        "id" : "Yarn::myProject:0.1.0-1-SNAPSHOT",
        "definition_file_path" : "",
        "declared_licenses" : [ ],
        "declared_licenses_processed" : { },
        "vcs" : {
          "type" : "Git",
          "url" : "https://path/to/my/project.git",
          "revision" : "",
          "path" : ""
        },
        "vcs_processed" : {
          "type" : "Git",
          "url" : "https://path/to/my/project.git",
          "revision" : "",
          "path" : ""
        },
        "homepage_url" : "",
        "scope_names" : [ "dependencies", "devDependencies" ]
      } ],
      "packages" : [ {
         ....
      }]
   }
}
```

This reference is taken from the package.json where the repository is defined.

The reporter will run, when I remove manually the vcs url in the projects definition (or package.json) or adding the vcs url to the repository configuration. Doing so in a pipeline however is a bit ... well ... not optimal.

Is there anything I'm missing or is there a configuration I can add to prevent the error?

**Comment by sschuberth** [comment]
> The `analyzer-result.json`does not contain any respository information

The question is: Why? Are you scanning a local directory that is not under version control? If so, that's currently not fully supported.

**Comment by tafli** [comment]
Yes, I am scanning a local directory but it is definitely under version control. I do checkout the repo and use a docker version of ORT to scan it.

**Comment by tafli** [comment]
I just found out, that the projects VCS information is taken from the file `[package.json`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#repository). When removing this information the report can be generated as the VCS information is not present anymore in the resulting `analyzer-result.json`.

**Comment by tafli** [comment]
Now it's getting interesting. I used a native ORT installation to scan the same directory I used to mount into the docker version of ORT and this time the VCS information was present in `analyzer-result.json`.

It seems the docker version does not recognize the mounted project as a GIT project?

**Comment by sschuberth** [comment]
> It seems the docker version does not recognize the mounted project as a GIT project?

If by "docker version" you mean the version of ORT running in Docker, that's no different from "native" ORT, and I don't believe it makes a difference.

I'm more wondering about Docker mount options or something into that direction. Do you mount the parent directory of the `.git` directory as a Docker volume, or maybe just some sub-directory of it?

**Comment by tafli** [comment]
I did test with the same project directory in both native/local ORT and ORT in docker. And yes, I did the test using subdirectories as the project is organized that way and I have no influence on that. The `.git`-folder was not mounted.
The effect however is as described above: the native ORT does recognize the VCS, the docker ORT does not.

I'll do some testing with the root folder and come back with my findings.

**Comment by tafli** [comment]
Can confirm that the `.git`folder must be mounted into docker to work correctly. This despite the description [here](https://github.com/oss-review-toolkit/ort/blob/master/docs/hints-for-use-with-docker.md#mount-current-working-directory-or-directory-relative-to-working-directory).

The relative directory does usually work but not in my yarn case, where repository is configured in _package.json_. It also does work when using the native ORT installation, as _git_ does recognize a subdirectory as under vcs control this way.

Probably a hint to the docker-hints might be helpfull!

And thanks for your help.

**Comment by sschuberth** [comment]
> Probably a hint to the docker-hints might be helpfull!

Mind contributing a PR to improve the wording that confused you?
