### ISSUE TITLE
Gradle: Support multiple projects defined in a single build.gradle

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#5089]
This needs to consider 

1. the exclude mechanisms
2. the association of files to projects

Depending on the chosen solution path excludes might not work out of the box for (1) and (2) might not either.

Note: This is an old ticket from HERE's internal backlog, description / approach may need to be revisited.

**Comment by sschuberth** [comment]
Do we have an example project that defines multiple Gradle projects in a single build file?

**Comment by sschuberth** [comment]
> Note: This is an old ticket from HERE's internal backlog, description / approach may need to be revisited.

Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
