### ISSUE TITLE
PIP: Read `project_urls` attribute from `setup.py`

### ISSUE THREAD

**Issue by haikoschol** [oss-review-toolkit/ort#509]
A VCS repository from which releases are created is preferrable to the location of a source artifact ("sdist" in Python lingo). There is a rarely used [attribute in `setup.py`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls) where this information can be recorded. Make sure this information is captured, if it is present.

**Comment by sschuberth** [comment]
Note that `project_urls` is a map of strings to strings, with not really standardized keys / values. For example, the key might be called "Source" or "Source Code", and the value might be "https://github.com/pypa/sampleproject/", but there is no convention about whether the URL should be the VCS clone URL or the entry point for browsing the source code, which makes leveraging this attribute a bit hard.
