### ISSUE TITLE
Pub: Gracefully handle sub-modules / projects

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#5100]
The following issues were observed with a Flutter project which has sub-modules. 

1. All Gradle definition files are analyzed regardless whether they
   correspond to a Flutter project.
2. The Gradle analysis of all Gradle definition files is not just done
   once in total, but once per Pub definition file.
3. If there are multiple Pub definition files, then each discovered
   Gradle project is added multiple times to the ORT result which yields
   and ORT issue due to duplicate project identifier.
4. The lockfile parsing dependency tree construction does not adhere to the `dependency` property:
     like `dependency: "direct main"` or `dependency: "direct transitive"`
5. The lockfile parsing does not handle `submodule` dependencies as per:
    ```
    description:
              path: "../my-submodule"
              relative: true
    ```
6. The dependency tree is pruned, no redundant subtrees.
7. `buildDependencyTree()` assumes that each package has a `name`, see usage of `val nameOfCurrentPackage = manifest["name"].textValue()`. If more than one package doesn't have a name, then that function is broken.

**Comment by fviernau** [comment]
In order to implement proper sub-module support, and as the implementation is lock-file based, I would like to change to actually require lock files and otherwise fail. However, I'm not sure which of the following is better:

1. The submodule `pubspec.yaml` files are analyzed by locating the root project's lockfile and parsing that one.
2. Each `pubspec.yaml` requires a lock file.

I tend towards opion 1, because the conflict resolution can then consider all version constraints of all modules leading to a more realistic result than analyzing the submodules independently. 

Any thoughts on this, maybe @MarcelBochtler @oss-review-toolkit/core-devs ?

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
