### ISSUE TITLE
ORT's heuristic for associating license IDs with exception creates "problematic" pairs

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#5101]
The heuristic does associate ScanCode's generic license such as e.g. `LicenseRef-scancode-unknown`, `LicenseRef-scancode-other-permissive` with exceptions. If there is no match for an exception then it gets associated with `NOASSERTION`.

For license compliance, combining a license with an exception may change the legal implication significantly and therefore
each license exception combination typically has to be reviewed by legal. For the evaluator rules the outcome of such review is place in `license-classifications.yml`. So, all combinations have to be dealt with at least once manually.

So it does create manual effort to associate any exception with generic license triggers, while these tuples do not have any meaning because the pairing is invalid.

**Comment by sschuberth** [comment]
> The heuristic does associate ScanCode's generic license such as e.g. `LicenseRef-scancode-unknown`, `LicenseRef-scancode-other-permissive` with exceptions.

I guess you're referring to the newly added `associateLicensesWithExceptions()` function. That function should actually *not* associate any `LicenseRef-scancode-*` licenses (yet), as they are not part of `associateLicensesWithExceptions`. I'll add a test to verify.

**Comment by fviernau** [comment]
> I guess you're referring to the newly added `associateLicensesWithExceptions()` function. That function should actually _not_ associate any `LicenseRef-scancode-*` licenses (yet), as they are not part of `associateLicensesWithExceptions`. I'll add a test to verify.

Sorry, @sschuberth. I've only seen the NOASSERTION one popping up, then had a quick look at the code and guessed that also generic licenses can be associated, but the latter was wrong. I missed the relevant bits in the code.

**Comment by tsteenbe** [comment]
@fviernau In https://github.com/oss-review-toolkit/ort/pull/5078#discussion_r812378327 @sschuberth  @mnonnenmacher  and myself decided to associate "orphan" exceptions with NOASSERTION. My thinking was that in this way one could easily write a policy rule to handle "orphan" exceptions

**Comment by fviernau** [comment]
So, the ticket is invalid. Agree that the added "manual" effort can be easily avoided by modifying the policy rules.

**Comment by sschuberth** [comment]
> I'll add a test to verify.

FYI: https://github.com/oss-review-toolkit/ort/pull/5102
