### ISSUE TITLE
Helper-CLI :: generate-package-configurations command not found in main branch

### ISSUE THREAD

**Issue by porsche-rishisaxena** [oss-review-toolkit/ort#5110]
During curation process, Porsche AG uses **generate-package-configurations** command to create package configuration for the source artifact scan and VCS scan which ran into problem with an error message: no such option: "--scan-results-storage-dir"

we found out that generate-package-configurations command is not existing in the "Main" branch as it depicts in https://github.com/oss-review-toolkit/ort/tree/f69edd841c18e1ed0c8ed631964ea85d5eb5e6f6
Note: Porsche AG is using Main Branch of ORT (3 months old)

Would it be possible to check on your end, if the commit was successfully merged with Main Branch? If moved or renamed, please provide relevant details.

**Comment by mnonnenmacher** [comment]
@porsche-rishisaxena This command was renamed to "create" and grouped together with other package configuration related commands in #4140. Also see:

```
orth package-configuration --help
```

and

```
orth package-configuration create --help
```
