### ISSUE TITLE
ORT Scanner freezes on some projects

### ISSUE THREAD

**Issue by borisbaldassari** [oss-review-toolkit/ort#5116]
We are running ORT on a bunch of Eclipse projects, and some of them freeze during the scanner exceution. 

We use the latest version of ORT (from git) and ScanCode (30.1.0), on Debian with OpenJDK 17. 
When executed directly with Scancode these projects run successfully within a couple of hours. When run through ORT I had to stop it after several days, so I assume it's not a matter of time (nor resources, the host is powerful enough).

Example of projects that freeze:
* Eclipse Tycho: https://github.com/eclipse/tycho
* Smartclide kie-wb-common: https://github.com/eclipse-researchlabs/kie-wb-common
* Eclipse Che: https://github.com/eclipse/che.git

The typical output when it happens is:
```
* Start scanner at 2022-03-01 08:51
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version a056b54c72.
 /   |   \|       _/ |    |
/    |    \    |   \ |    |    Running 'scan' under Java 17.0.2 on Linux with
\_______  /____|_  / |____|    8 CPUs and a maximum of 12192 MiB of memory.
        \/       \/
Environment variables:
ORT_CONFIG_DIR = /ort/eclipsefdn-ort/conf
ORT_DATA_DIR = /home/ort/.ort
SHELL = /bin/bash
TERM = screen.xterm-256color
JAVA_HOME = /usr/lib/jvm/java-17-openjdk-amd64

Using scan storage 'composite[readers:[FileBasedStorage with LocalFileStorage backend, ClearlyDefinedStorage], writers:[FileBasedStorage with LocalFileStorage backend]]'.
Using scanner 'ScanCode' version 30.1.0.
```
And then is stays still for days (tried to let it run for up to 4 days).

2 questions arise:
* Is it a known issue? I couldn't find anything in the bug tracker or online, but I may have missed something.
* Is there a way to make ORT more verbose when executing the scanner?

Thanks,

**Comment by borisbaldassari** [comment]
Forgot to mention: Some projects work just well (e.g. Eclipse jgit), and I can't figure out what is the difference between working and non-working projects.

**Comment by sschuberth** [comment]
> Is it a known issue? I couldn't find anything in the bug tracker or online, but I may have missed something.

I see you're using `ClearlyDefinedStorage`, so it *might* be related to https://github.com/oss-review-toolkit/ort/issues/4540.

> Is there a way to make ORT more verbose when executing the scanner?

Yes, you can pass `--info` or `--debug` as a top-level option. That is, use `ort --debug scan ...`, not `ort scan --debug ...`.

**Comment by borisbaldassari** [comment]
Thanks @sschuberth for the quick answer!

* I've seen the issue with ClearlyDefinedStorage, but the failures specifically happen on some projects and not on others. Furthermore I've seen logs that show clearlydefined works well on my setup. But I'll disable it to just make sure it's not related.
* I'll run it again with the info/debug flags and report it quickly. Thanks!

**Comment by borisbaldassari** [comment]
The `--debug` flag is very helpful, thanks for the hint. The last lines output (with `ClearlyDefined` active) is:
```
15:07:24.283 [DefaultDispatcher-worker-27] INFO  org.ossreviewtoolkit.utils.core.OrtAuthenticator - Authenticator was successfully installed.
15:07:24.297 [DefaultDispatcher-worker-27] INFO  org.ossreviewtoolkit.utils.core.OrtProxySelector - Proxy selector was successfully installed.
15:07:24.484 [DefaultDispatcher-worker-62] INFO  org.ossreviewtoolkit.scanner.storages.ClearlyDefinedStorage - Looking up results for 'NPM::chalk:4.1.2'.
```

OTOH when disabling `ClearlyDefined` the scanner shows a lot of activity, and eventually finishes. So it boils down to issue #4540 and I've been fooled by the fact that some projects actually just run fine. 

Thanks for the amazing support, @sschuberth !
