### ISSUE TITLE
Scan Report Web App not opening // Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by meeraa247** [oss-review-toolkit/ort#5144]
Hi everybody,

we are able to produce a scan-result.yml and also create a so called web-report-app.html. Unforts the web-report cannot be opened as it produces the following Javascript Error:

![Bildschirmfoto 2022-03-11 um 10 22 18](https://user-images.githubusercontent.com/95626831/157839072-b91e8463-fff4-461b-b493-4ee6c9ebe136.png)

Processing the data gets stuck :
![Bildschirmfoto 2022-03-11 um 10 23 51](https://user-images.githubusercontent.com/95626831/157839189-3b033e37-a938-44f1-a5cd-de67e8b3f2a6.png)

Any advise / help would be appreciated.

Thanks
P.

**Comment by meeraa247** [comment]
Please find the mentioned web-report.html below:
[scan-report-web-app.html.zip](https://github.com/oss-review-toolkit/ort/files/8230701/scan-report-web-app.html.zip)

**Comment by sschuberth** [comment]
@tsteenbe a quick fix for you?

**Comment by tsteenbe** [comment]
@meeraa247 I manually export the scan result data from the WebApp report your provided and loaded into reporter-webapp/public/index.html, ran yarn start and it shows me the follow error in the browser console.

```
TypeError: license is undefined
    licenseToHslColor index.js:48
    WebAppLicense WebAppLicense.js:39
    WebAppOrtResult WebAppOrtResult.js:127
    processOrtResultData processOrtResultData.js:28
```

The call to licenseToHslColor fails in [WebAppLicense.js#L39](https://github.com/oss-review-toolkit/ort/blob/main/reporter-web-app/src/models/WebAppLicense.js#L39) as the `licenses` in the EvaluatedModel contains `{ _id: 51, id: "" }` which is an invalid entry.

@meeraa247  Can you provided the Scanner output file so @sschuberth  or @mnonnenmacher can see why an empty string license is part of the ORT results?

**Comment by meeraa247** [comment]
HI @tsteenbe , first of all. Thanks for picking this up so quickly. Appreciate it ;-D
I attached the "scan-result.yml" file for further investigation (@sschuberth)
[scan-result.yml.zip](https://github.com/oss-review-toolkit/ort/files/8234557/scan-result.yml.zip)

**Comment by sschuberth** [comment]
The problem is that the `Pod::BVLinearGradient:2.5.6` package literally declares an empty license. I'll create a PR with a fix.
