### ISSUE TITLE
Unknown Scanner Error for Python Files in packages

### ISSUE THREAD

**Issue by schvvarzekatze** [oss-review-toolkit/ort#5168]
In the `scan-report-web-app.html` I get unknown scanner errors referring to serveral Python files e.g.:
Package: `Maven:com.drewnoakes:metadata-extractor:2.16.0`

``
ERROR: for scanner: licenses: ERROR: Unknown error: Traceback (most recent call last): File "/usr/local/lib/python3.8/dist-packages/scancode/interrupt.py", line 91, in interruptible return NO_ERROR, func(*(args or ()), **(kwargs or {})) File "/usr/local/lib/python3.8/dist-packages/scancode/api.py", line 175, in get_licenses matches = idx.match( File "/usr/local/lib/python3.8/dist-packages/licensedcode/index.py", line 819, in match qry = query.build_query( File "/usr/local/lib/python3.8/dist-packages/licensedcode/query.py", line 119, in build_query if not T.contains_text: File "/usr/local/lib/python3.8/dist-packages/typecode/contenttype.py", line 618, in contains_text elif self.is_pdf and not self.is_pdf_with_text: File "/usr/local/lib/python3.8/dist-packages/typecode/contenttype.py", line 594, in is_pdf_with_text doc = PDFDocument(parser) File "/usr/local/lib/python3.8/dist-packages/pdfminer/pdfdocument.py", line 701, in __init__ newxref.load(parser) File "/usr/local/lib/python3.8/dist-packages/pdfminer/pdfdocument.py", line 194, in load (_, obj) = parser.nextobject() File "/usr/local/lib/python3.8/dist-packages/pdfminer/psparser.py", line 604, in nextobject (pos, token) = self.nexttoken() File "/usr/local/lib/python3.8/dist-packages/pdfminer/psparser.py", line 518, in nexttoken self.fillbuf() File "/usr/local/lib/python3.8/dist-packages/pdfminer/psparser.py", line 233, in fillbuf raise PSEOF('Unexpected EOF') pdfminer.psparser.PSEOF: Unexpected EOF (File: wiki/docs/ICC1v43_2010-12.pdf)
``

What is reason for this errors and what is the best way to fix these errors?

It does not help to configure `.ort.yml`:
- message: "ERROR: for scanner: licenses: ERROR: Unknown error: Traceback (most recent call last)*"
      reason: "SCANNER_ISSUE"
      comment: "The error can be ignored because the file does not contain additional relevant license information. The Apache-2.0 License is compatible to its usage."

**Comment by meeraa247** [comment]
That sounds a lot like the previously mentioned Issue [5159](https://github.com/oss-review-toolkit/ort/issues/5159)

**Comment by sschuberth** [comment]
> That sounds a lot like the previously mentioned Issue [5159](https://github.com/oss-review-toolkit/ort/issues/5159)

No, this one has a different root cause (look at the last line of the stacktrace). It actually seem to be a ScanCode issue, so please report it directly at https://github.com/nexB/scancode-toolkit/issues.
