### ISSUE TITLE
Don't automatically add CocoaPods' trunk CDN in Docker

### ISSUE THREAD

**Issue by malice00** [oss-review-toolkit/ort#5176]
We have our own mirror of CocoaPods' Spec-Repo and just about all Pods that we use. This is both for security and speed reasons.
Because resolving the repos from our local network is a lot faster than resolving it from the internet, we would like ORT to not use the default CP CDN, but our Spec-mirror and from that our other mirrors.

**Comment by sschuberth** [comment]
As AFAIK ORT is mostly just calling the `pod` CLI for CocoaPods analysis, I would have expected this to "just work" if it works with plain `pod`.

If it works with plain `pod`, is there any (user-local) `pod` configuration that you have but ORT doesn't?

**Comment by malice00** [comment]
I feel like such a dummy -- this didn't work, because I didn't mount the CocoaPods repository in Docker!
