### ISSUE TITLE
Unable to resolve scoped NPM packages from Nexus Repository Manager 2

### ISSUE THREAD

**Issue by malice00** [oss-review-toolkit/ort#5177]
We have a Nexus 2 as a proxy for our NPM-packages. I have noticed that scoped packages are returning 404 upon being requested by ORT. It looks like ORT is URL-encoding the '/' in scoped packages, which Nexus doesn't like.
Seeing how normal installation of packages works, I assume that NPM itself requests packages without URL-encoding.
The official registry at https://registry.npmjs.org/ will serve modules for both encoded and direct requests.

```
18:48:11.513 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.analyzer.managers.Npm - Could not retrieve package information for '@react-native%2Fassets' from NPM registry https://XXX/publicNPM: Not Found (HTTP code 404)
18:48:12.566 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.analyzer.managers.Npm - Could not retrieve package information for '@react-native%2Fnormalize-color' from NPM registry https://XXX/publicNPM: Not Found (HTTP code 404)
18:48:12.819 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.analyzer.managers.Npm - Could not retrieve package information for '@react-native%2Fpolyfills' from NPM registry https://XXX/publicNPM: Not Found (HTTP code 404)
18:48:13.617 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.analyzer.managers.Npm - Could not retrieve package information for '@types%2Fistanbul-lib-report' from NPM registry https://XXX/publicNPM: Not Found (HTTP code 404)
18:48:13.985 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.analyzer.managers.Npm - Could not retrieve package information for '@types%2Fyargs' from NPM registry https://XXX/publicNPM: Not Found (HTTP code 404)
```

**Comment by sschuberth** [comment]
Which revision of ORT are you using? Specifically, are you using a version that has https://github.com/oss-review-toolkit/ort/pull/5162 merged? I would expect that PR to fix your issue.

**Comment by malice00** [comment]
My revision is a couple of days older than the merge -- I'll recreate my image and give it another go. Thanks for the info!

**Comment by raviteja0312** [comment]
I am currently using nexus oss 2.13.1 version and facing same issue for scoped packages, so what version should i upgrade to download scoped packages without any error?
