### ISSUE TITLE
Analyzer: WARNING: A connection to https://repo.maven.apache.org/ was leaked.

### ISSUE THREAD

**Issue by Alphavax** [oss-review-toolkit/ort#5236]
The analyzer scan for a maven project throws a lot of warnings regarding leaked connections to maven repo:

08:44:09.264 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Fixed up invalid SCM connection 'scm:git://github.com/lihaoyi/fastparse.git' without a provider to VcsInfo(type=Git, url=git://github.com/lihaoyi/fastparse.git, revision=, path=).
Apr 07, 2022 8:44:11 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://repo.maven.apache.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Apr 07, 2022 8:44:11 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://repo.maven.apache.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Apr 07, 2022 8:44:11 AM okhttp3.internal.platform.Platform log

**Comment by sschuberth** [comment]
I've also seen this, and did https://github.com/oss-review-toolkit/ort/pull/5026 a while back to set OkHttp's `FINE` when ORT's `DEBUG` is set, but so far had no lock seeing this again with a `--debug` run of ORT.

@Alphavax can you try to rerun with ORT's `--debug` i order to see OkHttp's `FINE` log output to hunt down the root cause?

**Comment by Alphavax** [comment]
Hello Sebastian,

Not sure from where to start putting the debug output, but here are the lines before and after the warning:

07:27:22.669 [DefaultDispatcher-worker-3] DEBUG org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Searching for 'com.here.schema.rib:topology-geometry_v2_proto:jar:sources:2.55.0' in [HERE_PLATFORM_ARTIFACT (here+artifact-service://artifact-service, default, releases+snapshots), here.olp.sit.repo (https://artifactory.in.here.com/artifactory/here-olp-sit, default, releases+snapshots), central (https://repo.maven.apache.org/maven2, default, releases), OLP (https://artifactory.in.here.com/artifactory/here-olp-sit, default, releases+snapshots), HERE_PLATFORM_REPO (https://repo.platform.here.com/artifactory/open-location-platform, default, releases+snapshots), HEREHADSENSORINGESTIONRELEASESREPO (https://artifactory.in.here.com/artifactory/had-sensor-ingestion-releases, default, releases+snapshots), mavencentral-mirror-in-here (https://artifactory.in.here.com/artifactory/mavencentral, default, releases)].
07:27:22.669 [DefaultDispatcher-worker-3] DEBUG org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Remote location for 'com.here.schema.rib:topology-geometry_v2_proto:jar:sources:2.55.0': com.here.schema.rib/topology-geometry_v2_proto/2.55.0/topology-geometry_v2_proto-2.55.0-sources.jar
07:27:22.669 [DefaultDispatcher-worker-3] DEBUG org.eclipse.aether.internal.impl.DefaultTransporterProvider - Using transporter WagonTransporter with priority -1.0 for here+artifact-service://artifact-service
07:27:22.669 [DefaultDispatcher-worker-3] DEBUG org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider - Using connector BasicRepositoryConnector with priority 0.0 for here+artifact-service://artifact-service
Apr 08, 2022 7:27:22 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://repo.maven.apache.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
07:27:22.767 [DefaultDispatcher-worker-3] DEBUG org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Transfer failed: GET_EXISTENCE FAILED here+artifact-service://artifact-service/com.here.schema.rib/topology-geometry_v2_proto/2.55.0/topology-geometry_v2_proto-2.55.0-sources.jar <> /root/.m2/repository/com/here/schema/rib/topology-geometry_v2_proto/2.55.0/topology-geometry_v2_proto-2.55.0-sources.jar
07:27:22.767 [DefaultDispatcher-worker-3] DEBUG org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Could not find 'com.here.schema.rib:topology-geometry_v2_proto:jar:sources:2.55.0' in 'HERE_PLATFORM_ARTIFACT (here+artifact-service://artifact-service, default, releases+snapshots)': ArtifactNotFoundException: Could not find artifact com.here.schema.rib:topology-geometry_v2_proto:jar:sources:2.55.0 in HERE_PLATFORM_ARTIFACT (here+artifact-service://artifact-service)

**Comment by sschuberth** [comment]
@Alphavax can you please check whether https://github.com/oss-review-toolkit/ort/pull/5240 solves the issue?
