### ISSUE TITLE
Unable to install ORT - repository is available

### ISSUE THREAD

**Issue by godfreysilvester** [oss-review-toolkit/ort#5252]
Failing with the below exception

[root@estalv53 ort]# ./gradlew installDist
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/opt/ort/build.gradle.kts' line: 46

* What went wrong:
Plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.6.20'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:1.6.20')
  Searched in the following repositories:
    Gradle Central Plugin Repository

**Comment by sschuberth** [comment]
There were occasional glitches in the past with the Gradle Central Plugin Repository, so please simply try again after a while. Meanwhile, you might want to manually check that you can access https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.6.20/kotlin-gradle-plugin-1.6.20.jar from your build machine.

**Comment by sschuberth** [comment]
And if you require a proxy to access the Internet, you need to [configure Gradle](https://docs.gradle.org/current/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy) to do so.

**Comment by godfreysilvester** [comment]
Now the build fails at when checked for requirements.
 ./gradlew cli:run --args="requirements"

> Task :cli:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cli:run'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-11.0.14.1.1-1.el7_9.x86_64/bin/java'' finished with non-zero exit value 6

**Comment by sschuberth** [comment]
> Now the build fails at when checked for requirements.

Please add the full console output.

**Comment by godfreysilvester** [comment]
> Configure project :
Building ORT version 5257c6db4f-dirty.

> Task :cli:run
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version 5257c6db4f-dirty.
 /   |   \|       _/ |    |
/    |    \    |   \ |    |    Running 'requirements' under Java 11.0.14.1 on Linux with
\_______  /____|_  / |____|    1 CPUs and a maximum of 916 MiB of memory.
        \/       \/
Environment variables:
ORT_CONFIG_DIR = /root/.ort/config
ORT_DATA_DIR = /root/.ort
SHELL = /bin/bash
TERM = xterm
http_proxy = http://87.254.212.120:8080
https_proxy = http://87.254.212.120:8080
JAVA_HOME = /usr/lib/jvm/java-11-openjdk-11.0.14.1.1-1.el7_9.x86_64

Scanners:
        - Askalono: Requires 'askalono' in no specific version. Tool not found.
        - BoyterLc: Requires 'lc' in no specific version. Tool not found.
        - Licensee: Requires 'licensee' in no specific version. Tool not found.
        - ScanCode: Requires 'scancode' in no specific version. Tool not found.

PackageManagers:
        - Bower: Requires 'bower' in version >=1.8.8. Tool not found.
        - Cargo: Requires 'cargo' in no specific version. Tool not found.
        - CocoaPods: Requires 'pod' in version >=1.11.0. Tool not found.
        - Composer: Requires 'composer' in version >=1.5.0. Tool not found.
        - Conan: Requires 'conan' in version >=1.18.0. Tool not found.
        - GoDep: Requires 'dep' in no specific version. Tool not found.
        - GoMod: Requires 'go' in no specific version. Tool not found.
        - Npm: Requires 'npm' in version >=6.0.0 <8.6.0. Tool not found.
        - Pip: Requires 'pip' in no specific version. Tool not found.
        - Pipenv: Requires 'pipenv' in version >=2018.10.9. Tool not found.
        - Pub: Requires 'dart' in version >=2.10.0. Tool not found.
        - Sbt: Requires 'sbt' in version >=0.13.0. Tool not found.
        - Stack: Requires 'stack' in version >=2.1.1. Tool not found.
        - Yarn: Requires 'yarn' in version >=1.3.0 <1.23.0. Tool not found.

VersionControlSystems:
        - Cvs: Requires 'cvs' in no specific version. Tool not found.
        + Git: Requires 'git' in version >=2.29.0. Found version 1.8.3.1.
        - GitRepo: Requires 'repo' in no specific version. Tool not found.
        - Mercurial: Requires 'hg' in no specific version. Tool not found.

Other tools:
        - PythonVersion: Requires 'python3' in no specific version. Tool not found.
        - VirtualEnv: Requires 'virtualenv' in version >=15.1.0. Tool not found.

Prefix legend:
        - The tool was not found in the PATH environment.
        + The tool was found in the PATH environment, but not in the required version.
        * The tool was found in the PATH environment in the required version.

ScanCode license texts not found.

Not all tools were found in their required versions.

> Task :cli:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cli:run'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-11.0.14.1.1-1.el7_9.x86_64/bin/java'' finished with non-zero exit value 6

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

**Comment by sschuberth** [comment]
The `run` task is special in that it'll fail if the application that was run failed. And ORT's `requirements` subcommand "failed" as it did not find all required tools that need to be installed to use ORT's full potential. So, this "failure" is actually expected.

**Comment by sschuberth** [comment]
Hi @godfreysilvester, feel free to reach out on [our Slack workspace](https://join.slack.com/t/ort-talk/shared_invite/enQtMzk3MDU5Njk0Njc1LThiNmJmMjc5YWUxZTU4OGI5NmY3YTFlZWM5YTliZmY5ODc0MGMyOWIwYmRiZWFmNGMzOWY2NzVhYTI0NTJkNmY) if you have further questions.
