### ISSUE TITLE
Support gathering of metadata for Pub dependencies not hosted on pub.dev

### ISSUE THREAD

**Issue by linuxdict** [oss-review-toolkit/ort#5268]
The current implementation of the Pub package manager only gathers meta-data from pub.dev. For dependencies meta-data check it ONLY relies on querying pub.dev. This does not work for packages that are hosted elsewhere.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
