### ISSUE TITLE
Record mapping of detected licenses done for scanners

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#5296]
By now have have several places where we do scanner-specific mappings of detected licenses, like

https://github.com/oss-review-toolkit/ort/blob/0d6780d3f550859e5af1473da06f54ae339456c6/scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt#L70-L93

and

https://github.com/oss-review-toolkit/ort/blob/0d6780d3f550859e5af1473da06f54ae339456c6/scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt#L34-L60

Once these mappings are applied, the user is not able to reproduce them anymore. We should avoid that by introducing a similar concept like we already have for *declared* licenses with the [DeclaredLicenseProcessor](https://github.com/oss-review-toolkit/ort/blob/main/utils/core/src/main/kotlin/DeclaredLicenseProcessor.kt), which records the mappings applied in the ORT result.

**Comment by mnonnenmacher** [comment]
Currently the only way to "document" changes in the detected is license are `LicenseFindingCuration`s. Maybe an option to solve this issue would be to let the `DeclaredLicenseProcessor` create `LicenseFindingCuration`s on the fly, this could make it easier to integrate the solutoin in later steps like the `LicenseInfoResolver`.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
