### ISSUE TITLE
ORT scanner is not cycle safe

### ISSUE THREAD

**Issue by bennati** [oss-review-toolkit/ort#5376]
Infinite loop is caused when scanning this file
https://github.com/soldair/node-walkdir/blob/master/test/dir/symlinks/dir2/loop

**Comment by sschuberth** [comment]
Sounds more like a ScanCode issue than an ORT issue, or?

**Comment by bennati** [comment]
I am not sure, here is the error trace:
```
08:03:44.874 [main] DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Not adding 'test/dir/symlinks/dir2/sdir1/file1' to archive.
08:03:44.874 [main] DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Not adding 'test/dir/symlinks/dir2/sdir1/sdir2/sdir1/file1' to archive.
08:03:44.875 [main] DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Not adding 'test/dir/symlinks/dir2/sdir1/sdir2/sdir1/sdir2/sdir1/file1' to archive.
08:03:44.875 [main] DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Not adding 'test/dir/symlinks/dir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/file1' to archive.
08:03:44.876 [main] DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Not adding 'test/dir/symlinks/dir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/file1' to archive.
08:03:44.876 [main] DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Not adding 'test/dir/symlinks/dir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/file1' to archive.
08:03:44.877 [main] DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Not adding 'test/dir/symlinks/dir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/file1' to archive.
08:03:44.877 [main] DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Not adding 'test/dir/symlinks/dir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/file1' to archive.
08:03:44.878 [main] DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Not adding 'test/dir/symlinks/dir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/file1' to archive.
```

**Comment by sschuberth** [comment]
Ah, so it's the model's `FileArchiver`; let me fix that quickly.

**Comment by linuxdict** [comment]
Looks the issue still not fixed. 
the OSS Review Toolkit, version f6d9ea2.

Still in loop.

02:54:53.473 [main] DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Not adding 'test/dir/foo/x' to archive.
02:54:53.473 [main] DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Not adding 'test/dir/nested-symlink/found-me' to archive.
02:54:53.474 [main] DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Not adding 'test/dir/symlinks/file' to archive.
02:54:53.474 [main] DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Not adding 'test/dir/symlinks/dir2/sdir1/file1' to archive.
02:54:53.474 [main] DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Not adding 'test/dir/symlinks/dir2/sdir1/sdir2/sdir1/file1' to archive.
02:54:53.475 [main] DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Not adding 'test/dir/symlinks/dir2/sdir1/sdir2/sdir1/sdir2/sdir1/file1' to archive.
02:54:53.475 [main] DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Not adding 'test/dir/symlinks/dir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/file1'

**Comment by sschuberth** [comment]
> Looks the issue still not fixed.

Thanks for the feedback, I'll have a look.

**Comment by sschuberth** [comment]
Fixed again in https://github.com/oss-review-toolkit/ort/pull/5385, this time with a test 😉

**Comment by linuxdict** [comment]
it works now, thank for quick fix. @sschuberth
