### ISSUE TITLE
Kaniko Build Broken

### ISSUE THREAD

**Issue by jens-erdmann** [oss-review-toolkit/ort#5434]
Hi there,

I know that Kaniko is not a supported environment but it was working until recently and is required to build ORT container images in Kubernetes.
7453ae00e9cf5d0ab2cd32325df9fe6b4cfdbfd4 broke the Kaniko build. Kaniko seems to not support to just mount the archive  yet as docker builtkit is able to do so.
This is the problem I ran into:
```
INFO[1224] RUN --mount=type=bind,from=build,source=/usr/local/src/ort/cli/build/distributions/ort-$ORT_VERSION.tar,target=/opt/ort.tar tar xf /opt/ort.tar -C /opt/ort --exclude="*.bat" --strip-components 1 && /opt/ort/bin/ort requirements
INFO[1224] Taking snapshot of full filesystem...
INFO[1262] cmd: /bin/sh
INFO[1262] args: [-c tar xf /opt/ort.tar -C /opt/ort --exclude="*.bat" --strip-components 1 && /opt/ort/bin/ort requirements]
INFO[1262] Running: [/bin/sh -c tar xf /opt/ort.tar -C /opt/ort --exclude="*.bat" --strip-components 1 && /opt/ort/bin/ort requirements]
tar: /opt/ort.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 2
```

I will probably have to maintain a fork until this is fixed.

**Comment by sschuberth** [comment]
> Kaniko seems to not support to just mount the archive yet as docker builtkit is able to do so.

That's interesting, as our Docker build required BuildKit before, and we're just making use of yet another BuildKit feature. So *is* BuildKit available in Kaniko, but probably just an older version of BuildKit?

**Comment by jens-erdmann** [comment]
> So is BuildKit available in Kaniko, but probably just an older version of BuildKit?

I can not really give you a qualified answer to this. What I know is that Kaniko was catching up with supporting the features needed to build ORT. I haven't found detailed information yet if this was by accident or not.

**Comment by woznik** [comment]
Hello @jens-erdmann 
I do reproduce the same issue for the recent commit 4048e7f5481d335b598e4d6b68f5676955c8e68b
The cache cannot be mounted with `--mount=type=bind` as it is still not implemented in kaniko from my knowledge https://github.com/GoogleContainerTools/kaniko/issues/1568
Have you succeed in building ort image with kaniko?

**Comment by jens-erdmann** [comment]
> Have you succeed in building ort image with kaniko?

Sadly no. We are back to square one again and are building it manually.

**Comment by jens-erdmann** [comment]
Update: I just built the latest version of ORT with v1.9.1 of Kaniko. Latest changes to the Dockerfile seem to enable it again.
