### ISSUE TITLE
GoMod: Dependency tree contains direct dependencies which should be indirect

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#5474]
When using `go mod tidy`, it adds all indirect dependencies to `go.mod` with a trailing `// indirect` comment.
Note that whether a separate requires block is produced depends on the Go version.
Since `go mod graph` does not adhere to the ´//indirect´ comments, all indirect dependencies appear is direct dependencies in output (requirements graph). This leads to the dependency tree being flattened, see also the expected outputs of `GoModFunTest`.

So, currently the tree structure output by the analyzer seems to be wrong while the actual dependencies seem to be correct.
This issue is about fixing the tree structure (edges).

``` 
require (
	github.com/fatih/color v1.13.0
	github.com/pborman/uuid v1.2.1
	github.com/stretchr/testify v1.7.1
)

require (
	github.com/davecgh/go-spew v1.1.0 // indirect
	github.com/google/uuid v1.0.0 // indirect
	github.com/mattn/go-colorable v0.1.12 // indirect
	github.com/mattn/go-isatty v0.0.14 // indirect
	github.com/pmezard/go-difflib v1.0.0 // indirect
	golang.org/x/sys v0.0.0-20220610221304-9f5ed59c137d // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
```

**Comment by sschuberth** [comment]
@fviernau could you please complete the title for this issue?
