### ISSUE TITLE
./gradlew installDist BUILD FAILED

### ISSUE THREAD

**Issue by karippery** [oss-review-toolkit/ort#5525]
Hello, 

I cannot install ORT into my system. 

### System info

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_211 (Oracle Corporation 25.211-b12)
OS:           Windows 10 10.0 amd64

Gradle       7.4.2
node         v16.15.0
npm          8.5.5
yarn          1.22.18

**java**

OpenJDK   11.0.15 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)

### Steps to reproduce the problem
 
First clone the source code to my system : `git clone --recurse-submodules https://github.com/oss-review-toolkit/ort.git`

To build the command line interface run:
```
cd ort
./gradlew installDist
      
```

```
./gradlew installDist --info
Initialized native services in: C:\Users\jk87829\.gradle\native
Initialized jansi services in: C:\Users\jk87829\.gradle\native
The client will now receive all logging from the daemon (pid: 13460). The daemon log file: C:\Users\jk87829\.gradle\daemon\7.4.2\daemon-13460.out.log
Starting 3rd build in daemon [uptime: 24 mins 59.667 secs, performance: 97%, non-heap usage: 16% of 256 MiB]
Using 8 worker leases.
Now considering [C:\code-challenge\ort] as hierarchies to watch
Watching the file system is configured to be enabled if available
File system watching is active
Starting Build
Settings evaluated using settings file 'C:\code-challenge\ort\settings.gradle.kts'.
Using local directory build cache for the root build (location = C:\Users\jk87829\.gradle\caches\build-cache-1, removeUnusedEntriesAfter = 7 days).
Generation of dependency accessors for libs is not up-to-date because:
  Task has failed previously.
Not watching anything anymore
Watching 0 directory hierarchies to track changes
Watching 1 directory hierarchies to track changes

FAILURE: Build failed with an exception.

* What went wrong:
org.gradle.api.internal.catalog.GeneratedClassCompilationException: No Java compiler found, please ensure you are running Gradle with a JDK
> No Java compiler found, please ensure you are running Gradle with a JDK

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**gradle-wrapper.properties**

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionSha256Sum=e6d864e3b5bc05cc62041842b306383fc1fefcec359e70cebb1d470a6094ca82
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.2-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

Please help me

**Comment by sschuberth** [comment]
Please have a look at what Gradle tells you:

> No Java compiler found, please ensure you are running Gradle with a JDK

So you need to ensure that Gradle is able to find your Java 11 installation, e.g. by pointing the `JAVA_HOME` environment variable to the respective directory, or by [setting the `org.gradle.java.home` property](https://stackoverflow.com/a/21212790/1127485).

**Comment by sschuberth** [comment]
> Plugin [id: 'com.palantir.graal', version: '0.12.0'] was not found in any of the following sources:

This message might be misleading, the plugin *is* [hosted](https://plugins.gradle.org/plugin/com.palantir.graal) at the "Gradle Central Plugin Repository".

Are you maybe behind a proxy? In any case, please check that https://plugins.gradle.org/m2/ is reachable from your machine / that you've [configured Gradle to use a proxy](https://docs.gradle.org/current/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy).

**Comment by karippery** [comment]
yes it is reachable from my machine to this website https://plugins.gradle.org/m2/ 

so I want to setup add HTTP and HTTPS  proxy to \ort\gradle.properties

Am I right?

**Comment by karippery** [comment]
i don't have gradle.properties  :(

    Directory: C:\Users\jk87829\.gradle


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        06-07-2022     08:51                .tmp
d-----        05-07-2022     18:58                caches
d-----        05-07-2022     18:58                daemon
d-----        04-07-2022     10:28                jdks
d-----        04-07-2022     15:04                kotlin-profile
d-----        05-07-2022     18:58                native
d-----        04-07-2022     10:24                notifications
d-----        04-07-2022     08:34                wrapper

**Comment by sschuberth** [comment]
> i don't have gradle.properties :(

Well, you obviously have to create it. Please also take some time to read through the Gradle docs that I linked.

> so I create manually this file gradle.properties and add `systemProp.http.proxyHost=proxy.example.com`

Looks like you just added example data / copied & pasted data from the example. Of course, you need to fill in the real data that is applicable to your environment.
