### ISSUE TITLE
GoMod and GoDep packages should use the same Identifier.type

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#5533]
Currently there are two ways to refer to the same thing:

1. `GoMod::github.com/nats-io/nats-server/v2:v2.1.0`
2. `GoDep::github.com/nats-io/nats-server/v2:v2.1.0`

Use `Go` as `Identifier.type` for packages of the managers `GoMod` and `GoDep` to fix that issue.

**Comment by tsteenbe** [comment]
I would not rename GoDep only GoMod to Go as [GoDep project](https://github.com/tools/godep) has been archived and removing this type make it more difficult for ORT users to detect where they have a legacy dependency on GoDep.

**Comment by fviernau** [comment]
Currenty, GoMod uses versions strings for the identifier which correspond to the (pseudo) version specification in the [Go Modules Reference] ([url](https://go.dev/ref/mod#versions). As the `v` prefix is part of the pseudo version format, we need to decide:

1. Should we stop using the Go specific version format
2. If yes, how to map Go's versions to version strings
