### ISSUE TITLE
Invite to ort-talk Slack channel has expired

### ISSUE THREAD

**Issue by timo-HERE** [oss-review-toolkit/ort#5539]
Join us in Slack link on the https://github.com/oss-review-toolkit/ort gives following message

_This link is no longer active

To join this workspace, you’ll need to ask the person who originally invited you for a new link._

Please update the link

**Comment by sschuberth** [comment]
Also, IIRC we replaced the originally temporary invitation link with a permanent one at some point in time. Did you maybe click on an outdated link in a fork?
