### ISSUE TITLE
Error while gradle  install "rescripts' is not recognized as an internal or external command"

### ISSUE THREAD

**Issue by karippery** [oss-review-toolkit/ort#5547]
Hello,
I am trying to install ORT into my Machine but my build is failed at 95%  :(

 yarn --version 1.22.18
 npm --version 8.5.5
node --version 16.15.0
Gradle --v  7.4.2

java --version
  java 11.0.15.1 2022-04-22 LTS
  Java(TM) SE Runtime Environment 18.9 (build 11.0.15.1+2-LTS-10)
  Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.15.1+2-LTS-10, mixed mode)

**ERROR**
![errorbuild](https://user-images.githubusercontent.com/33422429/178560576-b41b788e-4263-4a7d-94bb-510e6ab2d5ef.PNG)

**Comment by sschuberth** [comment]
FYI, we had a [similar report on Slack](https://ort-talk.slack.com/archives/C9M1SKQ48/p1644850567972509) when building on Windows by @bennati, who then concluded

> It worked on a fresh windows user, possibly a previous installation of node.js somehow messed with this installation

**Comment by karippery** [comment]
Hello Thomas,
 
 still have same issue.
 when I run build after delete yarn.lock and node_moules 
```
 yarn build
yarn run v1.22.18
error Couldn't find a package.json file in "C:\\code-challenge\\ort"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
 I delete whole ort repository and clone repo again.  and I got same error 
 
```
> Task :kotlinNodeJsSetup
Setting up Node.js / NPM in 'C:\Users\jk87829\.gradle\nodejs\node-v16.13.0-win-x64'...

> Task :kotlinYarnSetup
Setting up Yarn in 'C:\Users\jk87829\.gradle\yarn\yarn-v1.22.10'...

> Task :reporter-web-app:yarnBuild FAILED
yarn run v1.22.10
$ rescripts build
'rescripts' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':reporter-web-app:yarnBuild'.
> Process 'command 'C:\Users\jk87829\.gradle\nodejs\node-v16.13.0-win-x64\node.exe'' finished with non-zero exit value

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 59s
54 actionable tasks: 52 executed, 2 from cache
```

**Comment by karippery** [comment]
> FYI, we had a [similar report on Slack](https://ort-talk.slack.com/archives/C9M1SKQ48/p1644850567972509) when building on Windows by @bennati, who then concluded
> 
> > It worked on a fresh windows user, possibly a previous installation of node.js somehow messed with this installation

I tried on my personal laptop I have the same error

**Comment by sschuberth** [comment]
@karippery would you mind giving https://github.com/oss-review-toolkit/ort/pull/5659 a try to see if that also works around this issue of yours?

**Comment by sschuberth** [comment]
I'm reopening this as I now believe to have found the real root case. Watch this space 😃

**Comment by karippery** [comment]
I didn't find the solution for this issue.  that's why I used gitlab version of ORT

**Comment by sschuberth** [comment]
> I didn't find the solution for this issue. that's why I used gitlab version of ORT

See the linked PR https://github.com/oss-review-toolkit/ort/pull/5814 for the solution.
