### ISSUE TITLE
GoMod: Improve detecting the VCS info of packages

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#5555]
BLOCKED BY BELOW TICKETS

ORT's logic for determining VCS info currently works only for GitHub. It does not re-use the (non-trivial) logic from the tooling. 
As soon as the following tickets are completed / released, we can use the Go tooling to get the VCS info.
That would make VCS detection finally work and setting the source artifact URL can be dropped.

1. https://github.com/golang/go/issues/18387
2. https://github.com/golang/go/issues/44742

**Comment by sschuberth** [comment]
> BLOCKED BY BELOW TICKETS

This does seem to be true anymore as your https://github.com/oss-review-toolkit/ort/pull/6529 proposes a fix while https://github.com/golang/go/issues/18387 is still unresolved, right?
