### ISSUE TITLE
GoMod: go list -deps error: no matching files found

### ISSUE THREAD

**Issue by mawl** [oss-review-toolkit/ort#5560]
Hey,

We have an issue with the GoMod Package Manager

```
10:35:45.499 [DefaultDispatcher-worker-1] ERROR org.ossreviewtoolkit.analyzer.managers.GoMod - Resolving GoMod dependencies for path 'go.mod' failed with: 
IOException: Running 'go list -deps -f {{with .Module}}{{.Path}} {{.Version}}{{end}} ./...' in '/builds/some-go-app' failed with exit code 1:
XXXXXX.go:10:12: pattern some.file: no matching files found
```

Content of XXXXXX.go
```go
//go:generate cp ../../../some.file .
//go:embed some.file
```
some.file ist generated during build of another component in the project.

We don't want to run "go generate/go build" as a prequisite for ort. So, are there other ways to get this working?

Cheers,
Marco

**Comment by fviernau** [comment]
@mawl would you be able to share a minimal example to reproduce this issue?

**Comment by fviernau** [comment]
Slightly related: https://github.com/golang/go/issues/49534

**Comment by mawl** [comment]
As a workaround I use following script before running oss review toolkit, which removes the go:embed directive from relevant files:

`grep -rl --include \*.go --exclude-dir=vendor "go:embed" . | xargs sed -i 's/go\:embed//g'`

**Comment by sschuberth** [comment]
@mawl, can you still reproduce the issue with the latest version of ORT?

**Comment by fviernau** [comment]
> @mawl, can you still reproduce the issue with the latest version of ORT?

This is not supposed to be fixed yet, but it's in the makings. In theory it should be fixed once the next Go version is released and we upgrade to it. See

- https://github.com/golang/tools/pull/428
- https://github.com/golang/go/pull/58522

**Comment by sschuberth** [comment]
Note to myself: The upstream Golang issues have been closed as Gerrit changes with fixes were submitted. These changes did not make it into the 1.20.0 Golang release, but it's a bit hard to figure out whether they have been [cherry-picked to any 1.20.x minor release](https://go.dev/doc/devel/release#go1.20.minor). We should probably just try with a Golang upgrade.

**Comment by fviernau** [comment]
> Note to myself: The upstream Golang issues have been closed as Gerrit changes with fixes were submitted. These changes did not make it into the 1.20.0 Golang release, but it's a bit hard to figure out whether they have been [cherry-picked to any 1.20.x minor release](https://go.dev/doc/devel/release#go1.20.minor). We should probably just try with a Golang upgrade.

Here's a first step: https://github.com/oss-review-toolkit/ort/pull/6895
