### ISSUE TITLE
Handling of multiple overlapping rule sets in the same config

### ISSUE THREAD

**Issue by pepper-jk** [oss-review-toolkit/ort#5574]
We would like to implement **rules** for multiple use cases, is in different projects that require different restrictions regarding licenses based on the customer of the project.
A very abstract example would be, external customers require us to exclude any non-permissive license, while we can use most if not all copyleft licenses.

We defined categories for our Use Cases in `license-classifications.yml` and created **rules** to return an error if a license is not permitted in one of those Use Cases. This works without problems.
Now for the usability of this config, we would like to provide the ability to specify the Use Case of the projects in regards to ORTs evaluation.

The problem I'm facing is, **where and how to define this**. Especially, if you want the rule configs to share rules, e.g. the copyleft rules in the example rules file (as warnings). The last thing you want is redundant code, even in a config repo.

From what I understand, the **rules** can not "import" any secondary files [1], as ORT only reads the `rules.kts` script and parses it with `BasicJvmScriptingHost` [2], which does not support "sideloading" as I understand it from [this post in the kotlin forum](https://discuss.kotlinlang.org/t/basicjvmscriptinghost-imports-not-working-with-stringscriptsource/24919).

Then we checked out **resolutions**, which do what we want in theory. However, the documentation explicitly tells you not to resolve license rules [3]. Also it currently is not suited for our use case, since we would need a new `RuleViolationResolutionReason`, which are defined in the code [4] instead of a config file. Right now I do not see the reason for this, as it is just matched against the given reasons and printed for the report, correct? Am I missing something?

We also looked into `curations` and `package-configurations`, both of which seem not to fit our needs here.

Maybe we can find a solution for this problem together. Preferably one without redundant rules in multiple config files.

[1] https://github.com/oss-review-toolkit/ort/blob/f506303e98c8d4d672d025e9c785c9c425d26678/cli/src/main/kotlin/commands/EvaluatorCommand.kt#L249

[2] https://github.com/oss-review-toolkit/ort/blob/f506303e98c8d4d672d025e9c785c9c425d26678/utils/scripting/src/main/kotlin/ScriptRunner.kt#L41

[3] https://github.com/oss-review-toolkit/ort/blob/main/docs/config-file-resolutions-yml.md#resolving-policy-rule-violations

[4] https://github.com/oss-review-toolkit/ort/blob/main/model/src/main/kotlin/config/RuleViolationResolutionReason.kt

**Comment by tsteenbe** [comment]
@pepper-jk I think it best we have a call to discuss you specific rules requirements - it's possible in ORT to write rule where OK / Not OK = code context + license context + delivery context + security context + customer context. However writing these type of rules in the right way requires experience.  See https://github.com/tsteenbe/ how you can reach me.

**Comment by pepper-jk** [comment]
@tsteenbe that would be great actually. Let me talk to my colleagues on Monday and get back to you. I'll just create a slack account and reach out to you. Maybe we can find a time next week that works for both of us.

Thanks for the fast reply.

**Comment by jens-erdmann** [comment]
Hey @tsteenbe , I sent you an email to your open source address as @pepper-jk . Looking forward to have this discussion.

**Comment by tsteenbe** [comment]
@pepper-jk  @jens-erdmann  Quick recap of our call today I recommend you adopt 1 rules.kts and use labels `-L` passed to ORT's Analyzer to which rules to execute. For an example see https://github.com/oss-review-toolkit/ort-config/blob/main/evaluator-rules/src/main/resources/example.rules.kts#L1214-L1242 which has a section of shared rules and a label based switch between PolicyRules.PROPRIETARY_PROJECT and PolicyRules.OSS_PROJECT based on the project=oss-project label passed (see related getEnabledPolicyRules() function in https://github.com/oss-review-toolkit/ort-config/blob/main/evaluator-rules/src/main/resources/example.rules.kts#L123-L127)

**Comment by pepper-jk** [comment]
Thanks for your help @tsteenbe.
We now use labels for our internal use cases and it works like a charm.

Sorry for the late reply, I don't use my personal GitHub account on my work machine. So every time I thought about replying and closing this issue during the work hours I couldn't and in the evening I forgot. :see_no_evil:
