### ISSUE TITLE
Switch from the "all" to the standard "bin" Gradle distribution

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#5589]
According to [this comment](https://discuss.gradle.org/t/gradle-upgrade-from-v4-7-to-v7-3-3-gives-failed-to-notify-project-evaluation-listener-error/41844/2) from @Vampire there is no value in using Gradle's "all" vs. the standard "bin" distribution when using Kotlin DSL for the build scripts, which is what we do.

Thus I propose to switch from "all" to "bin"; but first want to check esp. with @mnonnenmacher, who in the past advocated for using "all". So, objections anyone @oss-review-toolkit/core-devs?

**Comment by mnonnenmacher** [comment]
If code completion for `build.gradle.kts` files works in IntelliJ with the "bin" distribution I have no concerns with switching to "bin".
