### ISSUE TITLE
Invitation link to slack is no longer valid

### ISSUE THREAD

**Issue by itrich** [oss-review-toolkit/ort#5600]
I just tried to join your community slack and discovered that the provided link in your `README.MD` is no longer valid. Could you please generate a new invitation link? Happy to connect with you!

**Comment by sschuberth** [comment]
Hmm, I just updated the link 13 days ago, see https://github.com/oss-review-toolkit/ort/issues/5539. Are you sure that you're not using an outdated link from a fork, maybe?
