### ISSUE TITLE
docker: Deprecate Ruby 2.x and made Ruby 3.x default

### ISSUE THREAD

**Issue by heliocastro** [oss-review-toolkit/ort#5613]
Ruby is already on version 3 since a long time, but version 2 was tolerated and kept it running ok.

But modern openssl installments, version3, break compatibility with Ruby 2, and created a problem to deployments, as mostly modern code migrated already to openssl3, but not Ruby.

The possible solutions on the system side would be have the two libraries side by side, but then there's no guaranteed how long maintenance of original openssl will be kept and will force us to copile customized Ruby, which is not Ort intention at all.
Second solution is expect someone patch Ruby 2.x old installments to new openssl, which is unlikely, and again, not Ort responsibility at all.

So, for next installments is recommended to move to Ruby 3.x on docker

**Comment by sschuberth** [comment]
Just for completeness: The Ruby being installed in the `Dockerfile` is *not* for Ruby / Bundler project analysis (ORT uses JRuby for that), but solely for running CocoaPods' `pod` command. CocoaPods added support for Ruby 3 in version 1.11, and we are using version 1.11.2. So from that perspective we should be good to just upgrade to Ruby 3 and drop Ruby 2 from the `Dockerfile`.

**Comment by sschuberth** [comment]
> So, for next installments is recommended to move to Ruby 3.x on docker

This has implicitly happened with https://github.com/oss-review-toolkit/ort/pull/5651.
