### ISSUE TITLE
python:  Possible replacement of virtualenv by pyenv

### ISSUE THREAD

**Issue by heliocastro** [oss-review-toolkit/ort#5614]
ORT Python process works today creating virtual  environments by virtualenv usage.

Despite working well, it fully dependent on the python installed version, and then preventing usage of a different python, unless you install a total different one.

Using [pyenv](https://github.com/pyenv/pyenv) we eliminate this issue as be able to create any version environment on demand, as long proper base headers is installed on system, and then preventing to need an specific reinstall of python.

This opens a huge opportunity to add specific request of python versions ( 2 included ) without the need to build everything on first time and setting the python which will run for each package. 

We can even consider usage of this on case of pyproject.toml projects:

```toml
[tool.poetry.dependencies]
python = "^3.6"
```

So, then we would ask to pyenv install a 3.6.x environment

**Comment by sschuberth** [comment]
> ORT Python process works today creating virtual environments by virtualenv usage.

That's not the case anymore as of c885541a5deab9acac13e75097a41e6f1d582aa1, so I believe we can close this.
