### ISSUE TITLE
Go: add license detection

### ISSUE THREAD

**Issue by arieltorti** [oss-review-toolkit/ort#5617]
Go mod currently doesn't provide license or copyright information for go modules hence ORT doesn't provide detected licenses for them.

In order to add license detection using go mod I propose to either integrate ORT with https://github.com/google/go-licenses or apply the same technique.

**Comment by sschuberth** [comment]
> Go mod currently doesn't provide license or copyright information for go modules hence ORT doesn't provide detected licenses for them.

Before going deeper into the discussion, let's ensure we're aligned on the terminology: What ORT calls "*detected* licenses" (and copyrights) are those determined by ORT's *scanner* tool. I.e. license / copyright findings returned by a scanner like [ScanCode](https://github.com/nexB/scancode-toolkit).

On the other hand, in ORT's terminology "*declared* licenses" (and copyrights) stem from package metadata (probably `go.mod` in this case) or package registries, and these are determined by ORT's *analyzer* tool.

So, what I assume you're saying is that ORT's *analyzer* fails to find *declared* licenses for `GoMod`?

What's the source for license information that https://github.com/google/go-licenses uses, is it metadata or source code?

**Comment by fviernau** [comment]
ORT distinguishes between `declared` and `detected` licenses. `Declared` licenses are defined in the package metadata, whereas `go.mod` files do not provide any means for doing so. `Detected` licenses are the licenses which reside in any file in the corresponding code respository. As ORT's `GoMod` integration is capable of figuring out the source code location, either the source artifact '.zip'' file or the VCS location, running ORT's scan stage on top of the analysis result will in fact detect the licenses as well as copyright statements.

The license tool above seems to run a license scanner just against the LICENSE file, while ORT runs it against any file in the code repository (disregarding some exclusion patterns for special files). The primary scanner used by ORT is ScanCode. So, how does ScanCode compare to above tool you mentioned?

All in all, I believe this ticket is invalid.

**Comment by sschuberth** [comment]
> What's the source for license information that https://github.com/google/go-licenses uses, is it metadata or source code?

So, after having a look it indeed seems as if https://github.com/google/go-licenses looks a license files in the source code (not metadata) and uses https://github.com/google/licenseclassifier to identify the license / SPDX id from the license file text.

As such, I believe all is fine with ORT's `GoMod` anaylzer. But we could consider adding https://github.com/google/licenseclassifier as yet another simple *scanner* implementation.

**Comment by fviernau** [comment]
@sschuberth @arieltorti. So, shall we convert this ticket to 'adding licenseclassifier as scanner', or close this ticket and open-up a new one?

**Comment by sschuberth** [comment]
> So, shall we convert this ticket to 'adding licenseclassifier as scanner', or close this ticket and open-up a new one?

I'd say we're blocked by https://github.com/google/licenseclassifier/issues/47 for now. Let's see how they react and decide depending on that.

**Comment by arieltorti** [comment]
I'll give a try tomorrow and let you know, but if the scanner already gives license information that should be enough for me.

What would be the process, running ORT analyze and then scan on the output of the analyze ?

An further on, can be output of the scanner be used on reports ? Our intention is to have a report of the licenses used across many micro services, https://github.com/oss-review-toolkit/ort/issues/5620 talks a bit more about it.

**Comment by sschuberth** [comment]
> What would be the process, running ORT analyze and then scan on the output of the analyze ?

Yes, the input to the scanner is the output of the analyzer. See [the respective *Getting Started* section](https://github.com/oss-review-toolkit/ort/blob/main/docs/getting-started.md#5-run-the-scanner) for details.

> And further on, can the reporter use the output of the **scanner and the analyzer** ?

That's implicitly so: Analyzer and scanner do not create separate outputs, but ORT result files are always amended by the tool being run. So the analyzer result is passed to the scanner, which amends its data to the analyzer result, creating a new single output file which contains *both* the analyzer *and* the scan result.
