### ISSUE TITLE
ORT hanging on analyze for multi-project Android app

### ISSUE THREAD

**Issue by pirvudoru** [oss-review-toolkit/ort#5622]
### Description

I am trying to extract the list of dependencies of a multi-project, multi-flavor Android application using ORT.
What I am experiencing is that ort, once it reaches a certain project, it hangs. 

### Setup
Built ORT docker image at https://github.com/oss-review-toolkit/ort/commit/c2b17a999520808bb9d9dde3a51f28f66507999a
Started the docker image with --cpus="3" to give it 3 cpus
export JAVA_OPTS="-Xmx12288M" to give java room to grow up to 12 gb of memory

Example in the image:
![image](https://user-images.githubusercontent.com/2707601/181501622-fba0421c-e151-4a01-b954-c14c374e0bc7.png)

Reference to sample app to reproduce the same "hanging" behavior:
https://github.com/pirvudoru/SampleArchApp

Is there anything that can be done so that we get the analyzer-result for this type of project?

**Comment by sschuberth** [comment]
Might be related to https://github.com/oss-review-toolkit/ort/issues/4694.

**Comment by pirvudoru** [comment]
Thanks @sschuberth. Is there any way to work around this issue for the moment?

**Comment by sschuberth** [comment]
@pirvudoru there's a chance that https://github.com/oss-review-toolkit/ort/pull/6276 also helps here, would you mind giving it a try?

**Comment by sschuberth** [comment]
I've verified that with current ORT the analyzer is not hanging when scanning https://github.com/pirvudoru/SampleArchApp.
