### ISSUE TITLE
Duplicate: Support for PNPM package manager

### ISSUE THREAD

**Issue by timo-HERE** [oss-review-toolkit/ort#5642]
PNPM is addressing some shortcomings of npm and yarn and is used by some teams, so would be nice to add support for it.
* https://pnpm.io/feature-comparison
* PNPM uses pnpm-lock.yaml as lockfile

**Comment by MarcelBochtler** [comment]
Hi @timo-HERE,
PNPM is already supported since https://github.com/oss-review-toolkit/ort/pull/5611.

**Comment by tsteenbe** [comment]
@timo-HERE  Do you agree we can close this issue?

**Comment by timo-HERE** [comment]
Yes, this can be closed for sure. 
I need to learn how to do use the search. I did not get any results yesterday, but I should have found all these; https://github.com/oss-review-toolkit/ort/issues?q=pnpm

**Comment by MarcelBochtler** [comment]
Closed as this is a duplicate of https://github.com/oss-review-toolkit/ort/issues/2024
