### ISSUE TITLE
Ubuntu update java error: Cannot create worker GC thread. Out of system resources

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#5670]
Hello
I have noticed that after an update (https://github.com/oss-review-toolkit/ort/commit/25c1e9a14273875808786a02aac043bde30126e1) from `focal` to `jammy` there is a java issue during docker build

```
[0.005s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
```

After changing to focal (+composer and cargo) the image is built withouy issues.

I have tested these two images for java:

![image](https://user-images.githubusercontent.com/17202024/185912098-96a75f79-f37f-4f1b-b8a1-af8aa994b2fb.png)

Are you able to test it on your side?

**Comment by sschuberth** [comment]
> Are you able to test it on your side?

I'm not able to reproduce this on my side...

**Comment by woznik** [comment]
Hi @sschuberth 
Do you mean the `java -version` check on focal vs jammy?
My I assume that there is no problem on building the image on your side with jammy release?

**Comment by sschuberth** [comment]
> My I assume that there is no problem on building the image on your side with jammy release?

Correct. Building the Docker image (and running function tests *in* that image) is being [checked for every PR](https://github.com/oss-review-toolkit/ort/runs/7826119027?check_suite_focus=true).

**Comment by woznik** [comment]
Thank you.
I will close the issue
