### ISSUE TITLE
Gradle: `generateSpdxEnums` fails fetching files from ScanCode repo

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#5725]
I've tried multiple times on my machine, but each time the task fails [1].
The reason for that may be [2]. 

A solution could be to re-write fetching data to simply download the zip archive instead of using `SvnExport`. 
This downloads more data but can be ok as the task is not performed frequently.

[1] 
```
./gradlew generateSpdxEnums
....

Execution failed for task ':utils:spdx-utils:importScanCodeLicenseTexts'.
> svn-export failed for https://github.com/nexB/scancode-toolkit/trunk/src/licensedcode/data/licenses
  svn: E175002: PROPFIND of '/nexB/scancode-toolkit/trunk/src/licensedcode/data/licenses': 504 Gateway Timeout (https://github.com)
```
[2] https://gramps.discourse.group/t/problem-downloading-gramps-source-code-from-github-using-svn-since-24-aug/750/12

**Comment by sschuberth** [comment]
> A solution could be to re-write fetching data to simply download the zip archive instead of using `SvnExport`.

I also once had a rewrite in mind to get rid of `SvnExport`, by leveraging https://docs.github.com/en/rest/repos/contents.

**Comment by sschuberth** [comment]
> > A solution could be to re-write fetching data to simply download the zip archive instead of using `SvnExport`.
> 
> I also once had a rewrite in mind to get rid of `SvnExport`, by leveraging https://docs.github.com/en/rest/repos/contents. We probably could even use [our own GitHub GraphQL client](https://github.com/oss-review-toolkit/ort/tree/main/clients/github-graphql) for that.

**Comment by sschuberth** [comment]
I'll investigate some alternatives to rewrite the code.

**Comment by tsteenbe** [comment]
Just to provide some context - I stumble upon this bug as I was trying to update ORT to SPDX license list 3.18.
