### ISSUE TITLE
Unable to determine a revision to checkout.

### ISSUE THREAD

**Issue by durr-hackenberg** [oss-review-toolkit/ort#5771]
Good morning, 

is there a procedure to fix this error ? 

`cicd-oss-scan-1  | 08:46:56.466 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Failed attempt to download source code for 'Maven:org.openapitools:openapi-spring:0.1.0' from VcsInfo(type=Git, url=https://github.com/spring-projects/spring-boot.git, revision=, path=) took 381.383400ms.
cicd-oss-scan-1  | 08:46:56.469 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download source artifact for 'Maven:org.openapitools:openapi-spring:0.1.0' from ...
cicd-oss-scan-1  | 08:46:56.469 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Failed attempt to download source code for 'Maven:org.openapitools:openapi-spring:0.1.0' from RemoteArtifact(url=, hash=Hash(value=, algorithm=)) took 428.9us.
cicd-oss-scan-1  | 08:46:56.474 [main] ERROR org.ossreviewtoolkit.scanner.PathScanner - Could not download 'Maven:org.openapitools:openapi-spring:0.1.0': DownloadException: Download failed for 'Maven:org.openapitools:openapi-spring:0.1.0'.
cicd-oss-scan-1  | Suppressed: DownloadException: Unable to determine a revision to checkout.
cicd-oss-scan-1  |     Suppressed: IOException: No matching tag for version '0.1.0' found in [v2.0.9.RELEASE, v3.0.0-M4, v3.0.0-M2, v3.0.0-M3, v2.3.10.RELEASE, v3.0.0-M1, v1.2.0.RC1, v1.2.0.RC2, v1.1.1.RELEASE, v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.1.1.RELEASE, v2.5.14, v2.0.0.RC2, v2.0.0.RC1, v1.4.7.RELEASE, v1.0.1.RELEASE, v1.3.7.RELEASE, v1.5.2.RELEASE, v2.0.1.RELEASE, v1.5.13.RELEASE, v1.5.22.RELEASE, v2.6.0-RC1, v2.2.12.RELEASE, v1.2.4.RELEASE, v2.2.4.RELEASE, v2.3.7.RELEASE, v1.2.7.RELEASE, v2.2.7.RELEASE, v1.3.1.RELEASE, v2.3.1.RELEASE, v2.2.10.RELEASE, v1.5.11.RELEASE, v1.1.11.RELEASE, v1.1.9.RELEASE, v2.3.4.RELEASE, v1.3.4.RELEASE, v2.1.0.M1, v2.1.0.M2, v2.1.0.M3, v2.1.0.M4, v2.0.4.RELEASE, v2.1.17.RELEASE, v1.4.2.RELEASE, v2.1.9.RELEASE, v1.5.7.RELEASE, v1.3.0.M3, v1.3.0.M2, v2.3.12.RELEASE, v1.3.0.M1, v2.0.7.RELEASE, v1.3.0.M5, v1.3.0.M4, v2.6.0-M3, v2.6.0-M1, v2.2.6.RELEASE, v2.6.0-M2, v1.1.3.RELEASE, v1.3.2.RELEASE, v1.5.1.RELEASE, v1.3.5.RELEASE, v1.5.4.RELEASE, v1.5.10.RELEASE, v1.1.6.RELEASE, v2.4.0-M2, v2.4.0-M1, v2.4.0-M4, v2.4.0-M3, v1.1.0.M1, v2.1.0.RC1, v2.6.10, v2.6.11, v1.1.0.M2, v1.2.2.RELEASE, v2.1.18.RELEASE, v1.5.20.RELEASE, v2.3.9.RELEASE, v0.5.0.M4, v0.5.0.M3, v0.5.0.M2, v0.5.0.M1, v1.4.1.RELEASE, v0.5.0.M7, v0.5.0.M6, v0.5.0.M5, v1.5.19.RELEASE, v2.0.0.M3, v2.0.0.M2, v1.4.4.RELEASE, v2.0.0.M5, v2.0.0.M4, v1.1.0.RELEASE, v1.2.5.RELEASE, v2.0.0.M1, v1.5.9.RELEASE, v2.3.3.RELEASE, v2.0.0.M7, v2.1.12.RELEASE, v2.0.0.M6, v2.2.9.RELEASE, v2.1.4.RELEASE, v2.3.6.RELEASE, v2.2.11.RELEASE, v2.0.2.RELEASE, v2.1.15.RELEASE, v2.1.7.RELEASE, v2.5.0-M1, v2.2.1.RELEASE, v2.5.0-M3, v2.5.0-M2, v1.5.16.RELEASE, v1.2.0.M1, v1.2.0.M2, v1.2.8.RELEASE, v1.4.3.RELEASE, v2.4.6, v2.4.5, v2.4.8, v2.4.7, v1.3.0.RELEASE, v2.4.9, v2.3.0.RELEASE, v2.4.0, v2.4.2, v2.4.1, v1.1.10.RELEASE, v2.4.4, v2.4.3, v1.5.0.RC1, v1.5.12.RELEASE, v2.1.5.RELEASE, v2.2.8.RELEASE, v2.4.0-RC1, v1.1.5.RELEASE, v1.1.8.RELEASE, v2.1.8.RELEASE, v1.2.0.RELEASE, v2.2.0.RELEASE, v2.1.16.RELEASE, v1.5.6.RELEASE, v1.5.17.RELEASE, v2.0.5.RELEASE, v1.4.0.RC1, v1.4.6.RELEASE, v2.5.5, v2.5.4, v2.5.7, v2.5.6, v1.1.2.RELEASE, v2.5.9, v2.2.0.RC1, v2.5.8, v2.0.8.RELEASE, v2.1.2.RELEASE, v2.5.1, v2.1.10.RELEASE, v2.5.0, v2.5.3, v2.5.2, v1.5.0.RELEASE, v1.0.0.RELEASE, v2.1.13.RELEASE, v2.3.0.RC1, v1.5.3.RELEASE, v2.0.0.RELEASE, v1.5.14.RELEASE, v1.2.3.RELEASE, v2.2.13.RELEASE, v2.5.0-RC1, v1.3.8.RELEASE, v2.3.8.RELEASE, v2.2.3.RELEASE, v1.4.5.RELEASE, v1.2.6.RELEASE, v2.3.0.M1, v2.3.0.M2, v2.3.0.M3, v1.5.18.RELEASE, v2.3.0.M4, v2.6.4, v2.6.3, v2.6.6, v2.6.5, v2.6.8, v2.6.7, v2.6.9, v2.1.3.RELEASE, v2.6.0, v1.4.0.M3, v1.4.0.M2, v2.6.2, v1.4.0.M1, v2.6.1, v2.7.0-M3, v2.1.11.RELEASE, v2.7.0-M2, v2.7.0-M1, v2.3.2.RELEASE, v2.3.5.RELEASE, v1.1.12.RELEASE, v1.3.0.RC1, v2.1.14.RELEASE, v2.1.6.RELEASE, v2.0.3.RELEASE, v2.2.2.RELEASE, v1.5.15.RELEASE, v1.5.8.RELEASE, v2.2.0.M6, v2.2.0.M5, v2.2.0.M4, v2.2.0.M3, v2.2.0.M2, v2.2.0.M1, v2.3.11.RELEASE, v2.2.5.RELEASE, v2.7.3, v2.1.0.RELEASE, v2.7.2, v1.1.4.RELEASE, v2.7.0-RC1, v2.7.1, v2.7.0, v1.0.0.RC5, v1.3.3.RELEASE, v1.0.0.RC2, v1.0.0.RC1, v1.0.0.RC4, v1.0.0.RC3, v2.4.13, v1.3.6.RELEASE, v2.4.12, v2.4.11, v1.1.7.RELEASE, v2.4.10, v1.5.5.RELEASE, v1.0.2.RELEASE, v1.2.1.RELEASE, v1.4.0.RELEASE, v1.5.21.RELEASE, v1.1.0.RC1, v2.0.6.RELEASE]. Please create a tag whose name contains the version.Suppressed: DownloadException: No source artifact URL provided for 'Maven:org.openapitools:openapi-spring:0.1.0'.
cicd-oss-scan-1  | 08:46:56.474 [main] INFO  org.ossreviewtoolkit.scanner.PathScanner - Finished scanning 'Maven:org.openapitools:openapi-spring:0.1.0' in thread 'main' (2 of 2).
cicd-oss-scan-1  | Exception in thread "main" java.lang.IllegalArgumentException: The VcsInfo(type=Git, url=https://github.com/spring-projects/spring-boot.git, revision=, path=openapi-spring) of project 'Maven:org.openapitools:openapi-spring:0.1.0' cannot be found in Repository(vcs=VcsInfo(type=, url=, revision=, path=), vcsProcessed=VcsInfo(type=, url=, revision=, path=), nestedRepositories={}, config=RepositoryConfiguration(analyzer=null, excludes=Excludes(paths=[], scopes=[]), resolutions=Resolutions(issues=[], ruleViolations=[], vulnerabilities=[]), curations=Curations(packages=[], licenseFindings=[]), packageConfigurations=[], licenseChoices=LicenseChoices(repositoryLicenseChoices=[], packageLicenseChoices=[]))).
cicd-oss-scan-1  |      at org.ossreviewtoolkit.model.OrtResult.getFilePathRelativeToAnalyzerRoot(OrtResult.kt:250)
cicd-oss-scan-1  |      at org.ossreviewtoolkit.model.OrtResult.getDefinitionFilePathRelativeToAnalyzerRoot(OrtResult.kt:236)
cicd-oss-scan-1  |      at org.ossreviewtoolkit.model.config.Excludes.findPathExcludes(Excludes.kt:52)
cicd-oss-scan-1  |      at org.ossreviewtoolkit.model.OrtResult$projects$2.invoke(OrtResult.kt:109)
cicd-oss-scan-1  |      at org.ossreviewtoolkit.model.OrtResult$projects$2.invoke(OrtResult.kt:105)
cicd-oss-scan-1  |      at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
cicd-oss-scan-1  |      at org.ossreviewtoolkit.model.OrtResult.getProjects(OrtResult.kt:105)
cicd-oss-scan-1  |      at org.ossreviewtoolkit.model.OrtResult.getProject(OrtResult.kt:326)
cicd-oss-scan-1  |      at org.ossreviewtoolkit.scanner.ScannerKt.scanOrtResult(Scanner.kt:145)
cicd-oss-scan-1  |      at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:321)
cicd-oss-scan-1  |      at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:242)
cicd-oss-scan-1  |      at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
cicd-oss-scan-1  |      at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
cicd-oss-scan-1  |      at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
cicd-oss-scan-1  |      at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
cicd-oss-scan-1  |      at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
cicd-oss-scan-1  |      at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
cicd-oss-scan-1  |      at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
cicd-oss-scan-1  |      at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:83)
cicd-oss-scan-1 exited with code 1`

**Comment by mnonnenmacher** [comment]
@durr-hackenberg It looks like 'Maven:org.openapitools:openapi-spring:0.1.0' does not set SCM information in the POM file and therefore inherits it from a Spring Boot parent POM file. This is a common issue in Maven projects and can be fixed by either setting the SCM information (if the project is under your control) or by creating a [curation](https://github.com/oss-review-toolkit/ort/blob/main/docs/config-file-curations-yml.md).

**Comment by durr-hackenberg** [comment]
Thank you for you feedback.  I looked at the dependency tree. unfortunately I can't find this dependency anywhere. This is a bit strange. Can I also ignore a specific dependency completely so that the scan doesn't stop ?
Is there a way to see where this dependency comes from ?

**Comment by mnonnenmacher** [comment]
You can either directly search for it in the analyzer result file or generate a web app report (`ort report -f WebApp ...`) and look for the dependency there.
