### ISSUE TITLE
Undetected jinjava license 

### ISSUE THREAD

**Issue by ghost** [oss-review-toolkit/ort#5798]
Using [jinjava](https://github.com/HubSpot/jinjava) 2.4.1 does not get its license detected:

    jq '.analyzer .result .packages[] .package | (.id +" "+ .declared_licenses_processed.spdx_expression)' < analyzer-result.json | grep -i jinj
    "Maven:com.hubspot.jinjava:jinjava:2.4.1 "

Looks like it is licensed under Apache 2.0:

https://github.com/HubSpot/jinjava/blob/master/LICENSE

**Comment by sschuberth** [comment]
So you're looking at the `analyzer-result.json`. That file is not supposed to contain *detected* licenses as found by a scanner in files like a `LICENSE` file, but only licenses *declared* as part of package manager metadata. And indeed, the [POM](https://repo1.maven.org/maven2/com/hubspot/jinjava/jinjava/2.4.1/jinjava-2.4.1.pom) does not contain any [licenses tag](https://maven.apache.org/pom.html#Licenses). So it seems to me all is correct / as expected.

You can generally read more about the license types over [here](https://github.com/oss-review-toolkit/ort/blob/main/docs/license-handling.md).

**Comment by DaveJarvis** [comment]
Thanks! I'll file an issue against jinjava.
