### ISSUE TITLE
Bug: npm version comparison in `requirements`

### ISSUE THREAD

**Issue by lucasgonze** [oss-review-toolkit/ort#5837]
`ort requirements` is returning this assessment of npm:

`	+ Npm: Requires 'npm' in version >=6.0.0 <8.6.0. Found version 8.18.0.
`

8.18.0 is within the required range, but has the `+` flag to show:

> The tool was found in the PATH environment, but not in the required version.

**Comment by sschuberth** [comment]
Version 8.18.0 is not below version 8.6.0 as 18 > 6. So I believe all is correct.

**Comment by lucasgonze** [comment]
I apologize for investing your time in that.

**Comment by mnonnenmacher** [comment]
@lucasgonze FYI, I have created a PR to relax the NPM version requirements and upgrade to 8.15.1: #5881

**Comment by sschuberth** [comment]
> I apologize for investing your time in that.

No worries, that one was easy 😉
