### ISSUE TITLE
requirements command not finding utilities

### ISSUE THREAD

**Issue by lucasgonze** [oss-review-toolkit/ort#5839]
When I run ./cli/build/install/ort/bin/ort requirements certain items are not found, but I am confident they are on the system. Can you help by describing how the algorithm for finding these tools works?

`- ScanCode: Requires 'scancode' in no specific version. Tool not found.`

Scancode is definitely installed and running.

```
- Pip: Requires 'pip' in no specific version. Tool not found.
- Pipenv: Requires 'pipenv' in version >=2018.10.9. Tool not found.
```

These work when invoked directly as `pip` or `pipenv`, but are not found by `which`.

**Comment by sschuberth** [comment]
> but are not found by `which`.

That's the key point, ORT basically uses the same approach as `which` by simply [looking at the `PATH` environment variable](https://github.com/oss-review-toolkit/ort/blob/84517788849e5efa2909baf23ebd9217f19ff28f/cli/src/main/kotlin/commands/RequirementsCommand.kt#L117).

Things to check:
- Maybe the `PATH` environment is different for the user running ORT than for the user you're running interactively. Maybe even a completely different shell is used.
- Maybe your `pip` and `pipenv` are shell aliases, not executable files.

**Comment by sschuberth** [comment]
Feel free to reopen if you need further help, @lucasgonze.
