### ISSUE TITLE
Reporter with NoticeTemplate almost empty notice file

### ISSUE THREAD

**Issue by unclejay80** [oss-review-toolkit/ort#5848]
tested with ort-gitlab-ci

All other reports with WebApp and Co are full with information. When generating Notice
with `-O NoticeTemplate=template.id=default,summary`  the notice file is pretty empty. Just the first lines from the templates are visible.

Any idea what could go wrong?

**Comment by fviernau** [comment]
Hi @unclejay80 

Without knowing the contents of your (1) notice template `.ftl` file and (2) `license-classifications.yml` file, it's hard to say.
However, looking at `ort-config` repository, you can see that a license is included in the `NOTICE` if and only if it is assigned to the dedicated category, see https://github.com/oss-review-toolkit/ort-config/blob/60ac04e73efe6dffac30a8bc8c0857474e71c58c/notice/summary.ftl#L27-L44. Therefore, you need entries for each respective license in your `license-classifications.yml` and pass the path to the latter as argument to the notice reporter CLI command. See also https://github.com/oss-review-toolkit/ort-config/blob/main/license-classifications.yml#L31.

Does this answer your question @unclejay80 ?

**Comment by unclejay80** [comment]
Hi @fviernau ,


Thanks for your comment. I'm using the Ort default notice template https://github.com/oss-review-toolkit/ort/blob/main/reporter/src/main/resources/templates/notice/summary.ftl and the licence classification file from this repo: https://github.com/unclejay80/policy-configuration/blob/main/license-classifications.yml 


From my point of view this looks fine. 


Do I need the notice template in a dedicated path in my Ort config?

**Comment by fviernau** [comment]
Your license classifications file uses `property:include-in-notice-file` as category while the `summary.ftl` filters by just `include-in-notice-file`.  Please try if aligning these fixes the issue.

**Comment by fviernau** [comment]
@unclejay80 is your issue solved / clarified?

**Comment by unclejay80** [comment]
@fviernau I‘m currently ooo. I‘ll verify it next week and give you feedback. But I think it should be solved with your latest hints.
   
   
   
    Frank Viernau ***@***.***> hat am 10.10.2022 22:06 WEST geschrieben:
    
   
     
    
   
     
    
     
   @unclejay80 is your issue solved / clarified?

**Comment by unclejay80** [comment]
thanks, working now
