### ISSUE TITLE
Evaluator rules: Allow for making checks against the commit history of the project's code repository

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#5853]
This ticket has been extracted from #5621.

Umbrella use case: "Prior to open sourcing policy rules
Perform checks against the commit history:
- flag revealing secrets, code names and so forth
- check non-exclusive language in commit messages
- ...tbc
- idea: maybe authors / emails

**Comment by sschuberth** [comment]
This would also be required to implement custom rules for https://github.com/oss-review-toolkit/ort/issues/5629. But what's missing exactly? Couldn't rules already now leverage JGit to inspect the Git history cloned by a `ProjectSourceRule`?

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
