### ISSUE TITLE
Reporter: ResolvedLicense without locations

### ISSUE THREAD

**Issue by schvvarzekatze** [oss-review-toolkit/ort#5902]
Hello, 
I found out that for some packages it is not possible to retreive the locations of `ResolvedLicense`, e.g.
```
Package:              com.github.jai-imageio:jai-imageio-core:1.4.0
                resolvedLicense: ResolvedLicense(license=BSD-3-Clause-No-Nuclear-License, originalDeclaredLicenses=[BSD 3-clause License w/nuclear disclaimer], originalExpressions=[ResolvedOriginalExpression(expression=BSD-3-Clause-No-Nuclear-License, source=CONCLUDED, isDetectedExcluded=false), ResolvedOriginalExpression(expression=BSD-3-Clause-No-Nuclear-License, source=DECLARED, isDetectedExcluded=false)], locations=[])
```
This is the reason why it is also not possible to get the artifact location in the NOTICE file though it is visible in the analyzer, scanner and evaluator step.

Do you have an explanation why there ist no location in `ResolvedLicense` for some licenses?

Thank you very much for your help.

**Comment by schvvarzekatze** [comment]
Likely it will also help to give answer to the issue https://github.com/oss-review-toolkit/ort/issues/4959 but I think it is different problem because it seems not to be an issue regarding to the NOTICE file itself.

**Comment by sschuberth** [comment]
> Do you have an explanation why there ist no location in `ResolvedLicense` for some licenses?

These `locations` refer to `TextLocation`s that are applicaable for *detected* licenses only. In your case, however, there's only a *declared* license (`source=DECLARED`) which does not have a `TextLocation` (in the sense of a line number in the code), but the info stems from package metadata. [Here](https://github.com/oss-review-toolkit/ort/blob/main/docs/license-handling.md) you can read more about ORT's names for different licenses.
