### ISSUE TITLE
How to customize EXCEL report

### ISSUE THREAD

**Issue by schvvarzekatze** [oss-review-toolkit/ort#5904]
Hello,

as I need to get a bill of material as Excel report, I am looking for ways to extend the Excel with source artifact and copyrights provided by ort. As I have found out there is no way to configure it except to change `ExcelReporter.kt`in a specific fork of ort. Is this the only way?

Thank you for your help.

**Comment by sschuberth** [comment]
> Is this the only way?

Currently yes. And actually, in one of the last [developer meetings](https://github.com/oss-review-toolkit/ort/wiki/Developer-Meeting#2022-09-01) we were discussing to drop the current Excel reporter, as people might be better of creating the Excel they want from e.g. the evaluated model by [post-processing the JSON with a tool that can output Excel](https://geekflare.com/json-to-excel-conversion/).
