### ISSUE TITLE
OrtResult: Store scan results "by provenance"

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#5950]
The ORT file currently holds the scan results per `Identifier`.
This exhibits redundancy for e.g. the `LicenseFindings` and `CopyrightFindings` in the following cases:

1. Multiple packages originating from the same code repository. 
2. The nested provenance of several packages overlap, like e.g. the code repository has `google-test` as Git submodule.

The changes to the data structure should have in mind the planned integration of a full file listing.
So, adhere to the initial proposal outline here https://github.com/oss-review-toolkit/ort/issues/5681#issuecomment-1266644671.

**Comment by hanna-modica** [comment]
Hi @fviernau,

I kindly want to ask, if there is a timeline for solving this issue, since this is causing a bug for us, where all findings in FossID are multiplied with a amount of detected projects leading to a wrong total number of pending findings.

Best regards,
Hanna

**Comment by dobringochev** [comment]
Hi @fviernau ,
Just a gentle reminder that we really need to have your feedback when this issue is planned to be resolved?
If you want to make ORT more accurate and popular we definitely need  so any timeline for solving this issue will be highly appreciated from us.

Best Regards,
Dobrin

**Comment by fviernau** [comment]
fyi: @dobringochev I'm starting to work on the epic #6945 which covers this ticket as well.
