### ISSUE TITLE
LICENSE: Copyright Owner and Year Missing

### ISSUE THREAD

**Issue by jens-erdmann** [oss-review-toolkit/ort#5977]
https://github.com/oss-review-toolkit/ort/blob/main/LICENSE#L189

License still contains place holders of original template for copyright owner and year.
I was instructed by a legal council once, that templates are not always valid in every jurisdictions.
I am not a lawyer and this is not legal advice. This is just an observation that the copyright does not look right to me.

**Comment by sschuberth** [comment]
> License still contains place holders of original template for copyright owner and year.

Yes, that's on purpose. We use the [original Apache-2.0 license text](https://www.apache.org/licenses/LICENSE-2.0.txt), as-is including the instructions how to apply the license.

> I was instructed by a legal council once, that templates are not always valid in every jurisdictions.

Note that the template from the appendix is not supposed to apply to ORT itself.

> This is just an observation that the copyright does not look right to me.

The actual copyrights for ORT are contained in the [NOTICE](https://github.com/oss-review-toolkit/ort/blob/main/NOTICE) file.
