### ISSUE TITLE
Unable to scan go mod project with docker image

### ISSUE THREAD

**Issue by kvy1kor** [oss-review-toolkit/ort#5982]
Hello,

We tried executing scan on the go mod project.
Unfortunately we are unable to understand the root cause of the issue.
We tried providing all necessary permissions to the folders and also cleared the cache folder.
The command  go list -deps -f '{{with .Module}}{{.Path}} {{.Version}}{{end}}'  worked and able to list all the dependencies from the go.mod file and attached the screenshot for the references.

go version : go1.19.2 linux/amd64

can someone look into this issue and provide the feedback.

![image](https://user-images.githubusercontent.com/112953008/197202155-7f86f60a-7489-4aea-b59c-97620d5df71e.png)

![image](https://user-images.githubusercontent.com/112953008/197203307-11f3b762-20da-41ac-8cd2-66a299356914.png)

**Comment by mnonnenmacher** [comment]
@kvy1kor Could you try if #5993 fixes your issue?

**Comment by mnonnenmacher** [comment]
@kvy1kor Please reopen if #5993 did not fix your issue.

**Comment by kvy1kor** [comment]
We used latest docker image and executed the analyser module for the go language.

The below go.mod was used for testing

module github.com/golanf-cafe/gomod
go 1.15

require (
        github.com/pkg/errors v0.9.1
        github.com/pkg/math v0.0.0-20141027224758-f2ed9e40e245
)


Generated ORT WebApp report didn't capture the license information.

![image](https://user-images.githubusercontent.com/112953008/200536394-15eee5d0-605d-41fd-b7ff-6ce9b0d50236.png)

**Comment by kvy1kor** [comment]
Please find the below screenshot:

![image](https://user-images.githubusercontent.com/112953008/200741805-eba545f7-c24e-4b2f-be70-63689f6f905a.png)

**Comment by sschuberth** [comment]
That's even more odd @kvy1kor, I have way more columns to show in there. Can it be that you're using a very outdated version of ORT and the web-app report?
