### ISSUE TITLE
Cannot find project resources with docker run

### ISSUE THREAD

**Issue by thadubsdavid** [oss-review-toolkit/ort#6023]
Dear project team,

As I run docker command for basic info on my project I receive a log about ORT not finding my project resource. 
As my project I use a simple github project: https://github.com/OWASP/Serverless-Goat

I would be very happy about any help. We would like to use ORT for a project :)

![image](https://user-images.githubusercontent.com/34520510/199285006-e747ee91-c5e5-4e63-a0d1-62e2d2ef4ec5.png)

**Comment by sschuberth** [comment]
Your screenshot doesn't actually show any error. The info / warn logs from logback can all be ignored.

PS: `--info` sets the log level to `INFO` level. It's not a command to display info about ORT or your project. Try with `ort analyze --help` instead.

**Comment by thadubsdavid** [comment]
Thank you for commenting! My Screenshot might have been misleading.. as soon as I use the input tag it errors "cant find resource". I tried to use back-/slashes and relative paths as well..
My folder structure & Screenshot:
- source
|-- ort
 |-- (clone of your ort-repo)
|-- project
 |-- Serverless-Goat
  |--- src
   |--- api/convert
    |--- index
     |--- package

![image](https://user-images.githubusercontent.com/34520510/199302923-9f738fce-a505-493d-8137-612a6c7de6f7.png)

**Comment by sschuberth** [comment]
You're mounting your `C:\users\david\documents\source` directory from the host to `/project` inside the Docker container, so your input directory for ORT as specified by `-i` needs to refer to the latter. You probably want to use `-i /project/project/Serverless-Goat`.

**Comment by sschuberth** [comment]
Also see our [Docker hints](https://github.com/oss-review-toolkit/ort/blob/main/docs/hints-for-use-with-docker.md).

**Comment by thadubsdavid** [comment]
Thank you Sebastian. I missed that point
