### ISSUE TITLE
JSchException: invalid privatekey for scanner via github access using recent ORT docker image

### ISSUE THREAD

**Issue by schvvarzekatze** [oss-review-toolkit/ort#6024]
For scanning our repository the recent ORT docker image, I still get the `invalid privatekey` for all github packes.

Reproduction steps:
prerequisite: Recent ORT image from Oct 28th

1. Generate SHA-2 key pair for github: `ssh-keygen -t rsa -b 4096 -C "<my email for github account>"`
2. Add the public key to the github account
3. Convert the private key: `ssh-keygen -p -f ~/.ssh/id_rsa -m PEM` as described [here](https://stackoverflow.com/questions/53134212/invalid-privatekey-when-using-jsch) but without passphrase
4. Add the private key in the ort configuration of the project to be analyzed and scanned and rename it to `github_key`
5. Run the Dockerfile: with `make container`

Dockerfile
```
FROM registry.intra.XXX.com/tools/oss-review-toolkit:1.1.0

USER root
RUN mkdir -p /root/.ssh/
COPY ssh/ /root/.ssh
RUN ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
RUN ssh-keyscan -t rsa git.intra.XXX.com >> /root/.ssh/known_hosts
RUN chmod -R 0600 /root/.ssh
```

Makefile:
```
TAG = 1.3.0
PREFIX = registry.intra.XXX.com/tools/oss-review-toolkit

container:
	docker build -t $(PREFIX):$(TAG) .
push: container
	docker push $(PREFIX):$(TAG)
```
6. run ort analyzer and scanner for gradle packages

Example for `invalid privatekey` error:
```
Caused by: TransportException: ssh://git@github.com/FasterXML/jackson-annotations.git: invalid privatekey: [B@25b2dc11
    Caused by: TransportException: ssh://git@github.com/FasterXML/jackson-annotations.git: invalid privatekey: [B@25b2dc11
        Caused by: JSchException: invalid privatekey: [B@25b2dc11
```
I also tried to clone the github project locally to verify the correctness of the ssh configuration which seems to be successful:
`git clone ssh://git@github.com/FasterXML/jackson-annotations.git`
```
Cloning into 'jackson-annotations'...
remote: Enumerating objects: 9137, done.
remote: Counting objects: 100% (1172/1172), done.
remote: Compressing objects: 100% (312/312), done.
remote: Total 9137 (delta 765), reused 1078 (delta 708), pack-reused 7965
Receiving objects: 100% (9137/9137), 3.51 MiB | 6.56 MiB/s, done.
Resolving deltas: 100% (5497/5497), done.
```

**Comment by sschuberth** [comment]
> Caused by: JSchException: invalid privatekey: [B@25b2dc11

A quick Internet search brings up [this](https://stackoverflow.com/questions/53134212/invalid-privatekey-when-using-jsch).

> I also tried to clone the github project locally to verify the correctness of the ssh configuration

Note that the Git CLI is not using JGit / JSch (obviously), so I'm not surprised that this works. JGit also *finds* the private key after all, you just have to convert it to the "classic" format as described in [this answer](https://stackoverflow.com/a/55740276/1127485).

**Comment by schvvarzekatze** [comment]
Thank you, this was the conversion I actually did.

After the conversion the key begins with:
```
-----BEGIN RSA PRIVATE KEY-----
```
This should be the correct format I think.

**Comment by sschuberth** [comment]
> Thank you, this was the conversion I actually did.

Ah, sorry, I only skimmed over your report and overlook that you already found that SO post.

Are there maybe *additional* private keys in the new format that JSch could stumble over?

**Comment by schvvarzekatze** [comment]
Yes, I use the following key config:
```
Host github.com
    Hostname github.com
    IdentityFile /root/.ssh/github_key

Host git.intra.XXX.com
    Hostname git.intra.XXX.com
    IdentityFile /root/.ssh/gitlab_key
```
Both private keys are in the old format.

**Comment by sschuberth** [comment]
@schvvarzekatze can you please try whether https://github.com/oss-review-toolkit/ort/pull/6030 resolves your issue?

**Comment by pxs-ort** [comment]
> @schvvarzekatze can you please try whether #6030 resolves your issue?

Thank you, this change resolves my issue.
