### ISSUE TITLE
What is the best way to add missing copyrights?

### ISSUE THREAD

**Issue by schvvarzekatze** [oss-review-toolkit/ort#6080]
Most of the copyrights can be retreived in the NOTICE File via `getCopyrights()`. 

If copyrights are missing, it is not possible to get the [using curations](https://github.com/oss-review-toolkit/ort/blob/main/model/src/main/kotlin/PackageCurationData.kt), isn't it? There are also no copyrights in the `scan-result.yml` for these packages.

Is there a different way to save the missing copyrights permanently and retreive them when scanning the project?

Thank you for your help.

**Comment by sschuberth** [comment]
> If copyrights are missing, it is not possible to get the [using curations](https://github.com/oss-review-toolkit/ort/blob/main/model/src/main/kotlin/PackageCurationData.kt), isn't it?

There currently only is an indirect way to achieve that: You have to enable the `addAuthorsToCopyrights` feature, and then curate the `authors`.

> Is there a different way to save the missing copyrights permanently and retreive them when scanning the project?

Not currently, but this will be resolved with a planned `concludedCopyrights` feature. Work on that has been done on and off and is currently on hold, see https://github.com/oss-review-toolkit/ort/pull/5680, but I plan to pick it up soon again.

**Comment by schvvarzekatze** [comment]
@sschuberth : Thank you very much. Where exactly do I have to enable `addAuthorsToCopyrights`?

**Comment by sschuberth** [comment]
Closing this question, the feature to curate copyrights is tracked separately at https://github.com/oss-review-toolkit/ort/issues/4519.
