### ISSUE TITLE
Scanner fails at: python3: command not found

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#6136]
Hello
After building a Docker image from the commit: dd52a06308647f46d82662c453058855b836cd58 I noticed that every time I use scanner I get an error </br> `python3: command not found` </br>
![image](https://user-images.githubusercontent.com/17202024/204493520-94a8bb58-aa64-4284-9ee9-95b6cfb80320.png)

I have noticed that in the container the PATH does not contain the python bin location.
Scanner works when I add `export PATH=$PATH:/opt/python/versions/3.10.6/bin`
I didn't notice any issue during the docker build process
Has anyone of you faced the same issue?

**Comment by sschuberth** [comment]
I see in the logs that ScanCode is getting bootstrapped, which seems wrong as it should be included in the Docker image.

Which `Dockerfile` did you build, the one in the root, or the one in `docker/legacy`?

**Comment by woznik** [comment]
Hi Sebastian
The one in the root
`- /kaniko/executor --context $CI_PROJECT_DIR --build-arg ORT_VERSION="DOCKER-SNAPSHOT" --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CONTAINER_RELEASE_IMAGE`

**Comment by sschuberth** [comment]
Can you please double check why ScanCode gets bootstrapped? Like, can you check whether ScanCode is already part of the built Docker image or not?

**Comment by woznik** [comment]
I see that the scancode-toolkit is installed during the build process: <br/>
![image](https://user-images.githubusercontent.com/17202024/204514092-e65d5e8f-2056-47e6-91ae-1b9c7517c82c.png)
and then:</br>
![image](https://user-images.githubusercontent.com/17202024/204514323-08b59877-968a-4f20-8814-f009c9a690ea.png)

This is a good question why the scacode toolkit is being downloaded during the scan phase
If this is relevant in my config.yml file I have:

![image](https://user-images.githubusercontent.com/17202024/204514931-e94e861d-c1ea-4df9-b1a7-951d0aa1cfde.png)

**Comment by sschuberth** [comment]
What does your `scancodeVersion` entry in `gradle.properties` say? See

https://github.com/oss-review-toolkit/ort/blob/9e5d5214291a7e99da92db7466978ab2efbd014d/gradle.properties#L34

That's what determines the ScanCode version ORT should use. If ORT does not find exactly that version, it gets bootstrapped, even if another version of ScanCode is present in the Docker image.

**Comment by woznik** [comment]
Yes I confirm the content of the `gradle.properties` file

```
scancodeVersion = 30.1.0
```

PS: true

**Comment by sschuberth** [comment]
Ok, then the underlying problem is that the installed ScanCode version cannot be found in `PATH` (of the user you're using to run the Docker image). Actually, the issue sounds similar to https://github.com/oss-review-toolkit/ort/issues/5871, can you check out what's said there @woznik?

**Comment by woznik** [comment]
That might be the case. I will check that

**Comment by woznik** [comment]
Yes, I resolved the issue on my side
The change of the entrypoint from /opt to /usr makes a difference
Thanks a lot for the #5871  issue
