### ISSUE TITLE
NuGet: Does not handle version ranges / wildcards

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#6183]
When the "Package Reference" notation is used to specify dependencies, e.g. in a `.csproj` file, then one can specify version ranges / wildcards as outlined in [1]. When doing so, for example with a `*` as version, ORT fails with e.g. [2]. 

[1] https://learn.microsoft.com/en-us/nuget/concepts/package-versioning
[2] 
```
Failed to get package data for 'NuGet::System.IO:*': IOException: Failed to retrieve package data for 'system.io' from any of [https://api.nuget.org/v3/registration5-gz-semver2].
```

**Comment by sschuberth** [comment]
This issue is somewhat related to the `TODO` about floating versions, see

https://github.com/oss-review-toolkit/ort/blob/2c8e7ad0c1afb3d7371285ebb3d9bddb59b6657d/analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt#L360-L361

**Comment by sschuberth** [comment]
@pombredanne was this also addressed as part of https://github.com/oss-review-toolkit/ort/pull/6209?

**Comment by pombredanne** [comment]
@sschuberth correct, nuget-inspector supports star versions aka. "floating ranges" in NuGet.
As a side note, these are the weirdest things as this is the only version range syntax that I know of that also influences how the underlying dependency resolution works. Here it changes whether the resolutions picks the lowest or highest version. That's a unique whart across all package managers I know of.
Feedback and tests are welcomed.
