### ISSUE TITLE
Support the BndTools build system

### ISSUE THREAD

**Issue by ottlinger** [oss-review-toolkit/ort#623]
In order to build OSGi bundles
http://bndtools.org/
can be used.

Not sure if you could scan bnd.bnd files to at least list possible dependencies as I assume analyzing its dependencies is not that easy as one can import raw JARs and bundle them in your target JAR.

**Comment by ottlinger** [comment]
Mmmmh - as all of our projects are not publicly available I tried to search Github ....
many projects seem to integrate Gradle with BNDTools or Maven with BNDTools.
I wasn't able to find a plain BndTools-only project :-(

Example for Gradle integration:
* https://github.com/bndtools/bnd
* https://github.com/antoniomaria/gradle-karaf-bnd-project

Example Maven integration:
* https://github.com/bndtools/bnd/tree/master/maven/bnd-maven-plugin

Format example for bnd.bnd files:
* https://bnd.bndtools.org/chapters/790-format.html

**Comment by zhsc** [comment]
I would also like to vote for this issue.

An example bndtools project is bndtools itself if that helps: https://github.com/bndtools/bnd

**Comment by sschuberth** [comment]
Thanks @zhsc, that link is already part of @ottlinger's comment. Would any of you be willing and able to contribute this?

**Comment by sschuberth** [comment]
BndTools support is not planned for the foreseeable future.
