### ISSUE TITLE
Bootstrap Flutter on macOS

### ISSUE THREAD

**Issue by MarcelBochtler** [oss-review-toolkit/ort#6272]
At the moment Flutter is only bootstrapped on Windows and Linux:
https://github.com/oss-review-toolkit/ort/blob/d4ca1b5febfbfade699dee934774ab32d40159f9/analyzer/src/main/kotlin/managers/Pub.kt#L149-L153

[As Flutter is also supported on macOS](https://docs.flutter.dev/get-started/install/macos), we should also bootstrap in on this platform.
This should also take into account that macOS support two different architectures: `x86-64` and `arm64`. Flutter is available for both, therefore the bootstrapping has to select the correct one.

**Comment by sschuberth** [comment]
ec6ff750b1a5b50bed9d24d5d0f479ecb0ef98bb should have closed this instead of referring to #7503.
