### ISSUE TITLE
REUSE compliance check?

### ISSUE THREAD

**Issue by dgutson** [oss-review-toolkit/ort#6287]
Is there any benefit if ORT includes the validation of REUSE compliance?
What do you think? I would find it useful.

https://reuse.software/

**Comment by sschuberth** [comment]
We [already](https://github.com/oss-review-toolkit/ort/blob/3db1b5ce55311fec59fd538702f1650dff63d727/.github/workflows/static-analysis.yml#L73-L86) do [that](https://api.reuse.software/info/github.com/oss-review-toolkit/ort).
