### ISSUE TITLE
Publish daily ORT distribution archive on GitHub

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#6301]
To make a slimmer and faster [GitHub action for ORT](https://github.com/oss-review-toolkit/ort-ci-github-action) I would like to daily publish ORT CLI fat JAR on GitHub package registry.

Using a fatJar instead Docker image drops the provisioning time of the action to less than 25 secs compared to > 1 mins when using the Docker image so I would like using the fatJar available as an option.

**Comment by sschuberth** [comment]
Should it be published with a version in its name (and multiple versions be kept), or simply keep just a single artifact without a version?

**Comment by tsteenbe** [comment]
@sschuberth  I was thinking to start off with publishing a nightly build as snapshot version.. what do you think about that?

**Comment by fviernau** [comment]
As agreed the shadow Jar / fat Jar is being remove, because it is not working, see https://github.com/oss-review-toolkit/ort/pull/6322. So, in scope of this ticket one might want to publish the distribution archive instead.

**Comment by tsteenbe** [comment]
In the community meeting of January 12, 2023 it was agreed to use latest as the version number when publishing the distribution archive (aligned with Docker publishing) until ORT has decided on version scheme to use for releases.

**Comment by tsteenbe** [comment]
@sschuberth  @mnonnenmacher  One of our developers has been working on implementing publishing the ORT distribution archive to GitHub registry - the first attempt  can be found at https://github.com/oss-review-toolkit/ort/compare/main...aziret26:ort:nightly-build-publish.

He was able to implement a first version task but would like your guidance on how to make it a proper ORT gradle task e.g. ./gradlew publishDistArchive-commandPublicationToGitHub?

**Comment by sschuberth** [comment]
> would like your guidance on how to make it a proper ORT gradle task e.g. ./gradlew publishDistArchive-commandPublicationToGitHub?

The tasks should be created automatically when adding a new publication, see `./gradlew tasks | grep publish`.

**Comment by tsteenbe** [comment]
@sschuberth Shared in the ORT Community meeting of Aug 24th, 2023 he has been working on publishing ORT to Maven Central. He suggested to have a look at the `repositories` bit https://github.com/oss-review-toolkit/ort/pull/7412/files for how to best implement this then simply file a pull request after which the finer details can be shorted out

**Comment by sschuberth** [comment]
> To make a slimmer and faster [GitHub action for ORT](https://github.com/oss-review-toolkit/ort-ci-github-action) I would like to daily publish ORT CLI fat JAR on GitHub package registry.

@tsteenbe do we really need *daily* release archives, and do they really need to be hosted in the GitHub package registry, or are the weekly archives we publish as part of GitHub releases enough now?

**Comment by tsteenbe** [comment]
@sschuberth  Yes we need daily releases and version releases basically the same what we doing for the Docker containers. Distribution archives will be used in some of the ORT CI integrations for users who are not allowed to run containers in their CI environments (think high regulated industry users).

**Comment by sschuberth** [comment]
> @sschuberth Yes we need daily releases and version releases basically the same what we doing for the Docker containers.

I'm still closing this for now to clean stale issues, as no one who feels that weekly releases are not enough seems to be willing and able to work on daily releases.
