### ISSUE TITLE
Provide more specific stack trace for config.yml parse error?

### ISSUE THREAD

**Issue by schvvarzekatze** [oss-review-toolkit/ort#6327]
Hello, I have problems on parsing my project specific `config.yml` . It seems to caused by an indentation error.

As it is hard to find the belonging line I would like to ask if it is possible also to provide the specific error category or at least the line in config.yml as it is the case when parsing NOTICE file templates.

Thank you very much.

```
13:43:43.361 [main] INFO  org.ossreviewtoolkit.model.config.OrtConfiguration - Using ORT configuration file '/project/ort/config.yml'.
Exception in thread "main" java.lang.IllegalArgumentException: Failed to load ORT configuration: **Could not parse /project/ort/config.yml**
	at org.ossreviewtoolkit.model.config.OrtConfiguration$Companion$load$1.invoke(OrtConfiguration.kt:156)
	at org.ossreviewtoolkit.model.config.OrtConfiguration$Companion$load$1.invoke(OrtConfiguration.kt:155)
	at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:115)
	at org.ossreviewtoolkit.model.config.OrtConfiguration$Companion.load(OrtConfiguration.kt:155)
	at org.ossreviewtoolkit.cli.OrtMain.run(OrtMain.kt:171)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:76)
```

**Comment by sschuberth** [comment]
I guess we're more or less stuck with what Hoplite tells us, and that seems to be no more than "Could not parse /project/ort/config.yml". If it fails that hard, the file seems to be completely wrong. Is it maybe still in HOCON format instead of YAML?

**Comment by schvvarzekatze** [comment]
It is shown as `.yml` in IntelliJ like `curations.yml`

**Comment by sschuberth** [comment]
That does not really mean anything... it could be a HOCON (`*.conf`) file that has been renamed to `*.yml`.

**Comment by schvvarzekatze** [comment]
I think you are right because actually I did this.

**Comment by schvvarzekatze** [comment]
The stack trace also comes with only one indentation error. So the only way to find the incorrect indentation seems to install a plugin e.g. Yamllint for IntelliJ which highlights the wrong line.

**Comment by sschuberth** [comment]
> I think you are right because actually I did this.

So, if you just renamed `ort.conf` to `config.yml` this cannot work. You also need to convert the file's contents from HOCON to YAML. The `ort config --hocon-to-yaml` command can assist with this.

**Comment by sschuberth** [comment]
@schvvarzekatze is your issue solved? If so, can you share your `config.yml` (with private data replaced)?

**Comment by sschuberth** [comment]
Or maybe, if you password starts with a special char like "*", that could also lead to problems as the variable is unquoted.

**Comment by schvvarzekatze** [comment]
Yes, this `config.yml` has been valid. But if I change one indentation I would not get the line of the first parsing error. But if it is possible to highlight wrong syntax with a plugin it should also work.

**Comment by sschuberth** [comment]
> But if I change only one indentation there should be a parsing error.

Right. But in that case you should get a pretty sophisticated error message (incl. line number) like

```
    - 'ort': - Could not instantiate 'org.ossreviewtoolkit.model.config.OrtConfiguration' because:
        - 'scanner': - Could not instantiate 'org.ossreviewtoolkit.model.config.ScannerConfiguration' because:
            - 'storages': Collection element decode failure (config.yml:97:6):
                Could not find appropriate subclass of class org.ossreviewtoolkit.model.config.ScanStorageConfiguration: Tried org.ossreviewtoolkit.model.config.ClearlyDefinedStorageConfiguration, org.ossreviewtoolkit.model.config.FileBasedStorageConfiguration, org.ossreviewtoolkit.model.config.PostgresStorageConfiguration, org.ossreviewtoolkit.model.config.Sw360StorageConfiguration (config.yml:103:12)

```

in most cases.

**Comment by schvvarzekatze** [comment]
I never got the stack trace like this. Did you get it with:
`ort config --check-syntax config.yml`?

**Comment by sschuberth** [comment]
> Did you get it with: `ort config --check-syntax config.yml`?

Yes, but you would also get it with regular ORT subcommands. For testing, I de-indented `type: PACKAGE_BASED` in line 104 of your example by 2 spaces.

**Comment by schvvarzekatze** [comment]
In my case I do not get this sophisticated error message with regular ORT subcommands, but I did not define any Sw360StorageConfiguration.

**Comment by sschuberth** [comment]
FYI, [this](https://github.com/oss-review-toolkit/ort/pull/6734) upgrade of Hoplite [brings](https://github.com/sksamuel/hoplite/commit/1160c4bab5692076e870abc957755e9703e5241d) more detailed YAML error messages.
