### ISSUE TITLE
Why does the analyzer ignore settings /project/.ort.yml and exclude node_modules?

### ISSUE THREAD

**Issue by schvvarzekatze** [oss-review-toolkit/ort#6354]
I tried to run the analyzer for yarn packages, but it seems not use the current settings of the `.ort.yml`

Even if `.ort.yml` is renamed to .ort1.yml and empty there are settings enabled to ignore several project specific directorys not only those refering to gitlab.

So it is not possible to run a local analyzer.

Here an extract of the analyzer logs:

```
______________________________
/        \_______   \__    ___/ The OSS Review Toolkit, version DOCKER-SNAPSHOT.
|    |   | |       _/ |    |
|    |   | |    |   \ |    |    Running 'analyze' as 'root' under Java 17.0.5 on Linux
\________/ |____|___/ |____|    with 8 CPUs and a maximum of 6556 MiB of memory.

Environment variables:
ORT_CONFIG_DIR = /project/ort
ORT_DATA_DIR = /root/.ort
JAVA_HOME = /opt/java/openjdk
ANDROID_HOME = /opt/android-sdk

Looking for ORT configuration in the following file:
	/project/ort/config.yml

--package-managers is deprecated, use -P ort.analyzer.enabledPackageManagers=... on the ort command instead.
Looking for analyzer-specific configuration in the following files and directories:
	/project/.ort.yml (does not exist)
	/project/ort/resolutions.yml
The following package managers are enabled:
	Yarn
Analyzing project path:
	/project
14:26:32.453 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/node_modules' as it is hard-coded to be ignored.
14:26:32.454 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/build/flattened-project/.gradle' as it is hard-coded to be ignored.
14:26:32.955 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/build/flattened-project/src/main/resources' as it is hard-coded to be ignored.
14:26:32.967 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/libs/translation/src/test/resources' as it is hard-coded to be ignored.
14:26:32.967 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/libs/translation/src/main/resources' as it is hard-coded to be ignored.
14:26:32.973 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/libs/pdf/renderer-openhtmltopdf/src/test/resources' as it is hard-coded to be ignored.
14:26:32.976 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/libs/pdf/src/test/resources' as it is hard-coded to be ignored.
14:26:32.977 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/libs/pdf/src/main/resources' as it is hard-coded to be ignored.
....
```

The `resolutions.yml` does not contain excludes.

Are there still some default settings provided in by ort I have overseen which overwrite my config for `.ort.yml`?

I hope this helps to understand my question or to reproduce the ignored `.ort.yml`

Thank you very much.

**Comment by sschuberth** [comment]
> as it is hard-coded to be ignored

Emphasis is on "*hard-coded*", see https://github.com/oss-review-toolkit/ort/blob/0baf66d4e1a52ef18c739a190bc2b5bd4f62ccf7/analyzer/src/main/kotlin/PackageManager.kt#L75-L117

**Comment by schvvarzekatze** [comment]
Thank you. This means, that it does not make sense to analyze all the `package.json` files in the node_modules for a n ORT run within the local branch of the project?

**Comment by sschuberth** [comment]
I'm not sure whether I'm getting your question right, but I'm trying to answer: A `node_modules` directory should never be committed to a project's Git repo because their contents are generated by `npm install`. If `node_modules` still is present when running ORT, it's contents are ignored when looking for *projects*. Then any existing `node_modules` directory is stashed away before ORT runs `npm install` itself, the `node_modules` contents are analyzed to get the *dependencies* / packages, and then any original `node_modules` is restored.
