### ISSUE TITLE
Getting over 200K AttributeErrors while running scan command

### ISSUE THREAD

**Issue by rmorein** [oss-review-toolkit/ort#6385]
While running following Command I getting over 200K AttributeErrors (see Screenshot):

`./cli/build/install/ort/bin/ort --info scan -f JSON -i /Users/rmorein/Projects/ovgr-ios-app/ort/analyzer/analyzer-result.json -o /Users/rmorein/Projects/ovgr-ios-app/Transport/ovgr-ios-app/ort/scan`

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/123451860/214251915-b83b2ccb-272c-4bab-9094-a953a4ca6fcb.png">

**Comment by sschuberth** [comment]
@rmorein what kind of report is this? This does not look like any of ORT's core report formats.

**Comment by rmorein** [comment]
> 

This is a report from out-worbench tool:

https://github.com/oss-review-toolkit/ort-workbench

**Comment by sschuberth** [comment]
Have you configured ORT to run ScanCode with some non-default options, [like maybe `--package`](https://scancode-toolkit.readthedocs.io/en/stable/cli-reference/basic-options.html#all-basic-scan-options)?

**Comment by rmorein** [comment]
Doesn't seem so:


options:
      # A map of maps from scanner class names to scanner-specific key-value pairs.
      ScanCode:
        commandLine: '--copyright --license --info --strip-root --timeout 300'
        parseLicenseExpressions: true

**Comment by sschuberth** [comment]
Can you share the repository you're scanning, its exact revision, and the version of ScanCode you're using? So far this looks like an upstream ScanCode issue to me.

**Comment by rmorein** [comment]
@sschuberth 
ScanCode version v31.2.3.

Unfortunately I can't share the repository, since it is a customer project. I tried multiple projects, all having the same issue...

**Comment by sschuberth** [comment]
We just forward these error from ScanCode at https://github.com/oss-review-toolkit/ort/blob/33531c7be99e97b219793bf1116b00f7d32db357/scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt#L345

@pombredanne would you have any idea why ScanCode reports `AttributeError`s on simple Java files?

**Comment by rmorein** [comment]
@sschuberth Thank you for forwarding

**Comment by rmorein** [comment]
@sschuberth Is there some new Information? Has Scancode answered ?

**Comment by mnonnenmacher** [comment]
@rmorein Your error seems to be related to https://github.com/nexB/scancode-toolkit/issues/3179, so upgrading to ScanCode 31.2.4 might help.

**Comment by rmorein** [comment]
Tried it already :) Having the newest version now (31.2.4), it reduced number of errors a little (from 218K to 202K). Unfortunately the problem still remains..

**Comment by mnonnenmacher** [comment]
Then please create an issue in the ScanCode project and link it here.

**Comment by sschuberth** [comment]
Closing, as this does not seem to be an issue in ORT itself.

**Comment by pombredanne** [comment]
@rmorein just saw this!
If you do not mind to enter an issue at https://github.com/nexB/scancode-toolkit ... and may be this is happening on any Java project?
