### ISSUE TITLE
ORT Image build fails on kaniko

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#6394]
Hello
I have noticed that after a change in Dockerfile delivered in the commit 52f61ebd431d33a77d9d5affab24c48989038c66 the ORT Image build fails in Kaniko

```sh
Installing ri documentation for cocoapods-core-1.11.2
Parsing documentation for cocoapods-1.11.2
Installing ri documentation for cocoapods-1.11.2
Done installing documentation for nanaimo, colored2, claide, CFPropertyList, atomos, xcodeproj, ruby-macho, nap, molinillo, gh_inspector, fourflusher, escape, cocoapods-try, netrc, cocoapods-trunk, cocoapods-search, cocoapods-plugins, cocoapods-downloader, cocoapods-deintegrate, ffi, ethon, typhoeus, public_suffix, fuzzy_match, concurrent-ruby, httpclient, algoliasearch, addressable, zeitwerk, tzinfo, i18n, activesupport, cocoapods-core, cocoapods after 18 seconds
35 gems installed
INFO[0593] Taking snapshot of full filesystem...        
INFO[0601] Saving file . for later use                  
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: pod "runner-gjbs4cbe-project-22417-concurrent-0jmpdj" status is "Failed"
```

I think there is a problem in the:

https://github.com/oss-review-toolkit/ort/blob/52f61ebd431d33a77d9d5affab24c48989038c66/Dockerfile#L375

I suspect that mount in type bind is causing the issue for gitlab runner in Kaniko

The build in DIND works ok.

Do you have some ideas?

**Comment by sschuberth** [comment]
I have a [deja](https://github.com/oss-review-toolkit/ort/issues/5434)-[vu](https://github.com/oss-review-toolkit/ort/issues/5403) 😆

**Comment by woznik** [comment]
Well yes
Previously there was a problem when there was a mount type `bind`. 
When the mount was replaced by type `cache` there was no issue. I will try to find the commits for that.

**Comment by sschuberth** [comment]
Looks like this is the [upstream Kaniko issue](https://github.com/GoogleContainerTools/kaniko/issues/1568).

**Comment by sschuberth** [comment]
@woznik you may want to try `docker/legacy/Dockerfile` which does not use the `bind` mount type.

**Comment by jens-erdmann** [comment]
We are in the same boat as seen in the previous issue by me.
Right now we face two different problems:
- kaniko does not support bind mounts and therefore it is not able to build the root Dockerfile
- kaniko is also not able to work with `COPY --link` commands. This is blocking the docker/legacy/Dockerfile as an option.

Development has slowed down a bit in kaniko apparently. As seen in the kaniko issue linked above, they seem to refer people to buildah for the time being. This is what I hope to investigate in the coming day. A short try with buildah provided by Ubuntu was not successful.

**Comment by jens-erdmann** [comment]
In addition:
In a discussion with @sschuberth we established that at least the legacy image can be modified easily to work with kaniko by replacing `COPY --link` with `COPY` as it only impacts build time.

**Comment by sschuberth** [comment]
I don't think there's anything reasonable we can do except waiting for Kaniko to implement the latest Docker BuildKit features, so I'm closing this.
