### ISSUE TITLE
Prevent ORT from accessing projects base repo and git submodules

### ISSUE THREAD

**Issue by schwippe** [oss-review-toolkit/ort#6400]
Dear ORT team,

is there any way to prevent ORT and its tools from accessing the project's Git repo and its submodules?
A scan of the corresponding source code is not required and accessing the Git repo causes some issues related to self-signed certificates and authorization.
Moreover, the complete code of the project is already available during the run of ORT.

11:40:17.726 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Detected VCS type 'Git' from type name 'Git'.
11:40:17.955 [main] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - No Git revision for package '' and version '' found: IOException: Cannot guess a revision name from a blank version.
11:40:18.244 [main] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - Metadata has invalid Git revision '2081f2dbd2a5e1c5efa155518112887aa2fa64e9': IOException: Unable to list the remote branches.
Caused by: TransportException: https://....git: not authorized

Thank you very much.

**Comment by sschuberth** [comment]
> is there any way to prevent ORT and its tools from accessing the project's Git repo and its submodules?

For the *scanner* (which calls the *downloader*), yes, just pass `--package-types PACKAGE` to `ort scan`.

**Comment by schwippe** [comment]
Thank you, but i have still the issue when using the evaluator:

`15:55:31.034 [main] INFO  org.ossreviewtoolkit.evaluator.SourceTreeResolver - The evaluator rules attempt to access the project's source code for the first time. Fetching sources...
15:55:31.068 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download ':::' sources to '/var/folders/zm/6m3550811qscfhh9vkcryk280000gq/T/ort-Companion10850420506453795804' from VCS...
15:55:31.075 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Using processed VcsInfo(type=Git, url=https://.../ios-app.git, revision=2081f2dbd2a5e1c5efa155518112887aa2fa64e9, path=). Original was VcsInfo(type=, url=, revision=, path=).
15:55:31.660 [main] INFO  org.ossreviewtoolkit.utils.ort.OrtProxySelector - Proxy selector was successfully installed.
15:55:31.679 [main] INFO  org.ossreviewtoolkit.utils.ort.OrtAuthenticator - Authenticator was successfully installed.
15:55:31.746 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Detected VCS type 'Git' from type name 'Git'.
15:55:32.214 [main] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - No Git revision for package '' and version '' found: IOException: Cannot guess a revision name from a blank version.
15:55:32.830 [main] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - Metadata has invalid Git revision '2081f2dbd2a5e1c5efa155518112887aa2fa64e9': IOException: Unable to list the remote branches.
Caused by: TransportException: https://.../ios-app.git: not authorized
    Caused by: TransportException: https://.../ios-app.git: not authorized
15:55:32.834 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Failed attempt to download source code for ':::' from VcsInfo(type=Git, url=https://.../ios-app.git, revision=2081f2dbd2a5e1c5efa155518112887aa2fa64e9, path=) took 1.770563261s.
15:55:32.874 [main] INFO  org.ossreviewtoolkit.utils.scripting.ScriptRunner - Evaluating the script took 5.094458163s.
Exception in thread "main" org.ossreviewtoolkit.downloader.DownloadException: Download failed for ':::'.
	at org.ossreviewtoolkit.downloader.Downloader.download(Downloader.kt:73)
`

**Comment by sschuberth** [comment]
Looks like you're making use of a `ProjectSourceRule`. In that case, of course, access to the source code is required. If you really don't want to run any checks on the project itself, remove the use of the `ProjectSourceRule`.

**Comment by schwippe** [comment]
Thanks a lot, that solved my problem :)
Is there any way to directly use/analyze the currently checked out source code without ORT having to access the remote repository?

**Comment by sschuberth** [comment]
> Is there any way to directly use/analyze the currently checked out source code without ORT having to access the remote repository?

Not directly, as ORT's tools are designed to work independently / on different build nodes. But you could try patching up the Git repository URL in ORT result file to start with `file://`.
