### ISSUE TITLE
ORT scan failure for Python project

### ISSUE THREAD

**Issue by karthika-g** [oss-review-toolkit/ort#6428]
Hello,
 I am new to ORT and have been trying to scan  my python project to get the dependencies but every time it is faailing with and error as given below : 

"message" : "Resolving PIP dependencies for path 'Legacy/requirements-from-pipenv.txt' failed with: IOException: Cannot run program \"python-inspector\" (in directory \"D:\\Azure_migrated\\CDXGEN\\Python\\clearingautomation-master\\Legacy\"): CreateProcess error=2, The system cannot find the file specified\nCaused by: IOException: CreateProcess error=2, The system cannot find the file specified",
          "severity" : "ERROR"

Could you please help resolve this?

**Comment by mnonnenmacher** [comment]
If you are not using Docker to run ORT please make sure that the [python-inspector](https://github.com/nexB/python-inspector) is installed on your system and in the `PATH`.

**Comment by karthika-g** [comment]
I figured out how to do the Docker run for ORT but getting a different error this time.

![image](https://user-images.githubusercontent.com/40568919/216934423-b5090980-c812-4c8b-a2a6-67657c9b27e1.png)

**Comment by sschuberth** [comment]
That seems to be a permission issue that's specific to your setup / the way you run Docker and mount volumes.

**Comment by karthika-g** [comment]
Dockers Configurations seems to be be fine...Can you give some hint if there is something specific i need to check?

**Comment by sschuberth** [comment]
I'm not very familiar with running Docker on Windows / from PowerShell (like you seem to be doing), but you should ensure that both the Docker service and the user being user inside the Docker container have permission to access the project directory you're mounting from the host into the container.

**Comment by karthika-g** [comment]
It was an issue with the docker command i had given.. Resolved and working fine now.Thank you for the support
