### ISSUE TITLE
ORT Community Days Berlin March 15-16, 2023

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#6464]
[![ORT Community Day Banner](https://user-images.githubusercontent.com/435781/221375014-1631cb8f-2660-4341-852b-a4d3c4a4a138.jpg)](https://github.com/oss-review-toolkit/ort/wiki/ORT-Community-Day/)

EDIT: **See https://github.com/oss-review-toolkit/ort/wiki/ORT-Community-Day/ for event details.**

Organize in March two days for the ORT community to come together to:

- Share what all are doing with ORT
- Discuss user issues
- New features of improvements
- Improvements to ORT community ways of working

**Comment by tsteenbe** [comment]
Created below doodle for people to register interest and indicate which dates would work for the in March.

https://doodle.com/meeting/participate/id/aQkqE0qd

**Comment by sschuberth** [comment]
As [FOSS Backstage](https://23.foss-backstage.de/) is happening March 13-14, 2023, in Berlin anyway, maybe it makes sense to put our community day adjacent to it, like on Wednesday, Match 15?

**Comment by tsteenbe** [comment]
Voting on doodle will close Monday February 20th any time on earth.

**Comment by nnobelis** [comment]
Can we have a remote option for the Community Day ?

**Comment by sschuberth** [comment]
Agenda ideas:
- @heliocastro to demo new `orthw` script rewritten in Python
- Hack on [initial Bazel support](https://github.com/oss-review-toolkit/ort/issues/264)

**Comment by mkurzman** [comment]
I can offer to present
a) the ORT-use in our current setup and 
b) the outlook for an overall Open Source Management setup and ORTs role in it

**Comment by mkurzman** [comment]
Furthermore I would appreciate if we can have a slot to discuss the homepage and fix concrete next steps.

**Comment by tsteenbe** [comment]
Per ORT community meeting with the ORT community day will be March 15 - 16 in Berlin

**Comment by mkurzman** [comment]
Hi Thomas, concerning the venue: shall we do it in the IoT campus or at your site. If we could fix this, then I would appreciate if we could have a landing page somewhere with date and preliminary agenda, that we could spread the news using such a link to that landing page. What do you think?

**Comment by tsteenbe** [comment]
@mkurzman I send you an email to discuss venue and already set up a [landing page](https://github.com/oss-review-toolkit/ort/wiki/ORT-Community-Day/) where people can RSVP.

**Comment by sschuberth** [comment]
The ORT Community Day is a wrap! Thank you all, it was a pleasure!
