### ISSUE TITLE
Ensure that all plugins implement `Plugin` or one of its sub-interfaces

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#6507]
ORT currently supports the following `ServiceLoader`-based plugins, grouped by whether they need to support plugin-specific configuration or not.

These are plugins that may require configuration and should implement the `org.ossreviewtoolkit.utils.common.TypedConfigurablePluginFactory` interface (ticked ones already do):

- [x] [org.ossreviewtoolkit.advisor.AdviceProviderFactory](https://github.com/oss-review-toolkit/ort/blob/9e1d31e2247553d116c3ab0bde0c213bd2810fb8/advisor/src/main/kotlin/AdviceProviderFactory.kt#L34) (currently implements `org.ossreviewtoolkit.utils.common.Plugin` only)
- [x] [org.ossreviewtoolkit.analyzer.PackageConfigurationProviderFactory](https://github.com/oss-review-toolkit/ort/blob/5d2fb19944757b1dbb9856fffc7ab9e60ae1c5c2/plugins/package-configuration-providers/api/src/main/kotlin/PackageConfigurationProviderFactory.kt#L34)
- [x] [org.ossreviewtoolkit.analyzer.PackageCurationProviderFactory](https://github.com/oss-review-toolkit/ort/blob/9e1d31e2247553d116c3ab0bde0c213bd2810fb8/analyzer/src/main/kotlin/PackageCurationProviderFactory.kt#L31)
- [ ] [org.ossreviewtoolkit.analyzer.PackageManagerFactory](https://github.com/oss-review-toolkit/ort/blob/9e1d31e2247553d116c3ab0bde0c213bd2810fb8/analyzer/src/main/kotlin/PackageManagerFactory.kt#L34) (currently implements `org.ossreviewtoolkit.utils.common.Plugin` only)
- [x] [org.ossreviewtoolkit.reporter.Reporter](https://github.com/oss-review-toolkit/ort/blob/9e1d31e2247553d116c3ab0bde0c213bd2810fb8/reporter/src/main/kotlin/Reporter.kt#L33) (currently implements `org.ossreviewtoolkit.utils.common.Plugin` only)
  - This implies to migrate reporter-specific (CLI) options to `config.yml`.
  - The conversion to typed plugins was done by migrating to the new `org.ossreviewtoolkit.plugins.api.Plugin` API.
- [x] [org.ossreviewtoolkit.scanner.ScannerWrapperFactory](https://github.com/oss-review-toolkit/ort/blob/9e1d31e2247553d116c3ab0bde0c213bd2810fb8/scanner/src/main/kotlin/ScannerWrapperFactory.kt#L31) (currently implements `org.ossreviewtoolkit.utils.common.Plugin` only)

These are plugins that don't need to support configuration and should just implement the `org.ossreviewtoolkit.utils.common.Plugin` interface (ticked ones already do):

- [x] [org.ossreviewtoolkit.cli.OrtCommand](https://github.com/oss-review-toolkit/ort/blob/9e1d31e2247553d116c3ab0bde0c213bd2810fb8/cli/src/main/kotlin/OrtCommand.kt#L29)
- [x] [org.ossreviewtoolkit.downloader.VersionControlSystem](https://github.com/oss-review-toolkit/ort/blob/9e1d31e2247553d116c3ab0bde0c213bd2810fb8/downloader/src/main/kotlin/VersionControlSystem.kt#L41)
  - There's currently a conflict with the `type` properties that needs to be resolved first.

**Comment by sschuberth** [comment]
@mnonnenmacher, am I correct to assume that this issue is now obsolete in favor of implementing the new KSP-based plugin API?

**Comment by sschuberth** [comment]
> This implies to migrate reporter-specific (CLI) options to `config.yml`.

Also, now that [reporters are migrated](https://github.com/oss-review-toolkit/ort/pull/9182) to the new KSP-based plugin API, should we remove the code

https://github.com/oss-review-toolkit/ort/blob/4596888e99fe5ead8cdcd8581349532a5c574826/plugins/commands/reporter/src/main/kotlin/ReporterCommand.kt#L280-L285

and require users to leverage the generic `-P` option to specify reporter-specific options? This would align with package manager plugins.

**Comment by mnonnenmacher** [comment]
> [@mnonnenmacher](https://github.com/mnonnenmacher), am I correct to assume that this issue is now obsolete in favor of implementing the new KSP-based plugin API?

With #9403 this issue is not required anymore.

> ... require users to leverage the generic -P option to specify reporter-specific options? This would align with package manager plugins.

Does this work? I thought with `-P` you cannot set map entries.

**Comment by sschuberth** [comment]
> Does this work? I thought with `-P` you cannot set map entries.

That's true (see https://github.com/sksamuel/hoplite/issues/358), but I thought that with typed plugin options they would not be configured as a map anyway.

**Comment by mnonnenmacher** [comment]
> > Does this work? I thought with `-P` you cannot set map entries.
> 
> I thought that with typed plugin options they would not be configured as a map anyway.

In the ORT config model it still has to be a map, because the model cannot know the config classes of the plugins.

**Comment by sschuberth** [comment]
> because the model cannot know the config classes of the plugins.

Could we solve that by making the plugin config classes of the plugin themselves also discoverable via the `ServiceLoader` mechanism?

**Comment by mnonnenmacher** [comment]
> > because the model cannot know the config classes of the plugins.
> 
> Could we solve that by making the plugin config classes of the plugin themselves also discoverable via the `ServiceLoader` mechanism?

I don't think so. The config class would need a property of the config class type for the mapping to work, like `webAppReporterConfig: WebAppReporterConfig`, so it needs to be known at compile time. Or you need some interface like `ReporterPluginConfig` to determine the type during serialization, but then I don't know how this could work with `-P`. Anyway, I think it makes sense to have a separate issue for this topic if we don't have one already.
