### ISSUE TITLE
Ability to generate Markdown report

### ISSUE THREAD

**Issue by dgutson** [oss-review-toolkit/ort#6538]
..so report can be added to a github/gitlab repository (eg README.md and/or set of files).

I know that Asciidoctor output could be converted to markdown with pandoc, but I'm not sure the conversion is optimal. I think it's worth to add a native reporter.

**Comment by sschuberth** [comment]
Actually, the existing `NoticeTemplateReporter` should already be capable of doing this: All it does it to take a "templatized" plain text file (which defaults to [default.ftl](https://github.com/oss-review-toolkit/ort/blob/main/reporter/src/main/resources/templates/notice/default.ftl)), runs FreeMarker on it to expand the templates, and writes out that file again.

So, if you'd create a custom template that's actually Markdown (plus FreeMarker templates to loop over packages etc.) and specific that via the [reporter-specific `template.path` option](https://github.com/oss-review-toolkit/ort/blob/main/docs/reporters/notice-templates.md), you should get a plain Markdown file in the end.

**Comment by tsteenbe** [comment]
Ping @fviernau as we were discussing a MarkDown-based summary ORT result report for the https://github.com/oss-review-toolkit/ort-ci-github-action

**Comment by fviernau** [comment]
FYI: I'm just starting working on a report which can create a short summary of a CI run, e.g. for use with a GitHub action, which would include some template.

**Comment by mnonnenmacher** [comment]
The `NoticeTemplateReporter` was renamed to `PlainTextTemplateReporter` in https://github.com/oss-review-toolkit/ort/pull/6584. This is the recommend way to generate Markdown reports.

**Comment by sschuberth** [comment]
> This is the recommend way to generate Markdown reports.

Also, a concrete example has been merged as part of https://github.com/oss-review-toolkit/ort-config/pull/456.
