### ISSUE TITLE
Introduce an issue template chooser to direct to issues, discussion, chat

### ISSUE THREAD

**Issue by lenucksi** [oss-review-toolkit/ort#6540]
### Motivation & Context

In our [community meeting on 2023-02-23](https://github.com/oss-review-toolkit/ort/wiki/Community-Meeting#2023-02-23) @sschuberth mentioned that activating the discussion feature to enable more open discussions that more of support and less of bug/feature discussion character could make sense.

@lenucksi pointed out that using the [GitHub YAML based issue template selection feature](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) to ensure all places are appropriately advertised to people looking at the issue tab and creating new issues would be use. Community agreed. 

It was also discussed to use the discussion feature to provide a dynamic/interactive FAQ.

### Action
Hence: We need to craft the matching YAML file to configure a proper issue chooser

### Features / Directions
 - [x] Small issue template for actual bug/feature request. Have there been discussions around this already? 
 - [x] The feature supports simple links. Have one for the discussion system. Maybe to a discussion / page with some expectations how to use the discussion feature?
 - [x] Make a discussion topic that can serve as interactive/dynamic FAQ (maybe split out to an issue?)
 - [x] Make a discussion info thing pointing back to issues / making clear what goes into issues and what into discussions
 - [x] Add a link to our Slack channel with the highlight that it is for interactive/more-sync-than-async chatter. (i.e. use the issue switcher as advertisement for the slack
 - [ ] ~Likely add some small words on the `README`regarding the switcher and discussion system.~

**Comment by sschuberth** [comment]
> Make a discussion topic that can serve as interactive/dynamic FAQ (maybe split out to an issue?)

I believe that's resolved via the default ["Q&A" category](https://github.com/oss-review-toolkit/ort/discussions/categories/q-a).
