### ISSUE TITLE
message: "Failed to retrieve findings from OssIndex: IOException: Unexpected

### ISSUE THREAD

**Issue by roshvin** [oss-review-toolkit/ort#6564]
message: "Failed to retrieve findings from OssIndex: IOException: Unexpected\

we are running ORT behind proxy , could you pls suggest which URL to whitelist to connect to OssIndex

**Comment by sschuberth** [comment]
@roshvin, could you please post more of the exception text? Could be that it's basically the same issue that's going to be fixed in #6554.

**Comment by roshvin** [comment]
Hi @sschuberth  thanks .

```ort --debug advise  -i out/analyzer-result.yml -o out -a OssIndex```
we are running this command to do scanning  inside a network where we use proxy to communicate to internet .
i suspect ort to have to reach OssIndex some URL to get scan result and we need this URL to white list in our proxy so that from the scan system we can communicate to OssIndex

scan log

```
Looking for ORT configuration in the following file:
        /home/coder/.ort/config/config.yml (does not exist)

The following advisors are activated:
        OssIndex
10:17:01.472 [main] DEBUG org.ossreviewtoolkit.cli.commands.AdvisorCommand - Input ORT result file has SHA-1 hash fbaf6e30357928f32012c1f57ba14e4df26eded6.
10:17:02.285 [main] INFO  org.ossreviewtoolkit.cli.commands.AdvisorCommand - Read ORT result from 'analyzer-result.yml' (0.01 MiB) in 804.989375ms.
10:17:02.334 [DefaultDispatcher-worker-3] DEBUG org.ossreviewtoolkit.advisor.advisors.OssIndex - Getting report for 6 components (chunk 0 of 1).
10:17:02.350 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.utils.ort.OrtAuthenticator - Authenticator was successfully installed.
10:17:02.379 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.utils.ort.OrtProxySelector - Proxy selector was successfully installed.
10:17:02.636 [DefaultDispatcher-worker-3] ERROR org.ossreviewtoolkit.advisor.AdviceProvider - Failed to retrieve findings from OssIndex: IOException: Unexpected response code for CONNECT: 403
10:17:02.640 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.advisor.Advisor - Found 1 distinct vulnerabilities via OssIndex. 
10:17:02.641 [DefaultDispatcher-worker-3] DEBUG org.ossreviewtoolkit.advisor.Advisor - Affected packages:

PyPI::flask:2.2.3
PyPI::itsdangerous:2.1.2
PyPI::werkzeug:2.2.3
PyPI::jinja2:3.1.2
PyPI::markupsafe:2.1.2
PyPI::click:8.1.3

Writing advisor result to '/home/coder/Python-Test/out/advisor-result.yml'.
10:17:02.898 [main] INFO  org.ossreviewtoolkit.cli.commands.AdvisorCommand - Wrote ORT result to 'advisor-result.yml' (0.01 MiB) in 252.380360ms.
10:17:02.903 [main] DEBUG org.ossreviewtoolkit.cli.commands.AdvisorCommand - Output ORT result file has SHA-1 hash 591086b0001cd9c8d6e843382dbc26c3e6e6bd05.
The advice took 324.681181ms.
6 of 6 package(s) (not counting excluded ones) are vulnerable, with 0 vulnerabilities in total.
Resolved issues: 0 errors, 0 warnings, 0 hints.
Unresolved issues: 6 errors, 0 warnings, 0 hints.
There are 6 unresolved issues with a severity equal to or greater than the WARNING threshold.
```
error

```
10:17:02.636 [DefaultDispatcher-worker-3] ERROR org.ossreviewtoolkit.advisor.AdviceProvider - Failed to retrieve findings from OssIndex: IOException: Unexpected response code for CONNECT: 403

```

**Comment by MarcelBochtler** [comment]
I doubt that a `403` error can be solved by https://github.com/oss-review-toolkit/ort/pull/6554. I've never used the OssIndex implementation, but I cannot see any authentication mechanism.
@roshvin Is it possible that you're behind an authenticated proxy?

**Comment by sschuberth** [comment]
> @roshvin Is it possible that you're behind an authenticated proxy?

Good point, as I also cannot reproduce the issue locally.

**Comment by roshvin** [comment]
Hi , Thanks,
this proxy dont need authentication , but we have to whitelist the URL for first time to allow connection .
normally we see 403 if proxy block the URL and we give the URL to proxy team to open. but for OssIndex i am not sure which URL to open

**Comment by MarcelBochtler** [comment]
> but for OssIndex i am not sure which URL to open

That should be: `https://ossindex.sonatype.org/`

**Comment by sschuberth** [comment]
@roshvin would you be able to share the analyzer result that you're using as input for the advisor? Something seems to be wrong with the counts for this case.

**Comment by tsteenbe** [comment]
@sschuberth  Spoke to @roshvin he has put in a request with his IT team to unblock https://ossindex.sonatype.org/ and will get back to us.

**Comment by sschuberth** [comment]
@tsteenbe, @roshvin, any update here?

**Comment by roshvin** [comment]
Hi , its working now after allowing the proxy to connect this site.
