### ISSUE TITLE
Analyzer: python-inspector ignores LICENSE file unless setup.py exists

### ISSUE THREAD

**Issue by bennati** [oss-review-toolkit/ort#6585]
Python projects are ignored if a setup.py file is not present, see https://github.com/oss-review-toolkit/ort/blob/218c55fd43854850e094066ca4869c984aee4ccc/analyzer/src/main/kotlin/managers/utils/PythonInspector.kt#L197

Is this an desired behavior?
Before switching to python-inspector, projects defined by a requirements.txt or a setup.cfg were supported.

**Comment by sschuberth** [comment]
@bennati you're quoting a line of code that's irrelevant in this context. The relevant lines are at

https://github.com/oss-review-toolkit/ort/blob/218c55fd43854850e094066ca4869c984aee4ccc/analyzer/src/main/kotlin/managers/utils/PythonInspector.kt#L220-L239

`requirements.txt`-projects are still supported and our according tests pass:

https://github.com/oss-review-toolkit/ort/blob/218c55fd43854850e094066ca4869c984aee4ccc/analyzer/src/funTest/kotlin/managers/PipFunTest.kt#L72-L87

**Comment by bennati** [comment]
Hi @sschuberth I clarified the context by editing the title.
The line I mention is what causes the LICENSE file to be ignored:

for a `requirements.txt`-project, `setupProject` would be null:
https://github.com/oss-review-toolkit/ort/blob/218c55fd43854850e094066ca4869c984aee4ccc/analyzer/src/main/kotlin/managers/utils/PythonInspector.kt#L197

Hence, `projectData` would also be null:
https://github.com/oss-review-toolkit/ort/blob/218c55fd43854850e094066ca4869c984aee4ccc/analyzer/src/main/kotlin/managers/utils/PythonInspector.kt#L198

and so `declaredLicense`:
https://github.com/oss-review-toolkit/ort/blob/218c55fd43854850e094066ca4869c984aee4ccc/analyzer/src/main/kotlin/managers/utils/PythonInspector.kt#L207

**Comment by sschuberth** [comment]
I agree that we'd have no *declared* license without a `setup.py`, and that's expected. But I don't get how that's related to a `LICENSE` file, which would contain a *detected* license. So, are you maybe confusing *declared* vs. *detected* license sources here, @bennati?

**Comment by bennati** [comment]
@sschuberth yes I thought the license in LICENSE file would count as declared. 
Maybe then this is a scanner bug, or where else are licenses detected?
It would be great if someone could point me to a function where I can start looking.

**Comment by sschuberth** [comment]
> Maybe then this is a scanner bug, or where else are licenses detected?

Could be. To start with, run plain `scancode` from the CLI on the project directory and look at its raw JSON results whether they contain your expected license finding.

**Comment by bennati** [comment]
Good idea! Yes, it's detected

```
{
      "path": "LICENSE",
      "type": "file",
      "licenses": [
        {
          "key": "here-proprietary",
          "score": 100.0,
          "name": "HERE Proprietary License",
          "short_name": "HERE Proprietary",
          "category": "Commercial",
       ```

**Comment by sschuberth** [comment]
> Yes, it's detected

Ok. Next step, debug `getLicenseFindings()` in `ScanCodeResultParser.kt` to see if it's picked up.

**Comment by bennati** [comment]
Ok never mind, the issue is caused by scancode v32.x.x having a different output format, which ORT does not support yet.
We ran a scan using V31 and the issue is not there. We can close this ticket!

**Comment by sschuberth** [comment]
> Ok never mind, the issue is caused by scancode v32.x.x having a different output format, which ORT does not support yet.

Ping @maxhbr who I believe was experiencing something similar with the latest ScanCode pre-release.
