### ISSUE TITLE
ORT analyzer keeps scanning node_modules files

### ISSUE THREAD

**Issue by nanguax** [oss-review-toolkit/ort#6664]
I am trying to run a scan against the [Ant Design framework](https://github.com/ant-design/ant-design), but running into a couple issues.

The analyzer says it will only exclude the .git file even though node_modules is hard-coded to be ignored in the Package.kt file and even though the .ort.yml file in the ant-design repo is configured to exclude it.

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/104227078/224624031-b6e198bb-371e-4626-9f8c-8548e0aafe2a.png">

The analyzer looks to be parsing files in the node_modules folder and in the end results in an error because of packages that share the same id:
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/104227078/224624520-829baa66-0af7-47e4-bb98-0706674e5fd9.png">

**Comment by sschuberth** [comment]
> The analyzer looks to be parsing files in the node_modules folder

That expected. Any *existing* / committed `node_modules` directory is "ignored" / temporarily stashed away, but just to recreate a `node_modules` directory (implicitly, by running `npm install`) whose contents are then parsed. This is to ensure the `node_modules` contents are always up to date.

Also, [excluding paths](https://github.com/oss-review-toolkit/ort/blob/main/docs/config-file-ort-yml.md#excludes) does *not* mean they don't get analyzer. By default they will only show up marked as excluded in reports. If you really want to skip / ignore excluded paths, you need to pass `-P ort.analyzer.skipExcluded=true` to the analyzer.

> in the end results in an error because of packages that share the same id:

Yes, that's a know issue with some projects, and https://github.com/oss-review-toolkit/ort/pull/6533 proposes a solution (but needs more work).
