### ISSUE TITLE
package configuration file not being read by ORT

### ISSUE THREAD

**Issue by saaskesaakura345** [oss-review-toolkit/ort#6686]
Hello team, I have created a jar from the sources and trying to run the same.
I was able to successfully test policies and curations but having difficulty in passing package configuration file.

````
ort/bin/ort -c ./config.yml evaluate -i ./analyzer-result.yml --copyright-garbage-file ./copyright-garbage.yml --license-classifications-file ./license-classifications.yml --rules-file ./evaluator.rules.kts --package-configuration-file ./package-configurations.yml -o ./ 

````
![image](https://user-images.githubusercontent.com/128026849/225548209-41990a98-0760-43cb-ae77-1e47dd39dbde.png)

#### The Package configuration file used,
![image](https://user-images.githubusercontent.com/128026849/225548866-60605153-d8d3-41c5-aa25-a5729f528076.png)

#### Following link was referred
https://github.com/oss-review-toolkit/ort/blob/main/examples/package-configurations.ort.yml

Looking forward for a feedback that will help me to fix the issue.

**Comment by sschuberth** [comment]
Please note that the https://github.com/oss-review-toolkit/ort/blob/main/examples/package-configurations.ort.yml file is an example for a package configuration as it should appear as part of a repository configuration in a `.ort.yml` file that is committed to the project repository. These files are used implicitly by ORT and are not supposed to be passed explicitly to the evaluator. The evaluator instead takes an optional *list* of package configuration that override any previously configured package configurations.

**Comment by saaskesaakura345** [comment]
@sschuberth , We tried the provided suggestion by adding package configuration details in .ort.yml file in the repository.
Still we seem to run into the same error. Looking for a guidance/support to proceed further will be highly grateful.

**Comment by sschuberth** [comment]
@saaskesaakura345 please provide exactly the file you're having trouble with, and exactly the command that you're running (as text, not as screenshots, so contents are searchable).

**Comment by saaskesaakura345** [comment]
Hello @sschuberth , Greetings!
Apologies for my late response, as I have been trying to understand more on the same.
Please find the file and commands that I have been using.

I have created a .ort.yml file with the below contents,
~~~
package_configurations:
- id: "NPM::delegate:3.2.0"
  source_artifact_url: "https://registry.npmjs.org/delegate/-/delegate-3.2.0.tgz"
  path_excludes:
  - pattern: "docs/**"
    reason: "DOCUMENTATION_OF"
    comment: "This directory contains documentation which is not distributed."
  license_finding_curations:
  - detected_license: "MIT"
    reason: "CODE"
    comment: "The scanner matches a variable named `mit`."
    concluded_license: "Apache-2.0"
~~~
Following Command is used:
From the understanding provided above, the above file should be invoked implicitly. Please correct if my misunderstanding is wrong.
~~~
ort/bin/ort -c ./config.yml evaluate  -i ./analyzer-result.yml --copyright-garbage-file ./copyright-garbage.yml --rules-file ./evaluator.rules.kts -o ./
~~~

I am looking forward for a clear understanding on how to use package configurations. Thanks in Advance.

**Comment by fviernau** [comment]
> I am looking forward for a clear understanding on how to use package configurations. Thanks in Advance.

Hi @saaskesaakura345 !

A license finding curation you can think of a "matcher bit" and a "data bit".
- matcher:
  - path
  - start_lines
  - line_count
  - detected_license
- data: 
  - reason
  - comment
  - concluded_license

With the matcher you can match zero to multiple findings. Some of the matcher properties are optional.
All matched findings get modified with the provided `concluded_license`. If a finding does not point to a license text, you should consider setting concluded license to "NONE", which I suggest to do in the above case. Concluding it to `Apache-2.0` seems wrong to me. Apart from that the `path` attribute is missing and must be added.
