### ISSUE TITLE
Having private packages in poetry.lock crashes the Analyzer

### ISSUE THREAD

**Issue by qequ** [oss-review-toolkit/ort#6691]
Having a private package in `poetry.lock` and running the analyzer makes the `python-inpector` crashes with the following error log
```
  File "/home/alvaro/ort2/env_ort/lib/python3.10/site-packages/python_inspector/resolution.py", line 581, in _iter_matches
    raise NoVersionsFound(f"This package does not exist: {name}")
python_inspector.error.NoVersionsFound: This package does not exist: private-package
```

built from source and running with the command

```
/cli/build/install/ort/bin/ort analyze -i ~/my-repo/ -o ~/ort_results/
```

**Comment by qequ** [comment]
CC: @dgutson

**Comment by sschuberth** [comment]
Please report this directly to https://github.com/nexB/python-inspector/issues also.

**Comment by qequ** [comment]
@sschuberth  https://github.com/nexB/python-inspector/issues/127

**Comment by sschuberth** [comment]
Let's track this in the above-mentioned _python-inspector_ issue only.

**Comment by unclejay80** [comment]
@sschuberth there is a new Release of python inspector available which might fix this Bug: https://github.com/nexB/python-inspector/releases/tag/v0.11.0

**Comment by sschuberth** [comment]
Thanks @unclejay80. Here's the update: https://github.com/oss-review-toolkit/ort/pull/8254.
