### ISSUE TITLE
Option to choose between prod and dev

### ISSUE THREAD

**Issue by dgutson** [oss-review-toolkit/ort#6695]
Some package managers allow to differentiate dependencies for development and dependencies (e.g. requirements.txt and requirements-dev.txt). I propose to add a command line option to choose what environment to choose, or both. Usually only prod is interesting.

**Comment by sschuberth** [comment]
As it's IMO quite impossible to reliable / generally tell which e.g. requirements file suffix refers to which "scope" of dependencies (and what the semantics of that scope are), I believe that our current mechanisms of [path](https://github.com/oss-review-toolkit/ort/blob/main/docs/config-file-ort-yml.md#excluding-paths)- and [scope](https://github.com/oss-review-toolkit/ort/blob/main/docs/config-file-ort-yml.md#excluding-scopes)-excludes are sufficient to deal with this. If you'd want to ignore dependency from a `requirements-dev.txt`, you'd simply create a path exclude for that single file.
