### ISSUE TITLE
[Enhancement] Be able to load custom --index-url packages from configuration file to python-inspector

### ISSUE THREAD

**Issue by qequ** [oss-review-toolkit/ort#6711]
Currently python-inspector can't find custom packages loaded from `--index-url`.
When having private packages that pip can load via --index-url, ort should be able to find them via ort's configuration file

CC: @arieltorti @dgutson

**Comment by sschuberth** [comment]
Probably related to https://github.com/nexB/python-inspector/issues/11.

**Comment by sschuberth** [comment]
Let's track this in the above-mentioned _python-inspector_ issue only.
