### ISSUE TITLE
The SPDX reporter should export detected licenses as part of the `licenseInfoFromFiles` field

### ISSUE THREAD

**Issue by dgutson** [oss-review-toolkit/ort#6716]
None of my SPDX generated files show anything but NOASSERTION in licenseConcluded, however the web-app shows licenses in most of the projects in the "Detected License" column.

Is this an inconsistency?

What is the relationship between the web-app's "Detected License" and the SPDX report's "licenseConcluded" fields?

Example dependency:   NPM::jpeg-js:0.1.2 but it also happens with other languages' package managers.

**Comment by mnonnenmacher** [comment]
`licenseConcluded` is used for a manually concluded license. Therefore if no license was concluded via a [package curation](https://github.com/oss-review-toolkit/ort/blob/main/docs/config-file-curations-yml.md) the reporter sets the field to `NOASSERTION`, that's in line with the SPDX [specification](https://spdx.dev/spdx-specification-21-web-version/#h.2lwamvv):

> The options to populate this field are limited to [...] NOASSERTION, if [...] (ii) the SPDX file creator has made no attempt to determine this field

**Comment by mnonnenmacher** [comment]
@tsteenbe It seems like detected licenses are currently ignored in the SPDX report, only declared and detected licenses are included. Is there any dedicated field for detected licenses or should they go to `licenseConcluded`?

**Comment by sschuberth** [comment]
FYI, in general the different types of licenses in ORT are described at https://github.com/oss-review-toolkit/ort/blob/main/docs/license-handling.md.

**Comment by dgutson** [comment]
I second what @mnonnenmacher's questions. The fact is clear: webapp shows "detected license" whereas SPDX shows constantly NOASSERTION for concludedlicense. Is there any field where detected license could go in SPDX?

> This field contains the license the SPDX file creator has concluded as governing the SPDX item or alternative values, if the governing license cannot be determined. The options to populate this field are limited to:

    (a) the SPDX License List short form identifier, if the Concluded License is on the SPDX License List;

    (b) a reference to the license text denoted by the LicenseRef-[idString], if the Concluded License is not on the SPDX License List;
    (c) NOASSERTION should be used if:
        (i) the SPDX file creator has attempted to but cannot reach a reasonable objective determination of the Concluded License;
        (ii) the SPDX file creator is uncomfortable concluding a license, despite some license information being available;
        (iii) the SPDX file creator has made no attempt to determine a Concluded License;
        (iv) the SPDX file creator has intentionally provided no information (no meaning should be implied by doing so);
        or (v) there is no licensing information from which to conclude a license for the package.

> With respect to (a) and (b) above, if there is more than one Concluded License, all should be included. If the package recipient has a choice of multiple licenses, then each of the choices should be recited as a "disjunctive" license. If the Concluded License is not the same as the Declared License, a written explanation should be provided in the Comments on License field (section 3.15). With respect to (c), a written explanation in the Comments on 

> License field (section 3.15) is preferred.

**Comment by dgutson** [comment]
Maybe there should be a configura le policy about what to report in SPDX' concluded license: in my case, where I don't have curations, it is useless as is, whereas detected licenses makes complete sense.

**Comment by sschuberth** [comment]
> whereas detected licenses makes complete sense.

IMO it's super dangerous to unseen take any detected license as concluded.

**Comment by dgutson** [comment]
> the mapping from OrtResults's detected licenses to SPDX licenseInfoFromFiles is not implemented

@qequ here is the All Oracle :)

**Comment by dgutson** [comment]
Thanks!
