### ISSUE TITLE
Add schema file for license-classifications.yml

### ISSUE THREAD

**Issue by oliver** [oss-review-toolkit/ort#6720]
It would be nice to have a JSON schema file for the [license-classifications.yml](https://github.com/oss-review-toolkit/ort/blob/main/docs/config-file-license-classifications-yml.md) file. This could make it easier to edit this file e.g. in VSCode.

Or is there a reason why https://github.com/oss-review-toolkit/ort/tree/main/integrations/schemas/ contains schemas for other configuration files but not for the license-classifications.yml? E.g. is the format of that file not fixed yet?

**Comment by tsteenbe** [comment]
Marking this a good issue for new contributors - @oliver  feel free to submit a pull request for this..
