### ISSUE TITLE
downloader: Support groups when initializing git-repo 

### ISSUE THREAD

**Issue by timo-HERE** [oss-review-toolkit/ort#6738]
ORT Downloader does not support git-repo groups to enable partial checkouts 

https://github.com/oss-review-toolkit/ort/blob/0cd0bdfe2060979c422b352be7fff788ff24a686/downloader/src/main/kotlin/vcs/GitRepo.kt#L169-L171

And reference to repo documentation: https://git-repo.info/en/docs/multi-repos/git-repo-init/ 

Please add additional parameter for downloader (my proposal would be ```--vcs-repo-groups```)

**Comment by mnonnenmacher** [comment]
The solution should work also for the scanner, therefore I would propose a different implementation.

The `GitRepo` class already supports appending the manifest path to the URL as a query parameter:
https://github.com/oss-review-toolkit/ort/blob/bf3ba7e64c124c053479386a8ba84a9b035fc687/downloader/src/main/kotlin/vcs/GitRepo.kt#L153

https://github.com/oss-review-toolkit/ort/blob/bf3ba7e64c124c053479386a8ba84a9b035fc687/model/src/main/kotlin/utils/Extensions.kt#L230-L244

This could be extended to also read the groups from the URL, then it would work for all places where the `GitRepo` class is used.

@timo-HERE git-repo is rarely used so this might not get attention from the @oss-review-toolkit/core-devs soon, but contributions are welcome!

**Comment by timo-HERE** [comment]
@mnonnenmacher elegant proposal, thank you!

**Comment by sschuberth** [comment]
Any update on your planned contribution, @timo-HERE?

**Comment by sschuberth** [comment]
> Any update on your planned contribution, @timo-HERE?

Ping again @timo-HERE.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
