### ISSUE TITLE
License in the README

### ISSUE THREAD

**Issue by dgutson** [oss-review-toolkit/ort#6751]
License does not show up in SPDX when the it is in the README, for example: https://github.com/ben-ng/sourcemap-validator#readme

I'm not sure how this should be handled, but it is clearly declared as MIT.

**Comment by sschuberth** [comment]
As this is about a *detected* license, the root cause is the same as in https://github.com/oss-review-toolkit/ort/issues/6716, and the way to implement this is described [here](https://github.com/oss-review-toolkit/ort/issues/6716#issuecomment-1475875620).
