### ISSUE TITLE
Android specific Google Maven Repository dependencies warning in ORT: Could not find artifact

### ISSUE THREAD

**Issue by felix-leyva** [oss-review-toolkit/ort#6762]
Hello ORT Team,
while testing ORT on different Android Projects, I have noticed that I get warnings and issues with **androidx** dependencies.

It seems that specific repositories (example Google Maven) in the build.gradle buildscript are not recognized correctly by ORT.
This happens specially with dependencies which are on the androidx google maven repository. 
For example, an Android project with a build.gradle ex:

buildScript {
    repositories {
        **google()**
        maven { url "https://plugins.gradle.org/m2/" }
    }
}

and with an app/build.gradle

dependencies {
  implementation "androidx.appcompat:appcompat:1.3.0"
}

When running the analyzer, the following issues / warns are reported:

This is a part of the log using the --info option of analyzer:
16:33:01.835 [DefaultDispatcher-worker-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Could not find artifact androidx.appcompat:appcompat::1.3.1 in any of [https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.3.1/appcompat-1.3.1, https://plugins.gradle.org/m2/androidx/appcompat/appcompat/1.3.1/appcompat-1.3.1].
16:33:02.448 [DefaultDispatcher-worker-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Could not find artifact androidx.activity:activity::1.2.4 in any of [https://dl.google.com/dl/android/maven2/androidx/activity/activity/1.2.4/activity-1.2.4, https://plugins.gradle.org/m2/androidx/activity/activity/1.2.4/activity-1.2.4].
16:33:03.059 [DefaultDispatcher-worker-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Could not find artifact androidx.fragment:fragment::1.3.6 in any of [https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.3.6/fragment-1.3.6, https://plugins.gradle.org/m2/androidx/fragment/fragment/1.3.6/fragment-1.3.6].

Is there any specific configuration or parameter I might be missing, so that the Google Maven Repository and androix dependencies get correctly identified?

Thanks and best regards
Felix

**Comment by sschuberth** [comment]
Yes, we're aware of several Android-specific issues when analyzing Gradle projects, and I'm working on a solution as part of https://github.com/oss-review-toolkit/ort/issues/4694, which will very like also fix this issue.

**Comment by felix-leyva** [comment]
Thanks for the quick response Sebastian.
Best regards
