### ISSUE TITLE
Improve means for addressing scanner timeout errors

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#6790]
Currently, a scanner timeout timeout results in an ORT issue with error severity.
The only way the error can be addressed is by an `IssueResolution`. 
Also the user has no control over the severity of the issue at all.

Goal:

1. It should be possible that the user decides to have the issue resolve if the file where the timeout happened
   was excluded by a path exclude.
2. It may be nice to have the severity fully customizable, leading to the question whether it would make sense to 
   report timeout errors as `RuleViolations` instead of as `OrtIssue`.

**Comment by sschuberth** [comment]
Related in the context of skipping paths that are excluded from scanning: https://github.com/oss-review-toolkit/ort/issues/5018

**Comment by tsteenbe** [comment]
Scanner timeouts are technical issues so I would not want to report it as RuleViolations as the timeout limit is not set in a rule. Would rather allow to change severity based on policy rules similar to how we handle security vulnerabilities.

**Comment by sschuberth** [comment]
> Scanner timeouts are technical issues so I would not want to report it as RuleViolations

👍🏻

**Comment by fviernau** [comment]
Scan timeouts can now be excluded via path excludes, as of: https://github.com/oss-review-toolkit/ort/issues/7921.
