### ISSUE TITLE
Support for .yaml file endings

### ISSUE THREAD

**Issue by hanna-modica** [oss-review-toolkit/ort#6848]
ORT does not detect files with .yaml as ending (e.g. .ort.yaml). According to YAML FAQs [1] it is the preferred official file ending. Supporting it would mean less chances for errors.

[1] https://yaml.org/faq.html

**Comment by sschuberth** [comment]
If we did this for `.ort.yml`, we'd consequently need to do it for a bunch of other files like `config.yml`, too. It also raises the question what to do if both `.ort.yml`and `.ort.yaml` are present. Thus, personally I currently have a tendency to not support this.

**Comment by tsteenbe** [comment]
I remember us having a discussion about this, although the spec preferred file ending is.yaml the community especially within CI/CD tools choose to standardize .yml file ending see:

Examples:
- GitHub actions [supports .yml or .yaml](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions), however GitHub itself only uses .yml see e.g. https://github.com/actions/upload-artifact
- GitLab: .gitlab-ci.yml only see https://docs.gitlab.com/ee/ci/yaml/gitlab_ci_yaml.html

**Comment by bjoern-arnold** [comment]
As I raised the topic initially I just wanted to say that I understand your points. The issue was, that we didn't realize that the ort file we provided was not recognized by the tool at all (because of the wrong file suffix). Probably it would be sufficient to explicitly mention this in the documentation and/or log a warning if no ort file was found.

**Comment by sschuberth** [comment]
> Probably it would be sufficient to explicitly mention this in the documentation

Isn't https://github.com/oss-review-toolkit/ort#repository-configuration-file sufficient / explicit enough?

**Comment by tsteenbe** [comment]
I believe it may be useful to add a check for *.ort.yaml files during a project scan which throws a technical issue with a how-to-fix explaining to the use .yml is the extension to use with a reference to https://github.com/oss-review-toolkit/ort/blob/main/docs/config-file-ort-yml.md

**Comment by bjoern-arnold** [comment]
> I believe it may be useful to add a check for *.ort.yaml files during a project scan which throws a technical issue with a how-to-fix explaining to the use .yml is the extension to use with a reference to https://github.com/oss-review-toolkit/ort/blob/main/docs/config-file-ort-yml.md

Yes, that sounds good. Probably it would even be better to scan for the absence of "*.ort.yml" and report a warning if it does not exist, together with a reference to the documentation. Assuming that virtually any project requires a project specific configuration file, of course.

**Comment by tsteenbe** [comment]
Discussed in the ORT community call of April 27th 

1. Agreed to add a warning 
2. Would like to have warning for parsing issues with .ort.yml file

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.

**Comment by sschuberth** [comment]
Note that

https://github.com/oss-review-toolkit/ort/blob/bca9748d262e485b9ffed56eab08bd9bcd3a54b1/model/src/main/kotlin/FileFormat.kt#L41-L44

already knows how to treat `.yaml` file extensions. So if you *really* want to use them, you could use the varous CLI options for specifying files, like `--config`, to point to a `.yaml` file.
