### ISSUE TITLE
scan analysis alway throw IOException: Running 'git fetch --unshallow --tags origin' in

### ISSUE THREAD

**Issue by tony549** [oss-review-toolkit/ort#6902]
environment: Mac OS  ventura 13.3.1
git version : 2.39.1
java:/Library/Java/JavaVirtualMachines/jdk-11.0.10.jdk/Contents/Home

when I run following command
./ort  scan -i /root/xxx/analysis/analyzer-result.json -o /root/xxx/scan/ --skip-excluded
 
it raise following errors:

12:11:10.787 [DefaultDispatcher-worker-55] WARN  org.ossreviewtoolkit.downloader.vcs.Git - Failed to fetch everything: IOException: Running 'git fetch --unshallow --tags origin' in '/var/folders/dv/hrb3kwjd47394896xmxxdjyr0000gn/T/ort-DefaultWorkingTreeCache10225342683386441815' failed with exit code 128:
error: Could not read e0325a28411f999d505f348fec3d4e1f34f3ec9e
error: Could not read 06a766da9964acabe045cafc516f5fe78830a8f7
error: Could not read 50dc48e06a7026135c15215dbb99b5dfbec91600
error: Could not read 2682543dd68cc43b7724070867716a5052ac75c7
error: Could not read 899fc9fef2008f8bb2160efae705e7cd974b45f5
error: Could not read 9770a80f6124f6cfa50f8f3d9a2ae8bb5e14a123
error: Could not read df32727a09a9f59264b25d420e5aa20bf7f8023b
error: Could not read 1305b46102794d591dcc001c91b8013ee973ca3c
error: Could not read c611abf170ad1503d71fe615a99a9b385c0f3441
error: Could not read 0e3ab475cdb86a1dff40998945cd5be20f7221c8
error: Could not read 5076a369c090414db439d6c9b9a4b39c5664b1c9
error: Could not read 65045cdcca656a1c2f000a8dbaec3142fe8259bb
error: Could not read 77baef49563f9910641a797d9a9b8dd01c807564
error: Could not read 73230f6d0643ceccaeb8ebafe774dce048239dac
error: Could not read 0d28b43e498141bb19ff454c47cc169994303bb9
error: Could not read c17993907fdf30e9fdccf1121318c14076472acf
error: Could not read 1069f0bdadb4068ed0b62276d4e418c9a0ca30c6
error: Could not read 40e782170f16628bc2ca6eaf26e79289186f1005
error: Could not read 155c46b2922131e17c8e25ac8b9dae2cd6c2dfc8
error: Could not read 04acb5390fa4f657562321d2de88d21602edcef8
[...skipping 89 lines...]
error: Could not read b07a54e4f56e2f681b76aa36cc8cc5a746da4ea0
error: Could not read 864217e225e91d3c476d0b6272ac65b51fa81579
error: Could not read aa3a5538c003c6098185d1c948e22054e2f27488
error: Could not read 0b64d3f72fc638f84dd2142d48f0e232fd278042
error: Could not read 5dbefe6ebc19275e6bd51f207c74c0de645bef8c
error: Could not read 18545a131ff090de854ab8423d609d7d47221cef
error: Could not read 0c41d8d8d63a7d818a08bf757cb3e6dc8b951933
error: Could not read 9a1ce3e57abc7ed67fdea510e13dea498556d50a
error: Could not read e0ad1def6fa18aa630169b43be489fa2c60e8c63
error: Could not read 1a7f5e94fb0f7183151be193ff0106ea19b65749
error: Could not read decc37f0f5e13e4b4a668851f724bbd0eb921705
error: Could not read 28535157ee80221a9cfd3dc886266fc7de3475cc
error: Could not read ab324436c729ab39010d8d6869519d16c7be563b
error: Could not read c3ae06c5e2fbde52ca8be5e44bb70f8e31ea6408
error: Could not read 9693f80eabc1fe4ddef6538f11e407187ded135a
error: Could not read bd2b6e05564d7ff411f6855043d2d1762565d702
error: Could not read 98180e10ec30987d4ed2634a3b83237435321c03
error: Could not read 8d0995698df2ad7400c01dc62b303c7db605e422
fatal: error in object: unshallow dbd344bcb79e48cd3a27ee3aca99e7a5d5460517

(Above output is limited to each 20 heading and tailing lines.)
12:12:28.030 [DefaultDispatcher-worker-7] WARN  org.ossreviewtoolkit.downloader.vcs.Git - Failed to fetch everything: IOException: Running 'git fetch --unshallow --tags origin' in '/var/folders/dv/hrb3kwjd47394896xmxxdjyr0000gn/T/ort-DefaultWorkingTreeCache10225342683386441815' failed with exit code 128:
error: Could not read e0325a28411f999d505f348fec3d4e1f34f3ec9e

**Comment by sschuberth** [comment]
Which version of ORT are you using? Is the scan command able to recover in the end, or does the top-level scan command also fail? If so, with which message exactly?

**Comment by tony549** [comment]
the last version, I just clone the master branch with command "git clone https://github.com/oss-review-toolkit/ort.git". and build it. then use the ./ort scan command.

no, the top-level scan command not fail. no message print.
if it is not a problem , I try to rerun again and wait how the the top-level scan command response. thank you

**Comment by tony549** [comment]
finaly the main thread show show work, so i think this is not a problem
please please close this ticket
