### ISSUE TITLE
GradleInspector has difficulties running in parallel in Docker image due to cache locks

### ISSUE THREAD

**Issue by devcooch** [oss-review-toolkit/ort#6915]
I am testing new GradleInspector introduced by @sschuberth .

Sometimes parallel scanning causes lock issues on gradle cache (I guess under `~/.gradle`).

I am attaching a screenshot with an example of such issues:
![image](https://user-images.githubusercontent.com/2089015/234051525-23c9b010-2a62-4409-aacd-e3b8e603905a.png)

**Comment by sschuberth** [comment]
A single analyzer is never run in parallel on multiple files, so this definitely should not happen. Are you sure you haven't enabled both the "Gradle" and "GradleInspector" analyzers at the same time? Also, does the same happen if you only use the "Gradle" analyzer?

**Comment by devcooch** [comment]
I am sure I used only GradleInspector. I didn't try with Gradle. However I am thinking now that it could be cause by Windows antivirus as my setup was like this:
Windows -> WSL (`~/.gradle` folder here) -> Docker (attaching as volume).
When I skip attaching volume for `~/.gradle` folder it's not happening.

**Comment by sschuberth** [comment]
> When I skip attaching volume for `~/.gradle` folder it's not happening.

So, are we good to close this?

**Comment by devcooch** [comment]
Good question.. I guess it's OK for scanning use case, so yeah, let's close
