### ISSUE TITLE
Exclude packages from analyzer/scanner

### ISSUE THREAD

**Issue by brueggenthies-ams** [oss-review-toolkit/ort#6923]
Hey,

I am currently trying out `ort` in an Android Project. I was wondering if there is any possibility to exclude any packages from the analyze or scan step that are trusted. I would, for example, exclude the `kotlin` dependency to reduce runtime of the analysis.

I found the possibility to [exclude specific files or scopes](https://github.com/oss-review-toolkit/ort/blob/main/docs/config-file-ort-yml.md#excludes), but could not determine if this was also possible for external dependencies/packages.

Thanks,
Tim

**Comment by sschuberth** [comment]
> could not determine if this was also possible for external dependencies/packages.

It's currently not, but IIUC your ask goes into the direction of https://github.com/oss-review-toolkit/ort/issues/5105, right?

**Comment by sschuberth** [comment]
Actually, we also have https://github.com/oss-review-toolkit/ort/issues/3537.

**Comment by sschuberth** [comment]
> Actually, we also have #3537.

Let's close in favor of that issue.
