### ISSUE TITLE
scanner: Store file listings in a dedicated storage

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#6943]

**Comment by fviernau** [comment]
We currently have the interface `FileArchiverStorage` with `FileArchiverFileStorage` and `PostgresFileArchiverStorage` as implementations. These can be re-used after generalizing them, e.g. rename as follows

1. `FileArchiverStorage` -> `ProvenanceFileStorage`
2. `FileArchiverFileStorage` -> `FileProvenanceFileStorage`
3. `PostgresFileArchiverStorage` -> `PosgresProvenanceFileStorage`

and then make the interface / implementation agnostic of any file extension and file name.

**Comment by sschuberth** [comment]
> These can be re-used after generalizing them, e.g. rename as follows

But aren't your proposed names actually more specific than more generic? Because previously, e.g. `FileArchiverFileStorage` could store any file archives, even those not containing any provenance-related information.
