### ISSUE TITLE
OrtResult: Make the file listing complete

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#6946]
Goal: 
- Instead of only listing the files corresponding to license and copyright findings,
  list "all" files
- Prepare for computing package verification code on-the-fly
- unlock optimization potential for file existence checks in policy rules
- Exclude certain files:
  1. Use hard coded exclude pattern, excluding files under e.g. `.git`. These exclude
      patterns must be decoupled from any other existing exclude patterns as these do
      not match the purpose
  2. VCS paths can be considered (can be extracted to separate task)

**Comment by sschuberth** [comment]
> Instead of only listing the files corresponding to license and copyright findings, list "all" files

FYI @jens-erdmann, this should be what you need.

**Comment by jens-erdmann** [comment]
So this is enabling further processing of data acquired by #5681, correct?

**Comment by fviernau** [comment]
> So this is enabling further processing of data acquired by #5681, correct?

That ticket will be covered by this epic: #6945.

**Comment by fviernau** [comment]
This ticket is now fully covered by #6944, so closing this one.

**Comment by sschuberth** [comment]
It's still open, @fviernau 😉
