### ISSUE TITLE
Unable to trigger policy violations- evaluator.rules.kts file

### ISSUE THREAD

**Issue by kvy1kor** [oss-review-toolkit/ort#6960]
Hello,

We have written the policy for our project use cases which would trigger copyleft policy violation if the project use case matches certain conditions as shared below and this is working as expected.

![image](https://user-images.githubusercontent.com/112953008/235843125-174e6139-d941-46d7-9730-9ac2a27d764e.png)

If i add few conditions as mentioned below, this is not triggering copyleft license policy in my scan.

~~~
        hasLabel("target-users", "external") && hasLabel( "architecture", "backend")  && hasLabel( "target-platform", "software-application") && hasLabel( "project-distribution-target", "external") -> Policy.REQUIRE_APPROVAL_MAJOR
        hasLabel("target-users", "in-house group") && hasLabel( "architecture", "frontend")  && hasLabel( "target-platform", "software-application") && hasLabel( "project-distribution-target", "external") -> Policy.REQUIRE_APPROVAL_MAJOR
~~~

Requesting your support/help to understand where i am doing wrong.

Kindly check and share your feedback on the same.

Thank you.

**Comment by kvy1kor** [comment]
Hello Team,

Can we expect any update on requested query?

Thank you,
Kavya B S

**Comment by kvy1kor** [comment]
Hello Team,
Greetings!!!

Can anyone help me in resolving the query.

**Comment by sschuberth** [comment]
@kvy1kor is still still an issue, or were you able to resolve it meanwhile?

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
