### ISSUE TITLE
Add authentication to OSS Index advisor options to increase rate limit

### ISSUE THREAD

**Issue by maklostermann** [oss-review-toolkit/ort#6973]
There are currently no authentication options available for using Sonatype OSS Index with a registered account. As the recently introduced low rate limits for unregistered users, this would be really useful (see https://ossindex.sonatype.org).

Authenticated requests need to use HTTP Basic authentication (https://ossindex.sonatype.org/doc/rest). It seems like there is an extra endpoint for such authenticated requests (api/v3/authorized/component-report).

**Comment by sschuberth** [comment]
Our OSS Index client actually already supports authentication; this only needs to be exposed via the options. I'll implement that soon-ish.
