### ISSUE TITLE
GoMod fails analyzing projects using multi module workspaces

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#6979]
The result of running ORT's analyzer against [1] does not contain any dependencies but just issues saying:
`Expected exactly one unique package without version but got...`.

[1] https://github.com/s0xzwasd/go-work-multi-module-example

Note: According to @MarcelBochtler this issue was not present a while ago. So, it may have been introduced either by recent changes in `GoMod` or by the added workspaces  support in Go version `1.18`.

**Comment by mnonnenmacher** [comment]
> Note: According to @MarcelBochtler this issue was not present before the refactoring done by @fviernau .

@fviernau Which refactoring does this refer to?

**Comment by fviernau** [comment]
> @fviernau Which refactoring does this refer to?

I've updated the comment to be less specific.
