### ISSUE TITLE
Web-App Scan Results: Increase Pagination Option or Copy-All-Button Feature

### ISSUE THREAD

**Issue by LukasWohlfart** [oss-review-toolkit/ort#6980]
Regarding the **Pagination Size Options** in the Web-App Report I suggest to either:

1.  add a fifth pageSizeOption significantly larger than the current maximum of 500. e.g. 5000
or
1.  add a Copy-All-Button Feature

**Reasoning:** Working with the Scan Results from the Web-App in another tool may require to copy the whole Scan Results [Use-case e.g. to filter on the path]. In many projects the Scan Results have way more than 500 detections making it necessary to copy paste multiple times by flipping through the pages.

**Comment by sschuberth** [comment]
> Working with the Scan Results from the Web-App in another tool may require to copy the whole Scan Results

That sounds like the wrong way to achieve what you want. Depending on what that other tool is, it might more sense to write a custom reporter plugin for your use-case.

**Comment by sschuberth** [comment]
I've changed my mind an decided to add 1000 and 5000 page size option unconditionally. Use at your own risk 😉, see https://github.com/oss-review-toolkit/ort/pull/7144.
