### ISSUE TITLE
Provide in ORT a (FossID) snippet report

### ISSUE THREAD

**Issue by nnobelis** [oss-review-toolkit/ort#7030]
https://github.com/oss-review-toolkit/ort/pull/6791 added support for snippets findings to ORT model.

Currently, no ORT report presents these findings.

A report showing these results needs to be added to ORT. 
Unfortunately, there are scanner-specific limitations.
For FossID for instance:
- FossID snippet results don't contain matching lines information due to performance issues (See https://github.com/oss-review-toolkit/ort/issues/7028)
- Current information available in the model does not fully cover the UI of FossID when presenting the snippets:
![image](https://github.com/oss-review-toolkit/ort/assets/66427221/1ad50a36-65c3-49fe-a342-411d2222aeb9)

Indeed our goal  at Bosch is to provide a rich report in ORT that would contain all FossID-available data, but also discards the need of FossID UI when writing snippet curations/choices.
To achieve this, new FossID-specific fields of the snippet would need to be added to the ORT model, in a generic way. See https://github.com/oss-review-toolkit/ort/pull/7022# for the preliminary work.
Then during report generation, the (costly) matched lines information could be fetched.

Here is an early prototype how such a report would look like :
[fossid-snippets.pdf](https://github.com/oss-review-toolkit/ort/files/11530425/fossid-snippets.pdf)

Please note our current prototype generates an html report instead to be able to leverage [Collapsible blocks of AsciiDoc](https://docs.asciidoctor.org/asciidoc/latest/blocks/collapsible/) : such blocks could be useful for e.g. "how to fix hints" for the snippet curations/choices.

**Comment by nnobelis** [comment]
Last comment: while it would be great to have a snipped report that support both FossID and ScanOSS findings, I fear that the implementation would be too complex due to Scanner-specific findings.
Therefore I would focus on creating one Reporter per scanner.

**Comment by sschuberth** [comment]
@nnobelis can this be closed due to the work done in https://github.com/oss-review-toolkit/ort/pull/7127?

**Comment by nnobelis** [comment]
Closed with https://github.com/oss-review-toolkit/ort/pull/7127.
