### ISSUE TITLE
Web-App-Reporter maps each line of an error to a separate issue for NPM

### ISSUE THREAD

**Issue by hanna-modica** [oss-review-toolkit/ort#7071]
The web app reporter maps the following 4-line error to 4 separate issues:

```
EEXIST: file already exists, open '/root/.npm/_cacache/tmp/3a8f6b96'
File exists: /root/.npm/_cacache/tmp/3a8f6b96
Remove the existing file and try again, or run npm
with --force to overwrite files recklessly.
```

![grafik](https://github.com/oss-review-toolkit/ort/assets/40762532/f27b15c4-0676-4106-8528-f3987c2d088f)

This increases the amount of reported issues and makes it harder to get an overview of the errors.

**Comment by sschuberth** [comment]
@hanna-modica can you please double-check how this looks in the raw analyzer result and in the evaluated model report? I'd like to rule out that this is related to https://github.com/oss-review-toolkit/ort/pull/6624.
