### ISSUE TITLE
Plugin support for custom FileStorages

### ISSUE THREAD

**Issue by vw-anton** [oss-review-toolkit/ort#7075]
We would like to use a custom (HTTP) file storage implementation as the existing ones do not fulfil our needs (custom auth in OkHttp client required via request interceptor). In our opinion a valid approach could be to plugin a custom implementation which is then configured via the config.yml file.

@MarcelBochtler / @mnonnenmacher mentioned in todays community call that there might be a bigger refactoring around storages (required) which should also be taken into account.

**Comment by vw-anton** [comment]
Absolutely, did not spot this during my initial search.

**Comment by sschuberth** [comment]
> Absolutely, did not spot this during my initial search.

Great, then please upvote that issue to reflect your interest!
