### ISSUE TITLE
NoSuchFileException gc.log.lock

### ISSUE THREAD

**Issue by dimitris-iliou** [oss-review-toolkit/ort#7128]
It's been a while we are getting to see an issue with some packages in the various scan reports wherein the tool has scanned the correct repository for the dependency and we have all the required scan results and license details as well but still ORT throws an error message something like 

`"Could not create file list for 'NPM::(package)': NoSuchFileException: /tmp/ort-DefaultWorkingTreeCache10010632486568145337/.git/gc.log.lock"`

Has anyone come across this issue?

**Comment by sschuberth** [comment]
I've not come across this issue before. Is it still reproducible for you @dimitris-iliou?

**Comment by dimitris-iliou** [comment]
I haven't seen that for a while. Feel free to close it.
