### ISSUE TITLE
Add ORT to the "Awesome SBOM" list

### ISSUE THREAD

**Issue by setchy** [oss-review-toolkit/ort#7158]
Hey team - keep up the great work.  Thought you may like to add ORT into https://github.com/awesomeSBOM/awesome-sbom

**Comment by surendrapathak** [comment]
It seemed like the right thing to do - 🤞  https://github.com/awesomeSBOM/awesome-sbom/pull/30

**Comment by sschuberth** [comment]
Yes, thanks a lot @surendrapathak for stepping in here!
