### ISSUE TITLE
Downloader failing for ssh-based project-url

### ISSUE THREAD

**Issue by zhernovs** [oss-review-toolkit/ort#7177]
### How to reproduce

1. Pull and compile ORT. I spotted this issue first in revision e771a67, but the latest revision from main branch also affected. 
2. Make sure you have ssh key registered in GitHub and it's accessible in the same environment where you run ORT.
3. Run ORT downloader as following: 
```
/opt/ort/bin/ort --debug \
    download \
    --project-name "OSS_Review_Toolkit" \
    --project-url "git@github.com:jshttp/mime-types.git" \
    --vcs-type "git" \
    --vcs-revision "c77d6b02139075e4f63230a970411b3c92d066e2" \
    --vcs-path "" \
    -o project  
```

It will fail with error: 
```
09:04:12.304 [main] ERROR org.ossreviewtoolkit.plugins.commands.downloader.DownloaderCommand - The following failure(s) occurred:
DownloadException: Download failed for 'Downloader::OSS_Review_Toolkit:'.
Suppressed: DownloadException: Git failed to get revisions from URL 'ssh://github.com/jshttp/mime-types.git'.
    Caused by: DownloadException: Unable to determine a revision to checkout.
        Suppressed: IOException: Cannot guess a revision name from a blank version.
        Suppressed: IOException: Unable to list the remote branches.
            Caused by: TransportException: ssh://github.com/jshttp/mime-types.git: remote hung up unexpectedly
                Caused by: TransportException: ssh://github.com/jshttp/mime-types.git: remote hung up unexpectedly
                    Caused by: NoSuchMethodError: 'java.lang.Object org.apache.sshd.client.future.ConnectFuture.verify(org.apache.sshd.common.future.CancelOption[])'Suppressed: DownloadException: No source artifact URL provided. 
```

### Observations

- Running the same command with [http](https://github.com/jshttp/mime-types.git) project-url instead of ssh passes without errors.
- Previous versions (c05ec08 and older) doesn't have this issue.
- Pure git (clone, fetch, etc) works fine on the same environment over ssh with the same key.
- Might be related to jgit [update](https://github.com/oss-review-toolkit/ort/commit/115f24149b0b720f4550009d3316653c3940d1c6) from 6.5.0.202303070854-r to 6.6.0.202305301015-r as it includes dependency update that might cause changes in ssh behavior - [581770](https://eclip.se/581770) Apache mina-sshd to 2.10.0. (Just a guess, I don't see related bug's or features in release notes).

[downloader_debug.log](https://github.com/oss-review-toolkit/ort/files/11832665/downloader_debug.log)

**Comment by sschuberth** [comment]
> * Might be related to jgit [update](https://github.com/oss-review-toolkit/ort/commit/115f24149b0b720f4550009d3316653c3940d1c6) from 6.5.0.202303070854-r to 6.6.0.202305301015-r

Could you simply try reverting that update?

**Comment by gmathiou4** [comment]
I have revert the version and downloader complete without Errors

**Comment by sschuberth** [comment]
> I have revert the version and downloader complete without Errors

Thanks for checking. Looks like https://github.com/apache/mina-sshd/blob/master/docs/changes/2.10.0.md#major-code-re-factoring could somehow be related.

**Comment by zhernovs** [comment]
I wonder why it doesn't appear when scanner calls downloader...

**Comment by sschuberth** [comment]
I've [reported this to JGit](https://bugs.eclipse.org/bugs/show_bug.cgi?id=582109). Looks to me like a classloader conflict between the sshd-common version bundled with JGit in sshd-osgi, and the sshd-common version that comes as a dependency of svnkit.

**Comment by sschuberth** [comment]
Guys, can you please try whether https://github.com/oss-review-toolkit/ort/pull/7189 fixes your issue?

**Comment by gmathiou4** [comment]
I have tested the change and didn't have any issues, we could proceed and merge [7189](https://github.com/oss-review-toolkit/ort/pull/7189)
