### ISSUE TITLE
Support the Swift Package Manager (iOS)

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#723]
Add support for the Swift dependency manager to the analyzer module.

https://github.com/apple/swift-package-manager

`swift package show-dependencies --format json` is the command to fetch dependencies according to https://www.cocoawithlove.com/blog/package-manager-fetch.html

Related materials:
- [The Swift package manifest file – Tibor Bödecs](https://theswiftdev.com/the-swift-package-manifest-file/)
- [SPM Repo Documentation](https://github.com/apple/swift-package-manager/tree/main/Documentation)
- [Swift.org SPM Documentation](https://swift.org/package-manager/)
- [Apple SPM Documentation](https://developer.apple.com/documentation/swift_packages)

**Comment by annania** [comment]
looking forward to iOS project support

**Comment by tsteenbe** [comment]
@annania supporting iOS build tools is always tricky as the common tools only run on macOS. Swift is the exception and according to https://github.com/apple/swift should run beside macOS also on Debian, Fedora and Ubuntu

**Comment by sschuberth** [comment]
Maybe https://github.com/mahmudahsan/Licenses could help.

**Comment by sschuberth** [comment]
Swift now also runs on Windows ([German article](https://www.golem.de/news/programmiersprache-apples-swift-laeuft-auf-windows-2009-151046.html)), so maybe this is a step towards adding platform-independent support for SPM to ORT.

**Comment by MarcelBochtler** [comment]
Swift is also available for Ubuntu, CentOS and Amazon Linux 2: https://swift.org/download/#releases
Using the provided docker image I was able to create a small Hello World app using a depdendency from the swift package manager:
```
root@bb84f80d3453:/swifttest# uname -a
Linux bb84f80d3453 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

root@bb84f80d3453:/swifttest# swift --version
Swift version 5.3 (swift-5.3-RELEASE)
Target: x86_64-unknown-linux-gnu

root@bb84f80d3453:/swifttest# cat Package.swift 
// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "swifttest",
    dependencies: [
	.package(
	    name: "Files",
            url: "https://github.com/johnsundell/files.git", 
            from: "4.0.0"
        )
    ],
    targets: [
        .target(
            name: "swifttest",
            dependencies: ["Files"]),
        .testTarget(
            name: "swifttestTests",
            dependencies: ["swifttest"]),
    ]
)

root@bb84f80d3453:/swifttest# cat Sources/swifttest/main.swift 
import Files

print(Folder.current)

root@bb84f80d3453:/swifttest# swift build
Fetching https://github.com/johnsundell/files.git
Cloning https://github.com/johnsundell/files.git
Resolving https://github.com/johnsundell/files.git at 4.1.1
[7/7] Linking swifttest

root@bb84f80d3453:/swifttest# swift run swifttest
Folder(name: swifttest, path: /swifttest/)
```

**Comment by sschuberth** [comment]
Swift System is Now Open Source: https://swift.org/blog/swift-system/

**Comment by sschuberth** [comment]
Just came across https://github.com/studo-app/Kotlift. Maybe it's of some use here?

**Comment by sschuberth** [comment]
Yet one more tool that might become useful: https://github.com/LGE-OSS/swift-depends

**Comment by MarcelBochtler** [comment]
One issue I see in general with SPM is, that it seems to not support `declaredLicenses` at all.

> Maybe https://github.com/mahmudahsan/Licenses could help.

This project requires the user to specify all dependencies with their licenses manually.

Other tools / articles I found:
https://github.com/MacPaw/spm-licenses This seems to clone the repository and to read the LICENSE file.
https://davidvonk.dev/2020/12/24/generating-spm-licenses.html Uses the GitHub API to get the license information.

The GitHub API approach might be okay, but may not be feasible in our case, as this would require an implementation for every package source, and some might not support that kind of API at all.
Additionally, API limits would be an issue.

What we could do is, to just not set `declaredLicenses` for SPM packages, which is IMO the correct way to handle that, because the package manager doesn't know about the license, and this is represented in the `AnalyzerResult`.
The scanner would then provide all necessary information.

**Comment by mnonnenmacher** [comment]
I agree that if the package manager does not provide a declared license we should leave the field empty.

**Comment by grEvenX** [comment]
This archived project could also maybe provide some pointers on how to support SPM: https://github.com/mattt/swift-package-sbom

**Comment by Smponias** [comment]
Any news on this? I think leaving it empty is the best Idea. :)

**Comment by sschuberth** [comment]
I took over the draft PR at https://github.com/oss-review-toolkit/ort/pull/6114, but didn't find the time yet to work on it. Maybe sponsoring could help to raise priority 😉
