### ISSUE TITLE
ort dependency_graphs

### ISSUE THREAD

**Issue by durr-hackenberg** [oss-review-toolkit/ort#7236]
Hello, 
is there somewhere a description how to generate the dependency graph from ORT Analyser? 
I want to render this structure in JavaScript but it is not so simple to understand how the structure was created. Is there any Documentation about that topic ? 

What I have understood so far:
1. So I currently understand that the "scopes" creating the roots of the tree. 
2. The nodes array have "pkg" and "fragment", what are the different ?
3.  "edges" creating the end of the branch ? "from" and "to" are selecting the range of packages ?
4. How do the indexes belong together ? I think somehow you have to be able to determine which edge/node belongs to which dependency. What array index determines that ?

Thank you!

**Comment by sschuberth** [comment]
Depending on the package manager, ORT currently uses two different internal formats to store the dependency graph (also see https://github.com/oss-review-toolkit/ort/issues/3825). But it is anyway highly recommended *not* to parse ORT's result file format directly, as it's an internal format that might change any at time, breaking things on your side.

Instead, you should probably consider writing a custom / private ORT reporter plugin. Maybe you'd also be interested in https://github.com/oss-review-toolkit/ort/issues/6636.

**Comment by durr-hackenberg** [comment]
Thank you for that infos, I will check the plugin part.
