### ISSUE TITLE
Advisor : OSV seems to be not working with latest source

### ISSUE THREAD

**Issue by kvy1kor** [oss-review-toolkit/ort#7239]
Hello Team,

We performed the scan by updating our docker image and as well as the source.
In both the cases, we observed OSV module was not giving any information on vulnerablity details.

NOTE: Previous to this recent update  with the older source code we are able to get the vulnerablity details in our scans.

Attached scrrenshot for reference.

Component used : **NPM ejs 3.1.6**

![MicrosoftTeams-image](https://github.com/oss-review-toolkit/ort/assets/112953008/8ff496cb-9af1-4f93-b461-9a1ece412cab)

Snippet of log form advisor module

~~~
 ______________________________
/        \_______   \__    ___/ The OSS Review Toolkit, version DOCKER-SNAPSHOT.
|    |   | |       _/ |    |
|    |   | |    |   \ |    |    Running 'advise' as 'ort' under Java 17.0.7 on Linux
\________/ |____|___/ |____|    with 2 CPUs and a maximum of 5120 MiB of memory.

Environment variables:
ORT_CONFIG_DIR = /home/ort/.ort/config
ORT_DATA_DIR = /home/ort/.ort
JAVA_HOME = /opt/java/openjdk
ANDROID_HOME = /opt/android-sdk

Looking for ORT configuration in the following file:
	/home/ort/.ort/config/config.yml

The following advisors are activated:
	OSV
05:00:17.130 [DefaultDispatcher-worker-3] ERROR org.ossreviewtoolkit.advisor.advisors.Osv - Requesting vulnerabilities IDs for packages failed: IOException: 
Writing advisor result to '/home/ort/.ort/ort-results/advisor-result.json'.
The advice took 1.060994995s.
0 of 16 package(s) (not counting excluded ones) are vulnerable, with 0 vulnerabilities in total.
Resolved issues: 0 errors, 0 warnings, 0 hints.
Unresolved issues: 0 errors, 0 warnings, 0 hints.
~~~
Could you please someone look this and share us your feedback.

Thank You,

**Comment by sschuberth** [comment]
At a first glance there indeed seems to be an issue. I'll investigate.

**Comment by sschuberth** [comment]
Thanks for the report. As a stop-gap measure, I've [reverted](https://github.com/oss-review-toolkit/ort/pull/7240/commits/f44b3f9c5129b9bf4598fc0d3c34bee9498f06d2) a recent change in OSV; more investigation is needed why the change did not work.
