### ISSUE TITLE
Add Carthage (iOS/Cocoa) as supported package manager

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#725]
Add support for the Carthage dependency manager to the analyzer module.

https://github.com/Carthage/Carthage

**Comment by sschuberth** [comment]
Here's some [good reading](https://www.raywenderlich.com/416-carthage-tutorial-getting-started#toc-anchor-007) on the `Cartfile` format.

**Comment by sschuberth** [comment]
Note that Carthage only supports transitive ("nested") dependencies [if the dependency itself also uses Carthage](https://github.com/Carthage/Carthage#nested-dependencies).

**Comment by sschuberth** [comment]
More good reading on [what iOS package manager to use when](https://www.codementor.io/blog/swift-package-manager-5f85eqvygj#what-package-manager-should-i-use).

**Comment by sschuberth** [comment]
We at Bosch are looking at this.
