### ISSUE TITLE
ort analyze --help throws exit code

### ISSUE THREAD

**Issue by mawl** [oss-review-toolkit/ort#7272]
Hey,

A trivial bug, but `ort analyze --help` throws an exit code since a couple of days.

**Comment by sschuberth** [comment]
Out of curiosity @mawl, (how) does this change affect you negatively? I mean, `--help` is probably always and exclusively used interactively, so it shouldn't e.g. break any CI pipeline or so.

**Comment by sschuberth** [comment]
It will be [fixed](https://github.com/ajalt/clikt/pull/425) in the next clikt release.

**Comment by mawl** [comment]
@sschuberth: We run the help commands in a CI pipeline to document the cli commands and to see if there deprecated parameters.

I have switched to ort --help-all now; there's no exit code thrown.
