### ISSUE TITLE
FileStorage code <-> JSON config schema mismatch?

### ISSUE THREAD

**Issue by schliesserams** [oss-review-toolkit/ort#7283]
Hello,

we are currently trying to integrate ORT in our CI/CD pipeline. Thank you for all your efforts creating such a project!

Short question:
the JSON Schema definition (https://github.com/oss-review-toolkit/ort/blob/main/integrations/schemas/ort-configuration-schema.json) defines a FileStorage with the properties localFileStorage and httpFileStorage, and localFileStorage as required.

https://github.com/oss-review-toolkit/ort/blob/main/model/src/main/kotlin/config/FileStorageConfiguration.kt needs exactly one implementation configured. 

Although a single httpFileStorage definition is indeed working this is violating the schema, because actually a localFileStrorage must be defined (and exactly one ;) )? 

Is the schema outdated or do I read it wrong?

Kind Regards

**Comment by sschuberth** [comment]
> Is the schema outdated or do I read it wrong?

It's a bug in the schema. Do you feel like contributing a fix to it, to document `localFileStorage` and `httpFileStorage` to be mutually exclusive?

**Comment by sschuberth** [comment]
> we are currently trying to integrate ORT in our CI/CD pipeline.

BTW, please be aware of our example [integrations](https://github.com/oss-review-toolkit/ort/tree/main/integrations) e.g. for Jenkins, or also the [GitHub Action](https://github.com/oss-review-toolkit/ort-ci-github-action) and the [GitLab CI Pipeline](https://github.com/oss-review-toolkit/ort-gitlab-ci).

**Comment by schliesserams** [comment]
Hello Sebastian,

> Do you feel like contributing a fix to it, to document localFileStorage and httpFileStorage to be mutually exclusive?

sure :) i will provide a PR.

**Comment by sschuberth** [comment]
> sure :) i will provide a PR.

Is there still interest to provide a PR @schliesserams?
