### ISSUE TITLE
Add AWS S3 as supported remote cache

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#730]
For re-using already known scan results, ORT can use a remote cache. Currently only Artifactory is supported but we would like to add AWS S3 support as it more commonly used and cheaper to set up than Artifactory instance.

See also: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/examples-s3.html

**Comment by sschuberth** [comment]
This was implemented in https://github.com/oss-review-toolkit/ort/pull/7413.
