### ISSUE TITLE
Exception reading last-build.bin when resolving gradle dependencies

### ISSUE THREAD

**Issue by brueggenthies-ams** [oss-review-toolkit/ort#7336]
Hi there!

I am currently trying to analyze an Android Project, and reached an exception that I cannot fully understand.

What is executed
I am executing the analyzer. Ort is run inside a docker container (build with the provided docker file)
**Commands**
```
gradlew build
docker run -v $PWD/:/project $ORT_IMAGE --info -c /project/ort/config.yml analyze --input-dir /project --output-dir /project/ort/output
```

**Result**
```
08:58:09.295 [DefaultDispatcher-worker-1] ERROR org.ossreviewtoolkit.analyzer.PackageManager - Gradle failed to resolve dependencies for path 'network/build.gradle.kts': BuildException: Could not fetch model of type 'OrtDependencyTreeModel' using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-8.0.2-bin.zip'.
  Caused by: LocationAwareException: Could not update /project/.gradle/8.0.2/fileChanges/last-build.bin
    Caused by: UncheckedIOException: Could not update /project/.gradle/8.0.2/fileChanges/last-build.bin
      Caused by: FileNotFoundException: /project/.gradle/8.0.2/fileChanges/last-build.bin (Permission denied)
```

This happens on all gradle modules.
I have run ort previously and did not encounter this error. We upgraded gradle from 7.4 to 8.0.2 in between.

Are there any file permissions i need to be aware of?

Thanks in regards!

**Comment by sschuberth** [comment]
Looks like there was previously run a Gradle build on the host, which created `$PWD/.gradle` (and contained files), and the other Gradle build running inside the Docker container cannot update the files in `$PWD/.gradle` due to permission issues.

Without knowing too much about your workflow (what do you build when and where), I guess deleting `$PWD/.gradle` on the host before starting the ORT analysis should do the trick.

**Comment by brueggenthies-ams** [comment]
That would make sense.

I tried to start the analyzer without building the project first (Ditching the `gradlew build` step).
However, now I get this exception:

```
09:03:06.450 [DefaultDispatcher-worker-1] ERROR org.ossreviewtoolkit.analyzer.PackageManager - Gradle failed to resolve dependencies for path 'network/build.gradle.kts': BuildException: Could not fetch model of type 'OrtDependencyTreeModel' using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-8.0.2-bin.zip'.
  Caused by: LocationAwareException: Could not update /project/.gradle/8.0.2/fileChanges/last-build.bin
    Caused by: UncheckedIOException: Could not update /project/.gradle/8.0.2/fileChanges/last-build.bin
      Caused by: FileNotFoundException: /project/.gradle/8.0.2/fileChanges/last-build.bin (No such file or directory)
```

**Comment by sschuberth** [comment]
> I tried to start the analyzer without building the project first (Ditching the `gradlew build` step).

Again, depending on your workflow that might not be enough, e.g. if the `.gradle` directory is restored from a cache. You really need to ensure the `.gradle` directory is not present by removing it.

If the problem persists nonetheless, then the user from your Docker container probably does not have write permissions in the host directory. If so, ensure to use a correct `USER_ID` when *building* (not running) the Docker image. The `USER_ID` defaults to 1000. If there is no user with ID 1000 on the host, or if that user does not have write permissions to `$PWD/.gradle`, that could be the cause of the above error.

**Comment by brueggenthies-ams** [comment]
However in the second case the error did not state `Permission denied` but `No such file or directory`.

Is ORT expecting this file to be present beforehand?

**Comment by brueggenthies-ams** [comment]
@sschuberth you were right about the permissions, we could resolve the issue by running the docker container with the right user and group id. Thanks for your help!
I will close the issue therefore.
