### ISSUE TITLE
Add license summary from TLDRLegal to WebApp report

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#734]
Would be great if we can expand the WebApp report added in #733 with more license summaries. The website https://tldrlegal.com/ over large amount of user generated ones. Although we know this data has likely not been reviewed by a legal counsel believe it's better to offer this info within ORT than user having to look it up themselves. Hopefully the more eyes will see these summaries them more errors get corrected. 

Example: https://tldrlegal.com/license/apache-license-2.0-%28apache-2.0%29

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
