### ISSUE TITLE
ORT failing to resolve some Vulnerability Reference URIs

### ISSUE THREAD

**Issue by hanna-modica** [oss-review-toolkit/ort#7364]
Some URIs can not be resolved correctly by ORT (e.g. [1]).

In the evaluated model the following entry is present:

```
{
    "_id" : 51,
    "timestamp" : "2023-07-30T03:11:50.719284Z",
    "type" : "ADVISOR",
    "source" : "VulnerableCode",
    "message" : "Failed to map VulnerabilityReference(url=https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:oracle:retail_category_management_planning_\\&_optimization:16.0.3:*:*:*:*:*:*:*, scores=[]) to ORT model due to java.net.URISyntaxException: Illegal character in query at index 137: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:oracle:retail_category_management_planning_\\&_optimization:16.0.3:*:*:*:*:*:*:*.",
    "severity" : "HINT",
    "pkg" : 6
  }
```
where pkg 6 is `Maven:com.fasterxml.woodstox:woodstox-core:5.1.0`

This error appears multiple times for several nvd.nist.gov URIs.

Also, the uri is redirected to [2], but the illegal character at index 137 looks to me, like this redirecting is not the issue. 

[1] [URI to vulnerability](https://nvd.nist.gov/vuln/search/results?adv_search=true&
isCpeNameSearch=true&query=cpe:2.3:a:oracle:retail_category_management_planning_\&
_optimization:16.0.3:*:*:*:*:*:*:*)
[2] https://nvd.nist.gov/general/news/temp-disable-keyword-searches

**Comment by sschuberth** [comment]
While I believe this to be a bug with URL escaping in VulnerableCode, I've implemented a work-around in the linked PR.
