### ISSUE TITLE
Detected licenses appear in cycloneDX bom, even though concluded licenses exist

### ISSUE THREAD

**Issue by hanna-modica** [oss-review-toolkit/ort#7370]
We have a report, which has a NOASSERTION detected. This is overridden in a curation, however, in the cycloneDX bom and the SPDX bom, it still appears as

<license>
  <name>NOASSERTION</name><ort:origin xmlns:ort="http://www.w3.org/1999/xhtml">detected license</ort:origin>
</license>

while others, like MIT appear twice (with concluded license and detected license as <ort:origin>)

I do not think, that hose should appear, if a curation has been done.

This is probably related to #7354

**Comment by sschuberth** [comment]
See my comment [over here](https://github.com/oss-review-toolkit/ort/issues/7354#issuecomment-1682079582). This is more or less intended, but could be changed.

**Comment by sschuberth** [comment]
> See my comment [over here](https://github.com/oss-review-toolkit/ort/issues/7354#issuecomment-1682079582). This is more or less intended, but could be changed.

@hanna-modica does my comment make sense to you?

**Comment by hanna-modica** [comment]
Hi @sschuberth,
thank you for making me aware of missing the previous answer. Yes, it makes sense how this came into place. I would appreciate, if this could be changed someday, but for us it has no a high priority, since I can argue to the customer, that, as you wrote, it is not generated for human readability.

**Comment by sschuberth** [comment]
Thanks for the reply. Then let me close this as "not planned" for now to clean up issues.
