### ISSUE TITLE
Cargo plug-in ignores dependencies from outside of crates.io

### ISSUE THREAD

**Issue by rbuch703** [oss-review-toolkit/ort#7372]
Rust uses `cargo` as its default (and virtually only) package manager and build system. Within a `Cargo.toml` file, a developer can specify a project's build dependencies, and `cargo` then automatically downloads and builds those. By default, Cargo assumes that the dependency shall be downloaded from crates.io, but `cargo` supports overriding this default to retrieve dependencies from arbitrary local folders and arbitrary `git` repositories. The latter is particularly useful for dependencies that are private to an organization.

ORT, however, only supports analyzing dependencies maintained at crates.io. In https://github.com/oss-review-toolkit/ort/blob/38c9be05d51cfcee46b07218810b3ad29a361de8/plugins/package-managers/cargo/src/main/kotlin/Cargo.kt#L304 it terminates parsing any other kind of dependency. Additionally, since ORT returns `null` in this case, application users will receive a misleading error message that ORT cannot determine the URL and the hash of a dependency, even though the dependency line in the `Cargo.toml` file contains both, and `cargo` uses them correctly to build the application.

**Comment by sschuberth** [comment]
> it terminates parsing any other kind of dependency.

Is that so? If I'm reading the code correctly, it only affect parsing of *source* artifacts, and if they don't come from `creates.io` they'll simply be empty:

https://github.com/oss-review-toolkit/ort/blob/38c9be05d51cfcee46b07218810b3ad29a361de8/plugins/package-managers/cargo/src/main/kotlin/Cargo.kt#L282

> even though the dependency line in the `Cargo.toml` file contains both

Can you provide an example `Cargo.toml` with a custom registry?

**Comment by rbuch703** [comment]
> > it terminates parsing any other kind of dependency.
> 
> Is that so? If I'm reading the code correctly, it only affect parsing of _source_ artifacts, and if they don't come from `creates.io` they'll simply be empty:
> 
> https://github.com/oss-review-toolkit/ort/blob/38c9be05d51cfcee46b07218810b3ad29a361de8/plugins/package-managers/cargo/src/main/kotlin/Cargo.kt#L282

Yes, at that point in the code, the source artifact is simply set to null. But later stages - judging by the error message somewhere below https://github.com/oss-review-toolkit/ort/blob/15e33b2310cb9eacd464121a325dd12ae8b173f1/scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt#L270 - then fail with `IOException: Could not resolve provenance for package 'my-custom-lib:0.1.0' for source code origins [VCS, ARTIFACT]. Resolution of VCS failed with: IOException: Could not resolve revision for package 'Crate::my-custom-lib:0.1.0' with VcsInfo(type=Git, url=https://mydomain.com/path/to/repo-containing-my-lib.git, revision=, path=):` due to that null value.

> 
> > even though the dependency line in the `Cargo.toml` file contains both
> 
> Can you provide an example `Cargo.toml` with a custom registry?

My use case isn't about custom *registries*, but about source dependencies coming directly from custom `git` repositories (i.e. without any registry as an intermediary)

One example line in `Cargo.toml` with a custom git dependency would be
```
my-custom-lib = { git = "https://mydomain.com/path/to/repo-containing-my-lib.git", rev = "19765d9a" }
```

**Comment by rbuch703** [comment]
> Can you provide an example `Cargo.toml` with a custom registry?

My use case isn't about custom *registries*, but about source dependencies coming directly from custom `git` repositories (i.e. without any registry as an intermediary)

One example line in `Cargo.toml` with a custom git dependency would be
```
my-custom-lib = { git = "https://mydomain.com/path/to/repo-containing-my-lib.git", rev = "19765d9a" }
```

**Comment by sschuberth** [comment]
> My use case isn't about custom _registries_, but about source dependencies coming directly from custom `git` repositories

Ah, sorry for that misunderstanding. That should be easy to support. Are you willing to contribute a PR?

**Comment by sschuberth** [comment]
> So, if you know how to easily add this functionality be my guest.

😆 

Here are the [relevant specs](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories).
