### ISSUE TITLE
SPDX reporter crashes due to invalid SPDX expressions

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#7384]
Since ScanCode was configured to associate exceptions with nearby licenses, one may get license-exception combinations with IDs for exceptions which are not on the SPDX list. These are invalid in SPDX 2.x spec which in turn makes some requires check in the SPDX report fail.

Possible solutions:

1. Add an additional option to ScanCode to only associate exceptions from the SPDX list, but not custom ones.
2. Add a configuration option to ORT for toggling whether the SPDX expression need to conform to 2.x spec

Probably in any case the SPDX Document needs to be changed to tolerate such expressions.

**Comment by mnonnenmacher** [comment]
Related PR: https://github.com/oss-review-toolkit/ort/pull/7367

**Comment by maxhbr** [comment]
relevant change proposal: https://github.com/spdx/change-proposal/issues/4

**Comment by sschuberth** [comment]
Can this be closed as https://github.com/oss-review-toolkit/ort/pull/7399 is merged?

**Comment by fviernau** [comment]
Closed as the crash is fixed. One might add a follow up e.g. as described in the ticket description though.
