### ISSUE TITLE
Why are there not tags on a repository you have to clone in order to use

### ISSUE THREAD

**Issue by NoFuchsGavin** [oss-review-toolkit/ort#7407]
Why not fixing versions?

**Comment by sschuberth** [comment]
ORT has a "rolling release" strategy, our `main` branch is always stable, and each commit on it is as good as a release. So effectively we'd need to tag each commit, which is meaningless.

Until we'll provide [pre-built binary release artifacts](https://github.com/oss-review-toolkit/ort/issues/1901) with Semver versioning, the ORT version is just the short Git SHA1 revision.

**Comment by sschuberth** [comment]
For the record, we have tags (and about weekly [releases](https://github.com/oss-review-toolkit/ort/releases)) now.
