### ISSUE TITLE
Enable fixing of metadata errors using ClearlyDefined in WebApp report

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#741]
Sharing fixes for broken metadata in OSS packages via https://clearlydefined.io/ would benefit entire OSS community. Propose to expand the WebApp in the reporter with an option to submit a package to https://clearlydefined.io/ so it can be curated

**Comment by sschuberth** [comment]
By now, I believe this will never become a feature in ORT and that https://clearlydefined.io/ should be used directly instead to submit fixes to ClearlyDefined.
