### ISSUE TITLE
Way to extract gradle dependency for specific configuration?

### ISSUE THREAD

**Issue by dineshr93** [oss-review-toolkit/ort#7479]
Hi 

we have specific configurations (like gradle runtimeClasspath,releaseRuntimeClasspath, even custom ones). The normal **ort analyze** doesnt provide any dependencies. but i see dependencies using **gradle dependencies -q --configuration releaseRuntimeClasspath** Is there a way to pass above configurations to analyze command to extract dependencies?

Thanks in advance.

**Comment by sschuberth** [comment]
> The normal **ort analyze** doesnt provide any dependencies.

That's unusual an ORT by default analyzes *all* configurations (called "scopes" in ORT's terms), and you actually have to [*exclude* the one's you're not interested it](https://github.com/oss-review-toolkit/ort/blob/main/docs/config-file-ort-yml.md#excluding-scopes).

So, before giving further advice, we should probably try to figure out what goes wring if you see no dependencies. Maybe give the [alternative `gradle-inspector` analyzer](https://github.com/oss-review-toolkit/ort/tree/main/plugins/package-managers/gradle-inspector) a try (as it's disabled by default) to see if that yields any dependency results?

**Comment by dineshr93** [comment]
Hi 
> Maybe give the [alternative `gradle-inspector` analyzer](https://github.com/oss-review-toolkit/ort/tree/main/plugins/package-managers/gradle-inspector)

![image](https://github.com/oss-review-toolkit/ort/assets/4498415/3c180487-e18e-44c6-84e1-dbdc86c00593)

Is -P option removed in latest version ? I am using ort docker built from yesterdays main line with only gradle package manager (because we use only gradle pkg manager)

**Comment by dineshr93** [comment]
> No, the example just used it at the wrong place, see [this fix](https://github.com/oss-review-toolkit/ort/pull/7480): It should be `ort -P ... analyze ...`.

Thanks the command worked with below error

```
Looking for ORT configuration in the following file:
        /home/ort/.ort/config/config.yml (does not exist)

Looking for analyzer-specific configuration in the following files and directories:
        /home/dinesh/aosp/AddressBookSync/.ort.yml
        /home/ort/.ort/config/resolutions.yml (does not exist)
The following 1 package manager(s) are enabled:
        GradleInspector
The following 2 package curation provider(s) are enabled:
        DefaultDir, DefaultFile
Analyzing project path:
        /home/dinesh/aosp/AddressBookSync
Found 1 GradleInspector definition file(s) at:
        build.gradle
Found in total 1 definition file(s) from the following 1 package manager(s):
        GradleInspector
11:41:21.453 [DefaultDispatcher-worker-1] ERROR org.ossreviewtoolkit.analyzer.PackageManager - GradleInspector failed to resolve dependencies for path 'build.gradle': BuildException: Could not fetch model of type 'OrtDependencyTreeModel' using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-8.3-bin.zip'.
Caused by: LocationAwareException: Could not resolve all dependencies for configuration ':debugAndroidTestCompileClasspath'.
    Caused by: ResolveException: Could not resolve all dependencies for configuration ':debugAndroidTestCompileClasspath'.
        Caused by: TaskCreationException: Could not create task ':processDebugResources'.
            Caused by: GradleException: Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle_core() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
Writing analyzer result to '/home/dinesh/aosp/AddressBookSync/analyzer-result.yml'.
The analysis took 8.684526s.
Found 1 project(s) and 0 package(s) in total (not counting excluded ones).
Applied 0 curation(s) from 0 of 2 provider(s).
Resolved issues: 0 errors, 0 warnings, 0 hints.
Unresolved issues: 1 error, 0 warnings, 0 hints.
There is 1 unresolved issue with a severity equal to or greater than the WARNING threshold.
```

**Comment by sschuberth** [comment]
> Caused by: GradleException: Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle_core() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.

This sounds like the Android Gradle plugin in that project is outdated. Try upgrading to a version 7.3+.

**Comment by dineshr93** [comment]
> Try upgrading to a version 7.3+.

After upgrading 
`androidGradlePlugin = "com.android.tools.build:gradle:7.4.0"`

Now it detected the package successfully. Thanks
