### ISSUE TITLE
Could not create 'SpdxDocument' report. IllegalArgumentException: The document must either have at least one relationship of type 'DESCRIBES' or contain the 'documentDescribes' field.

### ISSUE THREAD

**Issue by dineshr93** [oss-review-toolkit/ort#7482]
Hi 

For gradle project While generating spdx report

`ort report -i analyzer-result.json -o . -f SpdxDocument`

We got below error

```
Looking for ORT configuration in the following file:
        /home/ort/.ort/config/config.yml (does not exist)
Generating the 'SpdxDocument' report in thread 'DefaultDispatcher-worker-2'...
19:04:25.304 [main] ERROR org.ossreviewtoolkit.plugins.commands.reporter.ReporterCommand - Could not create 'SpdxDocument' report in 201.181070ms: IllegalArgumentException: The document must either have at least one relationship of type 'DESCRIBES' or contain the 'documentDescribes' field.
Created 0 of 1 report(s) in 246.708372ms.
```

I checked there is a pr regarding this https://github.com/oss-review-toolkit/ort/pull/3521

Thread is very long not sure what action step I should take to generate the report.

Please may I have your help.

Thanks once again in advance.

**Comment by sschuberth** [comment]
The `SpdxDocumentReporter` always writes out the `documentDescribes` field:

https://github.com/oss-review-toolkit/ort/blob/43aefef4e11bbd40eb7e8f70aa2593cb83271511/plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt#L164

So if the assertion at

https://github.com/oss-review-toolkit/ort/blob/43aefef4e11bbd40eb7e8f70aa2593cb83271511/utils/spdx/src/main/kotlin/model/SpdxDocument.kt#L171

fails, it means that your list of packages is empty. Please investigate in that direction.

**Comment by dineshr93** [comment]
Hi @sschuberth 

> fails, it means that your list of packages is empty. Please investigate in that direction.

I have packages. Here is the [analyzer-result.json.txt](https://github.com/oss-review-toolkit/ort/files/12596081/analyzer-result.json.txt)
Note: **analyzer-result.json** is renamed to **analyzer-result.json.txt** for uploading purpose

Please can you check if you are able to generate the spdx ?  
command: `ort report -i analyzer-result.json -o . -f SpdxDocument`

**Comment by sschuberth** [comment]
> I have packages. Here is the [analyzer-result.json.txt](https://github.com/oss-review-toolkit/ort/files/12596081/analyzer-result.json.txt)

Well, yes, there are (ORT) packages in the result file. But that's not what I was referring to. You don't have any (SPDX) project packages. And that seems to be because non-root projects (i.e. sub-projects that appear with linkage `PROJECT_DYNAMIC` or `PROJECT_STATIC` in the dependency tree) get filtered out. And in some scopes, like `debugAndroidTestCompileClasspath`, the root project `Gradle:com.company.project.AndroidSampleAPP:AndroidSampleAPP:200.0.233730000-SNAPSHOT` seems to depend on itself, making it a sub-project of itself, and thus gets filtered out. Looks like something is weird about that project's Gradle setup.

**Comment by sschuberth** [comment]
> Looks like something is weird about that project's Gradle setup.

Did you have a change to look at this @dineshr93?

**Comment by dineshr93** [comment]
> Did you have a change to look at this @dineshr93?
  
You are right when there is custom sub project which cannot be resolved by gradle it throws the above error.  In Blackduck they simply create the entry of that subproject and moves on without digging further as it is anyways not resolvable by gradle. (as found in tree section in ort webapp format) By the way webapp report generated successfully  including that unresolvable sub project at the leaf from its dependency line.

when I tried some other gradle project (without custom subproject dependencies), the spdx doc was generated successfully.

Improvements: In error, show the component name for which it cant able to describe/resolve dependencies further so that user know where the problem is.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
