### ISSUE TITLE
Requesting Support for vcpkg Integration in ORT Project

### ISSUE THREAD

**Issue by ksg97031** [oss-review-toolkit/ort#7521]
Hi ORT Team,

I have a C++ project that uses vcpkg as a dependency manager. However, it appears that ort project does not currently support it. Do you have any plans to add support for vcpkg?

https://vcpkg.io/en/

**Comment by sschuberth** [comment]
Please have a look at existing issue https://github.com/oss-review-toolkit/ort/issues/1643. In particular, it's marked as "help wanted", so the core team currently has no concrete plans to implement it.
