### ISSUE TITLE
Add shards (Crystal) as supported package manager 

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#756]
Add support for the hex dependency manager to the analyzer module.

https://github.com/crystal-lang/shards

**Comment by sschuberth** [comment]
As discussed in the [community meeting](https://github.com/oss-review-toolkit/ort/wiki/ORT-Community-Meeting#2023-04-27), no one has ever again asked for this, so I'm closing this as "not planned". Interested users could still implement this as a third-party plugin.
