### ISSUE TITLE
Renew website certificate

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#7565]
Docusaurus uses Let's Encrypt to generated certificate so the ORT website is accessible over https, however this certificate is only valid for 60 or 90 days. We should figure out how we can renew it ourselves.

**Comment by heliocastro** [comment]
You can set automated renewal. Owner of the domain can do that

**Comment by sschuberth** [comment]
@mnonnenmacher, do you know it this is still a thing?

**Comment by mnonnenmacher** [comment]
I don't think that the certificate is generated by Docusaurus in our case, Let's Encrypt is only mentioned in the docs for deploying it with Docker: https://docusaurus.community/knowledge/deployment/docker/

In our case it should be GitHub that creates the certificate: https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

I'll close this issue as so far we had no issues with the certificate.
