### ISSUE TITLE
Wrong url trimming for scm tag in maven

### ISSUE THREAD

**Issue by hanna-modica** [oss-review-toolkit/ort#7594]
We have a scan with the following error:
`
:1.0.0 | IOException:  Could not resolve provenance for package  'Maven:org.springframework.modulith:spring-modulith-starter-core:1.0.0'  for source code origins [ARTIFACT, VCS]. Resolution of VCS failed with: IOException: Could not resolve revision for package  'Maven:org.springframework.modulith:spring-modulith-starter-core:1.0.0'  with VcsInfo(type=Git,  url=https://github.com/spring-projects/spring-modulith.git, revision=,  path=starters/spring-modulith-starter-core): 	Discarding revision '1.0.0' because the requested VCS path  'starters/spring-modulith-starter-core' does not exist.
`
The path seems to be detected incorrectly at [1], because the scm tag actually reads:
```
<scm>
<connection>scm:git:https://github.com/spring-projects/spring-modulith/spring-modulith-starters/spring-modulith-starter-mongodb</connection>
<developerConnection>scm:git:ssh://git@github.com/spring-projects-experimental/spring-modulith/spring-modulith-starters/spring-modulith-starter-mongodb</developerConnection>
<tag>1.0.0</tag>
<url>https://github.com/spring-projects/spring-modulith/spring-modulith-starters/spring-modulith-starter-mongodb</url>
</scm>
```

[1] https://github.com/oss-review-toolkit/ort/blob/902bfef1dc2fbfed35a2ce156c1f2007e124d9bd/plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt#L443

**Comment by sschuberth** [comment]
Note, this seems to be a transitive Maven dependency, so I believe the quoted `GradleInspector` code related to the `projectPrefix` is irrelevant.

**Comment by sschuberth** [comment]
I have created a test locally reproducing this.
