### ISSUE TITLE
Consider switching the OSV model implementation to `osv4k`

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#7703]
See https://github.com/saveourtool/osv4k. This could ease maintenance on your side. What do you think @fviernau?

**Comment by fviernau** [comment]
In my view the model is so little and no complex at all, that it is currently worth paying the very little maintenace cost 
for full control and the ability to move instantly. Also compared to expected result updates, the effort for model alignments in my view was neglectable.

Futhermore, I haven't had the time yet to try to understand the use of generics here [1], on the first glance I don't get this.
Finally, it seems the serialization is based on jackson while in ORT we seem to move towards Kotlinx serialization.

[1] https://github.com/saveourtool/osv4k/blob/main/src/commonMain/kotlin/com/saveourtool/osv4k/OsvSchema.kt

**Comment by sschuberth** [comment]
> Finally, it seems the serialization is based on jackson while in ORT we seem to move towards Kotlinx serialization.

The [features](https://github.com/saveourtool/osv4k?tab=readme-ov-file#features) say [KotlinX Serialization](https://github.com/Kotlin/kotlinx.serialization) is supported. However, I tend to agree with your other points. So let's close this for now, but stay aware that their library (as well as some other interesting projects from the same organization) exists.
