### ISSUE TITLE
Docker image can not be built due to certificate issues

### ISSUE THREAD

**Issue by mneumei** [oss-review-toolkit/ort#7727]
I tried to build the dockerfile. After finding the solution to use ENV JAVA_OPTS="-Djdk.tls.client.protocols=TLSv1.2" , i even put that everywhere, even before the gradlew call. Still, it fails. Is there some additional trick to it?

**Comment by mneumei** [comment]
The call: 

WORKDIR $HOME/src/ort

ENV JAVA_OPTS="-Djdk.tls.client.protocols=TLSv1.2"

# Prepare Gradle
RUN --mount=type=cache,target=/var/tmp/gradle \
    --mount=type=bind,target=$HOME/src/ort,rw \
    export GRADLE_USER_HOME=/var/tmp/gradle \
    && sudo chown -R "$USER". $HOME/src/ort /var/tmp/gradle \
    && scripts/set_gradle_proxy.sh \
    && JAVA_OPTS="-Djdk.tls.client.protocols=TLSv1.2" ./gradlew --no-daemon --stacktrace \
    -Pversion=$ORT_VERSION \
    :cli:installDist \
    :helper-cli:startScripts \
    && mkdir /opt/ort \
    && cp -a $HOME/src/ort/cli/build/install/ort /opt/ \
    && cp -a $HOME/src/ort/scripts/*.sh /opt/ort/bin/ \
    && cp -a $HOME/src/ort/helper-cli/build/scripts/orth /opt/ort/bin/ \
    && cp -a $HOME/src/ort/helper-cli/build/libs/helper-cli-*.jar /opt/ort/lib/

**Comment by mneumei** [comment]
Part of the error:
91.09 Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target  
91.09   at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
91.09   at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
91.09   at java.base/sun.security.validator.Validator.validate(Validator.java:264)
91.09   at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
91.09   at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
91.09   at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
91.09   ... 131 more
91.09 Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
91.09   at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146)
91.09   at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:127)
91.09   at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
91.09   at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
91.09   ... 136 more

**Comment by mneumei** [comment]
So i was able to solve this in parts by adding a certificate to the ort folder (as i am working behind a corporate proxy). That would be helpful to be documented as well

**Comment by sschuberth** [comment]
> That would be helpful to be documented as well

We welcome PRs in this area, e.g. at https://oss-review-toolkit.org/ort/docs/guides/docker#docker-build-fails-with-an-ssl-handshake-error.
