### ISSUE TITLE
Add documentation for published Docker images

### ISSUE THREAD

**Issue by vw-anton** [oss-review-toolkit/ort#7781]
We now have different docker images published to GHCR, however this isn't mentioned in any of the guides or README (?) nor do we have any explanations of the different types (ort, ort-extended, ...?) which makes it hard for new users to get started with these images.

**Comment by sschuberth** [comment]
> any explanations of the different types (ort, ort-extended, ...?

Before we do this, we should rename the images to `ort-minimal` and `ort-full` as [agreed in the poll](https://oss-review-toolkit.slack.com/archives/C9NNJ54B1/p1695977688303359). Ping @tsteenbe and @heliocastro.

**Comment by heliocastro** [comment]
Ok, on to it today.

**Comment by sschuberth** [comment]
> I would mention which ones are included here to make this obvious to interested users.

Mind filing a PR @vw-anton? The [page](https://oss-review-toolkit.org/ort/docs/getting-started/installation) contains an "[Edit this page](https://github.com/oss-review-toolkit/ort/tree/main/website/docs/getting-started/installation.md)" link in the footer to make this super-easy 😉
