### ISSUE TITLE
Docker:  Update of python-inspector version not reflected in 'ort-extended' image 6.0.0

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#7798]
As per c841f41d26c8ffe5fbe6127d935546ea94795043 python-inspector version should be 0.10.0 in the 6.0.0 extended image, but it actually  is 0.9.8.

_edit: Also `git-lsf` is absent, but shouldn't be as of:_ https://github.com/oss-review-toolkit/ort/commit/a4b12df0acc6329cc164712e189d2c865c4280b2

**Comment by sschuberth** [comment]
Looks like the image simply hasn't been updated since Sep 8:

![image](https://github.com/oss-review-toolkit/ort/assets/349154/04d949b2-c89a-484b-abe9-c4ca5856822a)

**Comment by sschuberth** [comment]
Hmm, on the other hand, [this page](https://github.com/oss-review-toolkit/ort/pkgs/container/ort-extended) shows version 6.0.0 from today, weird.
