### ISSUE TITLE
Migration to `kotlinx-serialization` broke `Cargo.lock` parsing

### ISSUE THREAD

**Issue by CryZe** [oss-review-toolkit/ort#7825]
In #7709 the TOML parsing got migrated to `kotlinx-serialization`. This seems to have broken the parsing for us. 

We are getting the following error now:
```
MissingFieldException: Field 'metadata' is required for type with serial name 'org.ossreviewtoolkit.plugins.packagemanagers.cargo.CargoLockFile', but it was missing
```

Note how the `metadata` field is always required now:
https://github.com/oss-review-toolkit/ort/blob/e4f232a1a840d868c8a410b1173a40b6d2c46cb3/plugins/package-managers/cargo/src/main/kotlin/Cargo.kt#L123

Whereas before it was optional:
https://github.com/oss-review-toolkit/ort/blob/8de846081575f46b5416704d38730b8977c879d9/plugins/package-managers/cargo/src/main/kotlin/Cargo.kt#L115-L118

This seems to be the culprit:
https://github.com/oss-review-toolkit/ort/blob/e4f232a1a840d868c8a410b1173a40b6d2c46cb3/plugins/package-managers/cargo/src/main/kotlin/CargoLockFile.kt#L35

This almost certainly needs to be:
```kotlin
val metadata: Map<String, String>? = null
```
(or an empty map)

Also just for completeness. Here's cargo itself treating this field as optional:
https://github.com/rust-lang/cargo/blob/7046d992f9f32ba209a8079f662ebccf9da8de25/src/cargo/ops/lockfile.rs#L167

**Comment by sschuberth** [comment]
Thanks @CryZe for the sophisticated report! Your reference to Cargo itself indeed is interesting, as at https://docs.rs/cargo-lock/latest/cargo_lock/struct.Lockfile.html `metadata` seemed non-optional to me as it's not wrapped in `Option<>` (but maybe I just don't understand Rust enough :grinning:)

For the fix, however, I'd probably go for `val metadata: Map<String, String> = emptyMap()` instead to avoid the need to deal with a `null` value here.

**Comment by CryZe** [comment]
The `cargo_lock` package does not seem to be an official package. However it seems like `cargo` itself often treats this field as an empty list in its own source code:
https://github.com/rust-lang/cargo/blob/7046d992f9f32ba209a8079f662ebccf9da8de25/src/cargo/ops/lockfile.rs#L167

More importantly, the field / list simply doesn't exist in most serialized `Cargo.lock` files (in fact I can't even figure out how you can even get it in there, other than manually placing it there. I doesn't seem to be inherited from the `Cargo.toml`). The docs don't even seem to indicate that it's not a "real" field that Cargo manages:
https://github.com/rust-lang/cargo/blob/7046d992f9f32ba209a8079f662ebccf9da8de25/src/cargo/core/resolver/resolve.rs#L31-L33

**Comment by sschuberth** [comment]
Please let me know if https://github.com/oss-review-toolkit/ort/pull/7826 fixes the issue for you.

**Comment by CryZe** [comment]
Unfortunately I've never ran (or built) `ort` myself, as it is run as part of fairly opaque checks in our company's release process. I can try to get it running quickly, but I can't promise anything.

**Comment by CryZe** [comment]
Alright, I was able to confirm that this indeed resolves the issue. Thanks a lot :)

**Comment by franzlst** [comment]
@sschuberth Also thanks from my side for this really quick fix. How is your release process? Will this be integrated in the next releases soon? Can you tell me when?

**Comment by sschuberth** [comment]
We usually release once  week on Thursday before the community meeting. So I'm confident that this will make it into tomorrow's release.

**Comment by sschuberth** [comment]
> The `cargo_lock` package does not seem to be an official package.

BTW, are you aware of an official spec for Cargo's lock file then, @CryZe?
