### ISSUE TITLE
Advisor does not accept --advisors argument on latest main

### ISSUE THREAD

**Issue by geoandri** [oss-review-toolkit/ort#7835]
Building ORT on latest main version and running

```
./cli/build/install/ort/bin/ort advise -i /input/analyzer-result.yml -o /output -a OssIndex

```

I get the following error

```
Error: invalid value for -a: Advisor 'OssIndex' is not one of [].
```

It looks like this regression was introduced with [this](https://github.com/oss-review-toolkit/ort/pull/7803/commits/da74614c0e5a2358b3feaaa4e902ab8a05700acf) commit. Building ORT in a version before this commit, it works as expected.

**Comment by sschuberth** [comment]
This has just been fixed with https://github.com/oss-review-toolkit/ort/pull/7831, please try again. I'll also make another patch release with this fix today.

**Comment by sschuberth** [comment]
There's now also https://github.com/oss-review-toolkit/ort/releases/tag/6.1.1 available with the fix.
