### ISSUE TITLE
Issues with running functional tests against the published (full) `ort` Docker image

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#7859]
In my [experiments to remove Batect](https://github.com/oss-review-toolkit/ort/pull/7853) I came across [several test failures](https://scans.gradle.com/s/gpuvz3ix66jiu/tests/overview?outcome=FAILED) when using the published `latest` version of the `ort` Docker image instead of using Batect with `Dockerfile-legacy`:

![image](https://github.com/oss-review-toolkit/ort/assets/349154/1b2a39df-68b9-4592-9a9b-768600bf8b0a)

Problems seem to be:
* `ANDROID_HOME` / `ANDROID_SDK_ROOT` is not set (only the former should suffice).
* An unknown issue with JRuby / Asciidoctor.
* The Git `repo` tool is not in `PATH`.

**Comment by sschuberth** [comment]
@heliocastro, could you maybe have a look at the [Android](https://scans.gradle.com/s/gpuvz3ix66jiu/tests/task/:plugins:package-managers:gradle-package-manager:funTest/details/org.ossreviewtoolkit.plugins.packagemanagers.gradle.GradleAndroidFunTest/Root%20project%20dependencies%20are%20detected%20correctly?focused-exception-line=0-46&top-execution=1) and [repo](https://scans.gradle.com/s/gpuvz3ix66jiu/tests/task/:cli:funTest/details/org.ossreviewtoolkit.cli.AnalyzerFunTest/correctly%20report%20VcsInfo%20for%20git-repo%20projects?focused-exception-line=0-1-2-0&top-execution=1) issues?

**Comment by heliocastro** [comment]
@sschuberth Looking on it

**Comment by heliocastro** [comment]
@sschuberth latest now in 6.1.1, meaning the image is the old minimal one, so repo and android bits areis not there. Same for Ruby.

Easy to check with repo:

With latest ( tagged before the name changing )
```shell
❯ docker run -it --rm --platform linux/amd64 --entrypoint repo ghcr.io/oss-review-toolkit/ort:latest --help  
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "repo": executable file not found in $PATH: unknown.
``` 

With snapshot, that is already new naming:
```shell
❯ docker run -it --rm --platform linux/amd64 --entrypoint repo ghcr.io/oss-review-toolkit/ort:snapshot --help
usage: repo COMMAND [ARGS]

repo is not yet installed.  Use "repo init" to install it here.

The most commonly used repo commands are:

  init      Install repo in the current working directory
  help      Display detailed help on a command

For access to the full online help, install repo ("repo init").

Bug reports: https://issues.gerritcodereview.com/issues/new?component=1370071
```

**Comment by sschuberth** [comment]
I wasn't aware that we also have a `snapshot` Docker tag in addition to `latest`. So `snapshot` points to the more recent image built from `main`, and `latest` points to the more recent image built from a Git tag, correct?

**Comment by heliocastro** [comment]
Correct. snapshot tag is build every day at 5 of morning. 
latest is only the tagged.

**Comment by sschuberth** [comment]
The remaining problems have been resolved as part of https://github.com/oss-review-toolkit/ort/pull/7894.
