### ISSUE TITLE
Subversion plugin error

### ISSUE THREAD

**Issue by ramzini47** [oss-review-toolkit/ort#7899]
```
 ______________________________                                                       
/        \_______   \__    ___/ The OSS Review Toolkit, version 7.0.0-044.sha.bb742aa.
|    |   | |       _/ |    |                                                          
|    |   | |    |   \ |    |    Running 'scan' as 'remi' under Java 11.0.20.1 on Linux
\________/ |____|___/ |____|    with 8 CPUs and a maximum of 8944 MiB of memory.      
                                                                                      
Environment variables:                                                               
ORT_CONFIG_DIR = /home/remi/.ort/config                                              
ORT_DATA_DIR = /home/remi/.ort                                                       
SHELL = /bin/bash                                                                    
TERM = xterm-256color                                                                
JAVA_HOME = /usr/lib/jvm/java-11-openjdk-amd64                                       
                                                                                     
Looking for ORT configuration in the following file:
        /home/remi/.ort/config/config.yml

Scanning projects with:
        ScanCode (version 32.0.8)
Scanning packages with:
        ScanCode (version 32.0.8)
13:45:52.107 [DefaultDispatcher-worker-22] WARN  org.ossreviewtoolkit.plugins.versioncontrolsystems.subversion.Subversion - Failed to update the Subversion working tree at '/tmp/ort-DefaultWorkingTreeCache4751869421360972206' to revision 'trunk':
SVNException: svn: E160005: Target path '/commons/proper/cli/trunk' does not exist
svn: E175002: REPORT of '/repos/asf/!svn/vcc/default': 500 Internal Server Error (http://svn.apache.org)
```

System:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```
ORT installed using 

`./gradlew installDist`

**Comment by sschuberth** [comment]
This doesn't look like an error in ORT, but like something caused by a package pointing to an invalid / outdated Subversion URL. You probably need to create a [package curation](https://oss-review-toolkit.org/ort/docs/configuration/package-curations) for that package, pointing at the correct URL.

Try running the scanner with `--info` (like `ort --info scan ...`) to see the URL causing the problem. If you also cannot clone from that URL manually, it's not ORT's fault.

**Comment by sschuberth** [comment]
So, judging from [your other issue](https://github.com/oss-review-toolkit/ort/issues/7900) with more info, the offending package is `commons-cli`:

> 13:59:23.115 [main] WARN  org.ossreviewtoolkit.downloader.vcs.Subversion - Failed to update the Subversion working tree at '/tmp/ort-ScanCode1571366875593154323/Maven/commons-cli/commons-cli/1.4' to revision 'trunk':
SVNException: svn: E160005: Target path '/commons/proper/cli/trunk' does not exist
svn: E175002: REPORT of '/repos/asf/!svn/vcc/default': 500 Internal Server Error (http://svn.apache.org)

A quick research shows that `common-cli` as moved from Subversion to [Git by now](https://github.com/apache/commons-cli), but [the metadata of release 1.4 still points to Subversion](https://github.com/apache/commons-cli/blob/cli-1.4/pom.xml#L42-L46).

As we cannot change metadata for artifacts published in the past, you need to [use a package curation as outlined above](https://github.com/oss-review-toolkit/ort/issues/7899#issuecomment-1819260356).
