### ISSUE TITLE
Scanner: Avoid returning irrelevant issues

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#7921]
The scanner might run into an issue which related only to a single file.
If an issue related to a file which not within the set of files resulting from filtering the scan result by VCS path, then
the issue should also be filtered out. This happens e.g. for TIMEOUT issues.

In this context, it makes sense to consider enabling the path excludes to silence timeouts as well.

**Comment by fviernau** [comment]
Thinking about solving this by extending `ScanSummary` to have a dedicated property for `issues` which are specific to a single file. Maybe just a map `filePath -> issue` ? What do you think?

**Comment by mnonnenmacher** [comment]
Do we get the affected file for such issues from the ScanCode result model or would we have to parse the error messages to try to find out if an issue belongs to a single file?

**Comment by fviernau** [comment]
Finally, the following components adhere to the affected path of the issues WRT to path excludes and VCS:
- model such as `ScanSummary` / `OrtResult`
- `EvaluatedModelReporter`
- `StaticHtmlReporter`
- `WebAppReporter`

Therefore, closing the issue as completed. 

Note that the exist code / issues stats CLI output of the `ScannerCommand` does not yet adhere to excluded paths. 
Implementing that does require to also make the scanner command update the resolved config to import package
configurations and issue resolutions. This can be done as a (larger) follow-up task, which has its own ticket.

**Comment by sschuberth** [comment]
> This can be done as a (larger) follow-up task, which has its own ticket.

Mind creating such an issue (if it does not exist yet) so that we do not forget about it?

**Comment by fviernau** [comment]
> Mind creating such an issue (if it does not exist yet) so that we do not forget about it?

I've updated my above comment.
