### ISSUE TITLE
[ERROR] Invalid packaging for parent POM com.google.guava:listenablefuture:1.0, must be "pom" but is "jar" @ 

### ISSUE THREAD

**Issue by dimitris-iliou** [oss-review-toolkit/ort#7938]
We have several projects receiving the bellow log error:

`Could not get package information for dependency 'com.google.guava:listenablefuture:1.0': ProjectBuildingException: 3 problems were encountered while building the effective model for com.google.guava:listenablefuture:1.0 [ERROR] Invalid packaging for parent POM com.google.guava:listenablefuture:1.0, must be "pom" but is "jar" @ [ERROR] Invalid packaging for parent POM com.google.guava:listenablefuture:1.0, must be "pom" but is "jar" @ [FATAL] The parents form a cycle: com.google.guava:listenablefuture:1.0 -> com.google.guava:listenablefuture:1.0 @ for project com.google.guava:listenablefuture:1.0 at /builds/oss/oss-review-toolkit/ort-gitlab-ci/cache/.gradle/caches/modules-2/files-2.1/com.google.guava/listenablefuture/1.0/48183accf902b8d60bc6c853aa5c57febd124a48/listenablefuture-1.0.pom Caused by: ModelBuildingException: 3 problems were encountered while building the effective model for com.google.guava:listenablefuture:1.0 [ERROR] Invalid packaging for parent POM com.google.guava:listenablefuture:1.0, must be "pom" but is "jar" @ [ERROR] Invalid packaging for parent POM com.google.guava:listenablefuture:1.0, must be "pom" but is "jar" @ [FATAL] The parents form a cycle: com.google.guava:listenablefuture:1.0 -> com.google.guava:listenablefuture:1.0 @`

After some search I found this related issue https://github.com/oss-review-toolkit/ort/issues/2115 which was fixed a while ago. Did something change since then?

**Comment by sschuberth** [comment]
I've extended the [existing curation](https://github.com/oss-review-toolkit/ort-config/blob/main/curations/Maven/com.google.guava/listenablefuture.yml) for version `9999.0-empty-to-avoid-conflict-with-guava` of that artifact to also cover version 1.0: https://github.com/oss-review-toolkit/ort-config/pull/148

**Comment by sschuberth** [comment]
The curation has been merged in `ort-config`. Taking it into use should resolve the issue.

**Comment by sschuberth** [comment]
> This issue resurfaced using GradleInspector, while legacy Gradle works fine. [](https://github.com/sschuberth)

That doesn't make sense, as the issue was fixed via a curation, which is independent of the package manager being used.

If you still believe that the issue persists, please provide a repository to analyze to reproduce the issue.
