### ISSUE TITLE
Maven private repository

### ISSUE THREAD

**Issue by remi-cogito** [oss-review-toolkit/ort#7940]
How to set up docker image to authenticate with private maven repository?

**Comment by BinchenQ** [comment]
I have tried with  `/home/ort/.m2/settings.xml` and `~/.m2/settings.xml`, it did not work.
```
status code: 401, reason phrase:  (401) and 'parent.relativePath' points at no local POM @ line 19, column 13
```

**Comment by arunsmartarrow** [comment]
I am also facing the same issue as described by @BinchenQ.

@sschuberth: Can you please advise here, thanks

**Comment by sschuberth** [comment]
> status code: 401, reason phrase:  (401) and 'parent.relativePath' points at no local POM @ line 19, column 13

In this specific case from @BinchenQ it seems like the parent POM is hosted elsewhere, like another host, which might require different authentication than the primary project under analysis. Hard to say without more details...

**Comment by MNesche** [comment]
Hi, in my case, running ORT locally, only the solution with .gitconfig worked for private repositories.
The .netrc file is recognized when running with --debug, but the request leads always to "Not Authorized".
Maybe you could give that a try.
