### ISSUE TITLE
Config args for python-inspector

### ISSUE THREAD

**Issue by paulhfu** [oss-review-toolkit/ort#7945]
I want to use the analyzer with PIP to get my dependency list.

Is there a way to define arguments for `python-inspector`?
It  defaults to the wrong python version and the analyzer errors out.
I would like to set the correct version.

**Comment by sschuberth** [comment]
See

https://github.com/oss-review-toolkit/ort/blob/5bb6a681f18454b93bc26eacb9eba4af9f2e6548/plugins/package-managers/python/src/main/kotlin/Pip.kt#L50-L53

So you can configure the Python version to use for analysis via package manager specific options configured in the `config.yml`'s `packageManagers` section:

https://github.com/oss-review-toolkit/ort/blob/5bb6a681f18454b93bc26eacb9eba4af9f2e6548/model/src/main/resources/reference.yml#L98

Like:

```
packageManagers:
  Pip:
    options:
      pythonVersion: "3.10"
```
