### ISSUE TITLE
Introduce a helper function to generate a project name if none is available from metadata

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#7992]
See https://github.com/oss-review-toolkit/ort/pull/7991 for context. Individual package manager implementations currently use code like

    definitionFile.relativeTo(analysisRoot).invariantSeparatorsPath

in this case, but this should be aligned and factored out to a helper function provided by the package manager base.

**Comment by sschuberth** [comment]
0c748f4c24c499f058f169c6c66497c4646f983f actually already introduced `PackageManager.getFallbackProjectName()`. We're just not yet making good use of it 😉

**Comment by mnonnenmacher** [comment]
> We're just not yet making good use of it 😉

@sschuberth Aren't we? In a recent PR I was looking for places where we are not using it and fixed it there. Are there any left that I missed?

**Comment by sschuberth** [comment]
> In a recent PR I was looking for places where we are not using it and fixed it there.

I wasn't aware that your search was supposed to be exhaustive, I though you just fixed some random places where you saw fit.

My assumption was that there are some places lurking where we have no proper error handling at all in place when creating projects, and thus it would also not be obvious where to fall back to `getFallbackProjectName()`. But that really just was an assumption.

**Comment by mnonnenmacher** [comment]
> I wasn't aware that your search was supposed to be exhaustive, I though you just fixed some random places where you saw fit.

I tried to find all places but it could be that I missed some.
