### ISSUE TITLE
Reporter error on ill-formatted license info

### ISSUE THREAD

**Issue by paulhfu** [oss-review-toolkit/ort#8015]
I could run the the analyzer (`python-inspector`) and the scanner (`scan-code`) with success on my `setup.py`.
But once I try to run the reporter, I get the following error:

```
Generating the 'SpdxDocument' report in thread 'DefaultDispatcher-worker-2'...

11:59:11.878 [main] ERROR org.ossreviewtoolkit.plugins.commands.reporter.ReporterCommand - Could not create 'SpdxDocument' report in 1.565150230s: IllegalArgumentException: The entries in 'licenseInfoInFiles' must each be either an SPDX expression, 'NONE' or 'NOASSERTION', but found 'GPL-2.0-or-later AND Bootloader-exception'.

Created 0 of 1 report(s) in 1.639714315s.
```

I guess this error comes from a ill-formatted scanner result? Is it possible to ignore this error?
Thank you for your help.

**Comment by sschuberth** [comment]
`Bootloader-exception` is an exception to a license, not a license on its own, and thus must not stand alone. It can only be the second operand to the `WITH` SPDX license expression operator.

> I guess this error comes from a ill-formatted scanner result?

Probably. Though theoretically it could also come from package curations, package configurations, or even originally declared package metadata.

> Is it possible to ignore this error?

It's certainly technically *possible*, in several ways (package curations, package configurations), but we cannot give any legal advice whether it's safe to do that.

**Comment by sschuberth** [comment]
Closing this in favor of https://github.com/oss-review-toolkit/ort/issues/8052.
