### ISSUE TITLE
specific copyright garbage text not getting removed

### ISSUE THREAD

**Issue by dineshr93** [oss-review-toolkit/ort#8019]
I have copyright garbage `(c) uSSg1/2a-N (c) OY+` in the report

![image](https://github.com/oss-review-toolkit/ort/assets/4498415/b496ed15-8bff-48c1-9a4d-30bc1a829a4c)

 and trying to skip this using  /home/user/config/copyright-garbage.yml

![image](https://github.com/oss-review-toolkit/ort/assets/4498415/41f65f36-3797-4972-a71e-59766c7ae916)

But somehow the above garbage text doesnt seem to get removed

I tired adding escape slash behind non alpha numeric characters. 
 `(c) uSSg1\/2a-N (c) OY+`
 `(c) uSSg1/2a\-N (c) OY+`
 `(c) uSSg1/2a-N (c) OY\+`

nothing works. How to remove this copyright garbage text `(c) uSSg1/2a-N (c) OY+`  ?

I have added other copyright garbage it works. only above text seems to not getting removed. Please may I have your help?

Thanks

**Comment by sschuberth** [comment]
Please see the `CopyrightGarbage` class docs:

https://github.com/oss-review-toolkit/ort/blob/25361dd02648e8705bc0e0be3736ce9a09365f6f/model/src/main/kotlin/config/CopyrightGarbage.kt#L28-L32

So the `items` (in contrast to `patterns`) are *literal* strings. Just adding `(c) uSSg1/2a-N (c) OY+` should do the trick.

**Comment by dineshr93** [comment]
Hi Sebastian,

Thanks for the response. I already tried to add as it is. It didn't work.
That's why I had to raise this issue.


The patterns that I mentioned are the things I tried. Which didn't work as
well.

Regards
Dinesh

**Comment by sschuberth** [comment]
> I already tried to add as it is. It didn't work. That's why I had to raise this issue.

Then why didn't you make it explicit in the report that you also literally tried `(c) uSSg1/2a-N (c) OY+`? That would have saved both of us time.

> The patterns that I mentioned are the things I tried. Which didn't work as
well.

Ok, these are the *additional* things you tried, not the *only* ones (like it read to me).

One more thing that comes to my mind is: Where did you copy & paste the literal copyright garbage string from? You should probably *not* copy it from the PDF document, but from the raw scan ORT result, just to ensure no encoding issues play a role when inserting the literal string to `[copyright-garbage.yml](https://github.com/oss-review-toolkit/ort-config/blob/main/copyright-garbage.yml)`.

**Comment by dineshr93** [comment]
Hi @sschuberth 

You are right. In raw ort result file the text was like this 
![image](https://github.com/oss-review-toolkit/ort/assets/4498415/35e48394-705b-41f5-aaf4-cdf7813b5838)

**(c) uSSg1/2a+-N (c) OY** instead of  
**(c) uSSg1/2a-N (c) OY+** (in the **AsciiDoc_disclosure_document.html**)

Not sure though why **plus symbol +** is getting added at the end of **asciiDoc_disclosure_document.html**

 when I added **(c) uSSg1/2a+-N (c) OY** in **copyright-garbage.yml** file 

![image](https://github.com/oss-review-toolkit/ort/assets/4498415/64eb47d1-8ebc-42f1-a857-2b0ee41f6e54)
 

now it got removed (in the **AsciiDoc_disclosure_document.html**)
![image](https://github.com/oss-review-toolkit/ort/assets/4498415/26270a06-6fdc-4404-8f64-0c9fbe0f2f19)

thanks for the hint.

**Comment by fviernau** [comment]
@dineshr93

In order to add copyright garbage entries to the file I've created some easy workflow which
works really nicely for me. It's based on `orthw` [1], and works as follows

1. run: `orthw copyrights` which creates `copyrights.txt` containing all copyrights which have not matched
             any garbage entry
2. Open up the `.txt` file in your editor and remove all lines which are valid copyrights
    so that only garbage entries remain.
3. run `orthw export-copyright-garbage`

Now all garbage entries are places in your `copyrigh-garbage.yml` file. Done.
I suggest giving this a try.

[1] https://github.com/oss-review-toolkit/orthw

**Comment by dineshr93** [comment]
Thanks @fviernau  I will try it out.
In ort Assets there is orth-9.0.0.zip file. Is this the same as orthw ?

Does **orthw copyrights ** perform Ort scan internally to get all copyrights for the main project and all it's dependencies?

**Comment by sschuberth** [comment]
> In ort Assets there is orth-9.0.0.zip file. Is this the same as orthw ?

No, `orthw` is an additional wrapper script round `orth` (aka the "helper-cli") that currently needs to be downloaded separately at https://github.com/oss-review-toolkit/orthw.
