### ISSUE TITLE
False `InvalidLicenseChoiceException` for complex expression

### ISSUE THREAD

**Issue by mmurto** [oss-review-toolkit/ort#8082]
Expression `(MIT OR GPL-2.0-only) AND (MIT OR BSD-3-Clause OR GPL-1.0-or-later) AND (MIT OR BSD-3-Clause OR GPL-2.0-only)` doesn't allow choice of `MIT AND MIT AND MIT`, but throws the following exception:

`Caused by: org.ossreviewtoolkit.utils.spdx.InvalidLicenseChoiceException: MIT AND MIT AND MIT is not a valid choice for (MIT OR GPL-2.0-only) AND (MIT OR BSD-3-Clause OR GPL-1.0-or-later) AND (MIT OR BSD-3-Clause OR GPL-2.0-only). Valid choices are: [MIT AND BSD-3-Clause AND GPL-1.0-or-later, MIT AND BSD-3-Clause AND GPL-1.0-or-later AND GPL-2.0-only].`

**Comment by sschuberth** [comment]
@mmurto, I have a semi-off-topic question: Given `(MIT OR GPL-2.0-only) AND (MIT OR BSD-3-Clause OR GPL-1.0-or-later) AND (MIT OR BSD-3-Clause OR GPL-2.0-only)`, would you also expect / wish for `MIT` to be a valid choice, or is the explicit `MIT AND MIT AND MIT` ok / desired?

**Comment by mmurto** [comment]
> would you also expect / wish for `MIT` to be a valid choice, or is the explicit `MIT AND MIT AND MIT` ok / desired?

Personally I'd prefer `MIT` there, but `MIT AND MIT AND MIT` is totally ok to write in the configuration.

**Comment by sschuberth** [comment]
> Personally I'd prefer `MIT` there, but `MIT AND MIT AND MIT` is totally ok to write in the configuration.

I've [verified](https://github.com/oss-review-toolkit/ort/pull/8106/commits/c787f7a239f2b43f7be79901d5d73687b780a752) that just using "MIT" in this case is actually already working.
