### ISSUE TITLE
Support .tar.gz archives that do NOT contain intermediate directory entries

### ISSUE THREAD

**Issue by wkl3nk** [oss-review-toolkit/ort#8098]
When dealing with .tar.gz archives, ORT seems to have a problem in cases where the archive contains no intermediate diretory entries. For example, if the first entry in the archive is named _orjson-3.7.8/Cargo.toml_

You may argue that the archive in this case can be regarded as "corrupt", but other Unix tools like _gzip_ can handle that.

It seems to be a specific Java issue.

I currently have a problem in the scan step, when ORT downloads a _.tar.gz_ of source code of _orjson-3.7.8_.

**Quick steps to reproduce:**

* Download https://files.pythonhosted.org/packages/ac/4a/43daa65b7ed984612267983039a58703c48ccbc62561abb43ec7bc8b0663/orjson-3.7.8.tar.gz
* Replace the file _ort/utils/common/src/test/assets/test.tar.gz_ with _orjson-3.7.8.tar.gz_ (but keep the name, just exchange the test data)
* Run the tests in _ort/utils/common/src/test/kotlin/ArchiveUtilsTest.kt_
* This will result in test failures

**Comment by sschuberth** [comment]
Very weird... for `orjson-3.7.8/include` both `TarArchiveEntry.isDirectory` and `TarArchiveEntry.isFile` are `true`. I'll create a work-around.

**Comment by sschuberth** [comment]
BTW, I've filed [COMPRESS-657](https://issues.apache.org/jira/browse/COMPRESS-657) for this, but I guess it will be ignored just like [COMPRESS-645](https://issues.apache.org/jira/browse/COMPRESS-645).

**Comment by sschuberth** [comment]
> If I follow the steps I have given to reproduct, I still have the test failure as before.

@wkl3nk, I just tried *again*, and for the me fix works. Of course, the test still fails as the archive contents are different, but it does not error-out with the original exception anymore.

**Comment by wkl3nk** [comment]
@sschuberth Sorry for stealing your time. You are right, the original problem is gone. The test just failed because the archive's content is different.

**Comment by sschuberth** [comment]
FYI, the work-around has been [reverted](https://github.com/oss-review-toolkit/ort/commit/1ea5f3763839626a0c1cf44627e5e561781d062d) as part of a [`common-compress` update with the fix](https://github.com/oss-review-toolkit/ort/pull/8302).
