### ISSUE TITLE
Improve gathering of meta-data about Python dependencies

### ISSUE THREAD

**Issue by haikoschol** [oss-review-toolkit/ort#812]
The current implementation of the PIP package manager only gathers meta-data from a setup.py file in the repository being scanned. For dependencies it relies on querying PyPI. This does not work for packages that are hosted elsewhere.

Analogous to the NPM implementation, find the available meta-data about installed packages in the file system after all dependencies have been resolved.

**Comment by sschuberth** [comment]
Actually, ideally we do *not* want to download and install all dependencies, but at most only their meta-data (this is true for both Python and NPM).

**Comment by sschuberth** [comment]
@mnonnenmacher, can you tell whether this issue still makes sense / is applicable to our new approach of using `python-inspector`?

**Comment by mnonnenmacher** [comment]
No, I will close it. If there are specific issues with Python metadata we should create issues for `python-inspector` now.
