### ISSUE TITLE
Improve support for different Java versions

### ISSUE THREAD

**Issue by mnonnenmacher** [oss-review-toolkit/ort#8249]
Currently the Docker image and the artifacts published to Maven Central are both built with Java 17. This can cause two kinds of issues:

* Docker: As the Maven and Gradle analyzers are built into ORT and compiled with the same Java version, sometimes projects cannot be analyzed that require a different Java version. For example, the project could use a Gradle version that is not compatible with Java 17, or the project could require Java 21.
* Maven Central: Projects that use ORT programmatically as a library, like the ORT workbench, must be compiled with at least the same Java version as the ORT artifacts. However, for the same reason as above it could be required to build those tools with a different Java version.

One approach to solve this would be to release the Docker images and the Maven Central artifacts with different variants for each of the Java LTS releases, currently relevant are Java 11, 17, and 21.

Another more complex approach would be to decouple the Maven and Gradle analyzers from ORT itself and release them as standalone tools, comparable to the python-inspector. These tools could then be released with a bundled JVM for the different Java versions.

Also see some related PRs and issues: #4948, #6311, #8027, #8242

**Comment by sschuberth** [comment]
I'm also thinking into the direction of simply installing multiple JDK versions in parallel in the Docker image, and finding a way to choose the JDK at runtime for the package manager implementations. At least for SBT that would work, as it's called as an external CLI tool. Also for Gradle projects that leverage the [toolchains](https://docs.gradle.org/current/userguide/toolchains.html) mechanism that should work. Not sure about Maven, though.

**Comment by mnonnenmacher** [comment]
> Not sure about Maven, though.

I'm not sure if have seen the issue with Maven projects so far, maybe because it's more declarative than Gradle.

**Comment by heliocastro** [comment]
Maven you can have in the properties:
```xml
    <java_source.version>17</java_source.version>
    <java_target.version>17</java_target.version>
```

But then, this is the model applied, so, if you are using java 21 to compile, it will apply only 17 characteristics. Again. sometimes not work well to the plugins.

**Comment by sschuberth** [comment]
> Maven you can have in the properties

You have the same in Gradle, but these have no impact on the chosen JDK (if there are multiple ones on your system), but only on the command line options passed to the compiler.

**Comment by sschuberth** [comment]
My current idea, at least for SBT for now, is to bootstrap the required JDK via https://github.com/foojayio/discoclient at ORT analyzer runtime.

**Comment by fb33** [comment]
Hi, 
Just a feedback with jdk21.
I have some projects with gradle 8.5 and jdk21, and of course with the current ORT image, the analyzer failed.
I make a quick (and naive) test, building in ORT image with jdk21 and run the analyzer. 
=> there is no more issue, but the analyzer found no dependency !

I have also some projects with maven and jdk21, and there is no issue with them, all is fine.

**Comment by fb33** [comment]
Do you have any idea when you'll fix the usage of jdk21 for gradle and sbt project ?

**Comment by sschuberth** [comment]
> Do you have any idea when you'll fix the usage of jdk21 for gradle and sbt project ?

No commitment to that. But providing an example project could speed up things 😉

**Comment by sschuberth** [comment]
> Do you have any idea when you'll fix the usage of jdk21 for gradle and sbt project ?

@fb33 for Gradle it was basically fixed by https://github.com/oss-review-toolkit/ort/pull/9127, for SBT it will be fixed by https://github.com/oss-review-toolkit/ort/pull/9179. Both introduce package manager options to customize the JDK to use.

> here is a sample of gradle project on jdk21 with the results&logs of ORT
> https://github.com/fb33/sample-gradle8.5-jdk21

Could you give yourself https://github.com/oss-review-toolkit/ort/pull/9179 a try on it?

**Comment by fb33** [comment]
Hi @sschuberth 

I have done some successful tests with ORT-32.1.0   👍 

I don't know if I did it in the way you imagine, but here is what I done : 

I built a special ORT docker image (with only tools for my stacks) in which I added open jdk 21.
In the ort.yml, I indicate the javaHome here : 
```yaml
    packageManagers:
      GradleInspector:
        options:
          javaHome: /usr/lib/jvm/java-21-openjdk-amd64
```
I override javaHome (the default one - 17, or the jdk21) on the fly according to the stack of projects being audited.

**Comment by sschuberth** [comment]
> I override javaHome (the default one - 17, or the jdk21) on the fly according to the stack of projects being audited.

Yes, that's a perfectly valid way to do it. If you can limit the number of required JDKs beforehand, you can add them to the Docker image and just configure the right Java home per ORT run. Alternatively, if you don't know which JDK will be required, you can let ORT bootstrap a JDK at runtime that matches the `javaVersion` option. If both `javaHome` and `javaVersion` are given, `javaVersion` takes precedence.

**Comment by fb33** [comment]
Great ! I'll try the bootstrap method. 
thanks for the advice ! 

and good job for this new feature ! 👏

**Comment by sschuberth** [comment]
@mnonnenmacher, do you think this can be closed now with the recent additions to customize the Java home / version?

**Comment by mnonnenmacher** [comment]
> [@mnonnenmacher](https://github.com/mnonnenmacher), do you think this can be closed now with the recent additions to customize the Java home / version?

Yes.
