### ISSUE TITLE
Analyzer confuses Cargo dependency hosted in repo for a source artifact

### ISSUE THREAD

**Issue by bennati** [oss-review-toolkit/ort#8274]
When running the analyzer (revision 2b230b8) on a Cargo project, a dependency which is hosted in a git repo is identified as source artifact. 
The analyzer result contains the following:
```
"source_artifact" : {
          "url" : "https://repo.com/lib.git",
          "hash" : {
            "value" : "123abc",
            "algorithm" : "SHA-1"
          }
        },
        "vcs" : {
          "type" : "Git",
          "url" : "https://repo.com/lib.git",
          "revision" : "",
          "path" : ""
        },
```

Attached are the analyzer results generated by a minimal reproducible example, as well as the source code of the minimal project and library.
[sources.zip](https://github.com/oss-review-toolkit/ort/files/14280331/sources.zip)
[analyzer-result.json](https://github.com/oss-review-toolkit/ort/files/14280332/analyzer-result.json)

**Comment by sschuberth** [comment]
@bennati, can you please try again with the current `main` of ORT, as recently several Cargo improvements were merged?

**Comment by bennati** [comment]
Hi @sschuberth I tested again and the issue is still there

**Comment by sschuberth** [comment]
I had some problems reproducing the issue with your provided data, something was missing IIRC.  Could you set up an example repository that works out of the box?

**Comment by sschuberth** [comment]
I had some problems reproducing the issue with your provided data, something was missing IIRC.  Could you set up an example repository that works out of the box?

**Comment by sschuberth** [comment]
> Could you set up an example repository that works out of the box?

Any update @bennati?

**Comment by bennati** [comment]
This is no longer happening with a more recent ORT version, we can close this issue.
