### ISSUE TITLE
Fails if project has .python-version with a version that is not supported

### ISSUE THREAD

**Issue by elnygren** [oss-review-toolkit/ort#8366]
eg. `3.11.1`

causes analyzer to not be able to analyze Python requirements.txt because 3.11.1 is not installed

solution was to remove .python-version (not desirable, but worked)

**Comment by sschuberth** [comment]
I guess we could solve this by implementing something like in https://github.com/oss-review-toolkit/ort/pull/8080, but for Pip, eventually also temporarily stashing away the `.python-version` file.

**Comment by sschuberth** [comment]
@elnygren, could you please check whether https://github.com/oss-review-toolkit/ort/pull/8367 fixes the issue for you?

**Comment by heliocastro** [comment]
It goes a little deeper. .python-version is not strict to python version, but to python environments as well, even if we would be able develop a mechanism to install the required python, we would never be able to guess for example, if someone decided that the local env is something like "mypython". 
It could be even called "venv" and we don't know which version originally intended.

Stash could be a solution, but more an patch instead over solve the real problem.
On the direction of simplify things, i would say to check stash + get rid of entire mechanisms added like #8080 and focus on two simplifications, minimal python required over pyproject.toml or for older packages, setup.cfg. Both provides the minimum python required version as a minimal. And if not, the version of python used to analyze is the current one.

Beyond that, instruction on website explain how the user should prepare the code ahead.

**Comment by sschuberth** [comment]
> It goes a little deeper. .python-version is not strict to python version

I couldn't find a formal specification for the syntax in that file, and all examples from `pyenv` I saw just contain the version number. Do you have a link to a formal specification?

**Comment by heliocastro** [comment]
Python version is not a formal PEP and AFAIK is only used by pyenv.
You can find here how is described:
https://github.com/pyenv/pyenv?tab=readme-ov-file#understanding-python-version-selection
