### ISSUE TITLE
Add support for Bazel workspaces

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#8449]
Currently, only directories that contain a `MODULE` or `MODULE.bazel` file will be recognized as Bazel projects.

**Comment by sschuberth** [comment]
@nnobelis is this something you're also interested in?

**Comment by nnobelis** [comment]
@sschuberth Not really. At Bosch, we migrated away from the `WORKSPACE` files to the `MODULE` ones.

Additionally, Bazel is going to first disable, then drop support of the `WORKSPACE` files in the next major versions:
https://bazel.build/about/roadmap#bzlmod:-external.
