### ISSUE TITLE
best solution  to scan a project separately and combine results to a final report

### ISSUE THREAD

**Issue by ChenZhaobin** [oss-review-toolkit/ort#8545]
I'm exploring the usage of ORT (OSS Review Toolkit) for code scanning in my projects, and I have a specific scenario that I'd like some advice on.

Let's say I want to perform code scans on different parts of a project separately and then merge the final results. What would be the best approach for achieving this with ORT? Specifically, at which stage should the results be merged for optimal effectiveness, and how can this be accomplished? ie. how to deduplication.

Additionally, I often encounter GitHub timeout issues during the scanning process. What strategies or best practices would you recommend for handling these timeouts? Re-scanning the entire project can be time-consuming, and I'm concerned about potential dependencies that might arise if I use the  curation mechinism.

Any insights or advice would be greatly appreciated. Thank you!

**Comment by ChenZhaobin** [comment]
fyi, I also want to know how the version control system is worked , I can see it from logs that ,sometimes `Could not fetch only revision`, some times `Could not find any revision candidates for package`  , some times `Could not resolve revision for package `, and how is it mapped among `binary artifacts ` ,`source artifacts` and `source repository`.

**Comment by sschuberth** [comment]
> Let's say I want to perform code scans on different parts of a project separately and then merge the final results. What would be the best approach for achieving this with ORT?

We've had some (oral) discussions about this quite some time ago in our [ORT Community meetings](https://github.com/oss-review-toolkit/ort/wiki/ORT-Community-Meeting) in the context of [this PR](https://github.com/oss-review-toolkit/ort/pull/5519), but came to the (preliminary) conclusion that it's too hard to get right for all use-cases, and thus the idea to implement something like this stalled.

**Comment by sschuberth** [comment]
@ChenZhaobin please also stick to *one* topic per issue, and consider starting a [discussion](https://github.com/oss-review-toolkit/ort/discussions) instead if you're not actually reporting a bug or requesting a feature.

**Comment by ChenZhaobin** [comment]
understood, thanks for the quick help.

**Comment by sschuberth** [comment]
> Re-scanning the entire project can be time-consuming

One idea is to scan packages one-by-one in advance to populate the scan storage (you should [set up a database](https://oss-review-toolkit.org/ort/docs/tools/scanner#postgresql-storage) for that beforehand), so the "real" scan does through smoothly.

**Comment by sschuberth** [comment]
> how is it mapped among `binary artifacts ` ,`source artifacts` and `source repository`.

That depends a bit on your [configuration](https://github.com/oss-review-toolkit/ort/blob/ce7d028ad8344c29a955072bd2705bcfe1bef0f8/model/src/main/resources/reference.yml#L170) of source code origins:

https://github.com/oss-review-toolkit/ort/blob/ce7d028ad8344c29a955072bd2705bcfe1bef0f8/model/src/main/kotlin/config/DownloaderConfiguration.kt#L43-L47

In general, ORT does not download binary artifacts, but only source artifacts or source code from VCS. Which of the latter two (and in which order) is determined by the above setting, and any errors messages refer to getting code from that configured origin(s).
