### ISSUE TITLE
declared_license_mapping curations are not applied in git repo projects

### ISSUE THREAD

**Issue by bennati** [oss-review-toolkit/ort#8553]
Declared license mapping curations are not applied correctly when scanning a git-repo project:
Adding a curation to map "Dual license: Apache or Proprietary" to "Apache-2.0 AND BSD-3-Clause" does not work and the report still contains the undeclared license.

How to reproduce: 
Run ORT on the provided manifest file and ort.yml file, verify that "Dual license: Apache or Proprietary" is among the declared licenses.

[ort.yml.zip](https://github.com/oss-review-toolkit/ort/files/15065626/ort.yml.zip)
[manifest.xml.zip](https://github.com/oss-review-toolkit/ort/files/15065651/manifest.xml.zip)
[scan-result.json.zip](https://github.com/oss-review-toolkit/ort/files/15065620/scan-result.json.zip)

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
