### ISSUE TITLE
PURL encoding for SwiftPM is invalid as PURL specification.

### ISSUE THREAD

**Issue by heliocastro** [oss-review-toolkit/ort#8567]
Current Swift generated PURL has slash encoding, creating a result similar like:
```yaml
purl: "pkg:swift/github.com%2Fapple%2Fswift-argument-parser@1.3.0"
```

This is not valid following the [PURL specification](https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst). Quoting here from [Character Encoding](https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst#character-encoding) section:
```txt
the '/' used as type/namespace/name and subpath segments separator does not need to and must NOT be percent-encoded. It is unambiguous unencoded everywhere
```

This issue was first discussed with @pombredanne and this is really invalid.

On last community meeting, @fviernau  mentioned a probable cause that SwiftPM not provides the namespace like field, only entire namespace as a name, and Ort was assuming that slash was a part of name, so %2F enconding. 
Some package manager like Maven provides namespace ( a Java common ), so Ort probably wrong assuming that every single package manager follow.

A possible simple solution is just not encode anymore ant entry and treat PURL as single entity, instead of expecting namespace ( or consider as last fallback )

A more complex, un unlikely solution is make adjusts on the SwiftPM package manager code to separate namespace / name, but this can only work if retrieved names are consistent from the package manager.

A possible improvement is get rid of self made PURL code and use the [PURL official java library](https://github.com/package-url/packageurl-java) to assembly the PURL and have it validated as well.

**Comment by wkl3nk** [comment]
I am using `ModGo`, and also have an issue with the percent encoding.

From ort-result.zip:
```
id: "Go::github.com/quic-go/quic-go:0.40.0"
purl: "pkg:golang/github.com%2Fquic-go%2Fquic-go@0.40.0"
```

It seems that the namespace is not specified in the `id`, that it is part of the `name` of the package instead.

**Comment by fviernau** [comment]
@wkl3nk can you please provide some evidence why the behaviour you would expect is correct?

**Comment by sschuberth** [comment]
I believe we should not mix Go and Swift issues here: The main point is that after [some discussion](https://github.com/package-url/purl-spec/pull/176) it seems that PURLs are not supposed to encode `/` to `%2F` that are part of the namespace, and I'm working on [a fix for that](https://github.com/oss-review-toolkit/ort/pull/9304).

However, for Swift we always set the namespace to the empty string, so there is no question about how to encode the namespace. For Go it's different, as [it uses the host / organization of a URL as the namespace](https://github.com/package-url/purl-spec/pull/176#issuecomment-2420029239).
