### ISSUE TITLE
[BUG] Cargo: submodules and local packages are being skipped

### ISSUE THREAD

**Issue by barshaul** [oss-review-toolkit/ort#8571]
After the last releases, local packages and submodules that were defined with a 'path' in the Cargo.toml file are being skipped from the report file.

To reproduce it use a package dependency with a local path, for example:
```
# Cargo.toml
...
[dependencies]
bytes = { version = "^1.3", optional = true }
futures = "^0.3"
redis = { path = "../submodules/redis-rs/redis", features = ["aio", "tokio-comp", "tokio-rustls-comp", "connection-manager","cluster", "cluster-async"] }
logger_core = {path = "../logger_core"}

```
The generated NOTICE_DEFAULT file wouldn't contain attributions for both the `redis` and `logger_core` crates, as opposed to older ORT versions were these packages were included.

**Comment by barshaul** [comment]
It worked till 20.1.0

**Comment by sschuberth** [comment]
How exactly are you running the ORT analyzer on your repo? Can it be that you're not pointing it at the root of the repository, but at each `Cargo.toml` file separately or so?
