### ISSUE TITLE
Reuse emits deprecation warnings

### ISSUE THREAD

**Issue by rettichschnidi** [oss-review-toolkit/ort#8772]
### Describe the bug

Running `reuse lint` emits deprecation warnings for many files:

```shell
$ reuse --version
reuse 3.0.2
$ reuse lint
...
some/path/lib/python3.11/site-packages/reuse/project.py:286: PendingDeprecationWarning: Copyright and licensing information for '.github/actions/free-disk-space/action.yml' has been found in both '.github/actions/free-disk-space/action.yml' and in the DEP5 file located at '.reuse/dep5'. The information for these two sources has been aggregated. In the future this behaviour will change, and you will need to explicitly enable aggregation. See <https://github.com/fsfe/reuse-tool/issues/779>. You need do nothing yet. Run with `--suppress-deprecation` to hide this warning.
...
```

The warnings can also been seen on [api.reuse.software](https://api.reuse.software/info/github.com/oss-review-toolkit/ort):
![image](https://github.com/oss-review-toolkit/ort/assets/920644/feb2eee9-fe7f-4942-bb98-48d896de319b)

### To Reproduce

Run `reuse lint` using version 3.0.2

### Expected behavior

No warnings emitted.

### Possible workaround

Add the argument `--suppress-deprecation` to suppress the warning: `reuse --suppress-deprecation lint`.

### Proposed fix

1. Move away from dep5 file, adopt REUSE.toml. dep5 will be deprecated as of [REUSE 3.1.0](https://github.com/fsfe/reuse-tool/releases/tag/v3.1.0a1) anyway.

**Comment by sschuberth** [comment]
> Move away from dep5 file, adopt REUSE.toml. dep5 will be deprecated as of [REUSE 3.1.0](https://github.com/fsfe/reuse-tool/releases/tag/v3.1.0a1) anyway.

I agree that's the way forward. @carmenbianca did ping me about giving that alpha release and `REUSE.toml` a try, but I did not find the time to do that yet.

Anyway, I believe we should not fully migrate to it while it's still in alpha. And I do not regard those deprecation warnings as severe, esp. as mostly the REUSE check runs on CI only. So to me this is rather low priority.

**Comment by sschuberth** [comment]
Not reproducible anymore with reuse 4.0.3 on latest `main`, probably due to https://github.com/oss-review-toolkit/ort/pull/9075.
