### ISSUE TITLE
Bazel: It should be possible to disable the disk cache

### ISSUE THREAD

**Issue by nnobelis** [oss-review-toolkit/ort#8802]
The user can configure the usage of a disk cache in the .bazelrc file:

```
common --disk_cache=/home/dockeruser/.cache/bazel_disk_cache/
```

The pointed directory can be outside of the repository due to a specific environment.

When the pointed directory does not exist, ORT crashes on any `bazel` command, even `bazel --version`:

```
Exception in thread "main" java.io.IOException: Running 'bazel version' in '/test/' failed with exit code 2:
ERROR: /home/dockeruser/.cache/bazel_disk_cache (Permission denied)
ERROR: Error initializing RemoteModule
```

The workaround (taken [here](https://github.com/bazelbuild/bazel/issues/5308)) is to pass `--disk_cache=` as extra parameter to the Bazel commands run by ORT.
TBD if it should be configurable or passed every time.

@haikoschol FYI

**Comment by fviernau** [comment]
Instead of adding a parameter, would it be an option that ORT simply takes care of creating the directory in case it does not exist?

**Comment by fviernau** [comment]
I've just tried to reproduce the issue, by deleting `.cache/bazel_disk_cache` inside docker and then run the bazel fun test. The tests succeeds. So, I wonder if the issue description is correct. 

Could the problem be a permission issue rather than the non-existance of the dir?

**Comment by nnobelis** [comment]
> and then run the bazel fun test.

But did you test with the `.bazelrc` configuration described above ? I am not sure the disk cache is enabled by default.

> would it be an option that ORT simply takes care of creating the directory in case it does not exist

Creating this directory works but I don't see how ORT can get the name of this directory? By parsing the `.bazelrc` file?

Don't forget that some projects can use a custom Bazel RC e.g. `bazel --bazelrc=my_custom_bazelrc`.

**Comment by fviernau** [comment]
> But did you test with the `.bazelrc` configuration described above ? I am not sure the disk cache is enabled by default.

Oh no, I missed that this step is required. 

In my view, it could be a good solution to always overwrite any disk cache directory configured in `.bazelrc`.
If tested this and it avoid running into the error. For example, the following would work even if the
disk cache dir specified in `.bazelrc` does not exist:

```
mkdir -p ~/.cache/ort/bazel/disk-cache
bazel mod graph --disk_cache ~/.cache/ort/bazel/disk-cache
```
Maybe a better directory could be choosen.

**Comment by fviernau** [comment]
One additional question I just came across is whether the content of the cache dir should be re-used across scans on CI.
We have `~/.ort/cache/analyzer` which I believe is normally re-used. In this case (as its a build cache) it may be better to create a new empty temp directory, and use it only for a single ORT analysis process. What do you think ?

**Comment by nnobelis** [comment]
Yes I agree: better to use an empty temp directory for disk cache.

However I am not sure the commands run by ORT will fill the cache: these are not doing "a real build", no ?

**Comment by fviernau** [comment]
> However I am not sure the commands run by ORT will fill the cache: these are not doing "a real build", no ?

I'm not into this implementation deeply, but I do recall from the code review that there may be a build involved.

**Comment by nnobelis** [comment]
Thanks for the fix @fviernau!
