### ISSUE TITLE
Bazel: disable Bazelisk optional wrapper script when fetching the version of Bazel

### ISSUE THREAD

**Issue by nnobelis** [oss-review-toolkit/ort#8828]
Bazelisk (https://github.com/bazelbuild/bazelisk) has a mechanism to call a wrapper script if it exists.
One of our projects has such setup and it fails when fetching the version:

```
❯ bazel --version 
[FATAL 06:57:24.976 src/main/cpp/blaze.cc:1104] Unknown startup option: '--version'.
  For more info, run 'bazel help startup_options'.
```

The solution is to disable the wrapper script:

```
❯ BAZELISK_SKIP_WRAPPER=true bazel --version
bazel 7.1.0
```

IMO when ORT fetches the version, the wrapper should always be disabled.

**Comment by sschuberth** [comment]
AFAIU Bazelisk works similar to the Gradle wrapper, i.e. it bootstraps the version of Bazel configured by the project. So when disabling Bazelisk, we'd always get the version of a globally installed Bazel (if any). However, that's then not (necessarily) the version of Bazel that would be used by the project. Or an I getting something wrong?

**Comment by nnobelis** [comment]
This is quite confusing but here is what I found.

You can have a script in your project in `tools/bazel`. According to the [documentation](https://github.com/bazelbuild/bazelisk/blob/master/README.md#toolsbazel):

> If tools/bazel exists in your workspace root and is executable, Bazelisk will run this file, instead of the Bazel version it downloaded. It will set the environment variable BAZEL_REAL to the path of the downloaded Bazel binary. This can be useful, if you have a wrapper script that e.g. ensures that environment variables are set to known good values. This behavior can be disabled by setting the environment variable BAZELISK_SKIP_WRAPPER to any value (except the empty string) before launching Bazelisk.

So you can see that:
- either you have such a script. You are supposed in it to delegates to `BAZEL_REAL` which is the Bazelisk downloaded binary.
- or use `BAZELISK_SKIP_WRAPPER` that skips the script and Bazelisk will directly run the Bazel it downloaded.

IMO in both case the same Bazel version is run, i.e. the one from Bazelisk.

**Comment by sschuberth** [comment]
Indeed confusing. So the "WRAPPER" in `BAZELISK_SKIP_WRAPPER` doe snot refer to Bazelisk itself 8which is also a wrapper), but to this other optional wrapper script at `tools/bazel`.

**Comment by nnobelis** [comment]
I update the issue's title to clear a bit the confusion ?
