### ISSUE TITLE
Migrate the Opossum reporter from Jackson to kotlinx-serialization (KxS)

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#8839]
Ideally, this would also refactor the code to use properly typed `data class`es.

This is part of the https://github.com/oss-review-toolkit/ort/issues/3904 effort.

**Comment by maxhbr** [comment]
Hey, I posted it in our group chat.

**Comment by sschuberth** [comment]
> > Hey, I posted it in our group chat.
> 
> Were there any responses [@maxhbr](https://github.com/maxhbr)?

@maxhbr is the Opossum reporter still in use from your side? Otherwise we could consider removing it from ORT instead of investing the time to migrate it to KxS.

**Comment by sschuberth** [comment]
> Yeah, we are difinitely still using it.

Thanks @leslielazzarino for the comment. Is there also willingness to help maintaining it from your side, and assist with the migration to KxS?

**Comment by alexzurbonsen** [comment]
Hi @sschuberth I am taking a look.

**Comment by sschuberth** [comment]
> Hi [@sschuberth](https://github.com/sschuberth) I am taking a look.

Thank you @alexzurbonsen 🙏🏻 

Ideally, the conversion would not be done by simply migrating those untyped maps to KxS equivalents, but by introducing a proper data model class (like e.g. for [AOSD](https://github.com/oss-review-toolkit/ort/blob/d19c625f337573341b0849acd45abaebcb62ea9d/plugins/reporters/aosd/src/main/kotlin/Model.kt)) at the same time.
