### ISSUE TITLE
Drop support for several old versions of ScanCode

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#8881]
_ScanCode_ 30.0.0 [1] invented an output format version. Starting with that
version, it became possible not have _ScanCode_ version specific parsing logic anymore,
but to only have the parsing specific to the output format version. The
first handling of that output format version in _ORT_ has been introduced [2] for
_ScanCode_ version 30.1.0.

Drop support for all _ScanCode_ versions prior to 30.1.0 from _ORT_, to simplify the code.

[1]: https://github.com/nexB/scancode-toolkit/blob/develop/CHANGELOG.rst#v3000---2021-09-23
[2]: https://github.com/oss-review-toolkit/ort/pull/4916

**Comment by sschuberth** [comment]
> Drop support for all _ScanCode_ versions prior to 30.1.0 from _ORT_, to simplify the code.

More generally, we should say "drop support for all ScanCode versions that do not write the `outputFormatVersion` field".

**Comment by fviernau** [comment]
> More generally, we should say "drop support for all ScanCode versions that do not write the `outputFormatVersion` field".

I phrase it like this, because we skipped integrating ScanCode versions 30.0.0 and went to 30.1.0 directly. So, I wanted to save the effort to investigate that old 30.0.0 support.

**Comment by sschuberth** [comment]
> So, I wanted to save the effort to investigate that old 30.0.0 support.

I believe we can skip it anyway, as like we discussed, with general `outputFormatVersion` support the ScanCode version does not matter anymore, so we also don't need to prove that supporting `outputFormatVersion` 1.0.0 indeed works for parsing ScanCode 30.0.0 results.

**Comment by sschuberth** [comment]
Maybe we should work on this issue before upgrading to [ScanCode 32.3.0](https://github.com/aboutcode-org/scancode-toolkit/releases/tag/v32.3.0), which introduces new major output format version 4.0.0.

**Comment by fviernau** [comment]
I've unassigned myself, as I don't have time in the short term. I'd be interested in doing this but though.
