### ISSUE TITLE
The compiler plugin generates redundant `public` visibility modifiers

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#9105]
Looking at generated code with the IDE reveals these:

![image](https://github.com/user-attachments/assets/410d2bc0-b83b-4776-9d47-ca8b73cd1e5d)

**Comment by mnonnenmacher** [comment]
This is how KotlinPoet works and according to the information I found there are no plans to make it possible to omit those redundant public modifiers, for example:

https://github.com/square/kotlinpoet/issues/1001 (there are several more issues with basically the same answer)

Based on that, maybe we should even consider to enable the explicit API mode for library code:
https://kotlinlang.org/docs/whatsnew14.html#explicit-api-mode-for-library-authors

**Comment by sschuberth** [comment]
> Based on that, maybe we should even consider to enable the explicit API mode for library code:

I don't think I like this. Kotlin is all about having smart defaults to avoid boiler-plate compared to Java. Turning explicit API mode would make a mockery out of that.

Luckily, we only generate code on-the-fly and put it under `build/generated` instead of `src/main/kotlin`, so we probably barely look at generated code in the IDE. Thus I'm just closing this. Thanks for researching the reference in any case!
