### ISSUE TITLE
Declared license curations not being applied

### ISSUE THREAD

**Issue by bennati** [oss-review-toolkit/ort#9111]
Declared license curations are correectly parsed into the `resolved_configuration` section of analyzer report, but the declared license is still represented as the original value and a rule violation is shown in the report (both webapp and html).

To reproduce:

1. Configure ORT to use the curation from [curations.yml.txt](https://github.com/user-attachments/files/16930106/curations.yml.txt)
2. Configure ORT to use the rule below:
```
fun RuleSet.unmappedDeclaredLicenseRule() = packageRule("UNMAPPED_DECLARED_LICENSE") {
    pkg.metadata.declaredLicensesProcessed.unmapped.forEach { unmappedLicense ->
        error(
            "The declared license '$unmappedLicense' could not be mapped to a valid license or parsed as an SPDX " +
                    "expression. The license was found in package ${pkg.metadata.id.toCoordinates()}.",
            ""
        )
    }
}
```
3. Scan the file [requirements.txt](https://github.com/user-attachments/files/16930056/requirements.txt)
4. Check in the [analyzer-result.json](https://github.com/user-attachments/files/16930113/analyzer-result.json) that the curation is present in the `resolved_configuration` section
5. Check that the rule `UNMAPPED_DECLARED_LICENSE` is triggered in the scan report.

**Comment by fviernau** [comment]
@bennat I found a fix.

Independently of that, I guess the license ID in your curation should be changed from `LicenseRef-scancode-openssl-exception-lgpl3.0plus` to `LicenseRef-scancode-openssl-exception-lgpl3.0-plus`.
