### ISSUE TITLE
VulnerableCode returns no findings for Go packages

### ISSUE THREAD

**Issue by wkl3nk** [oss-review-toolkit/ort#9298]
### Describe the bug

I am scanning a project with `ModGo` ORT package manager. 
One dependency is _quic-go_, release 0.40.0 , which definitely has vulnerability findings in the [VulnerableCode](https://public.vulnerablecode.io/) database.
Unfortunately, no security vulnerabilites are found in the Advisor phase, using [VulnerableCode](https://public.vulnerablecode.io/).

### Detailed analysis

ORT uses a "bulk search", sending a POST request to the VulnerableCode API. This request has a list of Package URLs (purls) of the dependencies like quick-go. 
The purl for quick-go looks as follows:
_pkg:golang/github.com%2Fquic-go%2Fquic-go@0.40.0_

So, at some places we see the "/", in other places it is percent-encoded to "%2F".
I don't want to open discussions if this is valid or not, but there is a point in saying "the / character is used to separate the parts that build up a purl, and for this reason, if a namespace or name of a dependency contain /, then they need to be percent-encoded".

When I (in code) add an additional step that replaces all occcurrences of "%2F" with "/" before I feed it into VulnerableCode, then the VulnerableCode API is happy and returns the expected vulnerability records.

### Environment

ORT 34.0.0

### Additional context

I will prepare a PR to deal with the issue in a pragmatic way. Stay tuned.

**Comment by sschuberth** [comment]
> I don't want to open discussions if this is valid or not, but there is a point in saying "the / character is used to separate the parts that build up a purl, and for this reason, if a namespace or name of a dependency contain /, then they need to be percent-encoded".

Agreed, also regarding the topic that *if* VulnerableCode would be using a wrong encoding, we'd need to use a wrong encoding as well to make the lookup work.

**Comment by wkl3nk** [comment]
Cross-linking the issue ticket in VulnerableCode: https://github.com/aboutcode-org/vulnerablecode/issues/1620
