### ISSUE TITLE
The `Project` data class should have a `description` property like the `Package` data class has

### ISSUE THREAD

**Issue by wkl3nk** [oss-review-toolkit/ort#9443]
### What is the existing functionality and how should it be enhanced?

In NPM package manager,
there is the concept of a [Project](https://github.com/oss-review-toolkit/ort/blob/f23fbb211c90e69da896524bc60d70a346312bdf/model/src/main/kotlin/Project.kt#L39) and [Package](https://github.com/oss-review-toolkit/ort/blob/f23fbb211c90e69da896524bc60d70a346312bdf/model/src/main/kotlin/Package.kt#L42).

But while both data classes share attributes like `homepageUrl`,
only data class `Package` has attribute `description`. 

But, at least for the case in NPM, projects also have a `description` line in `package.json`, and it is not clear to me why `homepage` should be handled different than `description`. 

### Additional context

I had a case with the following error message
>  java.lang.IllegalArgumentException: Unable to create the AnalyzerResult as it contains packages and projects with the same ids

Yes, the identifiers were the same, but I was wondering why **one** result had a `description`, and the other not.

Please handle with low priority or close.

**Comment by fviernau** [comment]
Which ORT version has been used for observing this?

**Comment by sschuberth** [comment]
> Which ORT version has been used for observing this?

I guess that goes not matter. ORT's `Project` class never had a `description` property AFAIR.
