### ISSUE TITLE
NPM/PNPM: Add support for peer dependencies

### ISSUE THREAD

**Issue by mnonnenmacher** [oss-review-toolkit/ort#95]
Add support for the peerDependencies scope to NPM. Be aware that the specific version of the peer dependency will only be resolved in the context of a project using the library.

npm-install-peers can be used to install peer dependencies, see this relevant ticket:
https://github.com/spatie/npm-install-peers/issues/13

**Comment by tsteenbe** [comment]
@mnonnenmacher  Harp.gl has multiple peer dependency on three.js see https://github.com/heremaps/harp.gl/blob/e3110f1dc35a889059ba23faefc76e3a4c1cfe73/%40here/harp-debug-datasource/package.json#L42

Now ORT does not pick up the core library that powers harp.gl

**Comment by sschuberth** [comment]
Good write-up about what peer dependencies actually are: https://nodejs.org/en/blog/npm/peer-dependencies/. Basically, peer dependencies define against what API of a "host" package a (plugin) package has been written.
