### ISSUE TITLE
Missing template file in docker image

### ISSUE THREAD

**Issue by bennati** [oss-review-toolkit/ort#9515]
Running ORT from the docker image causes the reporter to fail with:

```
Exception in thread "main" java.lang.NullPointerException: getResource(...) must not be null
	at org.ossreviewtoolkit.plugins.reporters.webapp.WebAppReporter.generateReport(WebAppReporter.kt:65)
```

It looks like ORT does not find [`scan-report-template.html`](https://github.com/oss-review-toolkit/ort/blob/99e611b7db1270dbc13b87a1e17152de798946f7/plugins/reporters/web-app/src/main/kotlin/WebAppReporter.kt#L65) which [is required by the reporter](https://github.com/oss-review-toolkit/ort/blob/99e611b7db1270dbc13b87a1e17152de798946f7/plugins/reporters/web-app-template/README.md?plain=1#L7).

That file is generated at ORT build time and can be found in `./reporter-web-app/build/scan-report-template.html`, but that file is not copied into the docker image.
Manually copying the file into `/opt/ort/lib` solves the issue.

**Comment by sschuberth** [comment]
The `scan-report-template.html` is embedded as a resource into the web-app reporter's JAR; it's not expected to be located in the Docker image's filesystem.

Moreover, I cannot reproduce the problem; for me running ORT from the Docker image produces the web-app report just fine.

I assume that you have made some modifications to ORT which cause `scan-report-template.html` not to be built in the first place. As the [copy task](https://github.com/oss-review-toolkit/ort/blob/978a71f4e3f4f24590da26325b2fe3bdeadd2fdb/plugins/reporters/web-app/build.gradle.kts#L26-L36) silently ignores if there is no matching file, you won't notice.

**Comment by sschuberth** [comment]
Maybe https://github.com/oss-review-toolkit/ort/pull/9516 will help you to debug your issue.

**Comment by bennati** [comment]
It fixes the issue, thank you!
